WordPress-Core/ruleset.xml, WordPress/Sniff.php, WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php, phpcs.xml.dist.sample
A new format for passing array elements to PHPCS properties was added in PHPCS 3.3.0.
This new array format is far more readable and less error prone than the old format.
This commit implements using this new array format throughout WPCS, wherever relevant, including in property setting examples in the documentation.
Ref:
* squizlabs/PHP_CodeSniffer#1665
=> Rulesets: Start using the new XML array format (PHPCS 3.3+)

.phpcs.xml.dist, .travis.yml, WordPress-Core/ruleset.xml, WordPress-Docs/ruleset.xml, WordPress-Extra/ruleset.xml, WordPress/ruleset.xml, phpcs.xml.dist.sample
As of PHPCS 3.2.0, PHPCS includes an XSD schema for rulesets which defines what can be used in the XML ruleset file.
In PHPCS 3.3.0 a new array format for properties was introduced and as of PHPCS 3.3.2, the new array format is now also covered by this schema.
This commit:
* Adds the schema tags to the `ruleset.xml` files, the WPCS native `.phpcs.xml.dist` file, as well as to the example ruleset.
* Adds validation against the schema for the `ruleset.xml` files and the example ruleset to the Travis build.
Note:
The schema used in the tags points to the online schema in PHPCS `master` for two reasons:
1. While WPCS now has a minimum requirement of PHPCS 3.3.1, the schema in PHPCS `master` contains the changes which were made in PHPCS 3.3.2, so we can safely validate the rulesets against the …
=> Build/Rulesets: Add XSD schema tags and validate rulesets against schema (PHPCS 3.2+/3.3.2+)

WordPress/Sniff.php, WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
The (protected) `Sniff::$phpcsCommentTokens` property was a work-around for the `Tokens::$phpcsCommentTokens` array not being available prior to PHPCS 3.2.3.
This work-around is no longer needed now the minimum PHPCS version is 3.3.1.
Note:
This is a BC-break for external standards extending the WordPressCS `Sniff` class which may be using this property. They should adjust their code to use the PHPCS native `Tokens::$phpcsCommentTokens` array instead.
=> PHPCS 3.2.3+: Remove the Sniff::$phpcsCommentTokens property

.github/CONTRIBUTING.md, composer.json, phpunit.xml.dist
A `dev` requirement of `phpunit/phpunit` has been added to the `composer.json` file, as well as a script to run the unit tests.
While PHPUnit is not strictly speaking a dependency of WPCS (but of PHPCS), this just makes life easier on WPCS developers who use the Composer install for development.
If - as a WPCS sniff developer - you've installed WPCS using Composer, you can now run the unit tests, like so:
```bash
composer run-tests
```
A note to this effect has been added to the `CONTRIBUTING.MD` file as well.
Additionally:
* While not strictly necessary, a `testsuite` directive has been added to the `phpunit.xml.dist` file to document where the tests are located and how they are named.
* As `PHPCompatibility` will also be installed when using Composer to install WPCS and PHPCompatibility …
=> PHPUnit: add Composer script to run the tests

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
Those are generally only used for unit testing sniffs and as all WPCS native unit tests have been adjusted, the work-arounds for the _old style_ annotations are no longer needed.
Included removing a, now redundant, comment in the `Sniff` class. The comment was relevant before the new-style array annotation for `phpcs:set` comments was introduced. However, now those are used, this is no longer an issue.
=> PHPCS 3.2+: Remove work-arounds for old style PHPCS ChangeSettings annotations

README.md
Since PHPCS 3.1.0, the config file can be dot-prefixed, i.e. `.phpcs.xml` or `.phpcs.xml.dist`.
Since PHPCS 3.1.1, the loading order has been corrected for the config files.
So, as the minimum PHPCS version is now well passed those versions, let's mention this in the readme.
Refs:
* squizlabs/PHP_CodeSniffer#1566
* squizlabs/PHP_CodeSniffer#1693
=> Readme: Recommend/mention dot prefixed config files (PHPCS 3.1.1)

.github/CONTRIBUTING.md, .phpcs.xml.dist, WordPress/Sniff.php, WordPress/Sniffs/DB/SlowDBQuerySniff.php, WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.php, WordPress/Tests/DB/PreparedSQLUnitTest.php, WordPress/Tests/DB/SlowDBQueryUnitTest.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php, WordPress/Tests/PHP/StrictComparisonsUnitTest.php, WordPress/Tests/Security/EscapeOutputUnitTest.php, WordPress/Tests/Security/NonceVerificationUnitTest.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php, WordPress/Tests/WP/CapitalPDangitUnitTest.php, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
The WPCS native whitelist comments were introduced for lack of the ability to selectively ignore one or more sniffs for a piece of code.
PHPCS 3.2.0 introduced native PHPCS annotations which allow for selective ignoring/disabling of sniffs and while those were originally a bit buggy, all known bugs have been fixed since, making the WPCS native whitelist comments redundant.
This commit deprecates the method within WPCS which is used to check for the WPCS native whitelist comments.
It also introduces a warning which will be thrown whenever a WPCS native whitelist comment is encountered to alert people to this change and encourage them to switch over to the PHPCS native annotations.
Notes:
* No deprecation notice will be thrown when a WPCS whitelist comment is combined with a PHPCS native …
=> Deprecate use of the WPCS native whitelist comments

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/WP/I18nSniff.php
Array properties passed in from a custom ruleset need to have a `type="array"` attribute.
Until now WPCS was lenient when this attribute was missing and would convert an array passed as a comma delimited string to an array.
This functionality was deprecated for the only property which still "officially" allowed for a comma-delimited string list in WPCS 1.0.0 and will now be removed.
The only exception are the two array properties which can also be set via the command-line, i.e. the `prefixes` property for the `WordPress.NamingConventions.PrefixAllGlobals` sniff and the `text_domain` property for the `WordPress.WP.I18n` sniff.
If - and only if - these properties are set from the command-line, the sniffs will still convert the received string to an array.
Refs:
* #1390
This PR also removes …
=> Sniff::merge_custom_array(): Remove support for incorrectly set custom array properties

WordPress-Extra/ruleset.xml
The `Squiz.WhiteSpace.LanguageConstructSpacing` sniff has been deprecated in PHPCS 3.3.0 and will be removed in PHPCS 4, in favour of the newly introduced `Generic.WhiteSpace.LanguageConstructSpacing` sniff.
Ref:
* #1328
* squizlabs/PHP_CodeSniffer#1337
=> Extra: Use the new `Generic.WhiteSpace.LanguageConstructSpacing` sniff (PHPCS 3.3.0)

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
The upstream `PHP_CodeSniffer\Sniffs\AbstractVariableSniff` contains the same list of PHP reserved variables since PHPCS 3.3.0, so no need to maintain it ourselves.
Refs:
* squizlabs/PHP_CodeSniffer#1888
=> ValidVariableName: Defer to the upstream `$phpReservedVars` property (PHPCS 3.3.0)

WordPress-Extra/ruleset.xml
=> Extra: Document why two WPCS native sniffs are not (yet) replaced 

.travis.yml, composer.json
* Make the `scripts` section more readable by setting each script up as an array.
* `require-dev` the DealerDirect Composer plugin to make life easier on WPCS devs using Composer for their dev environment.
Includes:
- Adjusting the `install-codestandards` script to use the plugin.
This script should be considered _deprecated_, but is left in place for devs who are used to having it available in their workflow.
- Removing the `post-install-cmd` and `post-update-cmd` scripts which shouldn't be needed anymore as the plugin automatically takes care of installing the standards.
* Includes updating the inline documentation in the Travis script to be inline with these changes.
=> Composer: some tweaks

WordPress-Extra/ruleset.xml
The sniff already throws a warning for that error code, so we don't need to change the `type`.
=> Extra: remove superfluous directive

WordPress-Extra/ruleset.xml
PR #1103 added the `Squiz.Scope.MemberVarScope` sniff to the `WordPress-Extra` ruleset which checks that all class properties have their visibility declared.
The upstream `PSR2.Classes.PropertyDeclaration` sniff also does this, however it contains more extensive checks.
In addition to checking for the visibility of properties being declared, this sniff also checks:
* That property names are not prefixed with an underscore `_` to indicate visibility.
_For methods, we already check this in the `Extra` ruleset via the `PSR2.Methods.MethodDeclaration` sniff._
* That the `var` keyword is not used for property declarations.
This could be considered a duplicate check with the "use visibility" check.
* That each property declaration statement only declares one property, i.e. it forbids the use of …
=> Extra: Replace `Squiz.Scope.MemberVarScope` with `PSR2.Classes.PropertyDeclaration`

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php, WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php, WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/PHP/DontExtractSniff.php, WordPress/Sniffs/PHP/POSIXFunctionsSniff.php, WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Sniffs/PHP/YodaConditionsSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/Security/PluginMenuSlugSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/WP/TimezoneChangeSniff.php, WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
What with classes originally having underscore delimited names, then becoming namespaced and now the namespaces being changed, documentation still referencing old, outdated class names can be confusing for new contributors.
With that in mind, I've fixed up most of the documentation to either reference the sniff _code_ or the current sniff class name.
=> Documentation: Touch up the class and method documentation

.phpcs.xml.dist
When the item with the _longest_ array key is removed, WPCS requires the double arrows in the whole array to be re-aligned.
Setting the [`exact` property](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#array-alignment-allow-non-exact-alignment) to `false` removes this requirement and allows for cleaner diffs when this happens.
As PR #1547 removed a large number of items from the `Sniff::$autoEscapedFunctions` array, PHPCS was currently throwing warnings about the WPCS codebase.
This small tweaks gets rid of those.
=> PHPCS native ruleset: don't require exact array double arrow alignment

WordPress-Core/ruleset.xml, WordPress/Sniffs/PHP/TypeCastsSniff.php, WordPress/Tests/PHP/TypeCastsUnitTest.inc, WordPress/Tests/PHP/TypeCastsUnitTest.inc.fixed, WordPress/Tests/PHP/TypeCastsUnitTest.php
The WPCS native `WordPress.PHP.TypeCasts` sniff used to check that:
* Type casts are in lowercase;
* Boolean and integer casts are short form;
* The `(double)` cast is not used;
* Discourages the use of the `(unset)` and `(binary)` casts.
The lowercase checks has been removed in WPCS 2.0.0 in favour of the upstream `Generic.PHP.LowerCaseType` sniff via #1582.
Asides from that sniff, PHPCS 3.3.0 also introduces the `PSR12.Keywords.ShortFormTypeKeywords` sniff which checks that boolean and integer casts are in short form.
This PR removes that check from the `WordPress.PHP.TypeCasts` sniff in favour of using the upstream sniff.
There is currently one known bug in the upstream sniff - a false positive when a type cast contains whitespace, see squizlabs/PHP_CodeSniffer#2331 -, however, as WPCS …
=> Core: Defer to upstream `PSR12.Keywords.ShortFormTypeKeywords` sniff (PHPCS 3.3.0)

WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.php
PHPCS 3.3.0 introduces a `PSR12.Operators.OperatorSpacing` sniff.
I've investigated whether that sniff would be a better sniff to extend for the `WordPress.WhiteSpace.OperatorSpacing` sniff than the `Squiz.WhiteSpace.OperatorSpacing` sniff which is currently being extended and have concluded that it is not for the following reason:
* The PSR12 sniff demands _at least_ one space instead of _exactly_ one space (both allow for new lines with the correct properties).
All the same, the `PSR12` sniff did include an additional token - `T_INSTANCEOF` - which makes sense to add to the WPCS sniff.
=> OperatorSpacing: check spacing around `instanceof` operator

README.md
PHPCS 3.0.0 introduced an `<include-pattern>` directive as a counter-part to the pre-existing `<exclude-pattern>`.
This allows to easily limit the PHPCompatibility sniffs to PHP files only, while still allowing the rest of the ruleset to be applied to both PHP, JS as well as CSS files.
=> README: improve instructions about using PHPCompatibility (PHPCS 3.0+)

WordPress/Sniffs/DB/PreparedSQLSniff.php
The `WordPress.DB.PreparedSQL` sniff contains two different error messages, but didn't use unique error codes for these.
This is a breaking change as <exclude>s for the old errorcode currently in custom rulesets will now no longer exclude all errors and inline annotations using the error code may be invalidated by it.
=> PreparedSQL: use unique errorcode for messages

WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
This is more a cosmetic change than anything else.
The sniff name for this sniff got changed in WPCS 1.0.0 from `GlobalVariables` to `GlobalVariablesOverride`, however, the error code also contains `override` which is now redundant.
This is a BC-break and as the change is cosmetic, is a bit disputable to make this change.
However, as the sniff only contains one error code, excluding the whole sniff had the same effect as excluding the single error code, so with a bit of luck, not that many people will have excluded this based on the error code.
=> GlobalVariablesOverride: minor error code adjustment

WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniffs/DB/PreparedSQLSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Sniffs/PHP/TypeCastsSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
Removing:
* Unused `use` statement (no longer used after code removal).
* Some unnecessary interim variables (no longer needed as code which added to the variables has been removed).
* Unnecessary `return` statement.
* Simplify an (re-)assignment to the same variable.
* Remove an unused function parameter (no longer used after previous refactor of the function code).
=> CS: minor code clean up

WordPress/Sniffs/WP/DiscouragedConstantsSniff.php
This sniff is based on an array of constants the sniff looks for.
Previously, the sniff had two distinct error codes for the different use-cases in which the constant could be found (use of vs declaration).
This change makes the error codes unique to the constant found, making it easier to silence the error message(s) for just one particular constant.
This is a breaking change as `<exclude>`s for the old errorcodes currently in custom rulesets will be invalidated by it, as well as inline annotations using the error codes.
=> DiscouragedConstants: make the error codes more modular

WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.php
_When I started looking at #1280, I realized this sniff hadn't been synced with upstream for over two years, so here goes._
This adds similar fixes which were made to the upstream `PEAR` sniff to the WPCS native version of the sniff in as far applicable.
* The `WordPress.NamingConventions.ValidFunctionName` sniff would throw the same error twice for functions in nested classes.
The reasoning and solution used is the same as applied upstream.
> Turns out the `processTokensWithinScope()` method gets called for each whitelisted scope a `T_FUNCTION` token exists in.
>
> In effect, this means that the first time it gets called for the `nestedFunction()` method, it is because it is within the scope of the `Nested` class, the second time the function gets called, it is for the method being in …
=> ValidFunctionName: sync in fixes from upstream

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php
... rename it to `get_snake_case_name_suggestion()` and make it a static method so it's also available to sniffs extending upstream sniffs.
* Adjusts the error messages to include an alternative name suggestion in snake_case.
* Adds back the previously stripped `$` to the variable name for the error message.
* Adjusts the error messages the sniff throws to be more consistent.
Fixes #1280
Minor changes missed in PR #1586.
* Update the class documentation.
* Remove a, now unused, property array key.
... to confirm that the sniff handles multi-variable/property declarations correctly.
(some of these would have failed prior to PHPCS 3.3.0)
=> ValidVariableName: adjust error messages and codes

WordPress-Extra/ruleset.xml
This effectively reverts PR #1585 as the PEAR installation of PHPCS will not work with WPCS 2.0.0 if we leave this in.
Once upstream PR squizlabs/PHP_CodeSniffer#2340 has been merged, a new PHPCS version tagged & released and WPCS is ready & willing to upgrade to that version, this change should be made anew as the new sniff is definitely better than the old version, but until that time, it is not important enough to allow WPCS to be broken for anyone using a PEAR install of PHPCS.
Fixes #1614
=> Revert "Extra: Use the new `Generic.WhiteSpace.LanguageConstructSpacing` sniff (PHPCS 3.3.0)"

composer.json
Below 1.0 minor releases are treated as major releases so `^` locks to current minor release.
=> Bumped suggested installer version

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
The `PrefixAllGlobals` sniff verifies that functions declared in the global namespace are prefixed with one of the whitelisted prefixes as passed to the sniff in the `prefixes` property in a custom ruleset.
The sniff prevents false positives for polyfills for PHP native functions - which should be named exactly as named in PHP without prefix for them to be usable as a polyfill - by checking that the function doesn't exist.
Generally speaking this works fine in 98% of all cases as PHPCS is normally run stand-alone and doesn't contain any functions defined in the global namespace.
Similarly, when PHPCS is installed via Composer, this would normally work fine as the commonly used `autoload` options are `PSR-0`, `PSR-4` and `classmap` which are all based on code being in classes.
However, if …
=> PrefixAllGlobals: prevent false negatives for autoloaded user-defined global functions

WordPress/Sniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
The `Sniff::is_validated()` method did not check whether the variable being validated was in actual fact the same variable as the one for which validation was needed.
This could cause false negatives for the `InputNotValidated` error if an array key in, for instance, `$_GET` was validated, but that same array key was later requested - without validation - from `$_POST`.
=> ValidatedSanitizedInput: only recognize a variable as validated if the correct variable is examined

.phpcs.xml.dist
The `basepath` and `parallel` options were introduced in PHPCS 3.0 and can now be enabled for the WPCS native PHPCS checking.
And as WPCS 2.0.0 drops the `VIP` ruleset, we can now include the `WordPress` ruleset instead of including the `WordPress-Extra` + `WordPress-Docs` rulesets separately.
=> WPCS native PHPCS ruleset: minor tweaks

WordPress/Sniff.php
See: https://core.trac.wordpress.org/changeset/44701
=> Sniff::$test_class_whitelist: add newly added base test class to the list

.travis.yml
Nightly has become PHP 8.0 since PHP 7.4 has been branched, so to continue to also test against PHP 7.4, it needs to be added separately.
Refs:
* https://twitter.com/nikita_ppv/status/1089839541828112384
* https://twitter.com/nikita_ppv/status/1094897743594770433
As of recently, the Travis images for PHP 7.2+ ship with PHPUnit 8.x.
The PHPCS native test framework is not compatible with PHPUnit 8.x and won't be able to be made compatible with it until the minimum PHP version would be raised to PHP 7.1.
So for the unit tests to be able to run on PHP 7.2+, we need to explicitly require PHPUnit 7.x for those builds.
This has been implemented in the same way as a similar requirement was previously implemented fo HHVM.
As for nightly: there is no PHPUnit version which is currently compatible …
=> Travis: test builds against PHP 7.4 & work around for PHPUnit 8

WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Tests/WP/EnqueuedResourcesUnitTest.inc
Identified by @joyously in the ThemeReviewCS repo: WPTRT/WPThemeReview#202
When inline jQuery is used to reference a stylesheet link tag, the sniff misidentifies this as a stylesheet which needs to be enqueued.
This very simple fix should prevent that, at least for the reported cases.
=> WP.EnqueuedResources: bug fix

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
Reported by @remcotolsma in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/commit/49e7700073b7486077c95b37afe55d129b3e4881#commitcomment-32391794
While a little esoteric in a WP context, using the WP File Wrapper functions is not a suitable alternative when `php://input` is being read.
Note: an issue should probably be opened to check if any other sniffs should be adjusted to account for `php://input`. I have not verified this at this time, but the input validation sniff comes to mind.
=> AlternativeFunctions: allow for php://input used with file_get_contents()

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
When people run the sniffs without the `-s` option, the messages for some of the errors in this sniff were not specific enough as the "Prefix**AllGlobals**" part would not be seen.
I considered adjusting the error message template `ERROR_MSG`, however, this would cause more confusion as, for instance, namespace declarations will **always** be in the global namespace.
So, I've opted to adjust select error messages instead.
Issue identified by @justintadlock in https://github.com/WPTRT/WPThemeReview/issues/200#issuecomment-464789010
=> PrefixAllGlobals: improve error message clarity

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc, WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
Similar to #1649 which allowed for using `php://input` with `file_get_contents()` and surprisingly inspired by the closing of issue #295.
This PR expands on the earlier work done in relation to the PHP native input streams by:
* recognizing more PHP native input streams;
* recognizing the PHP input stream constants;
* allowing for these in a number of the `file_system_read` group functions as well as for the `file_get_contents` function.
Refs:
* http://php.net/manual/en/wrappers.php.php
* http://php.net/manual/en/features.commandline.io-streams.php
Related #1649
Related #295
Notes:
* I have not checked the WP FileSystem to see if it even could handle these input streams. If it can, we may need to discuss what is the preferred option in that case.
Personally, this to …
=> WP/AlternativeFunctions: allow for more input streams with file related functions

WordPress-Docs/ruleset.xml
=> Docs ruleset: exclude the `InlineComment.SpacingAfter` errorcode

WordPress-Docs/ruleset.xml
The `Generic.Commenting` category has three sniffs:
* `DocComment`
* `Todo`
* `Fixme`
As WP allows to do's and has no opinion on `FIXME` comments, we may as well just include the one sniff we actually need.
=> Docs: make the inclusion of the Generic sniff slightly more specific

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
`curl_version()` doesn't create or need a cURL resource, so is perfectly fine to use.
Ref: http://php.net/manual/en/function.curl-version.php
=> WP/AlternativeFunctions: allow calling `curl_version()`

WordPress/Sniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
Whether people comply with the WP style rules regarding whitespace and such, is irrelevant for determining whether or not a value is sanitized/unslashed.
This fixed a false positive where superglobals which were correctly unslashed/sanitized were not being recognized as such.
Includes unit test in the `ValidatedSanitizedInput` sniff.
=> Sniff::is_sanitized(): make the method more code style independent

WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
Removing some code duplication.
=> GlobalVariablesOverride: implement the Sniff::is_foreach_as() method

WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/WP/DiscouragedConstantsSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/PHP/DevelopmentFunctionsUnitTest.inc, WordPress/Tests/WP/DiscouragedConstantsUnitTest.inc
These should help make the checking of whether or not a function call is a global function, method call or a namespaced function call more consistent.
This also implements allowing for the [`namespace` keyword being used as an operator](https://www.php.net/manual/en/language.namespaces.nsconstants.php#example-258), though this may yield false negatives when the [operator is used in a non-namespaced file](https://www.php.net/manual/en/language.namespaces.nsconstants.php#example-259), but I rate the chances of that happening as small.
These functions will be unit tested by the implementations in various other places and the fact that the existing unit tests still pass after that.
Loosely related to #764
In:
* `Sniff::is_in_isset_or_empty()`
* `Sniff::is_validated()`
* …
=> Improve global function call detection

WordPress/Sniff.php
There may not be a next token during live coding. This prevents the method from evaluating `false` to `0` and looking at the first token in the file.
=> Sniff::is_comparison(): minor defensive coding tweak

WordPress/Sniff.php
There "bracket_closer" index may not be set during live coding/in case of parse errors. This prevents the method from throwing "_Undefined index: bracket_closer_" notices in that case.
=> Sniff::is_assignment(): minor defensive coding tweak

WordPress/Sniff.php, WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php, WordPress/Tests/WP/CronIntervalUnitTest.inc, WordPress/Tests/WP/CronIntervalUnitTest.php
Allows for checking whether a token is (part of) a parameter passed to a specific (set of) function(s).
Optionally checks whether the function call is to a global function.
Optionally only checks the "deepest" function call.
Returns the stack pointer to the `T_STRING` token for the function call or `false`.
Note: most of the time, it is more efficient to sniff from an outward structure-in, however, for some checks going from inside a structure-out works better.
This utility method is specifically for those situations.
This fixes potential false negatives when a method/namespaced function mirroring the name of the PHP array_key_exists() function would be used.
This fixes potential false negatives when a method/namespaced function mirroring the name of the WP unslashing/sanitization …
=> New utility method Sniff::is_in_function_call() + implement use of it

WordPress/Sniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, WordPress/Tests/WP/DeprecatedParametersUnitTest.php, phpcs.xml.dist.sample
The minimum version should be three versions behind the latest WP release, so what with 5.1 being out, it should now be 4.8.
Includes updating the list of deprecated functions. Input for this based on @JDGrimes's WP deprecated code scanner.
=> Update default minimum_supported_version to WP 4.8

WordPress/Sniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
While `doubleval()` is an alias of `floatval()` and shouldn't be used, for the purposes of the `ValidatedSanitizedInput` sniff, both functions should be recognized.
And as `count()` doesn't actually access the data in the variable, but only counts the number of elements, it is also safe to use without unslashing/sanitizing the variable beforehand.
Same goes for the `sizeof()` alias of `count()`.
Fixes #1659
=> Sniff::$unslashingSanitizingFunctions: add doubleval() and count()

WordPress/Sniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
This builds onto the previous enhancement made in #1635 which started recognizing `array_key_exists()` as a way to validate a variable.
`key_exists()` is an alias for `array_key_exists()` and while alias functions shouldn't be used,  for the purposes of the ValidatedSanitizedInput sniff, both functions should be recognized.
Notes:
* Removes the `array_key_exists()` method from the list of `$sanitizingFunctions` as it doesn't belong there and is now handled differently anyway (this should have been removed in #1635).
* Updates the version numbers for the change in the method documentation. We never released version 2.0.1, so both this change as well as the one from #1635 will now be released in 2.1.0.
=> ValidatedSanitizedInput: allow for validation using key_exists()

WordPress/Sniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
This PR builds onto earlier improvements to this sniff via PR #1634 and #1635
It adds a new `Sniff::get_array_access_keys()` utility method to retrieve _all_ array keys for a multi-level array access.
The original `Sniff::get_array_access_key()` method defers to the new method under the hood, however, the behaviour of that method has not changed.
It then implements the use of the new `get_array_access_keys()` method in the `WordPress.Security.ValidatedSanitizedInput` sniff and the `Sniff::is_validated()` method.
This allow for more precise checking of whether the correct variable has been validated properly before use.
This should prevent some false positives as well as false negatives.
=> ValidatedSanitizedInput/Sniff::is_validated(): allow for multi-level array key check

WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
This changes two things:
1. For both the `InputNotValidated` as well as the `InputNotSanitized` error, it will now display the array keys for the variable triggering the error.
Previously, the message would just say `$_POST`, now it will say `$_POST['foo']['bar']`.
2. For the `InputNotValidated`, the error message text has been expanded to make it more obvious how to fix this issue.
Fixes #1541
=> ValidatedSanitizedInput: make the error messages more informative

WordPress/Sniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
When a superglobal variable is being tested with, for instance, `is_numeric()`, unslashing or sanitization are not needed and it's ok for the nonce check to be done after it. This is completely safe.
Ref: https://php.net/manual/en/ref.var.php
Using these type testing functions should however not be regarded as a way of sanitizing/unslashing the variable and the variable does still need to be validated before being passed to one of these functions.
To test whether a variable is used in one of these functions, a new `is_in_type_test()` method has been added to the `WordPressCS\Sniff` class, along with a `$typeTestFunctions` property containing the names of the functions this applies to.
Notes:
* The `is_array()` function which was previously, incorrectly, listed in the …
=> Security: allow for type testing superglobals

WordPress/Sniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.php
This fixes potential false negatives when a method/namespaced function mirroring the name of the WP nonce verification functions would be used.
=> Sniff::has_nonce_check(): add `is_class_object_call()` and `is_token_namespaced()` checks

WordPress/Sniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
Array sanitization via `array_map()` was already recognized. This PR adds recognition of array sanization using `map_deep()`.
**Important note:**
Functions which alter the array by reference, such as the PHP native `array_walk()` and `array_walk_recursive()` are not listed in the new `$arrayWalkingFunctions` property on purpose.
* These cannot easily be used for sanitization as they can't be combined with unslashing, so could only be used in combination with the `$unslashingSanitizingFunctions`.
Additionally as they alter the array by reference, at this moment, accessing the array after the sanitization through one of these function would _still_ trigger errors.
If at some point in the future, the above combination would be accounted for, preventing these additional errors would also need …
=> Sniff::is_sanitized(): allow for map_deep() to sanitize arrays

WordPress/Sniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.php
A function, closure, anonymous class and other OO constructs are all "closed" scopes.
If any of these are nested, they open a nested closed scope and anything within that scope should be disregarded for the purpose of verifying whether or not a nonce check has been executed.
This small change implements that.
This fixes some potential false negatives.
=> Sniff::has_nonce_check(): ignore nonce checks in nested closed scopes

WordPress/Sniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
Whether a comparison is made via a comparison operator or via one of the array-value comparison functions shouldn't make a difference for this sniff. Both ways of making a comparison should be treated the same.
This was, so far, not the case. While `in_array()` was listed in the `$sanitizingFunctions` list, the other array-value comparison functions were not. And for `in_array()` a "missing unslash" error would still be thrown, while this doesn't happen when using straight comparisons.
At the same time, `in_array()` by itself does not_sanitize_ the value.
This PR fixes that and adds a new `is_in_array_comparison()` utility function to the `Sniff` class.
Includes unit tests via the sniff.
=> ValidatedSanitizedInput: treat array-value comparison functions same as other comparisons

WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.inc, WordPress/Tests/Security/EscapeOutputUnitTest.php
=> EscapeOutput: allow for map_deep() to output escape arrays

WordPress/Sniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc
This builds onto the similar changes made for the `ValidatedSanitizedInput` sniff in #1682.
This fixes false positives as reported in #1114 and #1506.
Note: it is not currently checked that the nonce check is done within the same conditional scope as the comparison. Just that it is done within the same _function_ scope.
Fixes #1114
Fixes #1506
=> Sniff::has_nonce_check(): allow for comparing a variable before nonce check

WordPress/Sniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
PHP 7.0 introduced the null coalesce operator, while PHP 7.4 will introduce the null coalesce equal operator.
These operators should be accounted for in the `ValidatedSanitizedInput` sniff as valid ways to validate a variable, but should still allow for the sniff to *also* check for sanitization.
Refs:
* https://php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce
* https://wiki.php.net/rfc/isset_ternary
* https://wiki.php.net/rfc/null_coalesce_equal_operator
Fixes #837
Closes #840 which is superseded by this PR
---
As part of this PR, two methods in the `Sniff` class received changes:
The null coalesce operator `??` is a special comparison operator, in the sense that it doesn't compare a variable to whatever is on …
=> ValidatedSanitizedInput: handle null coalesce (equal) correctly

WordPress/Sniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
As correctly pointed out by @sybrew in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/869#issuecomment-478329921 and confirmed via a trace-back of the functions used by `wp_unslash()`, WP contains two additional unslashing functions which are perfectly valid to use for unslashing received data.
Refs:
* https://developer.wordpress.org/reference/functions/wp_unslash/
* https://developer.wordpress.org/reference/functions/stripslashes_deep/
* https://developer.wordpress.org/reference/functions/stripslashes_from_strings_only/
This commit adds allowance for using these. It also updates the error message to reflect this.
=> ValidatedSanitizedInput: allow for more unslashing functions

WordPress/Sniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.php
This also gets rid of a bug were sanitization was not recognized as such if the call to `wp_unslash()` was nested inside it.
Fixes #572
=> Sniff::has_nonce_check(): allow for unslashing a variable before nonce check

WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.php
Any usage of superglobals in calls to sanitization functions were up to now ignored. As the output of sanitization is normally assigned to a names variable, this meant that it was possible to bypass the nonce verification sniff that way.
I don't believe that was the intended behaviour. Instead IMO, a sanitization call should be allowed prior to the nonce verification, but should not negate the nonce verification check.
=> NonceVerification: bug fix - sanitization is no alternative for nonce check

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
Move the `WordPress.CodeAnalysis.AssignmentInCondition` from the `Extra` ruleset to the `Core` ruleset.
As per the proposal in https://make.wordpress.org/core/2019/03/26/coding-standards-updates-for-php-5-6/
Open actions:
/cc @pento
=> Core: forbid assignments in conditions

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
As per the proposal in #1624, this moves the sniffs which `warn` against the use of loose comparisons from `Extra` to the `Core` ruleset.
Open actions:
/cc @pento
=> Core: warn against the use of loose comparisons

CHANGELOG.md, README.md
* Release date set at this **Monday April 8th**.
* Includes a minor update to the Readme file for the DealerDirect Composer plugin version number. Related to #1628 (which is included in this release)
Reviews & approval welcome. I'll merge this myself (if approved) just before the release.
=> Changelog for WPCS 2.1.0

WordPress/Sniff.php
I encountered a missing global variable called `$current_blog`.
It is used for Multisite installations and referes to the current site, just as `$current_site` (which is included in the list) refers to the current network.
=> Add missing WP global variable `$current_blog`

WordPress/Sniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc
The `Sniff::has_nonce_verification()` method would determine the scope within which to look for a nonce verification function based on the first function condition of the `$stackPtr` being examined.
This breaks when closures/functions are nested within other functions, as the code within those nested constructs will be ignored, while instead, that should be the code which should be examined.
By changing the start point of the scope within which the method looks for nonce verification functions to the deepest nested function, this use-case is handled correctly.
Note that PHPCS 3.5.0 is expected to contain a utility function which can largely replace the code which was now added. Once PHPCS 3.5.0 has been released and WPCS ups it's minimum version requirement, this change should be made. …
=> NonceVerification: improve handling of nested functions

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
WordPress has a global variable `$tag_ID`, used for example in `wp-admin/edit-tags.php` or `wp-admin/term.php`. It should be accepted as an exception for the valid variable name sniff.
=> Accept tag_ID as variable name

WordPress/Sniff.php
Remove `paginate_comments_links` from escaped functions list as it uses `paginate_links` on echo and return which is not a safe function.
=> Remove paginate_comments_links from escaped functions list

WordPress/Sniffs/WP/CapitalPDangitSniff.php, WordPress/Tests/WP/CapitalPDangitUnitTest.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed
Just like in array declarations, when `wordpress` is spelled incorrectly in constant declarations, this will be a false positive in 90% of the cases, so just ignore it.
Fixes #1698
=> CapitalPDangit: ignore misspellings in constant declarations

WordPress/Sniff.php, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.4.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.5.inc
What with WP dropping support for PHP 5.2, I expect that more and more projects will start to use `use` statements in their code.
When the PHPUnit native `PHPUnit\Framework\TestCase` is imported via a `use` statement and then `extend`ed, the WPCS sniffs would not recognize the extending class as a test class.
Adding `TestCase` to the default test class whitelist fixes this.
While this means that any class extending the quite genericly named `TestCase` will now be recognized as a test class, even when the `TestCase` in question is not the PHPUnit native one, I think it's safe to assume that even when it's not the PHPUnit native one, it _will_ be a test base class and for WPCS purposes the extending class can be marked as a test class.
Includes unit test via the `GlobalVariablesOverride` …
=> Sniff::is_test_class(): recognize `TestCase`

WordPress/Sniff.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, WordPress/Tests/WP/DeprecatedParametersUnitTest.php, phpcs.xml.dist.sample
The minimum version should be three versions behind the latest WP release, so what with 5.2 being out, it should now be 4.9.
Includes (not) updating the list of deprecated functions. Input for this based on @JDGrimes's WP deprecated code scanner.
=> Update default minimum_supported_version to WP 4.9

.travis.yml
Travis now offers stages. Using stages we can:
- Run the code style related checks before running any unit tests and stop the build early if any are detected.
- Remove the duplicate unit test runs - i.e. previously we had an extra (third) build against PHP 7.2 (now changed to 7.3) which would run the code style related checks, but would also re-run the unit tests. This extra build will now no longer run the unit tests.
While this does mean that the unit tests will run with a slight delay (the `Sniff` and `Rulesets` stages have to finish before they start), it also means that we:
* Get code style errors reported earlier as it's been moved to be the first stage and the build will just stop if any are found.
* We won't be wasting Travis's resources on builds which will have to be re-run …
=> Travis: run the code style related and ruleset checks in separate stages

WordPress/Sniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
=> Add wp_sanitize_redirect

WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.1.inc, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.php
String array keys for variable array access would also be examined as part of the hook name, while those should be skipped over as they are not part of the _hook_name.
This commit also lowers the nesting level of the loop by continuing early whenever possible.
=> ValidHookName: bug fix  / skip over array keys

composer.json
The repo has moved organization within GitHub.
Replaces #1749
=> Composer: Update repo URL references

.travis.yml
The "quicktest" stage will only run a CS check, ruleset check, linting and the unit tests against low/high PHP/PHPCS combinations. This should catch most issues.
The more comprehensive complete build against a larger combination of PHP/PHPCS combination will now only be run on PRs and merges to `develop`/`master`.
To see the difference, compare the output of the `push` and `pr` Travis runs for this PR.
=> Travis: add "quicktest" stage for non-PR/merge builds

WordPress/Sniffs/PHP/RestrictedPHPFunctionsSniff.php, WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.inc, WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.php
As this sniff is already included in the WP Core ruleset and the enhancement request is about PHP native functions, this seemed liked a logical sniff to add this to.
I've elected to make this an `error` instead of a `warning` as the code within WP Core has been cleaned up for this issue now and it would be good to prevent new instances of `date()` creeping in.
Fixes #1713
=> RestrictedPHPFunctions: add error for use of date()

WordPress/Sniff.php
If a plugin overrides the `$plugin` global, things can break. See https://github.com/Rarst/laps/issues/35.
This variable is missing from the list of global WP variables.
=> Add `$plugin` to the list of global variables that shouldn't be overridden

WordPress/ruleset.xml
Rulesets are processed top-to-bottom, one rule at the time.
For the `WordPress` ruleset, this means that PHPCS would first load the `WordPress-Core` ruleset and process all rules in that file, then read the `WordPress-Docs` ruleset and lastly, the `WordPress-Extra` ruleset.
As the `WordPress-Extra` ruleset includes `WordPress-Core`, it would re-process the `WordPress-Core` ruleset a second time and then process the additional rules in the `Extra` ruleset.
This means that in effect, the `WordPress-Core` ruleset is processed twice when using the `WordPress` ruleset which is inefficient.
By commenting that rule out, we still document that the `WordPress` ruleset includes `WordPress-Core` without double processing the ruleset.
=> WordPress ruleset: efficiency fix

WordPress-Core/ruleset.xml
Recently a new section has been added to the handbook which forbids the use of short arrays.
> Using long array syntax ( array( 1, 2, 3 ) ) for declaring arrays is generally more readable than short array syntax ( [ 1, 2, 3 ] ), particularly for those with vision difficulties. Additionally, it’s much more descriptive for beginners.
>
> Arrays must be declared using long array syntax.
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#declaring-arrays
This PR add an existing upstream sniff which addresses this.
Includes auto-fixer.
Also see: https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/
Loosely related to #764
=> Core: Add upstream Generic.Arrays.DisallowShortArraySyntax sniff

WordPress-Core/ruleset.xml, WordPress/Docs/PHP/DisallowShortTernaryStandard.xml, WordPress/Sniffs/PHP/DisallowShortTernarySniff.php, WordPress/Tests/PHP/DisallowShortTernaryUnitTest.inc, WordPress/Tests/PHP/DisallowShortTernaryUnitTest.php
This new sniff addresses the new "_The short ternary operator must not be used._" rule which was recently added to the handbook.
The sniff has been added to the `WordPress-Core` ruleset.
Refs:
* https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#ternary-operator
* https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/
Includes documentation.
Loosely related to #764
=> New DisallowShortTernary sniff

WordPress/Sniffs/Security/EscapeOutputSniff.php
This improved the error message output when array variables are being accessed.
```php
echo $strings['update-available'];
```
**Old output:**
`All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$strings'.`
**New output:**
`All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$strings['update-available']'.`
No unit tests added as the unit tests don't test the message thrown.
The effect can be tested & confirmed though by running the sniff over the above code snippet.
Partially fixes #749
=> EscapeOutput: improve the error message for non-escaped variables

WordPress/Sniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
WP Core contains the global `$content_width` variable which is intended to be set/overwritten by plugins and themes.
For that reason the variable was previously removed from the `Sniff::$wp_globals` list in WPCS 0.4.0. See #276, #331.
The downside of the variable not being in the list is that the `PrefixAllGlobals` sniff complains about it not being prefixed, as it doesn't realize it is a WP native global variable.
The upside was that the `GlobalVariablesOverride` sniff did not complain about the variable being overwritten.
Adding the variable to the `Sniff::$wp_globals` list would reverse that situation with the `PrefixAllGlobals` sniff staying silent and the `GlobalVariablesOverride` sniff starting to complain.
This PR intends to solve this conundrum.
* The list of WP Core globals in …
=> GlobalVariablesOverride/PrefixAllGlobals: handle WP variables intended to be overwritten

WordPress/Sniff.php
WPCS is running into two PHP 7.4 issues where we use array access on a non-array value.
This PR fixes both.
Refs:
* https://wiki.php.net/rfc/deprecate_curly_braces_array_access
Build showing the issues:
* https://travis-ci.com/WordPress/WordPress-Coding-Standards/jobs/218025587
=> PHP 7.4 compatibility / defensive coding

WordPress-Extra/ruleset.xml, WordPress/Docs/CodeAnalysis/EscapedNotTranslatedStandard.xml, WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php, WordPress/Tests/CodeAnalysis/EscapedNotTranslatedUnitTest.inc, WordPress/Tests/CodeAnalysis/EscapedNotTranslatedUnitTest.php
At times, people will accidentally forget to add the `__` when they intend to use one of the "translate + escape" functions.
I've run into this a number of times now when reviewing/fixing code and found that they aren't that easy to spot visually when you're focussed on other things.
So as it was such an easy sniff to write, I figured I may as well.
AFAICS there are only two escaping functions in core which have direct "translate + escape" sister-functions.
All the same, the sniff has been set up to allow for more similar function-combis to be added.
Includes documentation.
Sniff has been added to the `WordPress-Extra` ruleset.
=> New CodeAnalysis/EscapedNotTranslated sniff

WordPress/Docs/WhiteSpace/CastStructureSpacingStandard.xml, WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.inc.fixed
Allow for no whitespace before a cast when used in combination with a spread operator.
This pre-emptively prevents a fixer conflict between this sniff and the upstream sniff we intend to add to address #1762.
Includes updated docs.
Related #1762
Related #1524
=> CastStructureSpacing: allow for spread operator

WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php, WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.inc, WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.inc.fixed, WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.php
For non-string, non-numeric array keys, WPCS demands a space on the inside of the square brackets around the array key.
Up to now, the _size_ of the whitespace on the inside of the square brackets was not checked.
This PR adds that check.
Includes fixer.
If the array key should not be surrounded by spaces and there was more than one whitespace token between a bracket and the array key, the fixer would take several loops to remove the consecutive whitespace tokens.
This has been changed to fixing the whitespace in one go, reducing the chance of fixer conflicts and making the sniff more efficient.
This can be tested by running the sniff with the `-v` option. Without this fix, the sniff takes 4 loops when fixing the unit test cases in this commit, …
=> ArrayKeySpacingRestrictions: add space size check & fix errors in one go

WordPress/Sniff.php, WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php, WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc.fixed, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed, WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc, WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc.fixed, WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.php, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.1.inc, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.1.inc.fixed, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc.fixed
While we should probably define rules for long/short list constructs, WPCS at this time, does not have a opinion on the formatting of these.
The `Arrays` sniffs, however, would all treat _short lists_ as if they were _short arrays_ and apply the array rules on them.
This PR fixes this by bowing out early if a short array is in actual fact a short list.
Includes unit tests in each of the sniffs in the `Arrays` category affected by this issue.
Fixes #1692
---
This PR also adds a new `Sniff::is_short_list()` utility method to determine whether a _short array_ token is in actual fact representing a PHP 7.1+ short list.
This method will be short-lived in WPCS as it will be introduced in WPCS 3.5.0 and can be deprecated/removed once the minimum required PHPCS version goes up.
=> Array sniffs: ignore short lists

WordPress/AbstractFunctionParameterSniff.php, WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Sniffs/CodeAnalysis/EmptyStatementSniff.php, WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php, WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/PHP/IniSetSniff.php, WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php, WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Sniffs/Security/PluginMenuSlugSniff.php, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Sniffs/WP/DiscouragedConstantsSniff.php, WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php
Partially based on feedback from PHPStan as inspired by @szepeviktor in PR #1782
=> Various minor doc fixes

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
Global variables to which an assignment is made via the long/short `list()` construct should also be prefixed (`PrefixAllGlobals`), unless they are WordPress native global variables, in which case the `GlobalVariablesOverride` sniff should kick in and throw an error about overwriting WP globals.
Includes unit tests for both sniffs.
Fixes #1774 
Loosely related to #764 (short lists, keyed lists)
---
This PR includes adding two new utility methods to the `Sniff` class:
* `Sniff::find_list_open_close()` - Sister-method to the `find_array_open_close()` utility method to find the opener and closer for `list()` constructs, including short lists.
* `Sniff::get_list_variables()`  - A utility method which will retrieve an array with the token pointers to the variables which are being assigned to …
=> PrefixAllGlobals/GlobalVariablesOverride: detect variables being set via list()

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
The `php` prefix is reserved for PHP itself.
No unit tests added as the logic for this blacklist is already sufficiently unit tested.
Fixes #1728
=> PrefixAllGlobals: add "php" to the list of blacklisted prefixes

WordPress/Sniff.php
`sanitize_key()` only allows for lowercase characters, numbers, underscore and dash characters. So a variable run through `sanitize_key()` can be considered just as safe, if not more so, than a variable run through one of the escaping functions.
Ref:
* https://developer.wordpress.org/reference/functions/sanitize_key/
=> EscapeOutput: add sanitize_key() to escaping functions

WordPress/Sniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php
The `Sniff::$safe_casts` token list and the `EscapeOutputSniff::$safe_cast_tokens` were near duplicates.
This removes the duplicate code (which can be safely removed as it is a `private` property) and adds the missing `T_UNSET_CAST` to the `Sniff::$safe_casts` list.
=> EscapeOutput: use Sniff::$safe_casts

WordPress/Sniff.php
While intended for code highlighting of PHP code, based on some tests I've run, the output of the PHP native `highlight_string()` function does appear to be safe, so I'm proposing to add this to the list of `$escapingFunctions`.
Note: I'd appreciate some scrutiny of this PR. I wouldn't want to inadvertently add an unsafe function to the list.
Refs:
* https://3v4l.org/mYK5A
* https://www.php.net/manual/en/function.highlight-string.php
=> EscapeOutput: add highlight_string() to escaping functions

WordPress/Sniffs/PHP/YodaConditionsSniff.php
Performance: Don't unnecessarily use `array_merge()`.
=> YodaConditions: minor efficiency fix

WordPress/Docs/WP/DeprecatedClassesStandard.xml, WordPress/Docs/WP/DeprecatedFunctionsStandard.xml, WordPress/Docs/WP/DeprecatedParameterValuesStandard.xml, WordPress/Docs/WP/DeprecatedParametersStandard.xml
=> New error handling Deprecated Classes and Functions

WordPress/Docs/PHP/DisallowShortTernaryStandard.xml
The valid example line was a bit too long... oops...
=> DisallowShortTernary: improve docs

WordPress/Docs/Classes/ClassInstantiationStandard.xml
=> Documentation Class Instantiation

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
This new function:
* Tries to find a function docblock, if it exists.
* If found, checks if the docblock contains at least one `@deprecated` tag.
Returns boolean true/false.
Note: this method is `static` to allow the `ValidFunctionName` sniff which extends an upstream sniff to use the method as well.
Check the function docblock for a `@deprecated` tag and if found, bow out.
Check the function docblock for a `@deprecated` tag and if found, bow out.
Note: the same should probably also be done for classes/interfaces/traits/constants marked as deprecated, but that's for another PR.
---
Fixes #1797
=> PrefixAllGlobals + ValidFunctionName: ignore deprecated methods by design

WordPress/Docs/Arrays/ArrayKeySpacingRestrictionsStandard.xml, WordPress/Docs/Arrays/MultipleStatementAlignmentStandard.xml
Adds documentation for the following sniffs:
- Arrays.MultipleStatementAlignment
- Arrays.ArrayKeySpacingRestrictions
Related to #1722
=> Array sniffs documentation (Related to #1722)

WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
... with functions which will be deprecated in WP 5.3.
Not updating the `Sniff::$minimum_supported_version` property yet as WP 5.3 has not yet been released.
=> DeprecatedFunctions: update function list

WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
Instead of checking whether a `..._deprecated()` function was matched after the function matching, remove the deprecated hook invocation functions from the target function array in `getGroups()`.
This allows the sniff to fail earlier.
Also remove redundant check for `$parameters[1]`. If there are no parameters, the `process_parameters()` function wouldn't be called anyway.
=> ValidHookName: minor efficiency tweaks

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml, WordPress/Sniffs/DateTime/RestrictedFunctionsSniff.php, WordPress/Sniffs/PHP/RestrictedPHPFunctionsSniff.php, WordPress/Sniffs/WP/TimezoneChangeSniff.php, WordPress/Tests/DateTime/RestrictedFunctionsUnitTest.inc, WordPress/Tests/DateTime/RestrictedFunctionsUnitTest.php, WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.inc, WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.php, WordPress/Tests/WP/TimezoneChangeUnitTest.inc, WordPress/ruleset.xml
This introduces a new `WordPress.DateTime.RestrictedFunctions` sniff which initially includes two groups:
* `timezone_change` - moved from the `WordPress.WP.TimezoneChange` sniff
* `date` - moved from the `WordPress.PHP.RestrictedPHPFunctions` sniff (group not yet in a released WPCS version yet)
The `WordPress.WP.TimezoneChange` sniff is now deprecated.
* The sniff is no longer included in the WPCS rulesets.
* If the sniff is explicitly included via a custom ruleset, deprecation notices will be thrown.
* If the `exclude` property is set from with a custom ruleset, a deprecation notice will be thrown.
The new sniff is now included in the `Core` ruleset.
Note: once WP Core upgrades, the one instance of using `date_default_timezone_set()` in WP Core (in `wp-settings.php`) will need to be …
=> New "DateTime.RestrictedFunctions" sniff

WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.inc, WordPress/Tests/Security/EscapeOutputUnitTest.php
The first parameter passed to [`_deprecated_file()`](https://developer.wordpress.org/reference/functions/_deprecated_file/) generally is `basename( __FILE__ )` based on the code currently in WP Core.
As the result of that function call is safe, I'm proposing making an exception for that particular code pattern when used as the first param in a call to `deprecated_file()`.
Note: the current code does not allow for comments in the first parameter. This would be rare encounter in these function calls anyway and allowance for it can be added later if needs be.
=> EscapeOutput: allow for typical pattern with `_deprecated_file()`

WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.1.inc, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.php
* Trim whitespace off the "expected" and "found" values which are used in the error messages.
* Ignore comments and PHPCS annotations when building up the "expected" and "found" values.
* Improve line precision by throwing the error on the line where the hook name starts, not the line containing the function call.
The unit test basically only tests part 3 of the change. The error message improvement needs visual inspection as the message content is not tested.
=> ValidHookName: improve error messages

WordPress-Core/ruleset.xml, WordPress/Docs/DateTime/CurrentTimeTimestampStandard.xml, WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php, WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.inc, WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.inc.fixed, WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.php
This new sniff adds a check for use of current_time() to retrieve a timestamp.
A (fixable) `error` will be thrown when the `$gmt` parameter is set to `true` or `1`, a `warning` when it is not.
Includes fixer.
Includes documentation.
This new sniff has been added to the `Core` ruleset.
Fixes #1791
/cc @Rarst
=> New DateTime.CurrentTimeTimestamp sniff

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
Similar to #1815, but then for the `PrefixAllGlobals` sniff, allowing it to fail earlier for calls to deprecated hooks.
=> PrefixAllGlobals: minor efficiency tweak

WordPress-Extra/ruleset.xml, WordPress/Docs/NamingConventions/ValidPostTypeSlugStandard.xml, WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php, WordPress/Tests/NamingConventions/ValidPostTypeSlugUnitTest.inc, WordPress/Tests/NamingConventions/ValidPostTypeSlugUnitTest.php
Adds a new sniff. Checks if the first parameters given to a `register_post_type()` call is actually a valid value.
Fixes #1696
=> Fixes #1696, errors on invalid post type

WordPress/Sniff.php, WordPress/Tests/WP/DeprecatedClassesUnitTest.inc, WordPress/Tests/WP/DeprecatedClassesUnitTest.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
What with the target release date for WPCS 2.2.0 being November 11 and the target release date of WP 5.3 being November 12, updating this property before the release is probably a good idea.
=> Update default minimum supported WP version

WordPress/Docs/WP/CronIntervalStandard.xml
=> Adds documentation for WordPress.WP.CronInterval

WordPress/Docs/WP/PostsPerPageStandard.xml
=> Docs: Add PostsPerPage XML doc

WordPress/Docs/PHP/IniSetStandard.xml
=> Adds Ini_set documentation

WordPress/AbstractFunctionParameterSniff.php, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/WP/I18nSniff.php
=> Various minor documentation fixes

CHANGELOG.md
* Release date set at this **Monday November 11th**.
:exclamation: Reviews & approval welcome. I'll merge this myself (if approved) just before the release.
=> Changelog for WPCS 2.2.0

.travis.yml
As [PHP 7.4 has been released](https://www.php.net/archive/2019.php#2019-11-28-1), the build against PHP 7.4 should no longer be allowed to fail.
=> Travis: don't allow PHP 7.4 build to fail

WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc.fixed
Closure `use` parentheses do not have a parenthesis owner.
While this is a plaster on the wound as the sniff really needs to be split up, for now, it fixes the notice.
Fixes #1792
=> ControlStructureSpacing: fix undefined index error

WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
Add metrics to make it easier for people to decide whether or not to en/disable this rule.
The generated metrics will look like this and can be called up using `--report=info`:
```
PHP CODE SNIFFER INFORMATION REPORT
----------------------------------------------------------------------
Multi-line array - comma after last item:
no    => 2,064 ( 95.82%)
yes   =>    90 (  4.18%)
-------------------------
total => 2,154 (100.00%)
Single line array - comma after last item: 0 [804/804, 100%]
```
=> CommaAfterArrayItem: add metrics for comma after last item

WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php
The metrics for this sniff would be different depending on whether or not a (custom/default) whitelist was used.
If `use_default_whitelist` was set to `false` and no custom whitelist was passed, the metrics would look something like this:
```
Error silencing:
@header( 'Content-Type: ' ...                 => 1 ( 12.50%)
@header( 'Content-type: application/json' ... => 1 ( 12.50%)
@header( 'X-Robots-Tag: noindex' ...          => 1 ( 12.50%)
@ignore_user_abort( true ...                  => 1 ( 12.50%)
@include_once $converter_file...              => 1 ( 12.50%)
@ini_get( 'disable_functions' ...             => 1 ( 12.50%)
@ini_set( $key,...                            => 1 ( 12.50%)
@is_file( $this->...                          => 1 ( 12.50%) …
```
=> NoSilencedErrors: improve consistency metrics

WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.6.inc
Fixes #1847.
I would have added a unit test, but it wasn't clear how to add a new case while setting `$treat_files_as_scoped` to `true`.
=> Fix off-by-one error when $treat_files_as_scoped is true

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed, WordPress/Tests/WP/I18nUnitTest.php
When a function call to one of the singular/plural text translation functions - like `_n_noop()` - is missing an argument, the sniff would still try an execute the `compare_single_and_plural_arguments()` check and on PHP 7.4 would generate a "_Trying to access array offset on value of type null_" error which would stop the PHPCS run dead with an `Internal.Exception` error code.
Fixed by skipping the check in that case. The missing argument should be reported by the preceding `check_argument_tokens()` check anyhow.
**Note: I've set this PR to priority high as this bug stops the PHPCS run dead on PHP 7.4, so this fix should be included in the upcoming WPCS 2.2.1 release.**
=> I18n: bug fix - trying to access array offset on null (PHP 7.4)

.travis.yml, composer.json
The new `phpcsstandards/phpcsdevtools` package includes a script which can check whether sniffs are feature complete, i.e. whether all sniffs have unit tests and documentation.
By adding this check to the Travis script, we prevent untested and/or undocumented sniffs from entering the repo.
For now, the documentation check is silenced.
Ref: https://github.com/PHPCSStandards/PHPCSDevTools#checking-whether-all-sniffs-in-a-phpcs-standard-are-feature-complete
P.S.: the `PHPCSDevTools` package contains a few more goodies, have a look at the [readme](https://github.com/PHPCSStandards/PHPCSDevTools) for more information.
=> Travis/QA: always check that all sniffs are feature complete

WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc, WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
This is a follow-up on #1658 which special cased the `curl_version()` function for the `WP.AlternativeFunctions` sniff.
The bug reported to me was that the sniff was throwing an error for the below code:
```php
$curl = curl_version();
$ssl_support = true;
if ( ! $curl['features'] && CURL_VERSION_SSL ) {
$ssl_support = false;
}
```
Turned out, it wasn't throwing an error for the function call to `curl_version()`. Instead it was (incorrectly) throwing an error for the use of the `CURL_VERSION_SSL` constant, thinking that was a function call.
I've fixed this now and added a number of additional unit tests.
With an eye on modern PHP, the abstract sniff(s) needs more work, but as PHPCSUtils is expected to have a similar abstract sniff soon which will take all that into account and which we …
=> AbstractFunctionRestrictions: fix constants being recognized as functions

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed, WordPress/Tests/WP/I18nUnitTest.php
Fixes the non-controversial part of #1419 by adding a sniff that detects translated strings wrapped in HTML tags, and a corresponding unit test. Quoting https://github.com/WordPress/WordPress-Coding-Standards/issues/1419#issuecomment-403797241:
> Examples where the markup _should_ be removed from inside of the string would be:
>
> ```
> <?php __( '<h1>Settings Page</h1>', 'text-domain ); ?>
> should be
> <h1><?php __( 'Settings Page', 'text-domain' ); ?></h1>
> because the markup only wraps the string.
> ```
Note that I had to add code to `I18nUnitTest.php` to reset the text domain as set via `setConfigData()` for one test file, as it would otherwise persist for every test file after that one.
Based on a WordPress.com-internal check. /cc @akirk
=> I18n: Add check to detect string wrapped in HTML

.travis.yml
The Travis docs say that `$TRAVIS_BUILD_STAGE_NAME` is in "proper case" form:
> TRAVIS_BUILD_STAGE_NAME: The build stage in capitalized form, e.g. Test or Deploy. If a build does not use build stages, this variable is empty ("").
However, it looks like they made an (undocumented) change (probably a bug in their script handling) which means that the `$TRAVIS_BUILD_STAGE_NAME` name is now in the case as given, which in this case is _lowercase_.
This means that some of the comparisons are failing and the wrong things are executed for certain builds.
As I expect this to be a bug in Travis, I'm not changing the case for the comparisons at this time.
Instead I'm fixing this by inline fixing the case of the variable for the comparisons.
Refs:
* …
=> Travis: fix the build

WordPress/Sniffs/DB/PreparedSQLSniff.php, WordPress/Tests/DB/PreparedSQLUnitTest.inc
Reported in #1875: using a namespace separator with function calls in the `WordPress.DB.PreparedSQL` triggers a false positive on the namespace separator as "not being escaped".
While this really should be handled differently with proper FQN function name determination for function calls etc, for now, let's just ignore the namespace separator as that is not something which would need to be "prepared".
Fixes #1875
=> PreparedSQL: quick fix for namespace separator

WordPress/Sniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
The minimum version should be three versions behind the latest WP release, so what with 5.4 being out, it should now be 5.1.
Includes updating the list of deprecated functions. Input for this based on @JDGrimes's WP deprecated code scanner & WP Core `trunk`.
=> Update default minimum_supported_version to WP 5.1

WordPress/Sniffs/WP/I18nSniff.php
While running some tests for something else, I noticed that the I18n sniff was throwing all sorts of CS warnings.
Fixed now.
Rename a very long variable name and fix a CS warning for incorrect alignment.
The code as was, was throwing two warnings for the assignment in the for loop. Let's not set a bad example.
=> Clean up the I18n sniff

.travis.yml, composer.json
Update the minimum required PHPCS version to `3.5.0`.
Composer:
* Add PHPCSUtils and PHPCSExtra as dependencies.
* Remove the DealerDirect plugin from `require-dev` as well as from `suggests` as it comes with PHPCSUtils/PHPCSExtra automatically and not having it here may prevent conflicts with allowed versions in the future.
Travis:
* Alias PHPCS 4.x to `3.9.99` to allow testing with the dependencies before PHPCS 4.x is officially supported by them.
* When testing with PHPCS 4.x, we need `--prefer-source` as otherwise the test files we use from PHPCS itself won't be included.
The way I've implemented this uses a [new feature](https://github.com/composer/composer/issues/6301) which is available since Composer 1.10.0 to selectively download from source.
This prevents *all* packages being …
=> 3.0: Composer: set the new requirements for WPCS

.travis.yml
Current situation:
* The Travis native PHPUnit is used in most cases, though on PHP > 7.1, a PHPUnit phar is downloaded.
New situation:
* Always install PHPUnit with Composer.
For PHP 8 (`nightly`) ignore platform requirements to allow PHPUnit 7.x to install.
This makes us less dependent on the Travis images being correct (we've seen problems before aka the current special casing) and as the Travis cache should retain the downloaded Composer packages, this should really have much impact on the build time and gives us more flexibility to add other dev tools.
=> 3.0: Travis: simplify the script

WordPress/Tests/DB/RestrictedClassesUnitTest.php
PHPCS 4.x is set up to use PHPUnit 8+, including using the `void` return type for the `setUp[BeforeClass]()` and `tearDown[AfterClass]()` fixtures.
This commit makes our tests compatible with both PHPCS 3.x as well as 4.x and with PHPUnit < 8 and 8+.
This is done by:
* Renaming the fixtures in use in our test suite to use a different method name ( = only this class).
* And using the PHPUnit `@before` and `@after` annotations, which translate to `setUp()` and `tearDown()` to get round the `void` return type requirement.
Refs:
* https://phpunit.readthedocs.io/en/7.5/annotations.html#before
* https://phpunit.readthedocs.io/en/7.5/annotations.html#after
=> 3.0: Tests/RestrictedClasses: compatibility with PHPCS 4.x

WordPress/Sniffs/PHP/TypeCastsSniff.php
That token is no longer needed as the tokenization in PHPCS upstream was fixed in PHPCS 3.4.0.
Fixes #1600
=> 3.0: TypeCasts: remove sniffing for `T_STRING_CAST`

WordPress-Core/ruleset.xml
The `Generic.Arrays.DisallowShortArraySyntax` sniff does not take short lists using square brackets `[]` into account, which leads to incorrect detection and fixing of more modern PHP code.
The `Universal.Arrays.DisallowShortArraySyntax` sniff in PHPCSExtra does take short lists into account and prevents these issues.
Fixes #1838
Ref: https://github.com/PHPCSStandards/PHPCSExtra/pull/40
=> 3.0: Core: replace `Generic.Arrays.DisallowShortArraySyntax` with `Universal` version

WordPress-Extra/ruleset.xml
…with the `Generic` one.
Fixes #1616
=> 3.0: Extra: replace the `Squiz.WhiteSpace.LanguageConstructSpacing` sniff

.gitattributes, Tests/bootstrap.php, composer.json, phpunit.xml.dist
While not strictly necessary, it makes life easier to have this bootstrap in place.
The bootstrap file will:
* Load the PHPCS autoloader (was previously done from the command-line);
* Load the Composer autoload file.
* Will automatically set the `PHPCS_IGNORE_TESTS` environment variable to the correct value to prevent running tests from other standards.
For locally running the tests after having run `composer install`, all should work fine.
For locally running the tests with a _git clone_ of PHPCS, a `phpunit.xml` overload file can be used with a `env` variable `PHPCS_DIR` to point the bootstrap to that install. Do make sure that PHPCSUtils is installed and registered in the `installed_paths` of that install if you do so.
=> 3.0: Tests: add a bootstrap file

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractFunctionParameterSniff.php, WordPress/Sniff.php, WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php, WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php, WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php, WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php, WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php, WordPress/Sniffs/PHP/IniSetSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Sniffs/WP/DiscouragedConstantsSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
... in favour of the PHPCSUtils version of those methods.
This brings us:
* Improved functionality.
* Fewer bugs.
* Improved PHPCS cross-version compatibility.
* All PHPCSUtils are unit tested in depth.
**Note**: the current removals are based on [PHPCSUtils 1.0.0-alpha3](https://github.com/PHPCSStandards/PHPCSUtils/releases). There are a number of other methods which are still on the PHPCSUtils "To do" list, so I expect more utility methods to be removed/switched out in future PRs. 
For full details on the upstream classes and methods used, see the [PHPCSUtils documentation](https://phpcsutils.com/phpdoc/namespaces/phpcsutils-utils.html).
The removal is done in three steps, which correspond to the commits in this PR:
* Deprecate the old code
* Switch over any uses of the old code
* …
=> 3.0: Remove some utility methods from the Sniff class

WordPress-Core/ruleset.xml
PHPCSUtils does not contain any sniffs, so adding this rule isn't strictly necessary, but by having the rule in the ruleset anyway, if PHPCSUtils is missing, the user will get a descriptive error message - `ERROR: Referenced sniff "PHPCSUtils" does not exist` - during the loading of the ruleset instead of a fatal "class not found" error once the sniffs start running.
Adding this only in the `Core` ruleset is sufficient.
Both `Extra` as well as `WordPress` include `Core` and `Docs` currently doesn't use any sniffs which use PHPCSUtils, so doesn't need it.
Inspired by https://github.com/sirbrillig/phpcs-variable-analysis/issues/160
=> 3.0: Core ruleset: add PHPCSUtils requirement

WordPress/Sniffs/Classes/ClassInstantiationSniff.php, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php, WordPress/Tests/Classes/ClassInstantiationUnitTest.php, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
PHPCS 4.x will completely remove the JS/CSS tokenizers and all supporting features for JS/CSS support.
Until support for PHPCS 3.x will be dropped, WPCS will continue to support sniffing JS/CSS files.
This commit addresses the current PHPCS cross-version compatibility issues related to JS/CSS sniffing in WPCS:
* Prevent "Undefined property" notices in PHPCS 4.x for when WPCS tries to access the (removed) `File::$tokenizerType` property.
* Don't expect any errors/warnings in CSS/JS files being sniffed when on PHPCS 4.x.
=> PHPCS 4.x compatibility: allow for the JS/CSS tokenizer being dropped in PHPCS 4.x

WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.php
The `T_INSTANCEOF` token was added to the `OperatorSpacing` sniff targets in PR #1598.
In upstream PR squizlabs/PHP_CodeSniffer#2516, the same was done for the upstream sniff. This PR was merged & included in PHPCS 3.5.0.
As the minimum PHPCS version for WPCS has now been changed to PHPCS 3.5.0, the WPCS sniff no longer needs to register the `T_INSTANCEOF` token.
Includes _removing_ the unit tests related to this as the WPCS sniff should only test the differences between the upstream sniff and the WPCS version.
Includes minor code simplification for the remaining code.
=> OperatorSpacing: defer to upstream for "instanceof"

WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.php
This PR will be easiest to review by looking at the individual commits.
Use the improved PHPCSUtils versions of the PHPCS native methods.
Refs:
* [isMagicFunctionName()](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-FunctionDeclarations.html#method_isMagicFunctionName)
The magic method name list in PHPCSUtils is more complete than the one in the PEAR sniff.
Note: As this sniff bows out for methods declared in extended classes anyway, the PHP native double underscore methods from the SOAPClient class do not need to be taken into account, which is why the `isMagicMethodName()` method is used instead of the `isSpecialMethodName()` method.
Refs:
* [isMagicMethodName()](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-FunctionDeclarations.html#method_isMagicMethodName)
* …
=> 3.0: ValidFunctionName: implement PHPCSUtils and more

.travis.yml, composer.json
Parallel-Lint, as the name implies, runs PHP lint in parallel, making it faster than native linting.
It also provides more helpful output with a syntax highlighter code snippet showing the context of syntax errors.
And lastly, it allows for easily running PHP linting over the files in a local dev environment.
So, as we're now doing a full `composer install` on every Travis build anyway, we may as well use this tool.
=> CI: use Parallel-Lint

WordPress/Sniffs/WP/CapitalPDangitSniff.php, WordPress/Tests/WP/CapitalPDangitUnitTest.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed, WordPress/Tests/WP/CapitalPDangitUnitTest.php
This PR will be easiest to review by looking at the individual commits.
* The `Tokens::$textStringTokens` property was introduced in PHPCS 2.9.0 and is the same as the `$text_string_tokens` property in this sniff.
Replacing this was missed in an earlier review round after the minimum PHPCS version changed.
* Use the PHPCSUtils [`ObjectDeclarations::getName()`](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-ObjectDeclarations.html#method_getName) method instead of the PHPCS native `File::getDeclarationName()` method for a slightly more stable result.
Up to now, class names, trait names and interface names were already checked, but namespace names were not checked for the correct spelling of `WordPress`.
This new feature has now been added.
No need to call …
=> 3.0: CapitalPDangit: implement PHPCSUtils and check namespace names

WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Tests/WP/EnqueuedResourcesUnitTest.inc, WordPress/Tests/WP/EnqueuedResourcesUnitTest.php
This PR is a part of the next milestone where we are adding [PHPCSUtils](https://phpcsutils.com/) into existing sniffs.
- Added extra tokens to the check, to account for multiline text strings and inline HTML as well
- Fixed the handling of multi-line text strings:
- As it was, if the text the sniff is looking for was split over multiple lines, the sniff would incorrectly not throw an error (false negative).
By using the PHPCSUtils [`TextStrings::getCompleteTextString()`](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-TextStrings.html#method_getCompleteTextString) method, we can get access to the complete content of a multi-line text string and prevent the false negative.
This does create two minor complications though:
1. The complete text string may contain multiple link/script …
=> 3.0: EnqueuedResources: PHPCSUtils implementation

WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
The `$data` parameter of the `$phpcsFile->add[Fixable]Error|Warning()` methods is expected to be an array, not a string.
Without this fix, PHP 8 will throw an (uncaught) `TypeError: vsprintf(): Argument #2 ($args) must be of type array, string given`.
=> PHP 8 | ControlStructureSpacing: bug fix - $data should be an array

WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed
If an array item has something else on the same line before it, the indentation should be left alone.
This fixes a potential fixer conflict with the `DisallowInlineTabs` sniff which could occur when the sniffs are being run in a unconventional order.
Discovered when making a change to the Travis file and not reproducible locally, but consistently reproducible with the alternative running order of sniffs on select platforms, as per the [Travis build on Xenial](https://travis-ci.com/github/WordPress/WordPress-Coding-Standards/builds/176411794).
=> ArrayIndentation: bug fix - prevent fixer conflict

WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.inc
The `PassedParameters::getParameter()` method (and the `Sniff::get_function_call_parameter()` method before it), either returns an array with information on the parameter or `false` if the parameter does not exist.
A call to `trigger_error()` and the likes, without passing parameters is a little useless and will throw a warning in PHP 4/5/7 and a fatal `ArgumentCountError` in PHP 8.
However, those types of errors are not the concern of this sniff, so if a call to these functions is encountered without arguments, the sniff should conclude that there is nothing which needs escaping and bow out.
Fix now, including unit test to safeguard against it in the future.
=> EscapeOutput: defensive coding

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Sniff.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php
The "minimum WP version" related utilities are only used by a small set of sniffs, so are better placed in a dedicated trait.
This moves the `$minimum_supported_version` property and the `get_wp_version_from_cl()` method to a new `WordPressCS\WordPress\Helpers\MinimumWPVersionTrait` and starts using that trait in the relevant sniffs.
The `get_wp_version_from_cl()` method now uses the PHPCSUtils `Helper::getCommandLineData()` method instead of the `Helper::getConfigData()` for more reliable results.
Because of this change, the `$phpcsFile` object is now a required parameter for the `get_wp_version_from_cl()` method.
All calls to the method have been adjusted for this change.
--- [EDIT] New commit --- 
... to `get_wp_version_from_cli()` as per the review suggestion. …
=> Move "minimum WP version" related utilities to dedicated `MinimumWPVersionTrait`

WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php, WordPress/Tests/CodeAnalysis/EscapedNotTranslatedUnitTest.inc
The PHPCS native `getTokensAsString()` method has two drawbacks:
1. It is fiddly to use as you always need to do some calculation to find the number of tokens you want to method to concatenate.
2. It will concatenate **everything**, i.e. including new lines, comments etc.
The `getTokensAsString()` method is often used to display a "found" string in an error message and the error message would benefit from that "found" string being clean of comments and having whitespace compacted.
In comes PHPCSUtils. PHPCSUtils has dedicated [`GetTokensAsString`](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-GetTokensAsString.html) class which contains a variety of methods to retrieve a concatenated string of the content of a group of tokens.
So, for the `EscapedNotTranslated` sniff, replacing …
=> EscapedNotTranslated: use PHPCSUtils `GetTokensAsString`

.travis.yml
Initially I was only going to pull the first commit, but Composer `1.10.11` has just come out and is breaking builds, so the second commit is a temporary fix for that.
Once this PR has been merged, I will rebase @NielsdeBlaauw's two Docs PRs so we can have a passing build for those.
The builds are failing a little too often for my taste on the below error.
```
[Composer\Downloader\TransportException]
Peer fingerprint did not match
```
I'm prefixing the `composer install` commands now with `travis_retry` in an attempt to get round this problem.
Ref:
* https://docs.travis-ci.com/user/common-build-problems/#timeouts-installing-dependencies
~~... as there is an issue with Composer 1.10.11, which prevents the `install` from working.~~
~~For more information: composer/composer#9191~~
=>  Travis: retry composer install on failure

WordPress/Docs/WP/CapitalPDangitStandard.xml
Note I used 'Discouraged:' in the second standard code example.
This is because it is not necesserily invalid, but I still want
to mention the opposite of the 'correct'/'valid' use.
Opinions on this?
Related to #1722
=> Adds documentation for the WordPress.WP.CapitalPDangit sniff.

WordPress/Sniffs/PHP/TypeCastsSniff.php, WordPress/Tests/PHP/TypeCastsUnitTest.inc, WordPress/Tests/PHP/TypeCastsUnitTest.inc.fixed, WordPress/Tests/PHP/TypeCastsUnitTest.php
The `(unset)` cast has been removed in PHP 8 and should never be used.
Includes updated unit tests.
=> TypeCasts: change `(unset)` cast from warning to error

WordPress/Helpers/IsUnitTestTrait.php, WordPress/Sniff.php, WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-global-namespace-extends.1.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-global-namespace-extends.2.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.1.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.2.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.3.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.4.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.1.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.2.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.3.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.4.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.5.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.4.inc
This PR will be easiest to review by looking through the individual commits.
Related to #1877
This method is currently unused in WPCS and it is not 100% clear what the method _should_ do, so removing the method for now.
If needs be it can be brought back later if/when there is more clarity on what the method is supposed to solve.
The "is this test code" related utilities are only used by a small set of sniffs, so are better placed in a dedicated trait.
This moves the (`public`) `$custom_test_class_whitelist` and the `$custom_test_class_whitelist` properties as well as ~~the `is_token_in_test_method()` and~~ the `is_test_class` method to a new `WordPressCS\WordPress\Helpers\IsUnitTestTrait` and starts using that trait in the relevant sniffs.
The trait has been made stand-alone, i.e. it …
=> 3.0: Move "is unit test" utility functions to dedicated trait

WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.inc
Not a perfect solution as it doesn't take imported or namespaced functions into account, but that will need to wait for PHPCSUtils.
For now, it can prevent some false positives for fully qualified calls to `basename()`.
=> Security/EscapeOutput: bug fix - allow for basename() being fully qualified

.github/workflows/unit-tests.yml
As it looks like PHPCS 4.x is still quite a while away (2022 at the earliest), let's stop testing against PHPCS 4.x for the time being.
This should allow build failure reporting to be more accurate, as currently every PR has a failure on PHPCS 4.x due to a bug in some of the new code in 4.x (fix for this was pulled six months ago and still not merged).
The build against PHPCS 4.x should be re-enabled closer to the PHPCS 4.x release.
Note: PHPCSUtils will continue to test against PHPCS 4.x and will update the provided utilities ahead of time, so with a bit of luck, by the time the build against PHPCS 4.x is re-enabled, the build should largely pass thanks to the compatibility layers in PHPCSUtils.
=> GH Actions: don't test against PHPCS 4.x (yet)

WordPress/Helpers/MinimumWPVersionTrait.php
PHP 8.1 deprecates passing `null` to PHP native functions where the parameter(s) is not explicitly nullable.
While in PHP 8.1 this is only a deprecation, it should, of course, still be fixed.
This commit contains a fix for the one of the two issues in WordPressCS found related to this so far (based on the unit tests).
Passing `null` to `trim()` is now deprecated, so more defensive coding or explicit type casting is needed.
This comes into play for the `MinimumWPVersionTrait::get_wp_version_from_cli()` method where the `Helper::getCommandLineData()` method can return either string or `null`.
Ref: https://phpcsutils.com/phpdoc/classes/PHPCSUtils-BackCompat-Helper.html#method_getCommandLineData
=> PHP 8.1 compatibility: fix deprecation notice [1]

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/WP/I18nSniff.php
PHP 8.1 deprecates passing `null` to PHP native functions where the parameter(s) is not explicitly nullable.
While in PHP 8.1 this is only a deprecation, it should, of course, still be fixed.
This commit contains a fix for the second of the two issues in WordPressCS found related to this so far (based on the unit tests).
Passing `null` to `trim()` is now deprecated, so more defensive coding or explicit type casting is needed.
This comes into play for the `I18nSniff::process_token()` and the `PrefixAllGlobalsSniff::process_token()` methods where the `Helper::getConfigData()` method can return either string or `null`.
Ref: https://phpcsutils.com/phpdoc/classes/PHPCSUtils-BackCompat-Helper.html#method_getConfigData
=> PHP 8.1 compatibility: fix deprecation notice [2]

.github/workflows/unit-tests.yml
Letting PHPUnit read the config file causes an error on PHP 8.1 in combination with PHPUnit 7.
For now, special case the test run on PHP 8.1 and pass the only necessary config from the configuration file via CLI arguments.
=> GH Actions: get the tests running on PHP 8.1 (nightly)

.github/workflows/quicktest.yml, .github/workflows/ruleset-checks-sniffs.yml
The cs2pr tool will allow to display the results from an action run in checkstyle format in-line in the PR code view, which should improve usability of the workflow results.
Ref: https://github.com/staabm/annotate-pull-request-from-checkstyle
... as the `quicktest` workflow is run on `push` events, not on PRs, so displaying results in a PR is not relevant (and is done via the `test` workflow which _is_ run on `pull` events anyhow).
=> GH Actions: report CS violations in the PR

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
Pulling this after @GaryJones brought this up as [a suggestion on Slack](https://wordpress.slack.com/archives/C5VCTJGH3/p1568550568000300).
WP Core currently has 27 violations against this rule - 3 in `src`, the rest in `tests`.
All the same, it would be a good thing to move this sniff to the `Core` ruleset. /cc @pento 
Open questions:
* The `Extra` configuration downgraded this to a `warning`. Should this be an `error` or a `warning` now it's moving to `Core` ?
* The `Extra` configuration also adjusted the error message. Is this still necessary or should we just use the default message from the sniff ?
Location | Message
--------- | -------
Original sniff error message | `Only one object structure is allowed in a file`.
Message as it was in `Extra` | `Best practice suggestion: Declare …
=> OneObjectStructurePerFile: move from `Extra` to `Core`

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractClassRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
Though it is by the looks of it only a "beta" feature for the moment, I noticed in PR #1997 that warnings are now being shown for files unrelated to the current PR. To me this is just plain annoying as it is noise which distracts from the actual changes which need reviewing and can be confusing for contributors (should I fix these ? will my changes be accepted even though these warnings are there?).
With that in mind, I figured I might as well try to reduce this noise some more as well as fix up some other small issues.
... which show through in PRs, even when the code in those files has not been adjusted in the PR.
There's only one such warning remaining now, which is _actual_ commented out code.
=> CS/QA: get rid of (most) warnings

.github/workflows/quicktest.yml, .github/workflows/unit-tests.yml
Turns out the default setting for `error_reporting` used by the SetupPHP action is `error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT` and `display_errors` is set to `Off`.
For the purposes of CI, I'd recommend running with `E_ALL` and `display_errors=On` to ensure **all** PHP notices are shown.
In this script, error_reporting was already enabled, but the error display was not yet fixed. Sorted now.
=> GH Actions: turn display_errors on

WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php
... to the default "ignore" list.
The `libxml_disable_entity_loader()` function is deprecated in PHP 8.0, but a call to the function is still needed in select circumstances, in which case silencing the deprecation warning is perfectly acceptable.
... as WP now includes WebP support.
=> PHP/NoSilencedErrors: add two functions to the ignore list

.github/workflows/quicktest.yml, .github/workflows/ruleset-checks-sniffs.yml, .github/workflows/unit-tests.yml, composer.json
The `dealerdirect/phpcodesniffer-composer-installer` Composer plugin is used to register external PHPCS standards with PHPCS.
As of Composer 2.2.0, Composer plugins need to be explicitly allowed to run. This adds the necessary configuration for that.
Refs:
* https://blog.packagist.com/composer-2-2/#more-secure-plugin-execution
Previously, in Travis, when the same branch was pushed again and the "Auto cancellation" option on the "Settings" page had been turned on (as it was for most repos), any still running builds for the same branch would be stopped in favour of starting the build for the newly pushed version of the branch.
To enable this behaviour in GH Actions, a `concurrency` configuration needs to be added to each workflow for which this should applied to.
More than anything, this is …
=> CI: various updates

README.md
In the readme.md file it is stated that PHP 5.2 is the minimum supported PHP version, while it's already PHP 5.6 for quite some time and technically WP does not work on PHP 5.2-5.5.
=> README.md: Update the minimum supported PHP version

WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Tests/WP/CronIntervalUnitTest.inc, WordPress/Tests/WP/CronIntervalUnitTest.php
This allows for a time calculation to be wrapped in parentheses.
Fixes #2025
---
Note: just looking at the code, I can see multiple additional improvements which could/should be made:
* Only search for close parenthesis as a "valueEnd" if the `$valueStart` token is an open parenthesis.
* Allow for more assignment operators - the new schedule could be build up bit by bit and only assigned to the array later.
These additional things are not addressed here. This just addresses the immediate issue.
=> WP/CronInterval: bug fix for parentheses

.github/workflows/quicktest.yml, .github/workflows/ruleset-checks-sniffs.yml, .github/workflows/unit-tests.yml
A number of predefined actions have had major releases, which warrant an update to the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
=> GH Actions: version update for various predefined actions

.github/workflows/ruleset-checks-sniffs.yml
Fix failing installation of the xmllint tooling.
=> GH Actions/CS: fix build failure

composer.json
PHP Console Highlighter has released version `1.0.0` and PHP Parallel Lint version `1.3.2` is the first PHP Parallel Lint version which supports PHP Console Highlighter `1.0.0`.
As the minimum supported PHP version is still PHP 5.3 for both, we can safely update both dependency requirements.
Refs:
* https://github.com/php-parallel-lint/PHP-Console-Highlighter/releases/tag/v1.0.0
* https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.3.2
=> Composer: update PHP Parallel Lint and Console Highlighter

WordPress-Core/ruleset.xml
Fixes #1500
Note: as this isn't so much about coding standards, but about error prevention, I don't think this needs an entry in the Coding Standards docs.
=> Core: add the `Generic.VersionControl.GitMergeConflict` sniff

composer.json
While rare, there are some deprecations which PHP can show when a file is being linted.
By default these are ignored by PHP-Parallel-Lint.
Apparently though, there is an option to show them (wasn't documented until recently), so let's turn that option on.
=> GH Actions: show deprecations when linting

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/dependency-change.md, .github/workflows/quicktest.yml, .github/workflows/ruleset-checks-sniffs.yml, .github/workflows/unit-tests.yml, README.md, composer.json
While the minimum PHPCS version has already been upped to PHPCS 3.5.0 previously for the WPCS 3.0.0 branch, I'm proposing to up it yet further to the latest PHPCS version available.
PHP 8.0 and 8.1 introduced a lot of new syntaxes and, while a lot of this can be supported for older PHPCS versions via PHPCSUtils, this will always impact performance and precision, so it is strongly advisable to use the latest PHPCS version as the new minimum if we want to support the newly available PHP syntaxes.
For now, I'm upping the minimum version to PHPCS 3.6.2, which is the latest PHPCS release. This will unblock PRs to add support for PHP 8.0 features to WPCS.
Once PHPCS 3.7.0 has been released, the minimum PHPCS version should be upped again to unblock adding support for PHP 8.1 features to WPCS. …
=> Composer: up the minimum PHPCS version to 3.6.2

WordPress/Helpers/IsUnitTestTrait.php
Update the test class list based on changes in WP Core:
* The `Block_Supported_Styles_Test` was never a `TestCase`, but was a concrete test placed in the wrong directory.
* The `PHPUnit_Adapter_TestCase` class was added to allow for PHPUnit cross-version support.
Other than that, the list is now alphabetized within each category and the categories are annotated with comments.
=> IsUnitTestTrait: update test class list

WordPress/Docs/PHP/YodaConditionsStandard.xml
A basic example of a proper (and improper) Yoda conditional, with links back to full documentation on why.
=> Document YodaConditionals you must

WordPress/Helpers/DeprecationHelper.php, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
The "deprecation" related utilities are only used by a small set of sniffs, so are better placed in a dedicated class.
This commit moves the `is_function_deprecated()` method to a new `WordPressCS\WordPress\Helpers\DeprecationHelper` and starts using that class in the relevant sniffs.
**Note**:
It is expected for PHPCSUtils to have dedicated methods for the same at some point in the future. If/when those methods become available, it is recommended for the sniffs to start using the PHPCSUtils methods and for this class to be deprecated and removed in the next major release.
PHP 8.0 introduced attributes, which can be placed - and commonly are placed - between a function declaration and its docblock.
Ref: https://www.php.net/manual/en/language.attributes.php
This commit …
=> 3.0: Move "deprecation" related utilities to dedicated DeprecationHelper + handle PHP 8.0 attributes

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/dependency-change.md, .github/workflows/quicktest.yml, .github/workflows/ruleset-checks-sniffs.yml, .github/workflows/unit-tests.yml, README.md, composer.json
PHPCS 3.7.0 has just been released.
As discussed in issue #2048 and PR #2049, to add support for PHP 8.1 features to WPCS and prevent false positives related to PHP 8.1 features, this commit ups the minimum supported PHPCS version to PHPCS 3.7.0.
Includes updating the GH Actions matrixes for this change.
Fixes #2048
Refs: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.7.0
=> Composer: up the minimum PHPCS version to 3.7.0

WordPress/Helpers/VariableHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
The "array access keys" related utilities are only used by a small set of sniffs, so are better placed in a dedicated class.
This commit moves the `get_array_access_keys()` method and the `get_array_access_key()` method to a new `WordPressCS\WordPress\Helpers\VariableHelper` and starts using that class in the relevant sniffs.
In contrast to some of the other "move methods out of the Sniff class" PRs, these methods have been moved to a class and made `static` - instead of moved to a `trait`.
The reason for this difference is that the methods in other "moves" are setting properties which the sniff classes would need access to, while these methods are 100% stand-alone.
**Note**:
It is expected for PHPCSUtils to have dedicated methods for the same at some point in the future. If/when those …
=> 3.0: Move "variable" related utilities to dedicated VariableHelper + use PHPCSUtils + handle match

WordPress/Helpers/DeprecationHelper.php, WordPress/Helpers/TextStringHelper.php
For the `Helper` classes which do not contain WordPress specific code and for which it is likely that PHPCSUtils may at some point replace the functionality, make it very clear that those classes are not covered by a promise of backward-compatibility.
By doing this, we buy ourselves the freedom to remove methods from these classes/the classes completely if/when PHPCSUtils would offer similar functionality, without the need to create a new major release of WPCS when we do.
=> Helper classes: explicitly state there is no BC promise

WordPress-Extra/ruleset.xml, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Helpers/IsUnitTestTrait.php, WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php, WordPress/Sniffs/DB/RestrictedFunctionsSniff.php, WordPress/Sniffs/DB/SlowDBQuerySniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Sniffs/PHP/IniSetSniff.php, WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/PHP/NoSilencedErrorsUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.4.inc, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.4.inc.fixed, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.2.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7a.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7b.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7c.inc
Note: not claiming completeness - this PR is based on a code-base wide search for the terms `whitelist` and `blacklist`. Other potential non-inclusive terminology is not (yet) addressed, though I expect there won't be much else.
Related to #1915
---
... and update sniffs using that array key.
👉🏻 Note: this is a breaking change for any external sniffs extending this base class.
As this is a `protected` property, this is an internal change only (unless an external standard would be extending the sniff).
As this is a `protected` property, this is an internal change only (unless an external standard would be extending the sniff).
As this is a `protected` property, this is an internal change only (unless an external standard would be extending the sniff).
As this is a `protected` property, …
=> Remove typical non-inclusive language from the repo

WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Tests/WP/CronIntervalUnitTest.inc, WordPress/Tests/WP/CronIntervalUnitTest.php
If the WP time constants would be used in their fully qualified form, as is often encountered in namespaced files, the sniff would no longer be able to correctly determine the interval being scheduled.
Note: To prevent constants from a different namespace accidentally matching the WP native constants, the namespace separator is replace by a space character rather than just ignored. The regex before running the `eval()` will prevent code with identifier names other than the WP time constants from being passed to the `eval()`, meaning those will still be reported as "interval undetermined".
This commit fixes that.
=> WP/CronInterval: bugfix for fully qualified time constants

WordPress-Core/ruleset.xml
This PR will reorder the core ruleset to match the current [WordPress PHP Coding Standards handbook](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/) chapters.
The links to the handbook has been updated as well.
Closes #2064
=> Reorder core rules

composer.json
As per getcomposer.org/doc/04-schema.md#keywords by including "static analysis", then later versions of Composer will prompt users if the package is installed with `composer require` instead of `composer require-dev`.
=> Update composer.json keywords

.github/workflows/ruleset-checks-sniffs.yml, WordPress/Docs/Arrays/ArrayIndentationStandard.xml, WordPress/Docs/Arrays/ArrayKeySpacingRestrictionsStandard.xml, WordPress/Docs/Arrays/CommaAfterArrayItemStandard.xml, WordPress/Docs/Arrays/MultipleStatementAlignmentStandard.xml, WordPress/Docs/Classes/ClassInstantiationStandard.xml, WordPress/Docs/CodeAnalysis/EscapedNotTranslatedStandard.xml, WordPress/Docs/DateTime/CurrentTimeTimestampStandard.xml, WordPress/Docs/DateTime/RestrictedFunctionsStandard.xml, WordPress/Docs/NamingConventions/PrefixAllGlobalsStandard.xml, WordPress/Docs/NamingConventions/ValidHookNameStandard.xml, WordPress/Docs/NamingConventions/ValidPostTypeSlugStandard.xml, WordPress/Docs/PHP/IniSetStandard.xml, WordPress/Docs/PHP/StrictInArrayStandard.xml, WordPress/Docs/PHP/YodaConditionsStandard.xml, WordPress/Docs/Security/SafeRedirectStandard.xml, WordPress/Docs/WP/CapitalPDangitStandard.xml, WordPress/Docs/WP/CronIntervalStandard.xml, WordPress/Docs/WP/DeprecatedClassesStandard.xml, WordPress/Docs/WP/DeprecatedFunctionsStandard.xml, WordPress/Docs/WP/DeprecatedParameterValuesStandard.xml, WordPress/Docs/WP/DeprecatedParametersStandard.xml, WordPress/Docs/WP/EnqueuedResourceParametersStandard.xml, WordPress/Docs/WP/EnqueuedResourcesStandard.xml, WordPress/Docs/WP/PostsPerPageStandard.xml, WordPress/Docs/WhiteSpace/CastStructureSpacingStandard.xml, WordPress/Docs/WhiteSpace/OperatorSpacingStandard.xml, WordPress/Docs/WhiteSpace/PrecisionAlignmentStandard.xml, composer.json
PHPCSDevTools 1.2.0 introduces an XSD for the XML docs which can accompany sniffs.
This commit:
* Updates the PHPCSDevTools to version 1.2.0.
* Adds a new check against the XSD for all sniff XML Docs files.
Ref: https://github.com/PHPCSStandards/PHPCSDevTools/releases/tag/1.2.0
Includes minor tweaks to some of the titles.
Includes adding the `<?xml..?>` header if it didn't exist in the file.
=> Composer/GH Actions: start using PHPCSDevTools 1.2.0

.github/workflows/quicktest.yml, .github/workflows/unit-tests.yml
GitHub has deprecated the use of `set-output` (and `set-state`) in favour of new environment files.
This commit updates workflows to use the new methodology.
Refs:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
~~The `xmllint-problem-matcher` action runner has released a new version which updates it to use node 16.
This gets rid of a warning which was shown in the action logs.~~
~~Note: I've [suggested to the author to use long-running branches for the action runner instead](https://github.com/korelstar/xmllint-problem-matcher/pull/7), which would make this update redundant, but no telling if or when they'll respond to that, …
=> GH Actions: various updates

.github/workflows/ruleset-checks-sniffs.yml
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
=> GH Actions: harden the workflow against PHPCS ruleset errors

.github/CONTRIBUTING.md, .github/workflows/quicktest.yml, .github/workflows/ruleset-checks-sniffs.yml, .github/workflows/unit-tests.yml, README.md, WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, composer.json
**_Note: this is a minimal update to get rid of some deprecations and such. Once this has been merged, a lot more PRs will follow which will actually implement the new functionality from PHPCSUtils 1.0.0-alpha4._**
Ref: https://github.com/PHPCSStandards/PHPCSUtils/releases/tag/1.0.0-alpha4
Follow up on #2058
The minimum PHPCS version for PHPCSUtils 1.0.0 will be 3.7.1, so the minimum PHPCS version for WPCS should be in line with that.
The difference between 3.7.0 and 3.7.1 is very small. They were released just days apart with 3.7.1 fixing a pertinent bug in the retokenization of reserved keywords, which was updated in PHPCS 3.7.0.
Includes updating the GH Actions matrixes for this change.
All the `Collections` class properties have been deprecated in PHPCSUtils 1.0.0-alpha4 in favour of …
=> Update for PHPCSUtils 1.0.0-alpha4

WordPress/Helpers/TextStringHelper.php, WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php, WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php, WordPress/Tests/NamingConventions/ValidPostTypeSlugUnitTest.inc, WordPress/Tests/NamingConventions/ValidPostTypeSlugUnitTest.php
... in favour of the significantly more comprehensive PHPCSUtils `TextStrings::stripEmbeds()` method.
This improves the handling of embedded variables in double quoted strings (and consequently fixes some bugs).
Bug confirmed via the tests added to the `ValidPostTypeSlug` sniff.
Without this fix, the "text stripped of embeds" for these test cases would look like this:
```
string(24) "testing123-${(foo)}-test"
string(19) "testing123-"]}-test"
```
I.e. the embeds wouldn't be, or wouldn't be completely, stripped.
With the fix, the embeds in both texts are correctly stripped, resulting in:
```
string(16) "testing123--test"
```
As for the sniff, for the `ValidPostTypeSlug` sniff, the bug meant that the sniff would report three false positives:
```
55 | ERROR   | register_post_type() called …
```
=> TextStringHelper: remove the strip_interpolated_variables() method

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
PHPCSUtils 1.0.0-alpha4 has a new `Context` class containing a more versatile method for the same, so we can now switch out the WPCS native method for the PHPCSUtils one.
Ref: https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-Context.html#method_inForeachCondition
=> Sniff::is_foreach_as(): switch over to the PHPCSUtils version

WordPress-Extra/ruleset.xml
The reason why the sniff was disabled up to now was that WP uses callbacks a lot and the hooked in functions may not use all parameters passed to them.
This concern was previously raised in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/382#discussion_r29981655, also see https://github.com/WordPress/WordPress-Coding-Standards/pull/382/commits/522b35f3ebac915d6eebb92624fc703c193aee60
To this end, I've send in a [PR upstream](https://github.com/squizlabs/PHP_CodeSniffer/pull/1318) to address these concerns, which has subsequently been merged. The adjusted version of the sniff was released in PHPCS 3.4.0, which means the sniff can now be added.
Note: the sniff has since then also been adjusted to handle arrow functions correctly, as well as constructor property …
=> WPCS-Extra: enable the `Generic.CodeAnalysis.UnusedFunctionParameter` sniff

WordPress-Core/ruleset.xml, WordPress/Docs/WhiteSpace/ObjectOperatorSpacingStandard.xml, WordPress/Sniffs/WhiteSpace/ObjectOperatorSpacingSniff.php, WordPress/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.php
This sniff largely defers to the upstream `Squiz.WhiteSpace.ObjectOperatorSpacing` sniff, which was previously already included.
The only real difference between the two sniffs is that for class resolution using `ClassName::class`, new lines around the `::` object operator will not be ignored.
The WPCS sniff has the same default property settings as the upstream sniff and changes to the property values should be made in the ruleset.
Includes docs.
Includes unit tests covering the difference and safeguarding that the sniff doesn't overreach.
Related to: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#magic-constants
=> :sparkles: New `WordPress.WhiteSpace.ObjectOperatorSpacing` sniff

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
> 1. No parentheses shall be used for `include[_once]` and `require[_once]` statements.
>    As `include[_once]` and `require[_once]` are language constructs, they do not need parentheses around the path.
> 2. There should be exactly one space between the `include[_once]` and `require[_once]` keyword and the start of the path.
> 3. It is strongly recommended to use `require[_once]` for unconditional includes.
>    When using `include[_once]` PHP will throw a warning when the file is not found, but will continue execution which will almost certainly lead to other errors/warnings/notices being thrown if your application depends on the file being available, potentially leading to security leaks. For that reason, `require[_once]` is generally the better choice as it will throw a Fatal Error …
=> Core: move rules related to include/require statements from `Extra` to `Core`

WordPress-Core/ruleset.xml
As this rule is now in the handbook and has been explicitly listed in the Make post from March 2020, the error message should not look like a recommendation, but like the error which it is.
The standard message from the upstream sniff reads: "Only one object structure is allowed in a file".
Note: the upstream sniff we're using has been updated already to include PHP 8.1 `enum`s.
Refs:
* https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/ - One class-like definition per file section
* https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#only-one-object-structure-class-interface-trait-per-file
* WordPress/WordPress-Coding-Standards#1802
* WordPress/wpcs-docs#52
=> Core: remove custom message for `OneObjectStructurePerFile` sniff

.phpcs.xml.dist, WordPress-Core/ruleset.xml
> 1. There should be no blank line between the content of a function and the function’s closing brace.
Includes removing this rule from the WPCS native ruleset in which we already enforced it (as it will now be inherited from the `WordPress` ruleset).
Refs:
* https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/ - Function closing brace section
* https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#remove-trailing-spaces
* https://github.com/WordPress/wpcs-docs/pull/110
Loosely related to #1101
=> Core: add sniffs to check there is no blank line before a function close brace

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
> 1. For all constructs which allow it (properties, methods), visibility should be explicitly declared.
> 2. Using the var keyword for property declarations is not allowed.
The `PSR2.Classes.PropertyDeclaration` sniff contains a multitude of checks, amongst which two error codes which IMO should probably not (yet) go into the `Core` ruleset.
* `Underscore` - which warns against prefixing a property name with an underscore, advising to use visibility instead. While I'm 100% in favour of this, introducing this for WP Core would be problematic as renaming (`public`/`protected`) properties would be a BC-break.
* `Multiple` - which throws an error for multi-property declarations. I have excluded it as it is not something which is explicitly forbidden in the handbook, nor was it mentioned in …
=> Core: move rules related to explicit property/method visibility from `Extra` to `Core`

WordPress-Core/ruleset.xml
> 1. There should be one space, or a new line + appropriate indentation, before the spread operator.
> 2. There should be no space between the spread operator and the variable/function call it applies to.
> 3. When combining the spread operator with the reference operator, there should be no space between them.
Includes excluding a particular error code from the `Squiz.Functions.FunctionDeclarationArgumentSpacing` sniff to prevent duplicate messages about the same thing.
Refs:
* https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/ - Operators section
* https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#spread-operator
* WordPress/wpcs-docs#105
* WordPress/WordPress-Coding-Standards#1762
* squizlabs/PHP_CodeSniffer#2548 …
=> Core: add sniff to check spacing around spread operators

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
> 1. Use of the backtick operator is not allowed.
Refs:
* https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/ - Shell Commands section
* https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#shell-commands
* WordPress/wpcs-docs#114
* WordPress/WordPress-Coding-Standards#646
=> Core: move `BacktickOperator` sniff from `Extra` to `Core`

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
> 1. When using multiple modifiers for a property or method declaration, the order should be as follows:
>     1. First the optional `abstract` or `final` keyword.
>     2. Next a visibility keyword.
>     3. Lastly, the optional `static` [red: or `readonly`] keyword.
For property declarations, this is already covered by the `PSR2.Classes.PropertyDeclaration` sniff.
For method declarations, the `PSR2.Methods.MethodDeclaration` sniff has now been moved from `Extra` to `Core`.
The `PSR2.Methods.MethodDeclaration` sniff contains one additional error code, which IMO should probably not (yet) go into the `Core` ruleset.
* `Underscore` - which warns against prefixing a method name with an underscore, advising to use visibility instead.
While I'm 100% in favour of this, introducing this for WP …
=> Core: add initial sniffs for modifier keyword ordering rules

.github/workflows/quicktest.yml, .github/workflows/ruleset-checks-sniffs.yml, .github/workflows/unit-tests.yml
Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like `8.1.11`.
> * The options passed via `composer-options`.
> * The dependency version setting as per `dependency-versions`.
> * The working directory as per `working-directory`.
> * A hash of the `composer.json` and/or `composer.lock` files.
This means that aside from other factors, the cache will always be busted when changes are made to the (committed) `composer.json` or the …
=> GH Actions: bust the cache semi-regularly

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php
Discovered while working on #2112 that the command line argument wasn't being picked up by the `getCommandLineData` helper in the `get_wp_version_from_cli` method.
@jrfnl and I did all the manual tests to confirm that nothing will break with this change.
=> Minimum version trait fix

WordPress-Core/ruleset.xml, WordPress/Docs/WP/ClassNameCaseStandard.xml, WordPress/Sniffs/WP/ClassNameCaseSniff.php, WordPress/Tests/WP/ClassNameCaseUnitTest.inc, WordPress/Tests/WP/ClassNameCaseUnitTest.php
... to check that any class name references to WP native classes used the case of the class as per the class declaration.
As class names in PHP are case-insensitive, this is a `warning`, not an `error`.
**Open questions:**
* Should the same by checked for classes from external dependencies, like PHPMailer, SimplePie, Requests etc ? We could have separate arrays (groups) for each of these.
* Is the name of the sniff correct or should it be made more generic ? I mean, at this time, WP only contains classes, no interfaces, traits or enums, but that may change in the future and the logic for checking this is largely the same, so it would make sense to add those checks to this sniff.
I'm proposing to add this sniff to the WP Core ruleset, so both Core as well as plugins and themes will benefit …
=> :sparkles: New `WordPress.WP.ClassNameCase` sniff

.github/workflows/quicktest.yml, .github/workflows/unit-tests.yml, composer.json
Closes #2115.
The PR groups the checks that are useful to pass before the sniff is pushed to the repo for a PR.
It also adds a description of all the custom commands defined in the `scripts` section.
I'm not too happy about the `check-complete` description, as it's a bit long so I need to split it into two lines, which doesn't look too nice.
But I couldn't omit all the necessary information about what this command is doing 🤷🏼‍♂️
=> Group all the checks in one place and add script descriptions

WordPress-Extra/ruleset.xml, WordPress/Docs/WP/CapabilitiesStandard.xml, WordPress/Sniffs/WP/CapabilitiesSniff.php, WordPress/Tests/WP/CapabilitiesUnitTest.1.inc, WordPress/Tests/WP/CapabilitiesUnitTest.2.inc, WordPress/Tests/WP/CapabilitiesUnitTest.3.inc, WordPress/Tests/WP/CapabilitiesUnitTest.php
The sniff will check if the functions that are accepting capabilities as the argument actually use capabilities ([as described in the support article](https://wordpress.org/support/article/roles-and-capabilities/)) and not roles.
The sniff was rewritten from the original one in #1364 to include helper functions from PHPCSUtils. The list of core functions that are using capabilities as a parameter was updated with changes up to WordPress 6.1.0. The list of capabilities was updated as well. The sniff is also compatible with PHP 8 (named arguments).
Original PRs:
https://github.com/WordPress/WordPress-Coding-Standards/pull/1364
https://github.com/WPTT/WPThemeReview/pull/36
Ref:
https://make.wordpress.org/themes/handbook/review/required/#10-classic-themes …
=> Add sniff that will check that capabilities are used correctly.

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/CapabilitiesSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc, WordPress/Tests/WP/CapabilitiesUnitTest.1.inc, WordPress/Tests/WP/CapabilitiesUnitTest.php
As discussed in #2113, this changes the name for both the CLI setting as well as the property to `minimum_wp_version` in all applicable places.
Note: documentation (`phpcs.xml.dist.sample` and the Wiki) is not being updated in this PR. The wiki should be reviewed and updated just before release. The update to the `phpcs.xml.dist.sample` file is included in a WIP PR to update all public facing documentation just before the release.
Closes #2113
Note: This is a **breaking change** and should be so annotated in the changelog.
=> MinimumWPVersionTrait: rename minimum WP version property

WordPress/Tests/WP/CapabilitiesUnitTest.4.inc, WordPress/Tests/WP/CapabilitiesUnitTest.php
In the `CapabilitiesUnitTest::setCliValues()` method, the config value for `'minimum_wp_version'` is set for two test case files, but as the sniff did not have a test case file which would be run _after_ that, it would never get _unset_ again, which means it could negatively influence other tests as the value will persist and the value from the CLI will overrule "ruleset" passed values (including the values passed using `phpcs:set`).
This fixes this issue by adding an extra test case file, which makes sure that the CLI value gets reset/deleted.
Notes:
* The "proper" way to do this would be to use the test `tear_down()`, but unfortunately, the `tear_down()` doesn't have access to the `$config`, so resetting the value won't work.
* This is a known bug in the test framework for which I have …
=> WP/Capabilities: tests - prevent CLI value leaking

.github/workflows/ruleset-checks-sniffs.yml, WordPress/AbstractFunctionParameterSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
This commit gets rid of the last two PHPCS warnings in the code base, which allows us to run the CS check without allowing for warnings anymore.
=> CS: minor tweaks/don't allow warnings

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Tests/WP/DeprecatedClassesUnitTest.inc, WordPress/Tests/WP/DeprecatedClassesUnitTest.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
The minimum version should be three versions behind the latest WP release, so what with 6.1 being out, it should now be 5.8.
Includes adding a little more variation to the example code in the property docblock in the `MinimumWPVersionTrait`.
Includes updating the list of deprecated functions in the `WP.DeprecatedFunctions` sniff based on the WP 6.1.1 release. Input for this based on @JDGrimes's WP deprecated code scanner, though that is getting more and more difficult to run as it is no longer maintained and is throwing lots of errors.
Notes:
* The `sanitize_url()` function has been _un_deprecated in WP 5.9. See #2031.
* The replacement for the deprecated `wp_cache_reset()` function has been changed in WP Core.
Ref: https://core.trac.wordpress.org/changeset/52705
* The …
=> Update the minimum_wp_version to WP 5.8

.github/workflows/manage-labels.yml
This is a quite straight-forward workflow to just remove some labels which should only be on open issues/open PRs and which should be removed once an issue or PR has been closed/merged.
Just attempting to reduce yet some more manual labour.
**_Note: this is the first time I'm using this particular action runner, so consider this experimental and tweaks may be needed still._**
=> GH Actions: automate some label management

WordPress-Core/ruleset.xml
Follow up on #2102
This adds two new sniffs to the Core ruleset to cover the keyword modifier order rules for class declarations and OO constant declarations.
Refs:
* https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#visibility-and-modifier-order
* WordPress/wpcs-docs#108
* PHPCSStandards/PHPCSExtra#142
* PHPCSStandards/PHPCSExtra#143
=> Core: add sniffs to check class/constant modifier keyword order

WordPress-Core/ruleset.xml, WordPress/Sniff.php, WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php, WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
> 1. There should be no space between an increment/decrement operator and the variable it applies to.
> 2. Pre-increment/decrement should be favoured over post-increment/decrement for stand-alone statements.
>    “Pre” will in/decrement and then return, “post” will return and then in/decrement.
>    Using the “pre” version is slightly more performant and can prevent future bugs when code gets moved around.
Refs:
* https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/ - Increment/decrement operators section
* https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#space-usage
* https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#increment-decrement-operators
* WordPress/wpcs-docs#112
* …
=> Core: add sniffs to check formatting of increment/decrement operators

WordPress-Core/ruleset.xml
> 1. Type declarations must have exactly one space before and after the type.
>    In case of a multi-line function declaration, a new line + appropriate indentation should be used before the type declaration.
> 2. The nullability operator is regarded as part of the type declaration and there should be no space between this operator and the actual type.
> 3. Keyword-based type declarations should use lowercase.
> 4. Class/interface name based type declarations should use the case of the class/interface name as declared.
>
> And specifically for return type declarations:
> 5. There should be no space between the closing parenthesis of the function declaration and the colon starting a return type.
>
> These rules apply to all structures allowing for type declarations: functions, closures, …
=> Core: add sniffs to check formatting for type declarations

.github/workflows/manage-labels.yml
Follow up on #2127
Let's try this without the quotes around the labels. The example in the action runners' readme didn't contain quotes, I added them as the labels we use have a `:` in it, which has special meaning in YAML workflows, but clearly that's not working.
If this doesn't work either, I may need to report it as a bug to the action runner (or find another action runner for the same).
=> GH Actions: tweak label management workflow

WordPress-Core/ruleset.xml, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
The sniff in PHPCSExtra throws a `warning`. This is in line with the wording now used in the WP Core CS handbook.
All the same, as warnings for the `src` directory are currently ignored in CI for WP Core, we could consider making this an `error` once all known instances have been fixed, which should be soon as the fixes are all lined up to be committed, and we _really_ don't want new ones being introduced (as renaming the parameter after introduction would be a BC-break). For `Extra` we could then choose to make this less opinionated and revert it to a `warning`.
Refs:
* WordPress/wpcs-docs#120
* PHPCSStandards/PHPCSExtra#80
Related to WP Core tickets:
* https://core.trac.wordpress.org/ticket/51553
* https://core.trac.wordpress.org/ticket/55327
* …
=> Core: add sniff to discourage using reserved keywords as param names

WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php, WordPress/Tests/PHP/PregQuoteDelimiterUnitTest.inc, WordPress/Tests/PHP/PregQuoteDelimiterUnitTest.php
1. Adjusted the way the correct parameter is retrieved to use the new PHPCSUtils 1.0.0-alpha4 `PassedParameters::getParameterFromStack()` method.
2. Verified the parameter name used is in line with the name as per the PHP 8.0 release.
PHP itself renamed a lot of parameters in PHP 8.0. As named parameters did not exist before PHP 8.0, the parameter name as per PHP 8.0 (or above) is the only relevant name.
Includes minor tweak to the warning message to remove mention of the parameter position.
=> PHP/PregQuoteDelimiter: add support for PHP 8.0+ named parameters

WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, WordPress/Tests/WP/DeprecatedParametersUnitTest.php
1. Adjusted the way the correct parameter is retrieved to use the new PHPCSUtils 1.0.0-alpha4 `PassedParameters::getParameterFromStack()` method.
2. Verified the parameter name used is in line with the name as per the WP 6.1 release.
WP has been renaming parameters and is probably not done yet, but it doesn't look like those changes (so far) made it into changelog entries.... _sigh_.
It also looks like in the past, deprecated parameters were being renamed to `$deprecated` on deprecation. This practice should be strongly discouraged in the context of named parameters, but that's a different discussion and outside of the scope of this commit.
For the purposes of this exercise, I've taken the _current_ parameter name as the "truth" as support for named parameters hasn't officially been …
=> WP/DeprecatedParameters: add support for PHP 8.0+ named parameters

WordPress-Core/ruleset.xml
Related to previous efforts which already fixed all instances of this in WP Core.
The sniff from PHPCSExtra includes an auto-fixer for the issue.
Note: the sniff from PHPCSExtra also contains a check for nested `dirname()` function calls. This check is not (yet) enabled as the fix for this requires PHP 7.0+.
Fixes #1954
Refs:
* PHPCSStandards/PHPCSExtra#172
* PHPCSStandards/PHPCSExtra#187
Related to WP Core tickets:
* https://core.trac.wordpress.org/ticket/48082
* https://core.trac.wordpress.org/changeset/47198
=> Core: add sniff to enforce the use of __DIR__ instead of dirname(__FILE__)

WordPress-Core/ruleset.xml
The `function` and `const` keywords when used in import `use` statements are tokenized as `T_STRING`, not their keyword token, which means that the `Generic.PHP.LowerCaseKeyword` overlooks these.
This adds an additional sniff, which specifically checks that the `function` and `const` keywords in import `use` statements are in lowercase.
=> Core: ensure more keywords are lowercase

WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Tests/PHP/StrictInArrayUnitTest.inc, WordPress/Tests/PHP/StrictInArrayUnitTest.php
1. Changed the `$target_functions` property to not only contain information about "always needed", but also about the target parameter name and position.
2. Adjusted the logic in the sniff to allow for named parameters using the new PHPCSUtils 1.0.0-alpha4 `PassedParameters::getParameterFromStack()` method..
3. The parameter names used are in line with the name as per the PHP 8.0 release.
PHP itself renamed a lot of parameters in PHP 8.0. As named parameters did not exist before PHP 8.0, the parameter name as per PHP 8.0 (or above) is the only relevant name.
Also see: https://github.com/php/doc-en/pull/2044
=> PHP/StrictInArray: add support for PHP 8.0+ named parameters

.github/workflows/basic-qa.yml, .github/workflows/quicktest.yml, .github/workflows/unit-tests.yml
... of the bash `date` command in the earlier pulled cache busting.
PHP 8.2 has been released today 🎉 and the `setup-php` action has announced support for PHP 8.3, so adding PHP 8.3 to the matrix.
Note: PHPCS does not (yet) have full syntax support for PHP 8.2, but it does have runtime support (for the most part, see squizlabs/PHP_CodeSniffer#3629).
Builds against PHP 8.3 are still allowed to fail for now.
=> GH Actions: various tweaks / add PHP 8.3

WordPress-Extra/ruleset.xml, WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php
This PR will add the following useful rules to the WordPress-Extra ruleset from the PHPCSExtra ruleset:
- `Universal.Arrays.DuplicateArrayKey`
- `Universal.CodeAnalysis.ConstructorDestructorReturn`
- `Universal.CodeAnalysis.ForeachUniqueAssignment`
- `Universal.CodeAnalysis.StaticInFinalClass`
- `Universal.ControlStructures.DisallowLonelyIf`
- `Universal.Files.SeparateFunctionsFromOO`
For the entire documentation of the added sniffs check the [documentation](https://github.com/PHPCSStandards/PHPCSExtra).
The PR also fixes the violations of the newly added sniffs and does a small cleanup of the spaces in the ruleset file.
=> Extra: add additional rules

WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php, WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.inc, WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.php
Fixes #1472
Includes updated unit tests.
=> WP/EnqueuedResourceParameters: change `MissingVersion` to a warning

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/CapabilitiesSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php
... and implement it in the relevant places.
The PHP native `version_compare()` function expects two "PHP-standardized" version number strings and has some quirks if the numbers are not "PHP-standardized", i.e. one of the two numbers is a `#.#`-style version number, while the other is a `#.#.#`-style version number.
See: https://3v4l.org/OUMWE
This helper method works round those quirks and will ensure that the version comparisons done with the `$this->minimum_wp_version` are correct.
This fixes some subtle (and unreported) bugs with the version comparisons.
=> MinimumWPVersionTrait: add new `wp_version_compare()` method (bug fix)

WordPress/Helpers/WPHookHelper.php, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
... as it is not currently used anywhere in the WPCS codebase.
The "hook" related property is only used by a small set of sniffs, so are better placed in a dedicated class.
This commit moves the `$hookInvokeFunctions` property to a new `WordPressCS\WordPress\Helpers\WPHookHelper` class and starts using that class in the relevant sniffs.
Note:
* The property is now `private` (and `static`).
* Access to the property can be obtained via the new `WPHookHelper::get_functions()` method.
* This new method can also pre-filter the list to only return thos functions which are not specifically to invoke deprecated hooks.
... to support retrieving the hook name parameters from a stack of parameters, while supporting PHP 8.0+ function calls using named arguments.
This new method will …
=> New `WPHookHelper` utility class, incl PHP 8.0+ named param helper

WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
PHP 8.0 introduced union types which use the `T_BITWISE_OR` - `|` - token to separate the types. The `|` when used in a union type will be retokenized as `T_TYPE_UNION` since PHPCS 3.6.0.
PHP 8.1 introduced intersection types which use the `T_BITWISE_AND` - `&` - token to separate the types. PHP 8.1 also changed the way the `&` is tokenized natively in PHP itself. The PHP 8.1 tokenization change was accounted for in PHPCS 3.6.1. The `&` when used in a intersection types will be retokenized as `T_TYPE_INTERSECTION` since PHPCS 3.7.0.
PHP 8.1 `readonly` properties necessitated an extra fix in PHPCS to retokenize the `T_BITWISE_OR` token to `T_TYPE_UNION` for property types. This fix was included in PHPCS 3.7.0.
The union type separator and the intersection type separator are not a "normal" …
=> WhiteSpace/OperatorSpacing: add extra tests with PHP 8.0+ types

WordPress/Sniffs/PHP/YodaConditionsSniff.php
I've only done a cursory review of this sniff, i.e. not a deep dive analysis as [the intention is for this sniff to be removed](https://make.wordpress.org/core/2022/06/14/upcoming-disallow-assignments-in-conditions-and-remove-the-yoda-condition-requirement-for-php) as soon as consensus is reached.
With that in mind, I can't justify spending much time on improving this seriously flawed sniff, which doesn't protect against anything.
=> PHP/YodaConditions: implement PHPCSUtils + more tweaks

WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
Use the PHPCSUtils `Collections::arrayOpenTokensBC()` to future-proof the sniff for issues with the array tokenization, which keep cropping up every other PHP release.
=> Arrays/CommaAfterArrayItem: minor tweaks

WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
If an auto-fix contains more than one instruction, it should be wrapped in `beginChangeset()`/`endChangeset()` function calls.
This auto-fix code could potentially touch two tokens, so should included the changeset wrapper function calls.
FYI: the wrapper calls are used to potentially revert changes if they would conflict with changes made by another sniff in the same fixer loop. In that case, the changes are attempted again in the next fixer loop, with the fixer trying up to 50 loops before giving up.
=> Arrays/ArrayKeySpacingRestrictions: small bug fix

WordPress/Sniff.php, WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
The `Sniff::$cacheGetFunctions`, `Sniff::$cacheSetFunctions` and `Sniff::$cacheDeleteFunctions` properties are _only_ used by the `WordPress.DB.DirectDatabaseQuerySniff` sniff, so these don't belong in the generic base `Sniff` class.
A [code search](https://sourcegraph.com/search?q=context:global+-%3Ecache%28Get%7CSet%7CDelete%29Functions+-file:%5E%28.*/%29%3Fvendor/wp-coding-standards/.*%24&patternType=regexp&case=yes&sm=0) also shows these properties are not used by sniffs from external standards, so this change should have no noticeable impact.
=> Sniff: move the `$cache*Functions` properties to the `DB/DirectDatabaseQuery` Sniff

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Helpers/IsUnitTestTrait.php, WordPress/Helpers/RulesetPropertyHelper.php, WordPress/Sniff.php, WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php, WordPress/Sniffs/WP/CapabilitiesSniff.php, WordPress/Sniffs/WP/I18nSniff.php
The "property handling" related utilities are only used by a limited set of sniffs, so are better placed in a dedicated class.
This commit moves the `merge_custom_array()` method to a new `WordPressCS\WordPress\Helpers\RulesetPropertyHelper` and starts using that class in the relevant sniffs.
Note: the function has been moved without changes.
=> Move "property handling" related utilities to dedicated `RulesetPropertyHelper`

WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Tests/PHP/StrictInArrayUnitTest.inc
The `'raw'` key in the parameter arrays returned from the `PassedParameters` class contains - as per the name - the _raw_ contents of the parameter.
Since PHPCSUtils 1.0.0-alpha4, the return array also contain a `'clean'` index, which contains the contents of the parameter cleaned of comments.
By switching to using that key, some false positives get prevented.
Includes unit tests demonstrating the issue and safeguarding the fix.
=> PHP/StrictInArray: prevent some false positives

WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php, WordPress/Tests/PHP/NoSilencedErrorsUnitTest.inc, WordPress/Tests/PHP/NoSilencedErrorsUnitTest.php
... to cover a previously uncovered condition (and ensure that the configurable `$context_length` parameter is handled correctly).
As the methods from `GetTokensAsString` work slightly differently from the PHPCS native `File::getTokensAsString()` method, this would result in a "one token longer" code snippet. The `-1` in the function call in line 225 has been added to prevent this change in behaviour without the need for people to update the `context_length` property value in their custom ruleset (which would be an unnecessary BC-break).
Functionally, using the `GetTokensAsString::compact()` method will result in the code snippet in the error message being "cleaner" as those will no longer contain comments found in the code. The PHPCSUtils method will also "compact" the whitespace, so no …
=> PHP/NoSilencedErrors: implement PHPCSUtils methods

WordPress/Sniffs/PHP/IniSetSniff.php, WordPress/Tests/PHP/IniSetUnitTest.inc, WordPress/Tests/PHP/IniSetUnitTest.php
2. Verified the parameter names used are in line with the names as per the PHP 8.0 release.
PHP itself renamed a lot of parameters in PHP 8.0. As named parameters did not exist before PHP 8.0, the parameter name as per PHP 8.0 (or above) is the only relevant name.
Ref: https://www.php.net/manual/en/function.ini-set.php
The `'raw'` key in the parameter arrays returned from the `PassedParameters` class contains - as per the name - the _raw_ contents of the parameter.
Since PHPCSUtils 1.0.0-alpha4, the return array also contain a `'clean'` index, which contains the contents of the parameter cleaned of comments.
By …
=> PHP/IniSet: add support for PHP 8.0+ named parameters + bug fix

WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php, WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.inc, WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.inc.fixed, WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.php
For the purposes of this exercise, I've taken the _current_ parameter name as the "truth" as support for named parameters hasn't officially been announced yet, so any renames _after_ this moment are the only ones relevant.
The `'raw'` key in the parameter arrays returned from the `PassedParameters` class contains - as per the name - the _raw_ contents of the parameter.
Since …
=> DateTime/CurrentTimeTimestamp: add support for PHP 8.0+ named parameters + minor tweak

WordPress/Sniffs/Security/PluginMenuSlugSniff.php, WordPress/Tests/Security/PluginMenuSlugUnitTest.inc, WordPress/Tests/Security/PluginMenuSlugUnitTest.php
For the purposes of this exercise, I've taken the _current_ parameter name as the "truth" as support for named parameters hasn't officially been announced yet, so any renames _after_ this moment are the only ones relevant.
Adjust one test to use lowercase `__file__` to safeguard that the sniff correctly recognizes that these magic constants are case insensitive.
Throw the error on …
=> Security/PluginMenuSlug: implement PHPCSUtils and support modern PHP

WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.1.inc, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.php
Simplify the `transform_complex_string()` method by using the PHPCSUtils utilities to split a text string containing interpolated variables or expressions, instead of using custom logic to do this in the sniff.
Functionally this has no impact. The "old" code already handled complex expressions correctly.
Performance-wise, this could (should) have a small, positive impact as PHPCSUtils caches the results of the splitting of the text string and using the Utils functions allows for simplifying the logic in the function itself, which is called three times for each double quoted teẋt string.
Includes a few extra tests with some more complex variables/expressions.
Iterates on previously pulled PR #2056.
As function calls via closure callbacks are getting more common, probably a good idea to …
=> NamingConventions/ValidHookName: implement PHPCSUtils and support modern PHP

WordPress/Helpers/VariableHelper.php, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
The "is assignment" related utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
As this method also primarily expects a `T_VARIABLE` token as input, the `VariableHelper` class seems appropriate.
This commit moves the `is_assignment()` method to the new `WordPressCS\WordPress\Helpers\VariableHelper` and starts using that class in the relevant sniffs.
=> Move "is assignment" related utility to dedicated `VariableHelper`

WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Tests/WP/CronIntervalUnitTest.inc, WordPress/Tests/WP/CronIntervalUnitTest.php
This commit contains no functional changes.
... to add code coverage for some edge cases already accounted for in the code.
Follow up on #2026 (not yet released) which added handling of time calculations wrapped in parentheses to the sniff.
This improves on the initial fix by making the code more stable and preventing parse errors in the code (which will eventually be eval-ed) due to unmatched parentheses.
PHP 7.4 introduced arrow functions.
While these may not be the first choice for returning an adjusted array value, like is required for adjusting the `cron_schedules`, it is still perfectly possible to do so, so the sniff should handle callbacks declared via arrow functions correctly.
PHP 7.4 introduced numeric literals with …
=> WP/CronInterval: implement PHPCSUtils and support modern PHP 

WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Updated the array of parameters to search for based on a review of all calls to the `_deprecated_argument()` function in WP Core.
Findings:
* `get_user_option()` was listing the wrong WP version for its deprecation.
Ref: https://developer.wordpress.org/reference/functions/get_user_option/
* `unregister_setting()` was looking for the wrong (positional) parameter. Includes updating the unit test.
Ref: https://developer.wordpress.org/reference/functions/unregister_setting/
* The `_future_post_hook()` function contains a _soft_ deprecated parameter. Should still be detected by WPCS. As per the function docblock, I've set the expected value to `null`.
Ref: https://developer.wordpress.org/reference/functions/_future_post_hook/
* The `_load_remote_block_patterns()` is a newly deprecated function …
=> WP/DeprecatedParameters: verify against WP Core

WordPress/Sniffs/WP/DiscouragedConstantsSniff.php, WordPress/Tests/WP/DiscouragedConstantsUnitTest.inc, WordPress/Tests/WP/DiscouragedConstantsUnitTest.php
Ignore tokens preceded by the nullsafe object operator as they won't be the global constant.
Includes minor maintenance tweak to use a predefined array for all object operators.
Ignore tokens preceded by the `enum` keyword as they won't be the global constant.
Includes minor maintenance tweak to use a predefined array for all OO keywords.
2. Verified the parameter names used are in line with the names as per the PHP 8.0 release.
PHP itself renamed a lot of parameters in PHP 8.0. As named parameters did not exist before PHP 8.0, the parameter name as per PHP 8.0 (or above) is the only relevant name.
Ref: …
=> WP/DiscouragedConstants: implement PHPCSUtils and support modern PHP 

WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.inc, WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.php
For the purposes of this exercise, I've taken the _current_ parameter name as the "truth" as support for named parameters hasn't officially been announced yet, so any renames _after_ this moment are the only ones relevant.
Includes a change to the array format to allow for recording the parameter name.
Updated the array of parameters and values to search for based on a review of …
=> WP/DeprecatedParameterValues: support modern PHP + update for WP 6.1

WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php, WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.inc, WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.php
For the purposes of this exercise, I've taken the _current_ parameter name as the "truth" as support for named parameters hasn't officially been announced yet, so any renames _after_ this moment are the only ones relevant.
The `'raw'` key in the parameter arrays returned from the `PassedParameters` class contains - as per the name - the _raw_ contents of the parameter.
Since …
=> WP/EnqueuedResourceParameters: implement PHPCSUtils and support modern PHP

WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php, WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php, WordPress/Sniffs/PHP/RestrictedPHPFunctionsSniff.php, WordPress/Sniffs/PHP/TypeCastsSniff.php, WordPress/Sniffs/Security/SafeRedirectSniff.php
... to remove the presumption that positional parameters are being used.
... and remove the advise to assign `null` as this could cause yet other problems due to the PHP 8.1 "passing null to non-nullable" deprecation (though passing an unassigned variable is in a way just as bad, but that's a whole other story).
=> Various sniffs: improve error messages

WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
Change the format of the `$search` array to have the "value" as the key instead of as the value, which allows for using the more performance friendly `isset()` instead of `in_array()`.
... to cover an edge case which was already handled in the code, but not covered by a test.
The parsing of a `global` variable import statement would walk until the next semi-colon, while the statement can also be ended by a PHP close tag.
This could lead to false positives as well as false negatives.
Fixed now.
Includes removing a redundant variable assignment.
PHP 7.4 introduced arrow functions.
For the purposes of this sniff, default value assignments to parameters declared in an arrow function should be ignored to prevent false positives.
I've also reviewed the other places where …
=> WP/GlobalVariablesOverride: implement PHPCSUtils and support modern PHP

composer.json
PHPCSUtils 1.0.0 and PHPCSExtra 1.0.0 have both been tagged & released. :tada:
This means that the `minimum-stability`/`prefer-stable` settings should no longer be needed.
Ref:
* https://github.com/PHPCSStandards/PHPCSUtils/releases/tag/v1.0.0
* https://github.com/PHPCSStandards/PHPCSExtra/releases/tag/v1.0.0
=> Composer: update for PHPCSUtils + PHPCSExtra 1.0.0

WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php, WordPress/Tests/DB/DirectDatabaseQueryUnitTest.inc, WordPress/Tests/DB/DirectDatabaseQueryUnitTest.php
This code is a remnant of the old-style custom ignore comment mechanism which was removed in #2063.
... to cover the one uncovered line.
👉 This change will be easier to review while ignoring whitespace changes.
Prevent false negatives in case someone would use the PHP 8.0 nullsafe object operator on the `$wpdb` variable.
Also makes the token walking more stable by preventing an unrelated object operator from being recognized as if it were an operator operating on the `$wpdb` object (false positive).
Don't allow the sniff to get confused by comments.
Prevent false positives from walking too far when a database query statement is ended by a PHP close tag.
Prevent unsolvable false positives for `TRUNCATE` queries. Those …
=> DB/DirectDatabaseQuery: implement PHPCSUtils and support modern PHP 

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/CapabilitiesSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc, WordPress/Tests/WP/CapabilitiesUnitTest.1.inc, composer.json
.. into two methods:
* `wp_version_compare()` which does the actual compare.
* `normalize_version_number()` to handle the version number normalization.
This is just a code simplification/removal of duplicate code. No functional changes.
The default value for the `minimum_wp_version` property is used in a number of places, mostly in the test files when resetting a changed value for the property to its default, making it a "magic number".
Preferably, a magic number should be assigned to a constant and the constant should be used everywhere.
Unfortunately, that's not possible as a) constants in traits are not allowed prior to PHP 8.2 and b) code in test case files does not get executed, so using the constant is not an option anyway.
This commit now makes couple of changes to …
=> Helpers/MinimumWPVersionTrait: reduce use of magic number + other minor improvement

WordPress/Docs/NamingConventions/PrefixAllGlobalsStandard.xml, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.2.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.5.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.6.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.7.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.8.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.9.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
Using `type` instead of `code` is not currently needed as all relevant tokens will exist in PHPCS 3.7.1.
Using `code` has a minor advantage as it will allow for IDE auto-completion.
... which could never be reached anyway.
... to cover some previously uncovered code.
None of these should lead to errors/warnings.
No functional changes.
The regex as-was allowed for the `x7f` (= DEL) character to be part of a name.
The origin of this bug was the PHP manual, where the regexes were originally incorrect. This was fixed in php/doc-en@6187696
No unit tests included as, to be honest, I haven't got a clue how to add a test with the DEL character ;-)
Includes adding a note about why this condition is not using PHPCSUtils.
PHP 7.4 introduced arrow functions.
For the purposes of this sniff:
* …
=> NamingConventions/PrefixAllGlobals: implement PHPCSUtils and support modern PHP 

WordPress/Helpers/SnakeCaseHelper.php, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.php
The "snake case" related utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
This commit moves the `get_snake_case_name_suggestion()` method to the new `WordPressCS\WordPress\Helpers\SnakeCaseHelper` and starts using that class in the relevant sniffs.
**Note**:
It is expected for PHPCSUtils to have dedicated methods for the same at some point in the future. If/when those methods become available, it is recommended for the sniffs to start using the PHPCSUtils methods.
With that in mind, this class is marked as not part of the public API.
The `SnakeCaseHelper::get_suggestion()` method should have no opinion on the use of leading/trailing/double underscores in a name.
In practice, however, it did and the suggested name would be …
=> Move "snake case" related utility to dedicated SnakeCaseHelper + bug fix in method

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php
Synced in relevant changes as made upstream in the following commit:
* squizlabs/PHP_CodeSniffer@beeb36f - Making sure the sniff works correctly with PHP 7.4+ typed properties.
When a text string with interpolated variables contained a variable on the `$wordpress_mixed_case_vars` list, any variables found in the text string _after_ it would not be examined or flagged.
Fixed now.
Includes test proving the bug and safeguarding the fix.
Includes minor efficiency tweak.
Includes adding a test for the OO property verification, which was so far untested.
Includes minor efficiency tweaks.
Improve and stabilize the retrieval of embedded variables by:
1. Using the `TextStrings::getEmbed()` method to retrieve all embedded expressions.
2. Subsequently still using the regex to match variables within …
=> NamingConventions/ValidVariableName: implement PHPCSUtils and support modern PHP

WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.php
The handling of function names only consisting of underscore was already special cased in the sniff, but not covered by tests.
Similarly, live coding was not covered.
PHP is largely case-insensitive for class and method name, but not completely: the case-insensitivety does not apply to the non-ascii range.
The PHPCSUtils methods recognize this correctly.
Includes minor efficiency tweak by only doing the PHP4 constructor/destructor comparison when it's a real class as a name match can never be made for anonymous classes anyway.
Note: the test would previously pass, but only due to the `strtolower()` mangling both the class name as well as the method name equally.
The various PHPCSUtils `Scopes` functions support enums since PHPCSUtils 1.0.0-alpha4, so enums are …
=> NamingConventions/ValidFunctionName: implement PHPCSUtils and support modern PHP

WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed
... for previously uncovered code.
###Arrays/ArrayIndentation: implement PHPCSUtils
---
Note: I've not spend much time on this sniff as it is slated to be replaced with a sniff from PHPCSExtra in the future anyway. If anything still crops up, a quick fix can be made if needs be.
=> Arrays/ArrayIndentation: implement PHPCSUtils

WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.1.inc, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.1.inc.fixed, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc.fixed
... for previously uncovered code.
Includes removing some conditions which are now redundant.
=> Arrays/MultipleStatementAlignment: implement PHPCSUtils

WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.4.inc, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.4.inc.fixed, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.5.inc, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.6.inc, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.php
The `load_script_textdomain()` function was added to WP in WP 5.0.
Ref: https://developer.wordpress.org/reference/functions/load_script_textdomain/
... as per the current lists of supported headers in the linked theme/plugin handbook pages.
... for a few situations which were handled by the sniff, but so far not covered by tests.
For the purposes of this exercise, I've taken the _current_ parameter name as the …
=> Utils/I18nTextDomainFixer: implement PHPCSUtils and support modern PHP 

.github/workflows/unit-tests.yml, WordPress/Helpers/SnakeCaseHelper.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.php, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php, composer.json
This commit fixes two, closely related, issues:
1. The "is a name in snake case ?" determination was done in three slightly different ways between the `ValidFunctionName` sniff and the `ValidVariableName` sniff and the `SnakeCaseHelper::get_suggestion()` method, which meant that a name which would be regarded valid snakecase for the one, may not be regarded as valid snakecase for the other.
It could also result in the suggested name being the same as the existing name.
2. The "is a name in snake case ?" as well as the suggestion determination didn't take non-ASCII characters into account consistently.
While PHPCSUtils will at some point get better methods for handling these things, for now, we can still make a quick fix to improve this situation.
To that end, I've made the following …
=> NamingConventions/Valid(Function|Variable)Name: bug fix for error determination

WordPress-Core/ruleset.xml, WordPress/Helpers/VariableHelper.php, WordPress/Helpers/WPDBTrait.php, WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
Rules which are "covered" by a sniff normally are prefixed with "Covers rule:", while rules not (yet) covered by a sniff are prefixed with "Rule: ".
This updates the ruleset inline docs to be consistent with that again.
Includes fixing an incorrect link and some minor text tweaks to be in line with the handbook texts.
=> CS/QA: various minor fixes, incl docs fixes

.github/workflows/basic-qa.yml, .github/workflows/quicktest.yml, .github/workflows/unit-tests.yml
**_This is a prelim PR before updating the PHPCS version to allow for simplifying the management of the protected branches_**
**Note**:
**The protected branch settings will need an update before this PR becomes mergable, but after this, it shouldn't need updating that often anymore.
Once this PR has received approvals, I will update the required statuses and merge the PR myself.**
Since Composer 2.2, we can be more specific about which platform requirements should be ignored.
This change ensures that only the "high" end of a PHP requirement will be ignored and no other platform requirements are ignored.
Ref: https://blog.packagist.com/composer-2-2/#-ignore-platform-req-improvements
The `include` section was set up in Travis (and transferred to GH Actions) as the _lowest_ supported PHPCS …
=> GH Actions: various changes

.github/CONTRIBUTING.md, README.md, composer.json
Follow up on #2090 and #2058 and as discussed in #2214.
This updates the minimum PHPCS version from `3.7.1` to `3.7.2`.
Note: no changes are needed anymore to the GH workflows after the change merged with PR #2215
Ref: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.7.2
=> Composer: up the minimum PHPCS version to 3.7.2

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed, WordPress/Tests/WP/I18nUnitTest.2.inc, WordPress/Tests/WP/I18nUnitTest.3.inc, WordPress/Tests/WP/I18nUnitTest.php
The `AbstractFunctionRestrictionsSniff` already checks for a next token and verifies that token is an open parenthesis, this doesn't need to be duplicated.
Some new tests were added _after_ the property reset at the end of the test case file.
This commit moves the reset to the end of the file again.
As things were, the `WordPress.WP.I18n` sniff was based on the `AbstractFunctionRestrictionsSniff` class and used legacy custom code to parse the function call to parameters.
In this refactor, the parent sniff is switched to the `AbstractFunctionParameterSniff` class, which uses the PHPCSUtils `PassedParameters` class to parse the function call parameters.
Making this change will allow for supporting function calls using named parameters as supported since PHP 8.0.
As the code in the sniff …
=> WP/I18n: complete refactor, implement PHPCSUtils, modern PHP and more

WordPress/Sniff.php
...as it appears to be unused in WPCS.
=> Sniff::get_last_ptr_on_line(): remove function

WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Helpers/ContextHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/WP/DiscouragedFunctionsUnitTest.inc, WordPress/Tests/WP/DiscouragedFunctionsUnitTest.php
_Note: this PR is part of a series moving various method to this new `ContextHelper` class. Pulling each bit separately to allow for easier reviewing._
The `is_class_object_call()` utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
This commit moves the `is_class_object_call()` method to the new `WordPressCS\WordPress\Helpers\ContextHelper` class and starts using that class in the relevant sniffs.
The method has also been renamed to `has_object_operator_before()` as it doesn't actually check if something is a (method) _call_, just that something OO (method, constant, property) is being accessed.
This method is tested via the `WordPress.WP.DiscouragedFunctions` sniff.
* A non-inline HTML token will always have another non-empty …
=> Move is_class_object_call() utility method to dedicated `ContextHelper` + support nullsafe object operator

WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Helpers/ContextHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/WP/DiscouragedConstantsSniff.php, WordPress/Tests/WP/DiscouragedFunctionsUnitTest.inc, WordPress/Tests/WP/DiscouragedFunctionsUnitTest.php
_Next one in the series_
The `is_token_namespaced()` utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
This commit moves the `is_token_namespaced()` method to the new `WordPressCS\WordPress\Helpers\ContextHelper` class and starts using that class in the relevant sniffs.
This method is tested via the `WordPress.WP.DiscouragedFunctions` sniff.
* A non-inline HTML token will always have another non-empty token before it, if nothing else, the PHP open tag, so checking if `$prev` is `false` is redundant.
* Same for the second time this is done, as the same applies for the `T_NS_SEPARATOR` token.
=> Move is_token_namespaced() utility method to dedicated ContextHelper + minor simplifications

WordPress/Helpers/ContextHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/WP/CapitalPDangitSniff.php, WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.php
The `is_in_function_call()` utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
This commit moves the `is_in_function_call()` method to the new `WordPressCS\WordPress\Helpers\ContextHelper` class and starts using that class in the relevant sniffs.
Includes adding a type declaration for the `$valid_functions` parameter.
This method will be tested via the `WordPress.Security.NonceVerification` sniff (via pre-existing and a few new tests).
=> Move `is_in_function_call()` utility method to dedicated `ContextHelper`

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
This was previously not possible as the sniff extends an upstream PHPCS sniff and didn't have access to the methods in the `Sniff` class.
This is the only file in which snake_case parameter names are being used for the typical `$phpcsFile` and `$stackPtr` parameters.
This makes synching the file with upstream and otherwise editing the code counter-intuitive.
This commit normalizes the parameter names to use the expected case.
=> NamingConventions/ValidVariableName: various minor changes

WordPress/Helpers/ContextHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.php
The `is_in_type_test()` utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
This commit moves the `is_in_type_test()` method and the associated `$typeTestFunctions` property to the new `WordPressCS\WordPress\Helpers\ContextHelper` class and starts using that class in the relevant sniffs.
This method will be tested via the `WordPress.Security.NonceVerification` sniff (via pre-existing tests).
=> Move `is_in_type_test()` utility method to dedicated `ContextHelper`

WordPress/Helpers/ContextHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.php
The `is_in_isset_or_empty()` utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
This commit moves the `is_in_isset_or_empty()` method to the new `WordPressCS\WordPress\Helpers\ContextHelper` class and starts using that class in the relevant sniffs.
This method will be tested via the `WordPress.Security.NonceVerification` sniff (via pre-existing and new tests).
... instead of re-defining it each time the function is called.
... to simplify the determination of whether a token is within a call to `isset()` or `empty()`.
Includes tests in the `WordPress.Security.NonceVerification` test file.
=> Move is_in_isset_or_empty() utility method to dedicated `ContextHelper` + improve

WordPress/Helpers/ContextHelper.php, WordPress/Sniff.php, WordPress/Sniffs/DB/PreparedSQLSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/DB/PreparedSQLUnitTest.php
The `is_safe_casted()` utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
This commit moves the `is_safe_casted()` method and the associated `$safe_casts` property to the new `WordPressCS\WordPress\Helpers\ContextHelper` class and starts using that class in the relevant sniffs.
This method will be tested via the `WordPress.DB.PreparedSQL` sniff (via pre-existing tests).
A non-inline HTML token will always have another non-empty token before it, if nothing else, the PHP open tag, so checking if `$prev` is `false` is redundant.
=> Move is_safe_casted() utility method to dedicated ContextHelper

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed, WordPress/Tests/WP/I18nUnitTest.php
PHP 8.0 silently (not mentioned in migration guide, changelog etc - I only discovered it by accident via a small note in the manual) introduced two new placeholder characters for the `*printf()` range of functions.
This commit updates the regexes used in the `WordPress.WP.I18n` sniff to allow them to recognize those characters as placeholders which should be examined.
Ref: https://www.php.net/manual/en/function.sprintf.php
=> WP/I18n: allow for new PHP 8.0+ `[s]printf()` placeholders

WordPress/Helpers/ContextHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.php
The `is_in_array_comparison()` utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
This commit moves the `is_in_array_comparison()` method and the associated `$arrayCompareFunctions` property to the new `WordPressCS\WordPress\Helpers\ContextHelper` class and starts using that class in the relevant sniffs.
This method will be tested via the `WordPress.Security.NonceVerification` sniff (via pre-existing and new tests).
Function names are case-insensitive. The `ContextHelper::is_in_function_call()` method already handles this correctly, but the `ContextHelper::is_in_array_comparison()` method did not, which could result in `Undefined array key` error notices.
Tested by adjusting one of the tests.
With named parameters, the function …
=> Move is_in_array_comparison() utility method to dedicated `ContextHelper` + fixes

WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Tests/DB/RestrictedFunctionsUnitTest.inc, WordPress/Tests/DB/RestrictedFunctionsUnitTest.php, WordPress/Tests/WP/DiscouragedFunctionsUnitTest.inc, WordPress/Tests/WP/DiscouragedFunctionsUnitTest.php
... to ensure the abstract sniff doesn't act on functions which are not our target.
Tested via tests in the test file for the `WordPress.WP.DiscouragedFunctions` sniff.
_These tests are deliberately placed in this sniff as a) it doesn't have a WP version component, so the test file wouldn't need to be reorganized and b) the sniff is not likely to move to PHPCSExtra as it is WP specific._
1. The sniff only listens to `T_STRING`, so the check for a token code mismatch would never be `true`.
Note: there are other abstracts which extend from this one, which do listen to other tokens, but those have their own `is_targetted_token()` method.
2. A `T_STRING` token will always have another non-empty token before it, if nothing else, the PHP open tag, so checking if `$prev` is `false` is redundant. …
=> AbstractFunctionRestrictionsSniff: add extra tests and various bug fixes

WordPress-Core/ruleset.xml
PHP_CodeSniffer contains two sniffs which enforce that a file ends on a new line character:
* `Generic.Files.EndFileNewline`
* `PSR2.Files.EndFileNewline`
The `Generic` sniff _only_ checks if there is a new line character.
The `PSR2` sniff checks the same, but additionally also checks there is only one new line character (blank line) at the end of the file.
The checks in the `PSR2` sniff have distinct error codes, so plugins/themes who do not want to enforce the "single blank line" rule can choose to exclude it from their custom ruleset.
Additionally, both checks in the `PSR2` sniff have auto-fixers available.
The `Core` ruleset already contains the `Generic.Files.EndFileNewline` sniff.
I'm now proposing to switch the `Generic` sniff out in favour of the slightly stricter `PSR2` version.
=> Core: replace the Generic `EndFileNewline` sniff with the PSR2 one

WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/Security/NonceVerificationUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.4.inc, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.4.inc.fixed, WordPress/Tests/WP/CapabilitiesUnitTest.1.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc.fixed, WordPress/Tests/WP/ClassNameCaseUnitTest.inc, WordPress/Tests/WP/CronIntervalUnitTest.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
.. to make it easier to do a parse/compile error check on test case files.
Related to #2243
=> Tests: fix unintentional (parse/compile) errors in test case files

WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Tests/WP/EnqueuedResourcesUnitTest.1.inc
Commit dec9d40b33939678ed57ae88e977b5fe7198a55b, which was part of PR #2176 removed this `try/catch` and while it shouldn't be needed anymore for valid code, it _could_ still be needed for code containing parse errors.
This commit doesn't completely revert the previous commit, but does bring the try/catch back to prevent this situation.
Includes unit test safeguarding the fix.
Related to #2243
=> WP/EnqueuedResources: bring back try/catch

.github/workflows/basic-qa.yml
While checking something else, I came across a notice in the GH Actions logs showing that the fixer conflict check was failing.
Some backtracing shows that it has been failing for the past five months since PR #2132 was merged - see: https://github.com/WordPress/WordPress-Coding-Standards/actions/runs/3643130487
Unfortunately, the way the script was set up, this failure was not showing and not failing the builds. /cc @desrosj 
The changes I'm proposing now will fix that.
I've also made sure that once the current fixer conflicts are fixed, the build will properly succeed again: https://github.com/jrfnl/WordPress-Coding-Standards/actions/runs/5048089688/jobs/9055836148
Next up: fix the fixer conflicts and whatever other errors have crept in since the build originally started failing....
... …
=> GH Actions: fix fixer conflict check

WordPress-Core/ruleset.xml
> ### Namespace declarations
>
> Each part of a namespace name should consist of capitalized words separated by underscores.
>
> Namespace declarations should have exactly one blank line before the declaration and at least one blank line after.
>
> There should be only one namespace declaration per file, and it should be at the top of the file. Namespace declarations using curly brace syntax are not allowed. Explicit global namespace declaration (namespace declaration without name) are also not allowed.
Refs:
* https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/ - Namespace declarations section
* https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#namespace-declarations
* WordPress/wpcs-docs#97
* …
=> Core: add section about namespace declaration rules with select new sniffs

WordPress/Helpers/ConstantsHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.php
The `is_use_of_global_constant()` utility method is only used by a small set of sniffs, so is better placed in a dedicated class.
This commit moves the `is_use_of_global_constant()` method to the new `WordPressCS\WordPress\Helpers\ConstantsHelper` class and starts using that class in the relevant sniff.
The functionality in this new class will very likely be replaced at some point in the future by functions from PHPCSUtils.
This method will be tested via the `WordPress.Security.EscapeOutput` sniff (via pre-existing tests).
The `$tokens_to_ignore` array was set up using token types (strings) instead of token constants as some of the tokens would not always be available in all supported PHP/PHPCS combinations.
This is no longer needed now PHPCS 3.7.1 is the minimum …
=> Move is_use_of_global_constant() utility method to dedicated `ConstantsHelper`

WordPress/Helpers/PrintingFunctionsTrait.php, WordPress/Sniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.php
The printing function list is only used by a small set of sniffs, so are better placed in a dedicated trait.
The choice for a `trait` over a `class` is due to the `public` property allowing for adding additional functions to the list.
Moving both the base function list + the `public` property to the same trait will allow us to encapsulate all the functionality related to the use of this list in one place.
The `$printingFunctions` property, containing the base lists, has also been made `private`.
Checking whether or not something is a printing function should now be done by calling the `PrintingFunctionsTrait::is_printing_function()` method.
=> Move printing functions related functionality to dedicated `PrintingFunctionsTrait`

WordPress-Core/ruleset.xml
> ### Using import use statements
>
> Using import `use` statements allows you to refer to constants, functions, classes, interfaces, namespaces, enums and traits that live outside of the current namespace.
>
> Import `use` statements should be at the top of the file and follow the (optional) `namespace` declaration. They should follow a specific order based on the **type** of the import:
>
> 1. `use` statements for namespaces, classes, interfaces, traits and enums
> 2. `use` statements for functions
> 3. `use` statements for constants
>
> Aliases can be used to prevent name collisions (two classes in different namespaces using the same class name).
> When using aliases, make sure the aliases follow the WordPress naming convention and are unique.
>
> The following examples showcase the …
=> Core: add section about import use statement rules with select new sniffs

WordPress/Helpers/FormattingFunctionsHelper.php, WordPress/Sniff.php, WordPress/Sniffs/DB/PreparedSQLSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/DB/PreparedSQLUnitTest.php
The formatting function list is only used by a small set of sniffs, so are better placed in a dedicated class.
The `$formattingFunctions` property has also been made `private static`.
Checking whether or not something is a formatting function should now be done by calling the `FormattingFunctionsHelper::is_formatting_function()` method.
=> Move formatting functions related functionality to dedicated `FormattingFunctionsHelper`

WordPress/Sniffs/WP/CapitalPDangitSniff.php
This splits the `Misspelled` error code into two distinct error codes to allow for more modular ignoring of issues.
The new error codes are based on the context in which the misspelling is found (similar to other modular codes already in place, like `MisspelledNamespaceName`):
* `MisspelledInText`
* `MisspelledInComment`
As per the discussion in #1942.
=> WP/CapitalPDangit: use more modular error codes

WordPress/Helpers/ArrayWalkingFunctionsHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.inc, WordPress/Tests/Security/EscapeOutputUnitTest.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
The "array walking" function list is only used by a small set of sniffs, so are better placed in a dedicated class.
The `$arrayWalkingFunctions` property has also been made `private static`.
Checking whether or not something is an "array walking" function should now be done by calling the `ArrayWalkingFunctionsHelper::is_array_walking_function()` method.
* Transform the `$arrayWalkingFunctions` array to a multi-dimensional array to allow for it to include information about parameter names.
* Add new `get_callback_parameter()` method to retrieve the parameter information using the PHPCSUtils `PassedParameters` functionality.
* Adjust the sniff code retrieving a parameter from these functions to use this new method.
* Adjust the `get_array_walking_functions()` method to …
=> Move "array walking" functions related functionality to dedicated `ArrayWalkingFunctionsHelper` + support PHP 8.0+ named parameters

WordPress/Helpers/SanitizationFunctionsTrait.php, WordPress/Helpers/SanitizingFunctionsTrait.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
The sanitization function lists are only used by a small set of sniffs, so are better placed in a dedicated trait.
The choice for a `trait` over a `class` is due to the `public` properties allowing for adding additional functions to the lists.
Moving both the base function lists + the `public` properties to the same trait will allow us to encapsulate all the functionality related to the use of these lists in one place.
The `$sanitizingFunctions` and the `$unslashingSanitizingFunctions` property, containing the base lists, have also been made `private`.
Checking whether or not something is a sanitization function should now be done by calling the `SanitizingFunctionsTrait::is_sanitizing_function()` or the `SanitizingFunctionsTrait::is_sanitizing_and_unslashing_function()` method.
Related …
=> Move sanitization functions related functionality to dedicated `SanitizingFunctionsTrait`

WordPress/Helpers/UnslashingFunctionsHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
The unslashing function list is only used by a small set of sniffs, so are better placed in a dedicated class.
The `$unslashingFunctions` property has also been made `private static`.
Checking whether or not something is an unslashing function should now be done by calling the `UnslashingFunctionsHelper::is_unslashing_function()` method.
Includes removing a `@internal` comment from the `Sniff` class docblock as it is now redundant.
=> Move unslashing-only functions related functionality to dedicated `UnslashingFunctionsHelper`

WordPress/Sniffs/WP/PostsPerPageSniff.php
The WPCS `AbstractArrayAssignmentRestrictionsSniff` expects an array from `getGroups()` which includes a `'message'` key. The `callback()` method subsequently allows to override that message with a higher priority message if needed in specific circumstances.
This sniff, however, doesn't need to override the message, so the `callback()` method can just use the default behaviour of returning `true` or `false` and use the `'message'` as declared in the group.
=> WP/PostsPerPage: simplification

WordPress/Helpers/ConstantsHelper.php, WordPress/Sniffs/WP/DiscouragedConstantsSniff.php, WordPress/Tests/WP/DiscouragedConstantsUnitTest.inc
Cricky... not sure why none of us ever noticed this, but we had a huge chunk of duplicate code here, which can be removed by letting the sniff use the utility method.
Includes one minor tweak to the utility method.
Includes additional test which would previously have failed.
=> WP/DiscouragedConstants: use the `ConstantsHelper` class

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
The `PrefixAllGlobals` sniff has a tolerance for non-prefixed polyfills for PHP native functions. This check, however, did a case-sensitive comparison, while PHP natively treats function names case-insensitively.
Fixed now.
=> NamingConventions/PrefixAllGlobals: make the "is PHP native polyfill ?" check case-insensitive

WordPress/Sniffs/Security/PluginMenuSlugSniff.php
The list of functions has also been verified against WP Core. No changes were needed.
=> Security/PluginMenuSlug: order functions list alphabetically

WordPress/Helpers/ArrayWalkingFunctionsHelper.php, WordPress/Helpers/EscapingFunctionsTrait.php, WordPress/Helpers/FormattingFunctionsHelper.php, WordPress/Helpers/PrintingFunctionsTrait.php, WordPress/Helpers/SanitizingFunctionsTrait.php, WordPress/Helpers/UnslashingFunctionsHelper.php, WordPress/Tests/DB/PreparedSQLUnitTest.1.inc, WordPress/Tests/Security/EscapeOutputUnitTest.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.1.inc
These functions should be self-contained, so should not presume that the sniff has already lowercased the function name before passing it.
This fixes a bug as, in this case, the sniffs didn't actually lowercase the name before passing it to the Helper class methods, so the sniffs would throw false positives for non-lowercase function calls.
Tested by adjusting some pre-existing tests for the `EscapeOutput` sniff and the `ValidatedSanitizedInput` sniff.
These functions should be self-contained, so should not presume that the sniff has already lowercased the function name before passing it.
This fixes a bug as, in this case, the sniffs didn't actually lowercase the name before passing it to the Helper class methods, so the sniffs would throw false positives for non-lowercase function calls. …
=> Helpers: make sure function names are checked case-insensitively

WordPress/Helpers/ContextHelper.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.php
Follow up on #2232.
This property was previously not made `private` as it is used by the `EscapeOutput` sniff. For consistency with other classes and to better protect the value of the property, I'm proposing to make it `private` now anyway and add a `get_safe_cast_tokens()` method to retrieve the list.
This prevents potential problems if external standards would attempt to adjust the list (which they could while the property was `public static`, even though the class is `final`).
=> ContextHelper::$safe_casts: make `private`

WordPress/Sniffs/PHP/StrictInArraySniff.php
Follow up on #2140
... to a more logical name (as the parameter in PHP was renamed, but our local variable name which included that name was not updated).
=> PHP/StrictInArray: rename a local variable

WordPress/Helpers/ArrayWalkingFunctionsHelper.php, WordPress/Helpers/UnslashingFunctionsHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php
For the stand-alone Helper classes which only contain one "functions list" array property, name the retrieval method `get_functions()`.
After all, these are not traits, which run a risk of a class `use`-ing the trait overloading the method and as the method is `static`, the class name used in the function call already clearly indicates _which_ function list is being retrieved.
For the stand-alone Helper classes which only contain one "functions list" array property, name the retrieval method `get_functions()`.
After all, these are not traits, which run a risk of a class `use`-ing the trait overloading the method and as the method is `static`, the class name used in the function call already clearly indicates _which_ function list is being retrieved.
=> Improve consistency in method names across Helpers

WordPress/Helpers/ContextHelper.php, WordPress/Helpers/DeprecationHelper.php, WordPress/Helpers/ListHelper.php, WordPress/Helpers/ValidationHelper.php, WordPress/Helpers/VariableHelper.php, WordPress/Helpers/WPDBTrait.php
The `Helper` classes containing stand-alone `static` methods can be used by both WPCS itself as well as external standards extending WPCS.
As these methods have been made stand-alone, they should probably contain a little more defensive coding in select places.
Note: this code will not be "covered" by tests at this moment as the WPCS code as-is will never hit these conditions.
At a later point in time, we may want to add dedicated tests for the Helper methods which aren't moving to PHPCSUtils. When we do, we can make sure this defensive code gets covered too.
=> Helpers: add some more defensive coding

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
PR #2169 switched the sniff from using the `'raw'` parameter value to using the `'clean'` (without comments) parameter value, however, the `is_local_data_stream()` method still referred to the `'raw'` value, even though it is now using the `'clean'` value.
Fixed now to prevent future confusion.
=> WP/AlternativeFunctionsSniff::is_local_data_stream(): update param name and docs

WordPress/Helpers/MinimumWPVersionTrait.php
Follow up on #2187 which removed the need to reset the `minimum_wp_version` property in test case files to a specific WP version, in favour of allowing a reset to "unset".
This means the version number in the `WP/AlternativeFunctionsUnitTest.inc` test case file doesn't need to be updated anymore when the default value of the `minimum_wp_version` changes, so this comment is now just confusing.
=> Docs: remove redundant comment

WordPress/Helpers/ContextHelper.php, WordPress/Helpers/ListHelper.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
... which have two meanings:
* `@internal` stand-alone without braces means that a construct is intended for internal use only.
* `{@internal ....}` with a comment means this is a comment for other devs.
=> Docs: use correct format for `@internal` tags

WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractFunctionParameterSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php, WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php, WordPress/Sniffs/PHP/IniSetSniff.php, WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php, WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Sniffs/Security/PluginMenuSlugSniff.php, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/CapabilitiesSniff.php, WordPress/Sniffs/WP/ClassNameCaseSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Sniffs/WP/DiscouragedConstantsSniff.php, WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php, WordPress/Sniffs/WP/I18nSniff.php
When the `$matched_content` param is passed from the `AbstractFunctionRestrictionsSniff` or, by extension, from the `AbstractFunctionParameterSniff``, it will always already be in lowercase.
When the `$matched_content` param is passed from the `AbstractClassRestrictionsSniff` sniff it will be in its original case.
This commit updates the docs of all involved methods to include information about the case of the content of `$matched_content` to clarify this.
Includes removing two unnecessary calls to `strtolower()` in child classes.
Includes overloading the `process_matched_token()` method in the `AbstractClassRestrictionsSniff`, not because the code does anything different, but only to ensure the docblock annotates correctly that in child classes of that abstract the `$matched_content` …
=> Docs: clarify the `$matched_content` parameter

WordPress/Helpers/IsUnitTestTrait.php, WordPress/Tests/Files/FileNameUnitTest.php, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-phpunit6-case-insensitive.inc
As PHP treats namespace names and class names case-insensitively, this helper should do so too.
This is a bug fix as the sniff would previously throw false positives for test classes where the case of the class name/extended class name did not match.
Tested by adding an extra test to the `WordPress.Files.FilesName` sniff.
=> IsUnitTestTrait: make sure namespace and class names are checked case-insensitively

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
While the `PrefixAllGlobals` sniff already allowed for WP native constants which can be user declared, it did not allow for explicitly pluggable functions and classes being declared in plugins/themes.
I'm quite surprised actually that this was not reported as a bug so far.
Either way, fixed now.
In both cases, a case-insensitive name comparison is done as PHP natively treats function names and class names case-insensitively.
The lists added are based on some prelim sniffs created for issue #1803 and WP Core 6.3-beta2.
Notes:
* When generating these lists, I've explicitly excluded the `wp-includes/compat.php` file (which contains the polyfills for PHP native functionality).
* I've intentionally included the Twenty* theme related functions and classes as WPCS should also allow for being …
=> NamingConventions/PrefixAllGlobals: allow non-prefixed declarations for pluggable functions and classes

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/Tests/WP/PostsPerPageUnitTest.inc, WordPress/Tests/WP/PostsPerPageUnitTest.php
This PR is the result of a comprehensive review of the `AbstractArrayAssignmentRestrictionsSniff` class.
While this PR makes significant improvements, there is still more wrong with this abstract:
* The text quotes are stripped off the value before it gets passed to the callback, meaning the callback can no longer determine what type of value was received, which could lead to false positives/negatives.
Example: https://3v4l.org/YH5Rp (and yes, this means that even though numeric literals with underscores should be supported, we cannot do so reliably).
* A compound key, like `[ $prefix . 'posts_per_page' ]`, will be flagged as if the key were `'posts_per_page'` as the key does not get captured in its entirety.
* Along the same lines, the fact that the callback method gets a string value …
=> AbstractArrayAssignmentRestrictions: implement PHPCSUtils, bug fixes, modern PHP and more

.github/workflows/manage-labels.yml
As discussed in Slack, I've:
* Removed the `Status: PR Exists` label.
* Reviewed all other labels for consistency in the capitalization of the phrases and made fixes where needed.
This updates the GH Actions workflow which references those labels to match.
=> GH Actions/manage-labels: remove label which doesn't exist anymore

WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php, WordPress/Tests/DB/DirectDatabaseQueryUnitTest.inc, WordPress/Tests/DB/DirectDatabaseQueryUnitTest.php
This was already handled correctly for `ALTER` etc, but not for the new check for `TRUNCATE` (added in #2186).
Includes test.
... so the sniff needs to do the name comparisons in a case-insensitive manner.
Includes test.
=> DB/DirectDatabaseQuery: 2 fixes for case-insensitivity (PHP + SQL)

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/Sniffs/CodeAnalysis/AssignmentInTernaryConditionSniff.php
All methods in the `BCFile` class have PHPCSUtils native alternatives (which we already use), with the exception of the `findEndOfStatement()` method and the `findStartOfStatement()` method.
To be on the safe side, in case a polyfill is needed in those methods for a future PHP version or for support for PHPCS 4.x, let's consistently use the `BCFile` versions of these methods.
=> Always use BCFile for find[Start|End]OfStatement()

WordPress/AbstractArrayAssignmentRestrictionsSniff.php
👉🏻  **[OPTIONAL/PROPOSAL]**
The `getGroups()` method allows to pass a custom callback for any particular group, however, in practice that array key is never used as the `callback()` method (the default) is declared as `abstract` and therefore **must** be defined in a child class.
I propose to remove support for the `callback` array key from the abstract sniff.
Sniffs which extend this abstract can still use different logic for different groups by applying a switch to the `$group` parameter received in the `callback()`, along the lines of:
```php
public function callback( $key, $val, $line, $group ) {
switch( $group ) {
case 'groupA':
return $this->callback_for_group_A($key, val, $line);
case 'groupB':
return $this->callback_for_group_B($key, val, $line);
}
}
```
I have verified that [none …
=> AbstractArrayAssignmentRestrictions: remove support for 'callback'

WordPress/Helpers/ConstantsHelper.php, WordPress/Helpers/ContextHelper.php, WordPress/Helpers/DeprecationHelper.php, WordPress/Helpers/ListHelper.php, WordPress/Helpers/RulesetPropertyHelper.php, WordPress/Helpers/SnakeCaseHelper.php, WordPress/Helpers/VariableHelper.php
This adds _"the other"_ `@internal` tag to these classes, also marking the classes as "internal API" via the tag (on top of the notice in the docblock description).
=> Docs: add `@internal` tag to classes marked as internal API

WordPress/Helpers/VariableHelper.php
Prevent a potential "Undefined array key "bracket_closer"" PHP notice in the case of parse errors.
=> VariableHelper::is_comparison(): minor defensive coding tweak

composer.json
PHPCSUtils released version 1.0.8 with a small bug fix.
PHPCSExtra has just released version 1.1.0. with 7 new sniffs, most of which we'll want to add to WPCS (will be done in follow-up PRs).
Refs:
* https://github.com/PHPCSStandards/PHPCSUtils/releases/tag/1.0.8
* https://github.com/PHPCSStandards/PHPCSExtra/releases/tag/1.1.0
=> Composer: update PHPCSUtils + PHPCSExtra

WordPress-Extra/ruleset.xml
... which ought to be replaced by `printf(...)`.
Ref: PHPCSStandards/PHPCSExtra#242
=> Extra: add sniff to detect inefficient "echo sprintf(...)"

WordPress-Core/ruleset.xml
Includes preventing a duplicate notification about "spacing after the `use` keyword".
Refs:
* `Universal.UseStatements.DisallowMixedGroupUse` - upstream PHPCSStandards/PHPCSExtra#241
* `Universal.UseStatements.NoUselessAliases` - upstream PHPCSStandards/PHPCSExtra#244
* `Universal.UseStatements.KeywordSpacing` - upstream PHPCSStandards/PHPCSExtra#247
=> Core: add some more sniffs for import `use` statements

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
Double-checked the ruleset against the handbook. Everything currently in the handbook is now in the Core ruleset. :white_checkmark:
* Removed duplicate rule (the `Universal.UseStatements.LowercaseFunctionConst` was previously added here, but subsequently added to the "Use import statement" section as well).
* Removed links to closed issues when the issue has been addressed in the mean time. _(in the Core ruleset, the link is only supposed to be there for things which haven't got a sniff yet)_
* Made sure that rules which haven't got a sniff associated with them, while they are potentially sniffable, have an issue attached to them.
* Made sure that rules which are "covered" by one or more sniffs have the `Covers` prefix.
=> Rulesets: various minor tweaks

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php, WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.inc, WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.php
Ticket: https://core.trac.wordpress.org/ticket/52506
Change: https://core.trac.wordpress.org/changeset/53575
With WordPress 6.1 ([October 2022](https://make.wordpress.org/core/2022/06/23/wordpress-6-1-planning-roundup/)), the `%i` placeholder will provide a safe way to escape Identifiers (e.g. table/field names).
Technically it's not needed if the variable only contains [permitted characters](https://dev.mysql.com/doc/refman/8.0/en/identifiers.html), is not one of the ~286 [reserved words](https://dev.mysql.com/doc/refman/8.0/en/keywords.html), and is a `literal-string` (a value defined by the developer)... but that's not always possible, or can be hard to prove.
=> Support '%i' placeholders for escaping Identifiers

WordPress/Helpers/IsUnitTestTrait.php, WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Helpers/ValidationHelper.php, WordPress/Helpers/VariableHelper.php, WordPress/Sniffs/DB/SlowDBQuerySniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/WP/ClassNameCaseSniff.php, WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Sniffs/WP/PostsPerPageSniff.php, WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php
... mostly based on things I came across while creating the changelog and when updating the "lists".
(and yes, I have verified the `OperatorSpacing` sniff against the PHPCS native sniff again)
=> Docs: various minor tweaks

WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Updates the list of deprecated function parameters in the `WP.DeprecatedParameters` sniff based on the WP 6.3.0-RC1 release.
Based on a scan of WP Core at commit https://github.com/WordPress/wordpress-develop/commit/6281ce432c50345a57768bf53854d9b65b6cdd52 using a preliminary sniff created for issue #1803.
Notes:
* All items in the original list have been manually double-checked and are okay.
* The original list was based on checking for calls to `_deprecated_parameter()`. The prelim sniff also checks the function signature for parameters named `$deprecated*`.
* Where parameters named `$deprecated` were detected without a call to `_deprecated_parameter()` and without a documented good reason not to have that call, the call to `_deprecated_parameter()` should be added and I have a WIP …
=> WP/DeprecatedParameters: update the list based on WP 6.3-RC1

WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Tests/WP/DeprecatedClassesUnitTest.inc, WordPress/Tests/WP/DeprecatedClassesUnitTest.php
Based on a scan of WP Core at commit https://github.com/WordPress/wordpress-develop/commit/6281ce432c50345a57768bf53854d9b65b6cdd52 using a preliminary sniff created for issue #1803.
Manually verified.
Includes fixing a typo in the original list.
Previous: #1809 (for WPCS 2.2.0)
=> WP/DeprecatedClasses: update the class list based on WP 6.3-RC1

WordPress/Sniffs/WP/ClassNameCaseSniff.php
Based on a scan of WP Core at commit WordPress/wordpress-develop@6281ce4 using a preliminary sniff created for issue #1803.
Notes:
* The order of some of these lists have small changes due to non-natural alphabetic sorting being used in the auto-generated lists.
* The WP Core class list now includes various classes which are from non-externally maintained "external" dependencies.
* WP 6.2 and up contains Requests 2.0+. As this is a class name check and the Requests 1.0 class names are still supported, I'm adding the 2.0 class names, instead of replacing the Request 1.x list.
... and scan for those as well. After all, (child) themes can use WPCS as well.
=> WP/ClassNameCase: update the class lists based on WP 6.3-RC1

WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php
This only changes the order of the list. No reserved names were added or removed.
Includes adding a link to the source of the list and adding comments about the items in the "special" list of reserved names, which aren't WP native post types.
Based on a scan of WP Core at commit WordPress/wordpress-develop@6281ce4 using a preliminary sniff created for issue #1803.
Manually verified.
Also see: https://wordpress.slack.com/archives/C680YMW9H/p1688270736663219
=> NamingConventions/ValidPostTypeSlug: update the reserved post types list

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
This only changes the order of the list. No constants were added or removed.
Based on a scan of WP Core at commit WordPress/wordpress-develop@6281ce4 using a preliminary sniff created for issue #1803.
Manually verified.
Previous: #1718 (for WPCS 2.2.0)
=> NamingConventions/PrefixAllGlobals: update the constants list

WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php, WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.inc, WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.php
... to covered previously uncovered code.
Note: some of the messages generated for these (mostly invalid) code samples are not always that clear, but the fact that the queries are being flagged is still correct.
These variables are conditionally set within the `for()` loop. Just declaring them here to be more explicit/complete with the variables in use within the loop.
This change is already covered by existing tests (test case file line 58 and 259).
In both these cases, a "quick check" for the target function call was done prior to walking the tokens, but the token walking with a negative search for `Tokens::$emptyToken` doesn't contain the risk of walking very far, so this quick check isn't really needed and removing it shouldn't impact performance.
The `'raw'` key in the parameter …
=> DB/PreparedSQLPlaceholders: use PHPCSUtils, allow for modern PHP and some bug fixes

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, WordPress/Tests/WP/DeprecatedParametersUnitTest.php
The minimum version should be three versions behind the latest WP release, so what with 6.3 being in RC, to be released on August 8th, it should now become 6.0.
Includes updating the tests to match.
Previous: #2121
=> Update the `minimum_wp_version` to WP 6.0

.phpcs.xml.dist, WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
Follow up on #2137
As  WP Core has now dropped support for PHP < 7.0, it can start using the `dirname()` `$levels` parameters. Think:
```php
// PHP < 7.0.
$path = dirname( dirname( dirname( __DIR__ ) ) );
// PHP 7.0+.
$path = dirname( __DIR__, 3 );
```
The `Modernize.FunctionCalls.Dirname` sniff we include also includes a check (and fixer) for that, so we can now include that sniff completely in the `Core` ruleset.
For now, I'm proposing to silence the error code related to the PHP 7.0 modernization opportunity (again) for the `Extra` ruleset as not all plugins/themes will have dropped support for PHP < 7.0 yet.
To be on the safe side, I'm explicitly excluding the whole sniff from the ruleset used for WPCS itself as WPCS still has a PHP 5.4 minimum.
=> Core/Extra: tweak the inclusion of the `Modernize.FunctionCalls.Dirname` sniff

WordPress/Helpers/EscapingFunctionsTrait.php, WordPress/Helpers/SanitizingFunctionsTrait.php
This function was introduced in WP 5.5.
As it's been around for about three years now, I'm not going to special case it with a version check.
Ref: https://core.trac.wordpress.org/ticket/50117
Fixes #1937
This function was introduced in WP 2.9.0.
I've looked the code of the function over and agree it can be added to the auto-escaped functions list.
Ref: https://developer.wordpress.org/reference/functions/wp_timezone_choice/
Fixes #1904
This function was added in WP 5.9 to replace the `readonly()` function as `readonly` became a reserved keyword in PHP 8.1 (though only partially to allow the WP community some time to catch up).
I'm leaving `readonly()` in the list. While it shouldn't be used anymore, if it is, it still is a valid auto-escaped function.
Ref: …
=> Update various function lists

composer.json
PR #1856, which was included in WPCS 2.3.0, introduced a check for strings wrapped in HTML in the `WordPress.WP.I18n` sniff. The underlying code for this check uses the PHP XMLReader extension unconditionally.
This means that the PHP [`XMLReader` extension](https://www.php.net/manual/en/xmlreader.installation.php) and `libxml` are hard requirements for WPCS, but this was not yet annotated as such in the `composer.json` `require` section.
Along the same lines, `iconv` is used conditionally in the `PrefixAllGlobals` sniff, so should be listed as `suggest`.
And well, the dependency on the Tokenizer extension should be obvious ;-)
Fixed now.
Checked using the ComposerRequireChecker tooling: https://github.com/maglnet/ComposerRequireChecker
Note: as this tool relies on an `autoload` …
=> Composer: make PHP extension dependencies explicit

.github/release-checklist.md
While not an officially supported file, in my experience it is helpful to have a release checklist available. This makes the release process more transparent and less dependent on specific maintainers.
The checklist documents the release steps and can be updated via PRs to add additional steps/adjust existing steps whenever needed.
The checklist should be used as the PR description for the release PR from `develop` to `main`.
=> Add release checklist

WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc.fixed, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
This sniff hasn't had an extensive review as it realistically shouldn't exist - see #2332. It has been made compatible with modern PHP without a deep dive into whether what it is doing is correct in other ways.
---
Add metrics for blank line at start/end of control structure as per squizlabs/PHP_CodeSniffer@4fc2515 (PHPCS 2.5.1).
Check the spacing after the `finally` keyword as per squizlabs/PHP_CodeSniffer@eefb31c (PHPCS 3.2.3).
Handled in a slightly different way as upstream as the sniffs have diverged, but this should work for the most part (aside from pre-existing issues in the sniff anyway).
Check the spacing for `match` control structures as per squizlabs/PHP_CodeSniffer@549899b (PHPCS 3.6.0).
Ignore blank line/spacing rules when the next thing (inside/outside) is an enum as per …
=> Whitespace/ControlStructureSpacing: sync with upstream + minor tweaks

WordPress/Docs/WhiteSpace/ControlStructureSpacingStandard.xml
Follow up on closed PR #1736, but now with correct descriptions and standard blocks and code samples for all things being flagged by the sniff.
Related to #1722
Prop to @ckanitz for the initial draft.
=> WhiteSpace/ControlStructureSpacing: add documentation

phpcs.xml.dist.sample
* Replace an example of a rule exclusion as excluding security sniffs should be encouraged.
* Remove an example of an "extra rule" as that sniff is now included in WPCS.
* Minor tweak to the example of how to include PHPCompatibilityWP. Note: I've raised the minimum PHP version to 5.6, not yet to 7.0 as plugins/themes (which are the typical target public for this example ruleset) often support multiple WP versions.
* Update property name.
* Give a few examples of legitimate selective directory excludes.
=> Docs: update the sample ruleset

.codecov.yml, .gitattributes, .github/workflows/quicktest.yml, .github/workflows/unit-tests.yml, README.md, phpunit.xml.dist
Follow up after PR #2225 and other PRs which added more tests and raised code coverage.
The Codecov service is a way to monitor test vs code coverage of a project over time and allows for the code coverage % + delta to be reported in each PR.
This commit:
* Adds CodeCov configuration and ignores it for creating the package file.
* Note: by default CodeCov reports back with build statuses (in the table at the bottom of a PR) + posts a really extensive comment on a PR.
I personally find those comments + mail on each PR terribly annoying and unnecessary when the build statuses are set to required statuses anyway, so I've turned the posting of those comments off (via a setting in the configuration file).
* Another thing to note is the patch - threshold setting being at `3%` (= 3% deviation …
=> Code coverage: initial setup for CodeCov

WordPress/Helpers/IsUnitTestTrait.php, WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php, WordPress/Sniffs/WP/I18nSniff.php
Follow up on #1584, which was included in WPCS 2.0.0.
While PHPCS still supports the _old_ array syntax (comma-delimited string), WPCS no longer has a (WPCS native) tolerance for those properties being passed with the `type="array"` attribute, so these public properties should always be arrays.
=> Docs: array properties expect arrays

WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php
... to be more descriptive in the context of named parameters.
Includes defensive coding tweak of making sure the `$content_type` variable is always defined.
=> DateTime/CurrentTimeTimestamp: rename some local variables

WordPress/Sniffs/WP/CapabilitiesSniff.php
The `MinimumWPVersionTrait::set_minimum_wp_version()` method does not take a parameter.
=> WP/Capabilities: minor clean up

WordPress/Sniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
As things were, the "missing unslashing" error was being thrown from the `Sniff::is_sanitized()` method, based on whether the `$require_unslash` parameter was set to `true` or `false`.
In my opinion, it should not be the responsibility of utility functions to throw errors/warning, but always of the originating sniff.
This commit replaces the boolean `$require_unslash` parameter for the `Sniff::is_sanitized()` method to a nullable callable `$unslash_callback` parameter.
Instead of letting the `Sniff::is_sanitized()` method throw the error/warning, the callback will now be called and as the originating sniff passes the callback, the originating sniff can now handle the throwing of the error/warning.
To remove any presumptions of the callback being passed, being in the same context as the …
=> Sniff: move "missing unslashing" handling to callback function

WordPress/Helpers/SanitizationHelperTrait.php, WordPress/Sniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
These methods haven't had extensive work done as they barely do any token walking themselves and the underlying functions used by the methods all have had work done to improve them.
Note: the `is_only_sanitized()` method _could_ be moved to the `NonceVerification` sniff as it's only used by that sniff, but for now, I've elected to keep it together with the `is_sanitized()` method.
---
The `Sniff:;is_*sanitized()` utility methods are about to be moved to this trait, but once they have been, the trait name is no longer correct as all other `*Functions[Helper|Trait]` classes/traits _only_ deal with function lists and checking whether something is in those lists, while this trait will now do more than that.
With that in mind, I propose to rename the trait to `SanitizationHelperTrait`.
This …
=> Move sanitization methods to SanitizationHelperTrait + minor improvements

.github/workflows/quicktest.yml
Another follow up on #2338
Small tweak to the codecov upload step to not run for PHP `latest`.
_I had to tweak the code a couple of times because of the PHPUnit constraints and clearly forgot to update this condition._
=> GH Actions: fix quicktest for `develop`

CHANGELOG.md
The repo has moved and changed its name, so make sure old references to it won't confuse people.
Note: similar changes for the README and CONTRIBUTING guide will be made in the PRs updating those files.
=> Changelog: update references to the Composer PHPCS plugin

.codecov.yml
Another follow up on https://github.com/WordPress/WordPress-Coding-Standards/pull/2338
I'm proposing we turn patch coverage off as it is clearly sprouting nonsense (reporting 66% on changes which didn't touch any code under test (GH Actions changes, doc changes)).
=> Codecov config: tweak patch config

.gitattributes, .github/workflows/basic-qa.yml, .gitignore, phpstan.neon.dist
⚠️ **Note: this PR requires PR #2349 and PR #2354 (first commit) to be merged before the build can pass!**
PHPStan is a good addition to our QA toolkit and with improvements PHPStan has made over the years is now a viable tool for us to use (previously it would give way too many false positives).
This commit:
* Adds a separate job to the `basic-qa` workflow in GH Actions.
Notes:
- I've chosen **not** to add PHPStan to the Compose dependencies for two reasons:
1. It doesn't allow for installation on PHP < 7.2, which would break/block the `composer install` for our test runs.
2. It would add dependencies which could conflict/cause problems for our test runs due to those defining token constants too.
- We could potentially use [Phive](https://phar.io/) to still have a setup which can be used …
=> Add PHPStan to QA checks

.github/CONTRIBUTING.md, .github/workflows/quicktest.yml, .github/workflows/unit-tests.yml, CHANGELOG.md, README.md
Branch rename has just been executed via the GH interface. If you have a local clone, make sure you update it/fetch. A note about the rename will be in the changelog and the upgrade guides.
Note: install instructions in the README will be replaced still in a future commit.
Closes #1916
=> Updates related to branch rename from `master` to `main`

.phpcs.xml.dist, WordPress/Helpers/EscapingFunctionsTrait.php, WordPress/Helpers/IsUnitTestTrait.php, WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Helpers/PrintingFunctionsTrait.php, WordPress/Helpers/SanitizationHelperTrait.php, WordPress/Helpers/WPDBTrait.php
Traits cannot be made `final`, but the methods therein _can_.
There is a caveat though: the class `use`-ing the trait can still overload the method. Also see: https://externals.io/message/120576
In other words: the `final` keyword, in this case, only protects against _child_ classes of the class `use`-ing the trait overloading the method. And as most sniff are now `final` by design, this could be seen as a redundant change.
Having said that, I still think it has value to add the keyword, if only to signal that these method shouldn't be overloaded.
Includes adding a sniff to the WPCS native PHPCS ruleset to enforce this.
=> Make methods in traits `final`

WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php, WordPress/Sniffs/DB/PreparedSQLSniff.php
Inspired by https://github.com/WordPress/WordPress-Coding-Standards/pull/2362#pullrequestreview-1585235527 - this fixes up the other closures in the code base.
=> CS: closures not using `$this` should be static

WordPress/Helpers/ValidationHelper.php, WordPress/Sniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.1.inc, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
A superglobal key being unset doesn't need sanitization or validation, however, the unset should _not_ be seen as validation for use of the superglobal key later on.
This bug was introduced long ago (0.3.0 - 64fab4f) and later moved into the `is_validated()` method via ba15db9
Discovered when making some changes to the tests for the `ValidatedSanitizedInput` sniff.
Includes dedicated test for this situation.
Discovered when making some changes to the tests for the `ValidatedSanitizedInput` sniff.
A number of the tests in that file are in the _global_ scope.
As things were, if validation was encountered for a particular superglobal key in a _closed_ scope (function, class) prior to the use of the superglobal key in the _global_ scope, the superglobal key would be seen as correctly …
=> Security/ValidatedSanitizedInput: use PHPCSutils and bug fixes

WordPress/Sniff.php
As pointed out by @GaryJones, as all utility methods have now been made self-contained, it is no longer necessary to have a separate `init()` method in the `Sniff` class.
=> Sniff: remove `init()` method

.gitattributes, .github/CONTRIBUTING.md, .phpcs.xml.dist, README.md, Tests/RulesetCheck/class-ruleset-test.inc
This commit updates the README guide to be in line with WordPressCS 3.0.0.
This commit:
* Removes the "Last commit to stable" and "Nr of contributors" badges.
* Updates the "Tested on PHP..." badges.
* Updates the table of contents to match the new content of the file.
* Removes the "Project history" section (has been moved to the wiki).
* Makes the pre-requisites for the package more explicit and puts them in a separate section.
* Updates the installation instructions and adds update instructions.
- Removes the instructions related to stand-alone installs and using `composer create-project`.
- The new installation instructions take the changes in Composer 2.2 (permission required for plugins to run) into account.
- The new installation instructions include a link to the end user/ruleset …
=> Update documentation (README, CONTRIBUTING) for release of WordPressCS 3.0.0

WordPress/Tests/DB/DirectDatabaseQueryUnitTest.inc
It's the only error flagged by a non-inclusive terminology checker.
Originally added in https://github.com/WordPress/WordPress-Coding-Standards/commit/3cd319133d6ff20cc8957450326e4cdf8c97f9a6.
Fixes #1915.
=> Tests: Remove redundant placeholder function

phpcs.xml.dist.sample
Currently file [phpcs.xml.dist.sample](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/phpcs.xml.dist.sample#L149) has a case sensitive typo.
It is:
```xml
<rule ref="WordPress.Files.Filename">
<exclude-pattern>/path/to/Tests/*Test\.php</exclude-pattern>
</rule>
```
Should be:
```xml
<rule ref="WordPress.Files.FileName">
<exclude-pattern>/path/to/Tests/*Test\.php</exclude-pattern>
</rule>
```
I stumble across this when having [this issue](https://github.com/WordPress/WordPress-Coding-Standards/issues/2375).
=> Docs: Use `FileName` rule instead of `Filename` in the sample phpcs ruleset

.github/workflows/basic-qa.yml, Tests/RulesetCheck/example-ruleset-test.inc
... to prevent typos like reported in #2375 from entering it.
Note: On the "Actions" tab you can see that I've also tested the "failure" case. It doesn't show the fatal error, but it does fail the build with an "ERROR: Referenced sniff "WordPress.Files.Filename" does not exist" error, so this should safeguard things sufficiently, I hope.
=> GH Actions: add task to test example ruleset

.github/FUNDING.yml, README.md
For the FUNDING.yml file, I'm not 100% sure if we can link to the specific subpage, or will this work only with 
```yml
open_collective: thewpcc
```
=> Add funding to the readme and add funding file

.github/FUNDING.yml
This should either be an array of links or a singular link. The `WP PHP` was regarded as an invalid link (not as a link description).
Ref: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
=> Funding: fix format

.github/release-checklist.md
Apparently we have to pro-actively inform the team as they don't appear to watch Make.
Ref: https://developer.wordpress.org/news/2023/09/whats-new-for-developers-september-2023/#comment-1611
=> Release checklist: add link to monthly dev blog

WordPress/Sniffs/Security/EscapeOutputSniff.php
This splits certain cases out of `OutputNotEscaped` to allow for ignoring certain cases that are looking at error strings at time of generation (where they may eventually be used in both HTML and non-HTML contexts) rather than at time of output.
* `ExceptionNotEscaped` for unescaped strings in throws (cf. #2374).
* `ErrorNotEscaped` for unescaped strings in `trigger_error` (cf. #1864).
=> Security/EscapeOutputSniff: More modular error codes

.github/FUNDING.yml, .github/release-checklist.md, .github/workflows/basic-qa.yml, CHANGELOG.md, README.md, Tests/RulesetCheck/example-ruleset-test.inc, WordPress/Sniffs/Security/EscapeOutputSniff.php, phpcs.xml.dist.sample
:warning: **DO NOT MERGE (YET)** :warning:
**Please **do** add approvals if you agree as otherwise we won't be able to release.**
PR for tracking changes for the 3.0.1 release. Target release date: **Wednesday September 13, 2023**.
:pencil2: Make sure the "last updated" annotation in the docblocks for these lists has also been updated!
List based sniffs:
:pencil2: Remember to add a release link at the bottom!
:pencil2: Check if anything from the link collection at the bottom of the changelog needs to be copied in!
[phpcs-releases]:      https://github.com/squizlabs/PHP_CodeSniffer/releases
[phpcsutils-releases]: https://github.com/PHPCSStandards/PHPCSUtils/releases
[phpcsextra-releases]: https://github.com/PHPCSStandards/PHPCSExtra/releases
[month-in-wp]: …
=> Release WordPressCS 3.0.1

WordPress/Sniffs/WP/PostsPerPageSniff.php, WordPress/Tests/DB/SlowDBQueryUnitTest.inc, WordPress/Tests/DB/SlowDBQueryUnitTest.php, WordPress/Tests/WP/PostsPerPageUnitTest.inc
This will prevent the undefined offset internal error.
Closes #2390
=> Add defensive coding in posts per page sniff

WordPress-Extra/ruleset.xml
Looks like this one was missed in previous update rounds (not that it was a valid URL anyway).
=> Ruleset: update a URL

.github/workflows/unit-tests.yml
... which is expected later today.
* Builds against PHP 8.3 are no longer allowed to fail.
* Add _allowed to fail_ build against PHP 8.4.
=> GH Actions: update for the release of PHP 8.3

.github/CONTRIBUTING.md, WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml, composer.json
PHPCSExtra 1.2.0 was released yesterday and contains two new sniffs which IMO would be suitable for adding to WordPressCS.
Includes raising the minimum supported PHPCSExtra version. (will conflict with PR #2408 and will need rebase depending on which is merged first)
Ref:
* https://github.com/PHPCSStandards/PHPCSExtra/releases/tag/1.2.0
--
_Note: adding these sniffs means this PR will need to go into a new minor, while #2408 can go into a patch release._
=> Use two new sniffs from PHPCSExtra 1.2.0

.github/FUNDING.yml, README.md
The WP PHP Open Collective, aside from the name conveying the completely wrong message, has so far not been in touch with us about how funds can be released or anything else.
This seems like a dead-end.
Switching to the PHP_CodeSniffer Open Collective makes more sense (to me). Happy to have a discussion about this.
=> Update funding information

phpstan.neon.dist
... caused by improved, but not 100% correct, type information coming from PHPCSUtils.
This incorrect type info will be fixed in the next version of PHPCSUtils.
=> PHPStan: ignore two new issues

WordPress/Helpers/EscapingFunctionsTrait.php, WordPress/Helpers/SanitizationHelperTrait.php
WordPress 6.2.1 introduced the function [`sanitize_locale_name()`](https://developer.wordpress.org/reference/functions/sanitize_locale_name/). As it accepts only `[A-Za-z0-9_-]`, I propose to add it to escaping functions and unslashing sanitizing functions.
=> Add sanitize_locale_name() to escaping functions and unslashing sanitizing functions

WordPress-Core/ruleset.xml
Turns out the exclusion is a little too aggresive. The `Generic.WhiteSpace.LanguageConstructSpacing` _will_ throw an error when there is too much whitespace, but not when there is no whitespace and the next thing is an open parenthesis.
By removing the exclusion, an error will now (correctly) be thrown when there is no whitespace between a closure `use` keyword and the open parenthesis.
It also means that where there is _too much_ whitespace between the keyword and the open parenthesis, two errors will be thrown, one from the `Generic.WhiteSpace.LanguageConstructSpacing` sniff and one from the `Squiz.Functions.MultiLineFunctionDeclaration` sniff.
Well, so be it. As both sniffs expect the same thing, this shouldn't lead to fixer conflicts anyhow.
See …
=> Core: remove an exclusion

.github/CONTRIBUTING.md, .github/workflows/basic-qa.yml, .github/workflows/quicktest.yml, .github/workflows/unit-tests.yml, .gitignore, WordPress/Tests/DB/RestrictedClassesUnitTest.php, composer.json, phpstan.neon.dist, phpunit.xml.dist
PHP_CodeSniffer 3.8.0 now allows for running the tests, which are based on the PHPCS native test suite, with PHPUnit 8 and 9.
This commit updates the package to take advantage of that.
Includes:
* Widening the PHPUnit version requirements.
* Adding the PHPUnit 8+ cache file to `.gitignore`.
* Updating the PHPUnit configuration to make sure that deprecations will always show, even when on a high PHPUnit 9.6 version.
* Updating the info in `CONTRIBUTING`.
* Simplifications to the `quicktest` and `test` workflows. Also, the code coverage "high" run can now be run against PHP 8.3.
* Running PHPStan against PHP `latest` (couldn't previously be done due to the old PHPUnit version).
* Minor tweak to the PHPStan config to make sure PHP 8.x specific issues don't get flagged for this codebase.
* …
=> Tests: allow for PHPUnit 8/9

.github/CONTRIBUTING.md
I believe the path of the test case file used in the example of how to generate the list of expected lines with errors is wrong. This PR fixes it.
Here is the commit that introduced the current version of the line that is changed in this PR: https://github.com/WordPress/WordPress-Coding-Standards/pull/2367/commits/4a33d468821f805a1cd222990c46ad9d632b0bd7#diff-98e64bc1cd2db9333c6effe87bbe0d6dfe8714aba4c6bde45aa037fe0796e44cR141.
If we want to keep the current path for some reason, we might want to change the part that says "from the root directory of your WordPressCS clone".
=> Fix the test case file path used in a CONTRIBUTING.md example

WordPress/Sniffs/Security/EscapeOutputSniff.php
I spotted the `codind` typo, so I quickly skimmed for any other changes that Grammarly highlighted as well. 
No change to functionality.
=> EscapeOutput: Fix typos in code comments

.github/workflows/quicktest.yml, .github/workflows/unit-tests.yml
* Remove `--checkstyle` for a lint job which doesn't display with `cs2pr`.
* Remove a stray condition.
PHP 7.2 should be using PHPUnit 8, which doesn't use PHP Parser, so _fingers crossed_, this should solve the build failure.
=> GH Actions: minor tweaks

.github/CONTRIBUTING.md, Tests/RulesetCheck/class-ruleset-test.inc, WordPress-Extra/ruleset.xml, composer.json
This new PHPCS 3.9.0 sniff will flag code which contains a `||` and a `&&` operator in the same condition and their precedence is not clarified via parenthesis.
This should allow for users of WPCS to find/prevent some bugs in code.
I'd personally would **_highly_** recommend for WP Core to also use this sniff, but I suspect that will need due discussion/Make post/handbook change.
Note: running this sniff on WP Core as-is, would (to my surprise) not actually trigger any new errors.
Includes updating a code snippet in the Ruleset test to comply.
=> Extra: do not allow ambiguous conditions (needs PHPCS 3.9.0)

WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
Upstream a PR is open - and will be merged soon - to change the protection against the `Squiz` sniff, which this sniff extends, handling operators found in `declare()` statements. In particular, the PR is about how the sniff handles parse errors/live coding for declare statements.
As the WPCS sniff calls the parent `register()` method and falls through to the parent `process()` method, the WPCS sniff should automatically get that extra protection too.
This commit just adds an extra test to the `WordPress.WhiteSpace.OperatorSpacing` to safeguard things.
=> WhiteSpace/OperatorSpacing: add extra test

phpstan.neon.dist
PHPCSUtils 1.0.10 has been released, which fixes two false positives, meaning these ignore annotations can now be removed (as per the inline comments).
Ref: https://github.com/PHPCSStandards/PHPCSUtils/releases/tag/1.0.10
=> PHPStan config: update for release of PHPCSUtils 1.0.10

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php, WordPress/Sniffs/WP/ClassNameCaseSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.inc, WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.php, WordPress/Tests/WP/DeprecatedClassesUnitTest.inc, WordPress/Tests/WP/DeprecatedClassesUnitTest.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Based on a scan of WP Core at commit WordPress/wordpress-develop@3595704 using a preliminary sniff created for issue #1803.
Based on a scan of WP Core at commit WordPress/wordpress-develop@3595704 using a preliminary sniff created for issue #1803.
Based on a scan of WP Core at commit WordPress/wordpress-develop@3595704 using a preliminary sniff created for issue #1803.
Based on a scan of WP Core at commit WordPress/wordpress-develop@3595704 using a preliminary sniff created for issue #1803.
Based on a scan of WP Core at commit WordPress/wordpress-develop@3595704 using a preliminary sniff created for issue #1803.
The minimum version should be three versions behind the latest WP release, so what with 6.5 being in RC, to be released on next week, it should now …
=> Update list based sniffs for WP 6.5

.github/CONTRIBUTING.md, composer.json
Nothing major in the 1.0.10 release, but updating the requirement prevents us having to deal with invalid bug reports when people would already be running WPCS against PHP 8.4, as two issues related to a PHP 8.4 deprecation have been fixed.
Ref: https://github.com/PHPCSStandards/PHPCSUtils/releases/tag/1.0.10
=> Composer: raise the minimum supported PHPCSUtils version to 1.0.10

CHANGELOG.md
:exclamation: Reviews & approval welcome. I'll merge this myself (if approved) just before the release. :exclamation: 
* Release date set at this **Monday March 25th**.
=> Changelog for the release of WordPressCS 3.1.0

.github/workflows/basic-qa.yml
Okay, so apparently, there is a long-standing bug in the Microsoft package deploy process which caused `apt-get update` to fail in the first half hour after Microsoft has deployed a package.
The failure looks like this:
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
```
As this only happens intermittently (after a MS package deploy), the chance of running into this bug are slim, but guess what: today I ran into it.
This change to the workflow is intended to prevent the next person running into this issue from having to waste time on figuring this out.
By splitting the "Install xmllint" step into two steps: one doing the `apt-get update` and one doing the …
=> GH Actions: work around intermittent apt-get errors

.github/workflows/basic-qa.yml, .github/workflows/quicktest.yml, .github/workflows/unit-tests.yml, composer.json
When working with this repository as a developer, we should be using the latest compatible packages. By writing a lock file for Composer, we may get into a state where we are "stuck" on an older version of a dependency. This change avoids such a situation by telling Composer to not write out a lock file in the project.
=> Composer: avoid writing a lock file

WordPress/Docs/DB/PreparedSQLStandard.xml
This PR adds documentation for the `WordPress.DB.PreparedSQL` sniff.
Part of #1722
=> [Documentation]: WordPress.DB.PreparedSQL

WordPress/Docs/Arrays/ArrayIndentationStandard.xml, WordPress/Docs/Arrays/ArrayKeySpacingRestrictionsStandard.xml, WordPress/Docs/Arrays/MultipleStatementAlignmentStandard.xml, WordPress/Docs/NamingConventions/PrefixAllGlobalsStandard.xml, WordPress/Docs/PHP/IniSetStandard.xml, WordPress/Docs/PHP/YodaConditionsStandard.xml, WordPress/Docs/WP/CapabilitiesStandard.xml, WordPress/Docs/WP/CapitalPDangitStandard.xml, WordPress/Docs/WP/DeprecatedParametersStandard.xml, WordPress/Docs/WP/PostsPerPageStandard.xml, WordPress/Docs/WhiteSpace/ObjectOperatorSpacingStandard.xml
* Double checked that all existing XML docs have the `xsi` attributes and schema reference on the `<documentation>` element.
* Verified that the contents of `<standard>` elements is consistently indented (with four spaces).
* Verified that all `<code>` `title` attributes use proper capitalization and punctuation.
=> Documentation: various consistency fixes

WordPress/Docs/Arrays/MultipleStatementAlignmentStandard.xml, WordPress/Docs/DateTime/CurrentTimeTimestampStandard.xml, WordPress/Docs/NamingConventions/PrefixAllGlobalsStandard.xml, WordPress/Docs/NamingConventions/ValidFunctionNameStandard.xml, WordPress/Docs/NamingConventions/ValidHookNameStandard.xml, WordPress/Docs/NamingConventions/ValidPostTypeSlugStandard.xml, WordPress/Docs/PHP/IniSetStandard.xml, WordPress/Docs/PHP/StrictInArrayStandard.xml, WordPress/Docs/WP/CapabilitiesStandard.xml, WordPress/Docs/WP/ClassNameCaseStandard.xml, WordPress/Docs/WP/DeprecatedClassesStandard.xml, WordPress/Docs/WP/DeprecatedFunctionsStandard.xml, WordPress/Docs/WP/DeprecatedParameterValuesStandard.xml, WordPress/Docs/WP/DeprecatedParametersStandard.xml, WordPress/Docs/WhiteSpace/CastStructureSpacingStandard.xml, WordPress/Docs/WhiteSpace/OperatorSpacingStandard.xml
Follow up on #2468
Darn! Looks like I forgot to push an update to the commit. Sorry about that.
This adds the capitalization consistency fixes for the `<code>` `title` attributes.
=> Documentation: capitalization consistency fixes

WordPress/AbstractFunctionRestrictionsSniff.php
This PR fixes a small typo in the `AbstractFunctionRestrictionsSniff::is_targetted_token()` DocBlock.
=> Fix typo in AbstractFunctionRestrictionsSniff::is_targetted_token() DocBlock

WordPress/AbstractClassRestrictionsSniff.php
This commit fixes the test failure seen in PR #2499.
The test failure was surfaced due to a new exception in PHPCS (see: PHPCSStandards/PHP_CodeSniffer#524), which will be included in PHPCS 3.11.0.
The test failure highlighted that the above mentioned PHPCS PR needs a follow-up with some extra defensive coding, however, that defensive coding is needed in a part in PHPCS which does the error handling for PHP notices being encountered, i.e. the throwing of `Internal.Exception` errors.
This implied there was also an underlying issue in WPCS causing the `Internal.Exception`, which apparently was only triggered when the fixer was being run.
> Note: the fact that `Internal.Exception`s during a PHPCBF run are being suppressed is a known issue, but fixing that is not that easy, so that definitely …
=> AbstractClassRestrictionsSniff: fix insufficient defensive coding

.github/workflows/basic-qa.yml
This Monday, [PHPStan 2.0 will be released](https://phpc.social/@OndrejMirtes/113441109253809720).
I've done some preliminary scans with PHPStan 2.0-dev to check if this would have an impact on this codebase and as things are, this would mean the build would start to fail.
For now, I'm proposing to make a small change in the GH Actions workflow to explicitly use PHPStan 1.x.
This buys us some time to evaluate PHPStan 2.0 properly and to make any changes needed to make the codebase compatible with PHPStan 2.x when we're ready for it.
=> GH Actions: use explicit PHPStan major

WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
This commit updates various sniffs to use `return $phpcsFile->numTokens` instead of `return ($phpcsFile->numTokens + 1)`.
If a sniff file contains 50 tokens, the last `$stackPtr` will be 49, so returning `50` will already get us passed the end of the token stack and the `+ 1` is redundant.
Includes changing a few plain `return` statements to `return $phpcsFile->numTokens` for efficiency.
=> Various sniffs: simplify skipping the rest of the file

.github/workflows/basic-qa.yml, .github/workflows/unit-tests.yml
... to satisfy shellcheck rule SC2086: "Double quote to prevent globbing and word splitting".
Ref: https://www.shellcheck.net/wiki/SC2086
=> GH Actions: always quote variables

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
Even though PR #2507 ensured we didn't automatically move onto PHPStan 2.0, the build is still failing as PHPStan 1.12.9 contained a change which causes a new error to show up.
This commit fixes [the newly flagged issue](https://github.com/WordPress/WordPress-Coding-Standards/actions/runs/11775908547/job/32797254994) to allow builds to pass again.
Ref: https://github.com/phpstan/phpstan/releases/tag/1.12.9
=> CS/QA: remove redundant condition

.github/workflows/unit-tests.yml, README.md
* Builds against PHP 8.4 are no longer allowed to fail.
* Add _allowed to fail_ build against PHP 8.5.
* Update the "tested against" badge in the README.
Ref: https://www.php.net/releases/8.4/en.php
=> GH Actions: PHP 8.4 has been released

WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
While working on #2512, I noticed an unnecessary variable initialization, so I'm creating this PR to suggest that it be removed. Its value is immediately overridden in an if/else below.
https://github.com/rodrigoprimo/WordPress-Coding-Standards/blob/690f05a51d190586e0bb0426a0f04242224d0723/WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php#L727
https://github.com/rodrigoprimo/WordPress-Coding-Standards/blob/690f05a51d190586e0bb0426a0f04242224d0723/WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php#L749
=> I18nTextDomainFixer: remove unnecessary variable initialization

WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
As discussed in https://github.com/WordPress/WordPress-Coding-Standards/pull/2513#issuecomment-2510860338, this PR removes unused variables detected automatically using PHPStorm code inspection from a few sniffs.
I have checked that the removed variables do not trigger errors at PHPStan levels higher than what we are currently using and that the modified code has at least minimal test coverage.
@dingo-d, in the screenshot that you shared in https://github.com/WordPress/WordPress-Coding-Standards/pull/2513#issuecomment-2510860338, `EnqueuedResourcesSniff.php` is included, but I was not able to find any unused variables in this file.
=> Remove unused variables from a few sniffs

WordPress/Docs/NamingConventions/ValidVariableNameStandard.xml
=> Add documentation for WordPress.NamingConventions.ValidVariableName

WordPress/Docs/PHP/DontExtractStandard.xml
=> DontExtractStandard.xml file creation

.github/workflows/basic-qa.yml
The intention is for there to be a dedicated action runner available at some point for XML code style checking, so let's move this to a separate job.
Also see: PHPCSStandards/PHPCSDevTools#145
Instead of doing all the installation steps for xmllint validation in the workflow, use the ✨ new dedicated `phpcsstandards/xmllint-validate` action runner instead.
Ref: https://github.com/marketplace/actions/xmllint-validate
... for dev tool files.
=> GH Actions: use the xmllint-validate action runner and enhance checks

.github/CONTRIBUTING.md, .github/workflows/unit-tests.yml, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php, composer.json
This PR is just to unblock WPCS/fix the failing test run.
Fixing the failure test run without these version bumps would mean having to polyfill support for PHP 8.4 properties in interfaces, which is not something we should want to do (that's why we use PHPCSUtils, which does the polyfill for PHPCS 3.x as PHPCS natively will only start supporting this in PHPCS 4.0).
This PR does **NOT**:
* Start using the new features from PHPCSUtils 1.1.0.
* Add support for all the new PHP syntaxes for which support was added to PHPCS + PHPCSUtils since PHPCS 3.9.0.
---
... to benefit from new functionality.
This also automatically raises the minimum PHPCS version to `3.13.0` for PHP 8.2 DNF type support and tokenizer support for PHP 8.4 `final` properties and asymmetric visibility.
Includes syncing the …
=> Composer: raise the minimum supported PHPCSUtils version to 1.1.0 + fix CI

WordPress-Extra/ruleset.xml
Two new sniffs were introduced in PHPCS 3.11.0:
* The `Generic.Strings.UnnecessaryHeredoc` sniff recommends using nowdoc syntax for heredocs which don't contain interpolation or expressions. This is similar to the `Squiz.Strings.DoubleQuoteUsage` sniff which is included in the WP-Core ruleset. Ref: https://github.com/WordPress/WordPress-Coding-Standards/blob/48e59e97eb950dc011d25a6759feb949afd802a0/WordPress-Core/ruleset.xml#L58-L60
* The `Generic.WhiteSpace.HereNowdocIdentifierSpacing` sniff required that there is no space between the `<<<` and the heredoc/nowdoc identifier.
Both seem like useful additions to me,
I also think both sniffs should be regarded as candidates for moving them to the WPCS Core ruleset if/when a next update proposal is posted on Make.
=> Extra: add two new sniffs related to heredoc/nowdocs

WordPress/Tests/Files/FileNameUnitTest.php, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.php
This PR adds a test to cover code handling STDIN for the two sniffs that check it: `WordPress.Files.FileName` and `WordPress.Utils.I18nTextDomainFixer`. This is based on a related suggestion from @jrfnl for a PHPCS sniff: https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/681#pullrequestreview-2456746389.
I'm not sure if I missed something, but I could not make the `ConfigDouble` class work passing the standard and sniff names as parameters. I had to create a custom ruleset file and include the sniff passing its path. I believe this happens because the `ConfigDouble` class erases the config data, and thus, `installed_paths` is empty.
=> Add tests for code handling STDIN for the sniffs FileName and I18nTextDomainFixer

.github/CONTRIBUTING.md, .github/workflows/basic-qa.yml, CHANGELOG.md, README.md, WordPress-Core/ruleset.xml, WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Docs/PHP/DontExtractStandard.xml, WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Helpers/WPDBTrait.php, WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Sniffs/CodeAnalysis/AssignmentInTernaryConditionSniff.php, WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php, WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.5.inc, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.6.inc, _typos.toml
Follow up on PR #2472 - safeguarding that no new typos get introduced.
Notes:
* The "Typos" tool is known for having a low false positive ratio and being aware of code contexts. However, this also means, it may at times miss some things.
When selecting it, I deemed the low false positive ratio more important.
* The language has been set to `en-US` as that's the language predominantly used for the WordPress documentation.
This does mean that various phrases using `en-GB` spelling will need to be fixed/updated.
Ref: https://github.com/crate-ci/typos
Mostly US English vs UK English and as WP Core predominantly uses US English, I think we should standardize on that for this spellcheck as well.
Note: where text was copied from the rules on https://developer.wordpress.org/coding-standards/ …
=> GH Actions: add a basic spellcheck CI check + fix some typos

WordPress/Helpers/ConstantsHelper.php, WordPress/Helpers/ListHelper.php
While working on an unrelated task, I noticed that the class description in the docblock for the `ConstantsHelper` and `ListHelper` classes was incorrect. The previous description contained information about the `ContextHelper` class. This PR fixes that.
=> Fix the class description for ConstantsHelper and ListHelper

WordPress/Helpers/ConstantsHelper.php
The parameter description incorrectly mentioned that `$strackPtr` should be the pointer to a function call token, while it actually should be the pointer to a T_STRING token.
=> Update parameter description for `$stackPtr` in `ConstantsHelper::is_use_of_global_constant()`

WordPress/AbstractFunctionParameterSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/PHP/IniSetSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php
Not claiming completeness, but just fixing up some I ran into.
=> Docs: improve type specificity

WordPress/Tests/DB/RestrictedClassesUnitTest.2.inc, WordPress/Tests/DB/RestrictedClassesUnitTest.3.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.9.inc, WordPress/Tests/Security/NonceVerificationUnitTest.1.inc, WordPress/Tests/Security/NonceVerificationUnitTest.5.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc.fixed
While adding a new test to CapitalPDangitUnitTest.1.inc in an unrelated commit, I noticed unnecessary trailing spaces in this file. Instead of removing them just for this one test, I opted to create this PR removing unnecessary trailing spaces from all test files using `Squiz.WhiteSpace.SuperfluousWhitespace`. I'm including only the files where it was easy to check that the spaces were not added intentionally.
=> Tests: remove unnecessary trailing spaces from the test files

WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc.fixed
Typed class constants were introduced in PHP 8.3 (https://wiki.php.net/rfc/typed_class_constants). PHPCS started supporting it in version 3.9.0 (https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/321). Since WPCS requires PHPCS 3.13.x, with @jrfnl's help, I investigated what needed to be updated in the WPCS repository to accommodate this new syntax.
In this PR, I'm adding tests to `WordPress.NamingConventions.PrefixAllGlobals` and `WordPress.WP.CapitalPDangit` to safeguard that those two sniffs continue to handle type class constants correctly, as both sniffs use the `T_CONST` token. No changes were required to the code of those sniffs.
`ConstantsHelper::is_use_of_global_constant()` and `AbstractClassRestrictionsSniff` will need to be changed as well to support typed class constants. …
=> PHP 8.3 typed class constants: add tests to two sniffs

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php, WordPress/Sniffs/WP/CapabilitiesSniff.php, WordPress/Sniffs/WP/ClassNameCaseSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php, WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.inc, WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Based on a scan of WP Core at commit WordPress/wordpress-develop@c5d3e24 using a preliminary sniff created for issue #1803.
Based on a manual check of WP Core at commit WordPress/wordpress-develop@c5d3e24.
Based on a scan of WP Core at commit WordPress/wordpress-develop@c5d3e24 using a preliminary sniff created for issue #1803.
Based on a scan of WP Core at commit WordPress/wordpress-develop@c5d3e24 using a preliminary sniff created for issue #1803.
Based on a scan of WP Core at commit WordPress/wordpress-develop@c5d3e24 using a preliminary sniff created for issue #1803.
Based on a scan of WP Core at commit WordPress/wordpress-develop@c5d3e24 using a preliminary sniff created for issue #1803.
=> Update list based sniffs for WP 6.8.1

WordPress/Helpers/MinimumWPVersionTrait.php, WordPress/Tests/WP/DeprecatedClassesUnitTest.inc, WordPress/Tests/WP/DeprecatedClassesUnitTest.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc
The minimum version should be three versions behind the latest WP release, so what with 6.8.2 being the latest release, it should now become 6.5.
Includes updating the tests to match.
Previous: #2121, #2321. #2436
=> Update the `minimum_wp_version` to WP 6.5

CHANGELOG.md
Indentation in markdown should always be spaces, not tabs.
=> CHANGELOG: fix indentation

WordPress/Helpers/ListHelper.php, WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Sniffs/PHP/YodaConditionsSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php, WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.1.inc, WordPress/Tests/Security/EscapeOutputUnitTest.php
Just a collection of some small commits to take advantage of things which PHPCSUtils 1.1.0 brings.
---
The `FilePath::getName()` method will strip quotes from the file name, as well as normalize the slashes to forward (*nix) slashes.
This allows for a minor simplication in the code and improves code readability.
The `FilePath::getName()` method will strip quotes from the file name, as well as normalize the slashes to forward (*nix) slashes.
This allows for a minor simplication in the code and improves code readability.
As of PHP 8.4, the internal of `T_EXIT` are changing in PHP itself and `exit`/`die` will internally be treated as a function call.
The net effect of this is that named parameters can now be used with `exit()`/`die()`.
For the `WordPress.Security.EscapeOutput` sniff this …
=> Use PHPCSUtils 1.1.0 features

WordPress/Helpers/EscapingFunctionsTrait.php
The `wp_kses_allowed_html()` function is not an escaping function, but retrieves an array of allowed HTML tags and attributes for a given context.
Ref: https://developer.wordpress.org/reference/functions/wp_kses_allowed_html/
=> EscapingFunctionsTrait: remove `wp_kses_allowed_html()` from escaping functions

WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php
The `'type'` index in the token array should generally only be used for PHPCS cross-version compatibility, where the token constant we are looking for may not be defined in all supported PHPCS versions.
That's not the case for these.
=> NamingConventions/ValidPostTypeSlug: check token via code, not type

.phpcs.xml.dist, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.1.inc, WordPress/Tests/Security/EscapeOutputUnitTest.21.inc, WordPress/Tests/Security/EscapeOutputUnitTest.22.inc, WordPress/Tests/Security/EscapeOutputUnitTest.23.inc, WordPress/Tests/Security/EscapeOutputUnitTest.php
This PR fixes false negatives when the sniff `WordPress.Security.EscapeOutput` handles readonly anonymous classes and anonymous classes with attributes that are part of a throw statement.
When stepping over tokens after `T_THROW` to find the `T_OPEN_PARENTHESIS` of the exception creation function call/class instantiation, the sniff was not considering that it might need to step over `T_READONLY` tokens or attribute declarations when dealing with anonymous classes.
Fixes #2552
=> Security/EscapeOutput: fix false negatives when handling anonymous classes

WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php, WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.inc
While working on preparing WPCS for the changes in PHPCS 4.0, more specifically the changes around namespace tokenization, I noticed that the `WordPress.DB.PreparedSQLPlaceholders` sniff was not accounting for fully qualified calls to `implode()` in the code that checks for quotes in dynamically generated placeholders. This PR fixes that. See the modified test for an example of a code that would cause a false negative.
=> DB/PreparedSQLPlaceholders: fix false negative when checking quotes in dynamic generated placeholders

WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php, WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.1.inc, WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.2.inc, WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.php
Four non-standard type casts are going to be deprecated in PHP 8.5.
When any of these type casts would be used in the parameter this sniff examines in the "code under scan" and the sniff would be run on PHP 8.5, the non-standard type cast would be executed via the `eval()`, leading to a deprecation notice, which would stop the scan of the file.
This commit works around this by always using the "standard" type cast syntax in the code which would be passed to `eval()`.
=> PHP 8.5 | WP/EnqueuedResourceParameters: prevent deprecation notice for non-standard casts

WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php, WordPress/Tests/Security/NonceVerificationUnitTest.8.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.8.inc
Asymmetric visibility properties were introduced in PHP 8.4 (https://wiki.php.net/rfc/asymmetric-visibility-v2). PHPCS started supporting it in version 3.13.0 (https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/871). Since WPCS requires PHPCS 3.13.x, with @jrfnl's help, I investigated what needed to be updated in the WPCS repository to accommodate this new syntax.
In this PR, I'm adding tests to `WordPress.NamingConventions.PrefixAllGlobals`, `WordPress.NamingConventions.ValidVariableName`, `WordPress.Security.NonceVerification`, and `WordPress.WP.GlobalVariablesOverride` to safeguard that those four sniffs continue to handle asymmetric visibility properties correctly, as those sniffs have code related to class properties or parameters passed to the class constructor (in the case of …
=> PHP 8.4 asymmetric visibility properties: add tests to four sniffs

WordPress/Tests/DB/RestrictedClassesUnitTest.php
Calling `AbstractSniffUnitTest::setUpPrerequisites()` manually inside `RestrictedClassesUnitTest::enhanceGroups()` is not necessary, as this method already executes via its `@before` tag and results in the method running twice.
Originally, `RestrictedClassesUnitTest::enhanceGroups()` was named `RestrictedClassesUnitTest::setUp()` and called `parent::setUp()` ([WordPress/Tests/DB/RestrictedClassesUnitTest.php#L34-L35](https://github.com/WordPress/WordPress-Coding-Standards/blob/3b9ae92607295548df357e108fd27090cf89d1d7/WordPress/Tests/DB/RestrictedClassesUnitTest.php#L34-L35)). But later it was renamed, and then it probably didn't make sense to continue calling `parent::setUp()` (which was later renamed to `setUpPrerequisites()`): https://github.com/WordPress/WordPress-Coding-Standards/commi …
=> DB/RestrictedClasses: remove redundant call to `parent::setUpPrerequisites()`

.github/release-checklist.md
Rodrigo and me just noticed that a few PRs which were merged into the `3.2.0` release did not have a milestone attached. We've fixed those now and will fix the changelog too (only one needed a mention, the others were maintenance PRs).
This commit just adds a new reminder bullet to verify that all PRs are milestoned before creating the changelog to (hopefully) prevent this from happening again.
_Side-note: in other repos I actually have it required check for the milestone being set (can't merge without it), but that would require permission from the WordPress organisation to allow the [app which handles that](https://github.com/scholzj/milestone-check) and that might get complicated..._
=> Release checklist: add new bullet about checking all PRs are milestoned

CHANGELOG.md
@jrfnl is mentioned in the changelog, but there was no link for their GitHub profile page at the bottom, so the link was broken. This commits adds the link to fix this problem.
Per Juliette's suggestion, I'm adding links to the other maintainers as well to prevent this problem from happen to them in the future.
=> Changelog: add WPCS maintainers to the list of GitHub profile links

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
Fixes a typo found while investigating https://github.com/WordPress/WordPress-Coding-Standards/issues/2602 and https://github.com/WordPress/WordPress-Coding-Standards/issues/2603.
_N/A_
=> WP/AlternativeFunctions: fix typo in code comment

.github/CONTRIBUTING.md
=> CONTRIBUTING: update the example test output

WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
This PR adds tests for cases where the  `WordPress.WP.GlobalsVariableOverride` sniff is not able to resolve the value of `$GLOBALS` keys.
=> WP/GlobalVariablesOverride: more tests covering unresolvable `$GLOBALS` keys

.github/dependabot.yml, .github/workflows/basic-qa.yml, .github/workflows/manage-labels.yml, .github/workflows/quicktest.yml, .github/workflows/unit-tests.yml
Recently there has been more and more focus on securing GH Actions workflows - in part due to some incidents.
The problem with "unpinned" action runners is as follows:
* Tags are mutable, which means that a tag could point to a safe commit today, but to a malicious commit tomorrow.
Note that GitHub is currently beta-testing a new "immutable releases" feature (= tags and release artifacts can not be changed anymore once the release is published), but whether that has much effect depends on the ecosystem of the packages using the feature.
Aside from that, it will likely take years before all projects adopt _immutable releases_.
* Action runners often don't even point to a tag, but to a branch, making the used action runner a moving target.
_Note: this type of "floating major" for action …
=> GH Actions: "pin" all action runners 
