WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
Curently `else:` throws two errors:
1. Space after opening control structure is required (the Coding Standards handbook doesn't say anything on this)
1. No space before opening parenthesis is prohibited (this is just wrong - there is no paranthesis on this line)
This pull request prevents the sniffer from throwing these two errors.
------
If my interpretation of 1. is considered correct, I could add a fixable error for `else :`
=> Fix T_ELSE immediately followed by T_COLON

WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc
There are two different sanitization checks in the `VIP.ValidatedSanitizedInput` sniff. Only one of
them was considering that casting is a form of input sanitization. I’ve
moved the casting check out of the conditional it was in, and now the
`$is_casted` value is being checked for all sanitization checking paths.
Fixes #179
=> Always consider casting sanitization

WordPress/Sniffs/Arrays/ArrayDeclarationSniff.php, WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php, WordPress/Sniffs/Classes/ValidClassNameSniff.php, WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Sniffs/VIP/AdminBarRemovalSniff.php, WordPress/Sniffs/VIP/CronIntervalSniff.php, WordPress/Sniffs/VIP/FileSystemWritesDisallowSniff.php, WordPress/Sniffs/VIP/SessionFunctionsUsageSniff.php, WordPress/Sniffs/VIP/SuperGlobalInputUsageSniff.php, WordPress/Sniffs/VIP/TimezoneChangeSniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php
I've added granular error/warning names in most places.
* I've ignored some sniff files which only throw one specific error as those can be disabled by just disabling the sniff itself.
* For error/warning names, I've used the Squiz and PEAR coding standards for inspiration and stuck to the names used in there for the same error if one existed.
* In 1 instance (VIP/CronIntervalSniff), the existing error name did not comply with the CamelCaps convention for the names. I've changed the name. This will break backward compatibility for any rulesets referencing the 'old' name.
=> Add granular error/warning names - issue #297, #140

WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php, WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.php
As it's a hard rule mentioned in the core guide and most other spacing rules are enforced with errors, I suggest changing the enforcement of this rule from warning to error.
=> Change array key spacing message from warning to error

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
When a ternary operator is present in an `echo` statement, it is safe
to skip over everything before the `?`, since that part isn’t output.
Fixes #281
=> Account for ternary operator in XSS sniff

WordPress/Sniffs/Arrays/ArrayDeclarationSniff.php
This isn’t a part of WordPress’s coding standards. Actually, meta
queries require this for setting the query’s `relation`.
Fixes #233
=> Don't give an error for mixed key/keyless arrays

WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
=> Allow camel caps method names in child classes

WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php
WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php contains byte-order marks before the opening PHP tags. This causes output reports to also include this output. Unfortunately this breaks parsing of the JSON reports (See https://github.com/Block8/PHPCI/issues/768). 
This patch just removes the extra characters before the opening PHP tags.
=> Remove BOM that breaks JSON output parsing

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
Currently the XSS sniff will flag this:
```php
echo 5;
```
Of course, that’s harmless.
=> Allow integers in XSS sniff

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
Other functions we should possibly add: https://stackoverflow.com/questions/4673747/what-php-functions-create-output
See #170
=> XSS sniff: require escaping for die(), exit(), printf()

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
This bug would happen when there was code like this:
```php
if ( ! defined( ‘ABSPATH’ ) ) {
exit; // We skipped over the semicolon, assuming the next thing would be an opening parenthesis.
}
// This code would get flagged as needing escaping.
other_code();
```
See #312
=> XSS: don't flag code after an empty exit

WordPress/Sniffs/XSS/EscapeOutputSniff.php
Several improvements for the list of printing functions in the XSS sniff.
- Removes non-printing functions from this list.
- Renames the property to clarify what it is for.
- Allow custom printing functions to added via XML config.
=> XSS sniff: improvements for printing function list

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
=> XSS sniff: don't flag comments as needing escaping

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
`wp_die()` takes three parameters, and [all of their values may be
printed to the
user](https://developer.wordpress.org/reference/functions/_default_wp_di
e_handler/), without any escaping.
=> XSS sniff: Add wp_die() to the list of printing functions

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
Otherwise the ending parenthesis of the array will be reported in this:
```php
wp_die( esc_html( $message ), '', array( 'response' => 200 ) );
```
=> XSS sniff: ignore ending parenthesis for wp_die()

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
I have quite a few instances of `wp_die( -1 );` in some of my code.
This is used a lot in WordPress too.
=> XSS sniff: allow for negative numbers

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
`echo` accepts an unlimited number of arguments, separated by commas.
This was previously supported, however, there was a bug that any
arguments after the first escaping function would be ignored.
Recent changes (specifically e329860329df49f54a727aa2125b217b06a50e1f),
have made it so that now any commas themselves are being reported as
needing sanitization.
The fix is a simple change on line 373 so that we always wake up for
commas. All of the arguments given to `echo` are always checked, and
the commas themselves are ignored.
However, this causes an issue with the casting of function calls with
multiple arguments.
```php
echo (int) get_post_meta( $post_id, ‘some_integer’, true );
```
The first comma in the casted function would cause us to wake up
prematurely, and report the later …
=> Support for echo with comma-separated args

WordPress/Sniffs/XSS/EscapeOutputSniff.php
This function is almost identical to `urlencode()`, which is already in the list. The difference is that [`rawurlencode()` is more up-to-date with the standards](http://stackoverflow.com/q/996139/1924128), while `urlencode()` is more of a legacy function.
=> XSS sniff: Add rawurlencode() to the sanitizing functions

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
A regression was introduced in the `EscapeOutputSniff`, probably as part of #312, #314, #315, #316, or #317.
The second two of the three OK lines added to this unit test are failing. It seems not adding a semicolon to the first instance causes the second OK line to croak, but the third OK line seems to fail regardless of prior semicolons.
=> Fix EscapeOutput regression

WordPress/Sniffs/XSS/EscapeOutputSniff.php
Also remove unused variable.
I was getting these errors in a certain file, not sure which:
```
PHP Notice:  Undefined index: parenthesis_closer in .../phpcs/CodeSniffer/Standards/WordPress/WordPress/Sniffs/XSS/EscapeOutputSniff.php on line 299
```
=> Add isset check for parenthesis_closer to prevent undefined index notice

WordPress/Sniffs/Arrays/ArrayDeclarationSniff.php, WordPress/Tests/Arrays/ArrayDeclarationUnitTest.inc
When checking that the last line of an array ends in a comma, both whitespace ( `T_WHITESPACE`) and regular comments (`T_COMMENT`) were ignored, but not docblock comments (those beginning with `/**`, `T_DOC_COMMENT`). This fixes that.
Fixes #230
=> Ignore docblock comments within arrays

WordPress/Sniffs/Variables/GlobalVariablesSniff.php
I removed content_width from the globals array which makes it so it won't get flagged. #276
=> Removes content_width as non-overwritable global. Fixes #276

.travis.yml
Failures are allowed for PHP nightly (7.0) and HHVM.
#reviewmerge
=> Travis CI: run against PHP 5.6, nightly, and HHVM

.travis.yml
Looks like PHPCS has deleted the `phpcs-fixer` branch, so we need to revert to `master` for testing.
#reviewmerge
=> Change PHPCS branch used for testing

WordPress/Sniffs/XSS/EscapeOutputSniff.php
=> Add vip_powered_wpcom() to list of autoescaped functions

WordPress/Sniff.php, WordPress/Sniffs/VIP/SuperGlobalInputUsageSniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
Adds an abstract class, `WordPress_Sniff` to provide a bootstrap for our sniffs. Includes a method for checking for whitelisting comments. I've converted the sniffs that allow for whitelisting comments to use this method, however, the logic is a bit different than previously used, so it'd be helpful if some folks would test this against projects where they use whitelisting comments heavily.
Feedback would also be appreciated regarding https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/246#issuecomment-80720786 and  a9ad818.
Closes #246
=> abstract WordPress_Sniff class

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
`sprintf()` is often used for formatting translation strings, and it is common practice to escape the individual parameters passed to it as needed instead of escaping the entire result. This is especially true when the string being formatted contains HTML, which makes escaping the full result more difficult.
This provides better handling for `sprintf()` by ignoring the function itself and only requiring escaping for its parameters.
Note that `sprintf()` also provides limited sanitization for the values passed to it when number formatting is performed (i.e., for all but the `%s` placeholder). I had originally wanted to take this into account, but it proved too complex. So all parameters passed to `sprintf()` need to be escaped, even when they will be formatted using, e.g., `%d`, and are …
=> XSS sniff: better handling for sprintf()

WordPress/Sniffs/PHP/YodaConditionsSniff.php, WordPress/Tests/PHP/YodaConditionsUnitTest.inc, WordPress/Tests/PHP/YodaConditionsUnitTest.php
This fixes issues with comparison to constants not being flagged, and
probably will be less buggy overall.
There is one side-effect:
```php
// Before this was good:
if ( $true == strtolower( $check ) ) {}
// Now it’s bad, but this is OK:
if ( strtolower( $check ) == $true  ) {}
```
I think this is the correct behavior.
Another thing to consider is when comparing a variable to a variable. I
don’t remember what the previous behavior was, but this is current
behavior:
```php
if ( $foo == $bar ) {} // Bad
if ( ( $foo ) == $bar ) {} // OK
```
Finally, the matching code is no longer included in the error message.
It’s possible to add that back in, but it would take some work.
Feedback welcome. :-)
Fixes #290
=> Yoda Sniff: Use tokenizer instead of regex

WordPress-VIP/ruleset.xml, WordPress/Sniffs/Arrays/ArrayAssignmentRestrictionsSniff.php
If no groups of keys to look for are registered, it will remove itself
from listening to the rest of the file. Previously it would keep
getting called for each token in the file it sniffs for, even though
there were no checks to be performed. It did bail early, but now it
will only get called once per file with no groups registered.
We also remove the sniff from the VIP ruleset. This further improves
performance by keeping the sniff from being run at all. This may seem
like a strange thing to do, but this sniff actually does nothing by
itself. It is extended by some other sniffs, and should probably have
been abstract (but changing it now would not be backward compatible).
Even though the sniff is no longer part of the default configuration,
the performance improvements to the sniff …
=> Improve performance of the ArrayAssignmentRestictions sniff

WordPress/Sniffs/PHP/YodaConditionsSniff.php, WordPress/Tests/PHP/YodaConditionsUnitTest.inc, WordPress/Tests/PHP/YodaConditionsUnitTest.php
With the updates to the Yoda sniff (#319), a bug was introduced that
would cause this code to be flagged:
```php
return 0 === strpos( $foo, 'a' );
```
This is fixed by adding `return` to the list of tokens that, when
encountered without being preceded by a variable, indicate a condition
either already implements, or does not require, Yodaism.
#reviewmerge
=> Yoda sniff: fix issues with return statements

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
In #281 I introduces support for the ternary operator in cases like
this:
```php
echo ( $var ) ? esc_html( $var ) : ‘something’;
```
But sometimes it makes more since to put the ternary condition inside
of the escaping function:
```php
echo esc_html( $var ? $var : $other_var );
```
Up to now, both `$var` and `$other_var` would be flagged as needing
escaping. This PR fixes that.
#reviewmerge
=> XSS sniff: Support for ternaries within escaping functions

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
In #33, a list of localization functions like these were flagged as
needing escaping. In #315 I amended this list, removing non-printing
localization functions like `__()`, among other things. These changes
caused a regression in the treatment of the `_e()` and `_ex()`
functions, which remained on the list. They were previously flagged as
needing escaping, even when their parameters were “safe” values
(encapsed strings). That behavior was intentional, and was added
because these functions incorporate other values into their final
output, which need to be escaped before being printed. After #315,
however, these functions themselves were not flagged, only their
parameters when deemed unsafe (e.g., `_e( $var )`). This restores the
previous behavior, by classifying these as ‘unsafe printing …
=> XSS sniff: Mark _e() and _ex() as unsafe printing functions

WordPress/Sniff.php, WordPress/Sniffs/VIP/SuperGlobalInputUsageSniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php
This adds `$_COOKIE` and `$_FILE` to the list. `$_SERVER` was in the
list previously used by the `ValidatedSantizedInput` sniff, but not
that used by `SuperGlobalInputUsage` sniff. It is also now included for
both.
Fixes #354
=> Add centralized list of input superglobals

WordPress-Core/ruleset.xml
The reason that the `NewlineAfterOpenBrace` check is disabled is that
it is too finicky, and isn’t a part of the WordPress standards. It
would flag having two newlines at the top of a control structure
(something I do a lot), and would also flag this:
```php
if ( $var ) { // This comment would be flagged.
}
```
Fixes #355, #17
=> Sniff whitespace around braces of control structures

WordPress/Sniffs/Files/FileNameSniff.php
Instead of searching through the tokens of a file for each opening PHP
tag that is encountered, we keep a cache of the files that have been
checked, with lightning-fast lookup when we’re checking if a file has
already been processed.
Also removes a useless call to `ucfirst()` on a string that already has
an uppercase first letter.
=> Improve performance of the Files.FileName sniff

WordPress/Sniff.php
=> Fix typo in superglobal name

WordPress-Core/ruleset.xml
Copied from https://github.com/Yoast/yoastcs/blob/master/Yoast/ruleset.xml#L55-L61
The Squiz sniff actually checks whitespace for foreach loops as well as "as" being lowercase. We already [check whitespace](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php#L66) for `foreach`, so this is very much duplicating a bunch of checks.
I'm happy for this PR to be rejected if we want to have a separate Sniff for checking case, though it may make more sense to switch to the Squiz sniff for all `foreach` checks, if it has enough properties for us to set what our standard should be.
Edit: Added to Core, but may be more suited as an Extra.
=> Add check for lowercase "as" in foreach

WordPress/Sniff.php
We might want to consider doing a 0.4.1 release with this fix included.
Fixes #372
=> Fix fatal error for array_map() in sanitization check

WordPress/Sniffs/XSS/EscapeOutputSniff.php
Say you have code like this:
```php
if ( isset( $_REQUEST['foo'] ) && in_array( $_REQUEST['foo'], $array ) ) {
$foo = sanitize_key( $_REQUEST['foo'] );
}
```
This is safe, but the use of the raw `$_REQUEST['foo']` value in `in_array()` would be flagged. Adding `in_array()` to the list of auto-escaped functions avoids this.
=> Add in_array() to list of auto-escaped functions

WordPress/Sniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.php
Comparison of a super global to another value (e.g. `if ( 'a' === $_POST['foo'] )` or `switch ( $_POST['foo'] )`) doesn’t require sanitization. Previously it was flagged anyway, but this fixes that,
and introduces a new method to check for comparisons.
Fixes #186
=>  Santized sniff: don't flag comparisons 

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
Adds a few Generic sniffs for Core, and a whole bunch more for Extra. See the diff for which sniffs.
=> Add Core and Extra sniffs

WordPress-Docs/ruleset.xml, WordPress/ruleset.xml
There are still plenty of checks not made, but this first pass takes advantage of the existing code sniffs that match the WordPress handbook for inline documentation and commenting.
The exclusions are for specific checks that don't match that expected in WordPress-related code.
See #241
=> Add Squiz and Generic Commenting with exclusions

.travis.yml, composer.json
Right now we only test against PHPCS `master`. However, it is useful to test against older versions so that we know when we are breaking compatibility.
I changed the matrix to run against 2.0.0, 2.1.0, 2.2.0, and 3.0. Here is what I found:
We are incompatible with 2.0.0:
```
Fatal error: Call to undefined method PHP_CodeSniffer_File::findEndOfStatement() in /home/travis/build/WordPress-Coding-Standards/WordPress-Coding-Standards/WordPress/Sniffs/XSS/EscapeOutputSniff.php on line 347
```
We can run against 2.1.0, however, there are some oddities, possibly in the parser or something, that cause the tests for `WordPress.XSS.EscapeOutput` to fail.
So I've removed both those versions from the matrix. For more details you can see the travis build: …
=> Have Travis CI test against multiple verions of PHPCS

WordPress/Sniff.php, WordPress/Sniffs/CSRF/NonceVerificationSniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
Historically there has a been a list of “sanitizing” functions in the
XSS sniff. This list could be added to via the
`customSanitizingFunctions` property. This list of functions was also
used by the `ValidatedSanitizedInput` sniff.
However, what the XSS sniff is really checking for is that the output
is *escaped*. This is slightly different from *sanitization*, and is
(usually) performed by different functions.
In this commit, I’ve split the `sanitizingFunctions` list in the XSS
sniff, and moved it to the main sniff. This will allow the list to be
accessed from all sniffs more easily. I’ve also flipped the list so
that the functions are the keys instead of values, because this allows
for quicker lookup with `isset()` instead of having to use
`in_array()`. The values currently have no …
=> Separate sanitizing and escaping functions

WordPress-Core/ruleset.xml, WordPress/Sniffs/Arrays/ArrayDeclarationSniff.php, WordPress/Tests/Arrays/ArrayDeclarationUnitTest.inc.fixed, WordPress/Tests/Arrays/ArrayDeclarationUnitTest.php
This basically synchronizes it with `Squiz.Arrays.ArrayDeclaration`.
The upstream version is similar, except that we exclude a few errors.
Unfortunately we have to actually comment out the code rather than just
using the upstream sniff and `<exclude>` in our ruleset, due to a bug
(squizlabs/PHP_CodeSniffer#582). (I’ve also included a fix for another
bug, squizlabs/PHP_CodeSniffer#584.) Because of this, we cannot yet
eliminate duplicated logic from this child sniff.
I think this pretty much maintains the previous behavior, except that I
have added a warning for extra whitespace at the edges of multiline
arrays.
Another note, the whitespace messages are warnings:
```php
array(1, 2); // missing spaces
array(      1, 2        ) // extra spaces
```
Maybe these should be converted to errors? …
=> Add support for error fixing to ArrayDeclaration

WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.php
The validated/sanitized input sniff used not to handle super globals in
ternary conditions properly. Now it does, so I’ve added tests which
demonstrate this.
Closes #168
=> Add tests demonstrating ternary operator

WordPress/Sniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.php
This updates the validated/sanitized input sniff to also check for
slashing. This could have been made into another sniff instead,
however, it would have required lots of duplicated logic and this sniff
would need to be updated to accommodate the use of `wp_unslash()`
anyway.
Currently only `wp_unslash()` is recognized as an unlashing function,
but this can be changed in the future if needed.
The sniff currently requires that `wp_unslash()` be used *before* the
data is passed through a sanitizing function. Sanitizing first and then
wrapping that in `wp_unslash()` is not accepted.
The error for missing the use of `wp_unslash()` is independent of the
missing sanitizing function error, so an error will be given for
missing use of an unslashing function whether or not a sanitizing
function is …
=> Require unlashing of input superglobals

README.md
Rewrote "Standards subsets" section in readme:
- added new `WordPress-Docs` subset
- made list nesting reflect actual nesting structure
- reworded for shorter and more uniform descriptions
=> Clarified ruleset nesting in readme

WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Tests/VIP/DirectDatabaseQueryUnitTest.inc, WordPress/Tests/VIP/DirectDatabaseQueryUnitTest.php
See the commit messages for more info.
Fixes #397
=> Sundry improvements of the VIP.DirectDatabaseQuery sniff

WordPress/Sniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php
Sometimes one might use custom caching functions that wrap the
functions which WordPress uses. In that case, they should be able to
add them to the list used in this sniff using their XML config file.
=> DB query sniff: support custom cache functions

WordPress-VIP/ruleset.xml, WordPress/Sniffs/Functions/FunctionRestrictionsSniff.php, WordPress/Sniffs/Variables/VariableRestrictionsSniff.php
These rules are not really rules at all. Instead, they are parent
classes extended by other sniffs. They don’t do anything on their own,
and since the classes will be auto-loaded, we don’t need to include
them in the ruleset.
I’ve also updated each of these classes to skip over a file if there
are no tests to run. This will improve performance when running the
`WordPress` ruleset.
The function restrictions class could possibly be made abstract in the
future, if we wanted to do that. However, the variable restrictions
sniff has its own tests, and so it can’t be abstract.
Related: #345
=> Remove non-rules from VIP ruleset

.travis.yml
The `.travis.yml` file includes the following line which is intended to check for syntax errors:
`find . \( -name '*.php' \) -exec php -lf {} \;`
While it does indeed do this, it's not of any use because its output doesn't cause Travis to report the failure.
You can see [my recent efforts](https://travis-ci.org/johnbillion/user-switching/builds) to get this to work in my User Switching plugin. This is compatible with PHP and HHVM.
If you actually want to test it, you'll need to commit a file with a syntax error in it and wait for the Travis tests to run on the branch.
=> Correct the syntax error detection on Travis

WordPress/Sniff.php
They implicitly unslash the data passed to them, so it doesn't need to be put through `wp_unslash()` as well.
Fixes #426
=> Add intval() and boolval() to unslashing functions

WordPress/Sniff.php
`hash_equals()` returns a boolean value, and does not print anything directly, so it is safe to pass unsanitized data to it.
=> Add hash_equals() to list of sanitizing functions

WordPress/Sniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed
The `T_USE` token is also used to import traits to classes, and to
import classes into namespaces.
Fixes #431
=> Only check T_USE tokens associated with closures

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
Most ternary conditions handled by this sniff occur within a set of
parentheses, and these are handled when an open parenthesis is
encountered in the token loop. However, the echo “function” is often
used without parentheses. Because of this, special handling is required
for ternary conditions that are used in an echo statement without
parentheses.
Previously the code for detecting this scenario was unnecessarily
complex, and incorrectly identified some ternary conditions as not
occurring in parentheses when they actually did. The result of this was
twofold: first, it would sometimes flag an expression as needing to be
escaped when it did not; and second, it could also skip over an
expression that did need to be escaped without flagging it.
This is now fixed.
Fixes #421
=> Simplify and improve ternary handling in XSS sniff

WordPress/Sniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
Because `implode()` is mostly useless without `array_map()`.
Fixes #442
=> XSS sniff: support implode() and array_map()

WordPress/Sniff.php
It is possible to disable direct output from this function, however, it is enabled by default.
See #358
=> Add wp_dropdown_pages() to printing functions list

WordPress-Extra/ruleset.xml, WordPress-VIP/ruleset.xml, WordPress/Sniffs/WP/PreparedSQLSniff.php, WordPress/Tests/WP/PreparedSQLUnitTest.inc, WordPress/Tests/WP/PreparedSQLUnitTest.php
It flags any calls to `$wpdb->query()` and related functions that
incorporate variables, if they aren’t properly escaped using
`$wpdb->prepare()`.
Fixes #20
=> Add sniff for unprepared SQL

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
The logic was supposed to be looking for a second set of parentheses
within an outer set of parentheses. But because it passed `$i` to
`findNext()`, the current opening parenthesis was being found, since
`$i` points to the opening parenthesis at that point, and `findNext()`
starts with the _current_ token.
The solution is to start looking for the next opening parenthesis at
`$i + 1` instead.
Fixes #466
=> XSS sniff: fix ternary detection bug

WordPress/Sniff.php
=> Add count() to the list of auto-escaped functions

WordPress-VIP/ruleset.xml
https://vip.wordpress.com/documentation/code-review-what-we-look-for/#commented-out-code-debug-code-or-output
> ## Commented out code, Debug code or output
> […] The use of commented out code should be avoided. Having code that is not ready for production on production is bad practice and could easily lead to mistakes while reviewing (since the commented out code might not of been reviewed and the removing on a comment might slip in accidently).
=> Add Squiz.PHP.CommentedOutCode to WordPress-VIP

WordPress/Sniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/WP/PreparedSQLSniff.php, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.php, WordPress/Tests/WP/PreparedSQLUnitTest.inc, WordPress/Tests/WP/PreparedSQLUnitTest.php
Account for cases where '$' is used in double-quoted strings and is not referring to a variable.
=> Improve WordPress.WP.PreparedSQL.NotPrepared

WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.php
Now included among the uncached functions: https://vip.wordpress.com/documentation/caching/uncached-functions/
=> Add attachment_url_to_postid() to the restricted functions for WordPress-VIP

WordPress/Sniffs/PHP/YodaConditionsSniff.php, WordPress/Tests/PHP/YodaConditionsUnitTest.inc
Type casts were not taken into account.
=> Fix for incorrect Yoda sniff message when comparing two variables.

WordPress-Core/ruleset.xml, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php
Forks `Squiz.NamingConventions.ValidVariableName` for WordPress conventions.
Fixes #489.
=> Introduce WordPress.NamingConventions.ValidVariableName

WordPress/Sniff.php, WordPress/Sniffs/WP/PreparedSQLSniff.php, WordPress/Tests/WP/PreparedSQLUnitTest.inc, WordPress/Tests/WP/PreparedSQLUnitTest.php
The prepared SQL sniff was incorrectly flagging code that was properly escaping SQL without using the `$wpdb->prepare()` function. I've updated it not to flag this code, but perhaps it should be possible to toggle this feature (in case we want to force `$wpdb->prepare()` to be used)?
The sniff was also incorrectly only looking for variables being incorporated into SQL queries, not constants, function calls, etc. This is now fixed, and anything being incorporated into an SQL query will be flagged.
Fixes #508
=> Fix false positives and false negatives in PreparedSQL sniff

WordPress/Sniffs/PHP/YodaConditionsSniff.php, WordPress/Tests/PHP/YodaConditionsUnitTest.inc, WordPress/Tests/PHP/YodaConditionsUnitTest.php
(I added the unrelated function assignment check because there wasn’t
one in the tests yet and I wanted to make sure that we didn’t change
behavior on that.)
Fixes #497
=> Require yoda conditions for object properties

WordPress/Sniffs/Arrays/ArrayAssignmentRestrictionsSniff.php, WordPress/Sniffs/VIP/SlowDBQuerySniff.php, WordPress/Tests/VIP/SlowDBQueryUnitTest.inc, WordPress/Tests/VIP/SlowDBQueryUnitTest.php
Fixes #479.
Also removes a bunch of extra whitespace that got stripped out by Atom when I saved the file.
=> Add whitelisting comment for tax query

CONTRIBUTING.md
Explains how to check whether one of our sniffs is the one flagging a piece of code.
=> Note about some issues coming from upstream

WordPress-Core/ruleset.xml
This change adds the ConcatenationSpacingSniff, which checks that the concatenation operator is correctly surrounded by spaces. Tests are also included.
The relevant WordPress coding standard [reads](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage): "Always put spaces after commas, and on both sides of logical, comparison, string and assignment operators."
Both the sniff and test classes are simply extensions of the `Squiz.Strings.ConcatenationSpacing` code (which kindly already supported the functionality we require here).
Refs #535.
=> Add sniff and tests for concatenation operator spacing

WordPress-Core/ruleset.xml
=> Include PSR2.ControlStructures.ElseIfDeclaration in WordPress-Core

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.inc
These don't take a `$number` arg.
See #50 and #136.
=> Fix _n_noop() and _nx_noop()

WordPress-Docs/ruleset.xml
A bugfix upstream now causes `Doc comment short description must start with a capital letter` errors for `/* translators: ... */` comments.
Excluding the offending rule to continue to allow these type of comments.
Ref: https://github.com/squizlabs/PHP_CodeSniffer/pull/855
=> Allow `translators:` comments.

WordPress-Core/ruleset.xml, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.inc, WordPress/Tests/WP/I18nUnitTest.php
* Introduce `WordPress_Sniffs_WP_I18nSniff::$text_domain` property.
* Skip reporting issues for missing `$domain` if `WordPress_Sniffs_WP_I18nSniff::$text_domain` is not defined.
* Increase severity of domain issues from warning to error.
* Add `WordPress.WP.I18n` to WordPress-Core.
A project's ruleset can opt-in to doing `$domain` validation via adding this to there PHPCS `ruleset.xml`, here for the Customize Posts plugin:
```xml
...
<rule ref="WordPress.WP.I18n">
<properties>
<property name="text_domain" value="customize-posts" />
</properties>
</rule>
...
```
See #50.
=> Validate $domain arg in WordPress.WP.I18n

WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php
added check for 
get_intermediate_image_sizes()
serialize() / unserialize()
error_log(), var_dump(), trigger_error(), set_error_handler()
wp_redirect(),
wp_is_mobile()
urlencode()
As well as added get_previous_post_link() and get_next_post_link() to the adjacent_post check
=> Update with latest VIP checks

WordPress/Sniffs/VIP/PostsPerPageSniff.php
The current VIP docs for "no-limit queries" suggest that 100 can be an acceptable value for `posts_per_page`: https://vip.wordpress.com/documentation/code-review-what-we-look-for/#no-limit-queries.
=> Allow 'posts_per_page' of up to 100 on VIP

WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php
Functions include ereg, eregi, ereg_replace, and split
=> Added support for catching functions that will be deprecated once php7 updates

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.inc, WordPress/Tests/WP/I18nUnitTest.inc.fixed, WordPress/Tests/WP/I18nUnitTest.php
This PR is to add another test to the I18nSniff.php to ensure that multiple placeholders are orderable.
e.g. from the PHP: sprintf page:
`__( 'The %s contains %d monkeys' );` is a problem because the variables will need to be the other order in some languages, and the string should be:
`__( 'The %1$s contains %2$d monkeys' );`
The PR includes tests and a fixer.
One thing worth discussing is that the fixer could potentially get it wrong if:
1. It's a pluralised string
2. The order of the placeholders is different between the two strings
3. The placeholders are unordered.
The test file gives an example of the sort of string I'm talking about:
`_n( 'There is %d monkey in the %s', 'In the %s there are %d monkeys', $number, 'my-slug' );`
My assessment here is that this is a bug in the code, …
=> Add more i18n sniffs

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
Usage example:
```xml
<rule ref="WordPress.NamingConventions.ValidVariableName">
<properties>
<property name="customVariablesWhitelist" value="PHP_classes" type="array" />
</properties>
</rule>
```
Related #555
=> [VariableName Sniff] Add ability to add to the whitelisted variables list

WordPress/Sniffs/PHP/DiscouragedFunctionsSniff.php
This sniff has a few differnt type of functions. By creating a bit more of a detailed order I hope this can help us work out if it makes sense to move some of the functions to a different sniff.
Related to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/576
=> Sort the list in a better order

.travis.yml
Considering PHP 7 has been out for 7 months... might it be time for this ?
=> Run travis against PHP 7.0 as well.

WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.php
> Using ini_set() for alternating PHP settings, as well as other functions with ability to change configuration at runtime of your scripts, such as error_reporting(), is prohibited on the WordPress.com VIP platform. Allowed error reporting in production can lead to Full Path Disclosure.
See https://vip.wordpress.com/documentation/code-review-what-we-look-for/#settings-alteration
I've added the most obvious PHP functions which would relate to this. Careful review of the functions listed needed & appreciated.
Fixes #460
=> Add two sections to the VIP.RestrictedFunctions sniff.

.travis.yml, WordPress-Core/ruleset.xml, composer.json
Closes #588
Added to `extra` as the handbook mentions it as a best practices, not a **_must do_**.
Ref: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#remove-trailing-spaces
Code style PR has already run against this rule, so should cause no issue when merging in either order.
=> Add sniff for (no) closing PHP tag at end of file to `core` ruleset.

WordPress-Core/ruleset.xml
This will let PHPCS run a lint over the PHP files it checks as well.
Closes #522
=> Add PHP syntax check sniff to the `core` ruleset.

WordPress-Core/ruleset.xml
> Constants should be in all upper-case with underscores separating words:
> ```php
> define( 'DOING_AJAX', true );
> ```
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions
This was so far not covered by WPCS.
=> Add sniff to detect lowercase CONSTANT definitions.

.travis.yml, composer.json
PHPCS 2.6 contains a fix for the bug reported in issue https://github.com/squizlabs/PHP_CodeSniffer/issues/698.
PHPCS 2.6 also [contains a fix](https://github.com/squizlabs/PHP_CodeSniffer/pull/581) which will allow for checking that [`include/require` statements have DocBlocks](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#3-requires-and-includes) as required by the handbook.
Closes #566
=> Up the minimum required PHPCS version to 2.6.

WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed
As reported here:
> This rule does conflict with the `WordPress.WhiteSpace.ControlStructureSpacing.BlankLineAfterEnd` rule for the last method in a class if the function does not have a `} // end myfunction()` comment.
Still - the fact that it throws a message `Blank line found after control structure` when finding a blank line after the last method in a class might actually be a bug....
Added separate commits for unit test and fix to let travis demonstrate the bug and the fix.
=> Fix bug in control structures whitespace sniff triggered on last method of class

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/AbstractVariableRestrictionsSniff.php, WordPress/Sniffs/Arrays/ArrayAssignmentRestrictionsSniff.php, WordPress/Sniffs/Functions/FunctionRestrictionsSniff.php, WordPress/Sniffs/VIP/OrderByRandSniff.php, WordPress/Sniffs/VIP/PostsPerPageSniff.php, WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Sniffs/VIP/RestrictedVariablesSniff.php, WordPress/Sniffs/VIP/SlowDBQuerySniff.php, WordPress/Sniffs/Variables/VariableRestrictionsSniff.php, WordPress/Tests/Arrays/ArrayAssignmentRestrictionsUnitTest.php, WordPress/Tests/Variables/VariableRestrictionsUnitTest.php
Solves:
> Apart from the main WordPress_Sniff, there are three sniffs in WPCS which do not have native functionality, but look to be intended as abstract classes to be implemented in concrete child classes.
>
>    WordPress_Sniffs_Arrays_ArrayAssignmentRestrictionsSniff - 3 child classes
>    WordPress_Sniffs_Functions_FunctionRestrictionsSniff - 1 child class
>    WordPress_Sniffs_Variables_VariableRestrictionsSniff - 1 child class
The solution as implemented in this PR will prevent backward-compatibility breaks from custom sniffs implementing the "old" classes and/or references to these from `phpcs.xml` files.
The three 'interim' classes which allow for this, have all been marked with detailed `@deprecated`  documentation.
It also continues to unit test the two which had (and have) unit …
=> Turn the three abstract classes into proper abstracts.

WordPress-Core/ruleset.xml, WordPress/Sniffs/Functions/DontExtractSniff.php, WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Tests/Functions/DontExtractUnitTest.inc, WordPress/Tests/Functions/DontExtractUnitTest.php, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc
Currently only VIP checked for the usage of `extract()`, even though it is an explicit rule for core.
Ref: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#dont-extract
Solves #90 for real ;-)
=> Separate out the sniffing for `extract()`.

WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.php
`AbstractFunctionRestrictionsSniff` did not allow for case-insensitive comparison of function names.
> **Note**: Function names are case-insensitive, though it is usually good form to call functions as they appear in their declaration.
Ref: http://php.net/manual/en/functions.user-defined.php
Also:
* Better be safe than sorry, so `preg_quote()`-ing the function names passed to this class.
* Minor memory management improvement: no need to remember the matched function name.
The first commit adds a unit test proving the bug. The second commit fixes the bug.
=> Fix bug in function name comparison.

WordPress/Sniffs/PHP/DiscouragedFunctionsSniff.php, WordPress/Tests/PHP/DiscouragedFunctionsUnitTest.php
One of the unit tests for the `WordPress.PHP.DiscouragedFunctions` sniff was disabled as it was failing.
This related to the `get_attachment_innerHTML` function.
I've debugged the failing unit test and send in a [PR upstream](https://github.com/squizlabs/PHP_CodeSniffer/pull/1076) to fix the underlying issue in the `Generic.PHP.ForbiddenFunctions` sniff.
The above in effect meant that WPCS was *not* testing usage of the `get_attachment_innerHTML()` function as the sniff was failing.
The work-around in this PR will:
1. fix the bug and enable sniffing for `get_attachment_innerHTML()`.
2. not clash with PHPCS if the bug fix send in upstream will be merged.
3. can be removed once the minimum PHPCS version required by WPCS has gone beyond the PHPCS version which will contain the bugfix.
=> Bug work-around for the DiscouragedFunctions sniff.

CONTRIBUTING.md
I don't have `phpcs` installed globally, but PHPCS now has it as a requirement, so `vendor/bin/phpcs` can be used.
=> Update WPCS testing procedure

WordPress-Core/ruleset.xml, WordPress/Sniffs/DB/RestrictedFunctionsSniff.php, WordPress/Tests/DB/RestrictedFunctionsUnitTest.inc, WordPress/Tests/DB/RestrictedFunctionsUnitTest.php
From the handbook:
> Avoid touching the database directly. If there is a defined function that can get the data you need, use it. Database abstraction (using functions instead of queries) helps keep your code forward-compatible and, in cases where results are cached in memory, it can be many times faster.
Ref: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#database-queries
This section was, AFAICS, so far not covered.
This PR covers checking for any calls made to PHP functions which can approach mysql type databases.
If any such function is found, an `error` will be thrown.
In a future PR, a similar check should be created for calls to native PHP DB Classes, such as PDO.
To that end, I've created a new sniff sub-folder called `DB` to hold both this as well …
=> Disallow direct database calls.

WordPress-Core/ruleset.xml, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.1.inc, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.2.inc, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidHookNameUnitTest.php
Covers the `action` part of this rule in the handbook:
> Use lowercase letters in variable, **action**, and function names (never camelCase). Separate words via underscores.
Ref: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions
Review appreciated.
Also: I've made non-lowercase hook names an `error` and non-underscore punctuation a `warning`. Should that also be an `error` ?
=> Add new sniff to check whether a hook name is valid.

WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php
`PHP_CodeSniffer_Tokens::$emptyTokens` contains `T_WHITESPACE` and all comment tokens making for a more stable check.
=> Use PHPCS build in static token arrays.

WordPress-Core/ruleset.xml, WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniffs/DB/RestrictedClassesSniff.php, WordPress/Tests/DB/RestrictedClassesUnitTest.1.inc, WordPress/Tests/DB/RestrictedClassesUnitTest.2.inc, WordPress/Tests/DB/RestrictedClassesUnitTest.3.inc, WordPress/Tests/DB/RestrictedClassesUnitTest.php
* Added `AbstractClassRestrictionsSniff` class which can sniff for the use of (namespaced) classes. The abstract class does currently not support `use` statement aliased namespaces.
* Refactored the `AbstractFunctionRestrictionsSniff` somewhat to make parts more reusable and extended the `AbstractClassRestrictionsSniff` from this class.
* This refactoring includes a small efficiency improvement where the function regular expressions are no longer rebuild for every token, but only build once.
* Added `DB/RestrictedClassesSniff` to actually sniff for the Restricted DB Classes.
* Added extensive unit tests which test both the `DB/RestrictedClassesSniff` as well as the complete functionality of the Abstract class.
If at some point in the future the `AbstractFunctionRestrictionsSniff` would …
=> Add sniff for Restricted Database Classes.

WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Tests/PHP/StrictInArrayUnitTest.inc, WordPress/Tests/PHP/StrictInArrayUnitTest.php
Will only check for the `$strict` parameter for `array_keys()` if the second parameter has been set.
Fixes #503.
The file/sniff name is now a bit dated as the sniff checks for more than just `in_array()`, but changing the file/sniff/classname would break backward compatibility.
What do you think ?
=> Add strict type checking for array_search() and array_keys().

WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniffs/DB/RestrictedFunctionsSniff.php, WordPress/Tests/DB/RestrictedFunctionsUnitTest.inc
This whitelist options is only useful when used in combination with blocking a function group using a wildcard in the function name.
However, it does make it more forward compatible. This allows to still block all the functions for a complete (PHP) extension , even for new functions being added to the extension, while whitelisting - for instance - a WP native function which was named a bit unfortunately.
This was brought to my attention when @octalmage opened issue https://github.com/wimg/PHPCompatibility/issues/123. The same problem he described there would occur with the new `WP.DB.RestrictedFunctions` sniff. This PR fixes that.
=> Add ability to whitelist functions to the `AbstractFunctionRestrictions` class

WordPress-Core/ruleset.xml, WordPress/Sniffs/PHP/DiscouragedFunctionsSniff.php, WordPress/Sniffs/PHP/POSIXFunctionsSniff.php, WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Tests/PHP/DiscouragedFunctionsUnitTest.inc, WordPress/Tests/PHP/POSIXFunctionsUnitTest.inc, WordPress/Tests/PHP/POSIXFunctionsUnitTest.php
From the handbook:
> Perl compatible regular expressions (PCRE, preg_ functions) should be used in preference to their POSIX counterparts. Never use the /e switch, use preg_replace_callback instead.
>
> It’s most convenient to use single-quoted strings for regular expressions since, contrary to double-quoted strings, they have only two metasequences: \' and \\.
Ref: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#regular-expressions
This can be split into three distinct rules:
1. Don't use `POSIX` functions
2. Don't use the `/e` modifier
3. Prefer single quoted stings.
Rule 1 was up to now not covered in core. Parts of it were covered in `extra` and in `vip`, but the implementations were inconsistent and both were incomplete.
Rule 2 was not covered at all. …
=> Better cover the regex related rules.

.travis.yml
Previously HHVM was version 3.6.6, this was the last release ~12 months ago that Facebook released for Ubuntu Precise. The HHVM job now runs HHVM 3.14.2 on Ubuntu Trusty
https://travis-ci.org/WordPress-Coding-Standards/WordPress-Coding-Standards/jobs/144369210
=> Travis CI: Upgrade the HHVM job to use Ubuntu Trusty, and a more recent version of HHVM.

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
This PR does not add or remove any new rules, it just re-orders the core ruleset to follow the handbook and documents the rules as they are in the handbook - both covered and not covered.
Closes #602
For any core rules which are not yet covered, but *could* possibly *be* covered, a new issue has been opened if one didn't exist already and the link to the issue is included in the ruleset.
Rules included, but not (explicitly) covered in the handbook are listed in their own section at the bottom of the ruleset.
I've made three changes which should be noted:
* Removed the `WordPress.WP.I18n` sniff from the `extra` ruleset as it is included in the `core` ruleset and `core` is included in `extra`.
* Moved the `WordPress.WP.PreparedSQL` sniff from `extra` to `core` as the checks included in that …
=> Order the `core` ruleset according to the handbook.

WordPress/Sniff.php, WordPress/Sniffs/Arrays/ArrayDeclarationSniff.php, WordPress/Sniffs/CSRF/NonceVerificationSniff.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Sniffs/PHP/DiscouragedFunctionsSniff.php, WordPress/Sniffs/PHP/StrictComparisonsSniff.php, WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Sniffs/VIP/FileSystemWritesDisallowSniff.php, WordPress/Sniffs/VIP/SessionFunctionsUsageSniff.php, WordPress/Sniffs/VIP/SessionVariableUsageSniff.php, WordPress/Sniffs/VIP/SuperGlobalInputUsageSniff.php, WordPress/Sniffs/VIP/TimezoneChangeSniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php, WordPress/Sniffs/WP/PreparedSQLSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php
Ensured that any sniff with a dependency on an external sniff has a consistent `class_exists()` check and throws an appropriate error message.
Verified that classes which extend a parent actually *use* that parent and if not, removed the `extend`.
If they use the parent, leverage the properties available in the parent and remove duplicate function calls.
=> Verify extended classes.

README.md
Add some additional relevant information about running the PHPCompatibility sniffs.
=> Update readme section on PHPCompatibility

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
:exclamation: **This PR should be merged before 0.10.0 is released as it contains a feature compleness fix for a new feature which was introduced in one of the 0.10.0 commits.**
Depending on how the tokenized file is build up, any of the methods in the sniff might be called first, so the whitelist should be also be merged (if not done so already) in the other method which uses the whitelist.
=> Improve VariableName whitelisting for the `ValidVariableName` sniff.

WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.php
:exclamation: **This PR should be merged before 0.10.0 is released as it contains a bug fix for a bug which was introduced in one of the 0.10.0 commits.**
The `urlencode` check was checking for `rawurlencode()` instead of `urlencode()` while at the same time advising to use `rawurlencode()`.
The grammar of the error message was incorrect as well.
Both are now fixed.
In the [same commit](e7707b2338e7823a2d14cfbdca8bdc88488d6081) as this was introduced, a number of other restricted functions were added, but none of them were accompanied by unit tests.
This is now fixed as well.
=> Fix bug in VIP restricted functions + unit tests

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.inc, WordPress/Tests/WP/I18nUnitTest.inc.fixed, WordPress/Tests/WP/I18nUnitTest.php
When developing feature plugins, there is often a need to re-use strings in core. In such cases, the sniff should allow an explicit `default` text domain to allow for core strings to be re-used without being flagged.
For example: https://github.com/xwp/wp-customize-object-selector/blob/c7957ea0e7549a7d3fdc8ef0f811e3e05b4f46e4/php/class-plugin.php#L90
=> I18n: Always allow text domain of 'default' to facilitate feature plugins

WordPress-Core/ruleset.xml, WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.php
The `WordPress_Sniffs_WhiteSpace_CastStructureSpacingSniff` is based upon the `Squiz_Sniffs_WhiteSpace_CastSpacingSniff`.
This PR contains the following changes:
* The class now extends the class it is based upon.
This also means that the class now only contains the WP specific checks and defers to the parent for anything else.
* The check which is covered by the parent was already fixable there. This benefit is now carried over to this sniff.
* Made the two WP specific checks fixable as well and added a `.fixed` file to unit test this.
* Removed the class property which was at the bottom of the class which looks like it was left over from an earlier attempt to use the parent class in combination with making the check covered in the parent a `warning` instead of an `error`. The property …
=> Sync the WhiteSpace_CastStructureSpacing sniff with its base class.

WordPress-Core/ruleset.xml, WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.php
=> Change error level for `WordPress.WhiteSpace.CastStructureSpacing` checks to `error`.

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc
Though obscure, this global variable is used by WordPress core in `wpdb`, as a remnant of when it was forked from EzSQL. See https://core.trac.wordpress.org/browser/branches/4.6/src/wp-includes/wp-db.php#L1350.
See #691 for previous discussion.
=> Whitelist $EZSQL_ERROR in variable naming conventions sniff

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
Only properties can be whitelisted using this, so the name "variables" is confusing. See #691.
The term "member var" is used elsewhere within this sniff, so possibly that should be used here for consistency, rather than "property".
I've kept the old whitelist around for back-compat, but I've marked it as deprecated. The old internal flag `$addedCustomVariables` I removed completely rather than deprecating, though I suppose in theory it is possible that someone has a custom sniff extending from this one that might be referencing it.
=> Rename "variables" whitelist to "properties"

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.inc, WordPress/Tests/WP/I18nUnitTest.inc.fixed, WordPress/Tests/WP/I18nUnitTest.php
I've investigated #698 and discovered a couple of additional issues because of it.
This PR fixed both the original issue as well as the additionally discovered ones.
Fixes #698 
If several of the same kind of unordered placeholders were found - `%s` -, the `str_replace()` would replace them all with the replacement value for the first, i.e. `%1$s`, resulting in something like `'my %1$s and my %1$s'`.
`preg_replace()` allows for limiting the amount of replacements per match so offers the ability to replace each placeholder with their corresponding replacement.
This does however create some other complexities as a `$` in a regex replacement value can be interpreted as a match replacement, so will need escaping to prevent potential replacement with a numbered match.
Example:
Placeholder …
=> Fix I18n placeholder numbering and add error for mixed placeholders

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
WordPress sets the `$PHP_SELF` global in [`wp_fix_server_vars()`](https://developer.wordpress.org/reference/functions/wp_fix_server_vars/) in `load.php`.
=> Add $PHP_SELF to mixed case vars

README.md
Modern Composer versions will magically pick up latest stable release
=> Removed dev-master from installation instructions

WordPress/Sniffs/PHP/YodaConditionsSniff.php
Avoid confusion by thinking the rest of the message has been truncated.
Fixes #724.
=> Add period to Yoda condition error message

.travis.yml
WordPress now expects PHP 7.1 to pass.
Note: PHP "nightly" is now 7.2-alpha
Aside: Rather than a branch in my own fork this is a WPCS branch,made possible from the recent changes in my access privs here at WPCS, is this ok?
=> Add PHP 7.1 to Travis CI job matrix

WordPress/AbstractFunctionRestrictionsSniff.php
This feature was added in #626, but not properly documented so far.
=> Document the functions whitelist option in AbstractFunctionRestrictionsSniff

README.md
This adds a `Requirements` section to the Readme.
Fixes the remark in this comment: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/733#issuecomment-267773214
=> Make the minimum PHPCS requirements more explicit.

WordPress-Core/ruleset.xml, WordPress-Docs/ruleset.xml, WordPress-Extra/ruleset.xml, WordPress-VIP/ruleset.xml
This PR addresses [this comment](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/717#issuecomment-269217452) from issue #717:
> > If at all, I think links to the PRs/issues which introduced those sniffs into the Extra ruleset should be sufficient as those will give the reasoning of why those sniffs were included.
>
> If someone wants to open an issue/PR for that, feel free.
* Added a section with the "Interpolation for Naming Dynamic Hooks" rules (currently not yet covered) & documentation link.
* Corrected one existing link
* Added links to the handbook pages about internationalization for the `WP.I18n` sniff.
* Added a generic link to the documentation handbook at the top. Could use more specificity (doc section vs rule), but this should do for now.
* …
=> Improve ruleset documentation

README.md
* Add a table of contents to the readme which has become quite long.
Auto-generated with: http://ecotrust-canada.github.io/markdown-toc/ and then manually tweaked a little
* Add extra header and indent subheader for rulesets section
* Move the rulesets section up, as it was - by now - quite far down what with all the information on the different integrations
=> Add a TOC to the readme and move rulesets info up

.travis.yml
We should increase the PHPCS version in travis as composer installs this version on new installs.
The reason for this is that we do not have a `composer.lock` in the project and the version in `composer.json` is set for `^2.7` which will install any minor versions.
=> Increase PHPCS version to 2.7.1

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc, WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
As I was looking at https://github.com/WPTRT/WordPress-Coding-Standards/pull/79 I realized I missed two functions.
This is also part of the Theme Check plugin and the VIP Scanner https://vip.wordpress.com/documentation/vip/code-review-what-we-look-for/#filesystem-writes
https://github.com/WordPress/theme-check/blob/master/checks/malware.php#L9
https://github.com/Automattic/vip-scanner/blob/master/vip-scanner/checks/VIPRestrictedCommandsCheck.php#L143
Ref: #633
=> Add file_get_contents() & file_get_contents()

WordPress/Sniffs/PHP/DiscouragedFunctionsSniff.php
The `WordPress.PHP.DiscouragedFunctions` sniff is deprecated and not used anymore, but as PHPCS still autoloads it, it does need the required methods to prevent errors being thrown.
Fixes #760
=> Fix PHPCS throwing errors for deprecated sniff.

WordPress/Sniffs/WP/I18nSniff.php
This solves the following error:
`An error occurred during processing; checking has been aborted. The error message was: "count(): Parameter must be an array or an object that implements Countable" at /home/travis/build/WordPress-Coding-Standards/WordPress-Coding-Standards/WordPress/Sniffs/WP/I18nSniff.php:233`
[`array_shift()`](http://php.net/manual/en/function.array-shift.php) returns null if the array is empty or not an array which may have happened when less arguments where passed to the i18n function than expected.
In that case `$tokens` will be null and start throwing the `countable` error for PHP nightly.
=> Fix unit tests failing on PHP nightly for the `WordPress.WP.I18n` sniff.

WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Tests/PHP/StrictInArrayUnitTest.inc, WordPress/Tests/PHP/StrictInArrayUnitTest.php
This should be left up to the `Generic.PHP.Syntax` sniff.
See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/770#discussion_r94809371
=> Don't error for syntax errors in StrictInArray sniff

WordPress-Extra/ruleset.xml, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.inc, WordPress/Tests/WP/I18nUnitTest.inc.fixed, WordPress/Tests/WP/I18nUnitTest.php
Implemented based on the following specs:
* Only one error should be thrown per gettext call.
* A translators comment is only required when (one of) the text string(s) contains placeholders.
* It's ok for there to be a translators comment if the text string(s) does not contain placeholders.
* The translators comment must be directly above the gettext call.
* If the comment is not on the *line* directly above the gettext call, there should only be whitespace lines between the comment and the line containing the gettext call.
* The translators comment must be in `//` or `/* */` format, docblocks are not allowed.
* A translators comment must start with `translators:`
* The check defaults to throwing a warning. If the `extra` ruleset is enabled, the error level will change to `error`.
Fixes …
=> Add checking for translators comments to the I18n sniff.

WordPress/Sniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php, WordPress/Tests/Variables/GlobalVariablesUnitTest.inc, WordPress/Tests/Variables/GlobalVariablesUnitTest.php
The `GlobalVariablesSniff` contained a number of bugs which will be fixed by this PR.
* Assignments to global variables using other assignment operators than the `=` (`T_EQUAL`) operator were not detected, so `$post .= 'something';` would skate by.
* If a `T_GLOBAL`, i.e. `global ...;`, was detected, the whole file would be checked for the variables which were made global, not just the code **_after_** the `global` statement.
* If a `T_GLOBAL` was detected, the whole file would be checked for the variables which were made global, **_including_** code contained within a function/closure/class scope where there is no access to the global variable (without it being set explicitly within the function as well).
* If a `T_GLOBAL` was detected within a function call or closure, the whole file …
=> Fix a number of bugs in the global var override detection

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
To be merged **_after_** 0.10.0 has been released so we can test & fine-tune before it's released.
Fixes #607.
=> Implement the extra rules as suggested in #607.

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc
This PR implements the third option mentioned in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/776#issuecomment-271109986
> ... only recognize the optional padding character if there is also a width specifier in the placeholder. This could potentially mean that some valid placeholders would no longer be recognized as such.
Fixes #776
* Includes additional unit test.
* Includes detailed documentation of the regular expressions as they were getting quite hard to manage without.
=> I18n Sniff: Only recognize the space as a padding character when accompanied by a width specifier.

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
These would be thrown when live coding/running the sniffs on code with parse errors.
Quick fix for https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/248#issuecomment-270635692
/cc @grappler
=> Fix some undefined index notices in the `WordPress.XSS.EscapeOutput` sniff.

WordPress/AbstractFunctionRestrictionsSniff.php
This abstract sniff is extended by quite a few of our sniffs, and so it has a major impact on the performance of the ruleset as a whole.
Here we make two improvements:
1. We use `isset()` instead of `in_array()`.
2. We don't call `findPrevious()` a second time unless we actually need the information. We only need to check if the namespace is top-level if the function is prefixed with `\\`, the namespace separator.
This seems to improve the performance of these sniffs by as much as 25%.
Profiled with Blackfire (free edition, so the links will only be retained for 1 day), by running over a sizable plugin (using a custom ruleset that includes Core, Extra, Docs, and VIP, but with some exclusions):
[Before](https://blackfire.io/profiles/dc4d99a8-59a5-4ccf-9b40-11aae9d30ef6/graph?settings%5Bdime …
=> Improve performance of function restriction sniffs

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php
* Allow for usage of whitelisted mixed case WP vars in double quoted strings and heredocs.
=> Fix bug in WordPress_Sniffs_NamingConventions_ValidVariableNameSniff

WordPress/Tests/DB/RestrictedFunctionsUnitTest.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed
Reviewed test case files for (unintended) erroneous comment style. As per comment of @JDGrimes in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/782#discussion_r96122877
=> Fix comment style in testcase files.

WordPress-Extra/ruleset.xml
the other is in [line 49](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/compare/develop...grappler:fix/duplicate-rule?expand=1#diff-9dbd3b63f5d2589b5eb1701e92893803R49)
=> Remove duplicate rule

WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php
The `WordPress.VIP.DirectDatabaseQuery` sniff allows for adding custom database query caching functions to the predefined lists of known WP core database query caching functions.
The known WP core database query caching functions are contained in static variables in the `WordPress_Sniff` base class and are currently only used by the `WordPress.VIP.DirectDatabaseQuery` sniff.
Up to now, if custom functions were passed to this sniff, it would merge them with the lists of WP core functions and then **overwrite** the values of the static properties in the `WordPress_Sniff` base class.
While no other sniff is using these properties, this is not much of a problem (yet), but as soon as another sniff would start using these properties, this behaviour would have the unintended side-effect of …
=> Fix bug in WordPress_Sniffs_VIP_DirectDatabaseQuerySniff

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/AbstractVariableRestrictionsSniff.php
#779 applied a performance fix to the function restrictions abstract.
This PR builds onto that for all the abstract classes:
* Bow out early if all the groups have been excluded.
* `array_flip()` the excluded groups and use `isset()` instead of `in_array()`, i.e. applying the fix from #779 to the other abstracts
I've chosen to add a new `$excluded_groups` property to the abstracts which holds the exploded & flipped array of excluded groups. This allows for that array to be accessed by child classes and other methods within the class without having to reprocess the original property. This is done with an eye on a refactor of the function restrictions sniff in anticipation of introducing a function parameter abstract sniff.
While for the other abstracts, the property is - at this moment - …
=> Improve efficiency of the abstract sniffs.

WordPress/Sniff.php
@JDGrimes Found another one ;-)
This should be left up to the Generic.PHP.Syntax sniff.
See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/770#discussion_r94809371
=> Don't throw error for syntax errors

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
The `WordPress.WhiteSpace.ControlStructureSpacing` sniff is based upon the upstream `Squiz.WhiteSpace.ControlStructureSpacing` sniff, but has since diverged a lot to be more specifically relevant to WordPress.
Even so, I've gone through all commits to the upstream sniff to see if there were any bugfixes which we should implement in the WPCS version of the sniff.
As expected, there were a few and while implementing these, I came across a few other optimizations which could be made and have implemented these as well.
I've kept each change in a separate commit for easier review and easier reference to the related upstream issues.
Commit summary:
* Enhancement: Handle try/catch statements as well.
* Efficiency: Bail early if no trailing content found (otherwise we'll get lots of undefined …
=> Sync in upstream fixes to controlstructure whitespace sniff

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php
Allow for incorrectly set custom properties.
The `customPropertiesWhitelist` and (deprecated) `customVariablesWhitelist` properties should be provided with `type="array"`, but it's an easy mistake to miss that and provide a comma-delimited list instead as the value of the property would be the same.
Along the same lines, setting the property inline for unit testing the property handling will fail as there is no way to pass the `type="array"` part via an inline setting change.
Without the fix in this commit, this would lead to errors that `array_merge()` expects the parameters to be in array format.
* For the `$customPropertiesWhitelist`, a warning will be thrown that the format of the custom property should be corrected.
* If the received value is a string, the format will be corrected. …
=>  	Improve custom property handling in WordPress_Sniffs_NamingConventions_ValidVariableNameSniff

WordPress/Sniffs/WP/I18nSniff.php
Stared at this one a number of times and never understood why this wasn't a straight method call, so changing.
=> I18nSniff: Remove unnecessary call_user_func()

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/VIP/AdminBarRemovalSniff.php, WordPress/Sniffs/VIP/CronIntervalSniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php
Add `strip_quotes()` utility method to consistently and correctly strip quotes from `T_CONSTANT_ENCAPSED_STRING` / `T_DOUBLE_QUOTED_STRING` strings.
Until now, most often `trim( $var, '\'"' )` was used which might incorrectly strip too much.
Example: `"'my' string"` would become `my' string` (note the extra `'` which was removed) instead of `'my' string`.
This utility function will strip the quotes off correctly.
The second commit implements use of the `strip_quotes()` method where appropriate in the current codebase.
=> Utility: Add `strip_quotes()` utility function & implement use

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
While working on #789, I noticed that the control structure whitespace check did check for *no* space after the open parenthesis / before the closing parenthesis, but did **not** check whether this was exactly one space.
This PR fixes that.
Includes fixer.
Includes fixes to the WPCS codebase for issue detected by this check.
Notes:
* For multi-line conditions, the superfluous space check will not be executed. See the last unit test as an example.
* For the space after the open parenthesis, it disregards function declarations as those are already being checked for superfluous spacing after the open parenthesis by the `Squiz.Functions.FunctionDeclarationArgumentSpacing` sniff which is included in the WP Core ruleset.
* For the space before the closing parenthesis, it …
=> Enhancement: check controlstructure for superfluous whitespace

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.php
For people who work on a lot of WP projects and want to use a generic custom ruleset, setting the `text_domain` property in the ruleset would mean they would either need to have - yet another - custom ruleset in each project or they would need to manually edit the ruleset each time they would run PHPCS.
Think: theme/plugin reviewers.
With that in mind, adding the ability to set the `$text_domain` property from the command-line as well, seemed a logical next step.
Inspired by a remark made by @grappler.
To use this from the command-line:
`phpcs -p . --standard=WordPress --runtime-set text_domain my-slug,default`
Notes:
* The command line property is to be provided as a comma-delimited list without spaces in it.
* The value passed via the command-line will **overrule** any value already set …
=> I18n: Allow setting the allowed text-domains via the command-line.

WordPress-Extra/ruleset.xml
This sniff will forbid the use of size functions in loops as it's highly inefficient.
So code like the below would be flagged:
```php
for( $i = 0; $i < count( $something ); $i++ ) {}
```
And this code would be fine:
```php
$max = count( $something );
for( $i = 0; $i < $max; $i++ ) {}
```
=> Extra: Add Squiz.PHP.DisallowSizeFunctionsInLoops sniff

WordPress-Extra/ruleset.xml
Allow for string concat if the string is broken up in several lines - for instance to avoid overly long lines.
Just came across this property and figured it was worth having a discussion on whether or not to include it.
=> Extra: Make the unnecessary string concat check a little bit more lenient

WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
This PR contains three distinct commits. The first is a refactor of the abstract function restrictions class, the second and third are changes to child classes taking advantage of the refactor.
-----
Refactor the WordPress_AbstractFunctionRestrictionsSniff
This refactor is intended to make the WordPress_AbstractFunctionRestrictionsSniff more extendable and reusable.
The refactor does not contain any functional changes.
* Extend the main `WordPress_Sniff` to be able to use the `init()` function which will save us having to pass around the `$phpcsFile` and `$tokens` variables and make the utility functions contained in that class available (and allow for moving some utility functions contained in the `WordPress_AbstractClassRestrictionsSniff` to the main `WordPress_Sniff ` class in a future …
=> Refactor the WordPress_AbstractFunctionRestrictionsSniff

WordPress-Core/ruleset.xml
=> Core: also check closure braces for being on the same line as the function opener

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
* Use `isset()` instead of `in_array()` for efficiency. Changed the array formats to allow for this.
=> Efficiency / WordPress_Sniffs_NamingConventions_ValidVariableNameSniff

WordPress/Sniffs/VIP/TimezoneChangeSniff.php
There were three sniffs which still extended the upstream `Generic_Sniffs_PHP_ForbiddenFunctionsSniff` class.
Extending the `WordPress_AbstractFunctionRestrictionsSniff` instead has the following advantages:
* Functions can be provided in groups and the `exclude` property to selectively exclude groups becomes available.
* The sniffs no longer have a `public $forbiddenFunctions` property which could be overruled via the ruleset.
* Once callback checks have been added to the `WordPress_AbstractFunctionRestrictionsSniff`, the sniffs will benefit from the additional detection. (#611)
* If needed at some point, the functions within the `WordPress_Sniff` class are available for use.
This PR addresses the above for the `VIP.TimezoneChange` sniff.
This PR contains no functional changes. The sniff …
=> TimezoneChange: Use the WPCS abstract function call sniff.

WordPress/Sniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php, WordPress/Tests/CSRF/NonceVerificationUnitTest.inc, WordPress/Tests/CSRF/NonceVerificationUnitTest.php, WordPress/Tests/VIP/DirectDatabaseQueryUnitTest.inc, WordPress/Tests/VIP/DirectDatabaseQueryUnitTest.php, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.php, WordPress/Tests/Variables/GlobalVariablesUnitTest.inc, WordPress/Tests/Variables/GlobalVariablesUnitTest.php, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
Reviewed all uses of the `T_FUNCTION` and `T_CLASS` tokens and, where appropriate, added support for anonymous functions `T_CLOSURE` and anonymous classes `T_ANON_CLASS`.
=> Improve sniffs to deal with anonymous functions and classes

WordPress/Sniff.php
Reviewed usage of the `preg_quote()` function which should always be passed the delimiter if not using `/` to make sure the correct characters are being escaped.
=> Accuracy: always pass the delimiter to `preg_quote()` if not using `/`.

WordPress/AbstractFunctionParameterSniff.php, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Sniffs/VIP/PluginMenuSlugSniff.php, WordPress/Tests/VIP/PluginMenuSlugUnitTest.inc, WordPress/Tests/VIP/PluginMenuSlugUnitTest.php
Now #795 has been merged, it was possible to create an abstract function parameter class which builds upon the logic for determining function calls already contained in `WordPress_AbstractFunctionRestrictionsSniff`.
This PR introduces the abstract and a number of related utility functions.
I initially introduced these utility functions in the [PHPCompatibility](https://github.com/wimg/PHPCompatibility) standard were they are also [individually unit tested](https://github.com/wimg/PHPCompatibility/tree/master/Tests/BaseClass).
They have been in use there for a number of months and proven useful & accurate.
The functions are:
* `does_function_call_have_parameters( $stackPtr )` - returns bool
* `get_function_call_parameter_count( $stackPtr )` - returns int
* `get_function_call_parameters( …
=> Add function call parameter related utility functions and abstract class

WordPress/Sniffs/WP/I18nSniff.php
Add missing `@since` tags for PR #742 which introduced one new property and two new methods.
=> I18n: Add some missing @since tags

WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractFunctionParameterSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php
PHPCS allows for the `process()` method to optionally return a stack pointer. If so, it will not call the sniff for the current file again until the returned stack pointer has been reached.
I did not take that into account in the refactor of the AbstractFunctionRestrictionsSniff and the creation of the AbstractFunctionParameterSniff which basically blocks any child classes from using the ability to return a stack pointer.
=> Abstracts: Fix potential bug - methods should allow for optionally returning a stack pointer

WordPress/Sniff.php
The `$sanitizingFunctions` and `$unslashingSanitizingFunctions` are two distinct lists and custom sanitizing / unslashsanitizing functions are only merged with one or the other.
The `$sanitizingFunctions` list currently contained an (incomplete) overlap with the `$unslashingSanitizingFunctions` which would become even more incomplete if/when custom functions would be merged in.
The `$unslashingSanitizingFunctions` was only considered to determine whether or not unslashing was needed.
Functions contained in that list which were not *also* contained in the `$sanitizingFunctions` list were not taken into account for the final result of the `is_sanitized()` function.
* Removed overlap between the functions listed in the two properties
* `is_sanitized()` now also takes …
=> Bug fix: `is_sanitized()` did not consistently take all sanitization functions into account for final result

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/AbstractVariableRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/I18nSniff.php
Introduce new `string_to_errorcode()` utility method and implement where applicable.
This PR addresses two distinct but closely related issues.
This PR introduces a new `string_to_errorcode()` method to be used for dynamic errorcodes using arbitrary strings which will convert any non-valid characters to underscores.
This PR also implements the usage of this function for all `addError()`/`addWarning` calls which warrant it.
The sniffs which are based on the abstract classes all provide the public `exclude` property to selectively exclude a certain group from the checks the sniff executes.
The sniffcode, however, was also based on the group.
So while there were two different ways to disable the messages about a certain group (`<property name="exclude" ...>`, `<exclude name=... sniffcode>`), …
=> Introduce new `string_to_errorcode()` utility method and implement where applicable.

WordPress-Docs/ruleset.xml, WordPress-VIP/ruleset.xml
The `Squiz.PHP.CommentedOutCode` sniff triggers on `// End if()` long conditional closing comments which would lead to conflicting messages.
By upping the threshold for the `Squiz.PHP.CommentedOutCode` sniff, this conflict is removed.
=> Remove conflict between Long conditional closing comments and commented out code rules

WordPress/Sniff.php, WordPress/Sniffs/VIP/AdminBarRemovalSniff.php, WordPress/Tests/VIP/AdminBarRemovalUnitTest.css, WordPress/Tests/VIP/AdminBarRemovalUnitTest.inc, WordPress/Tests/VIP/AdminBarRemovalUnitTest.php
This sniff has been completely overhauled with the additional wish-list of the Theme Review Team in mind.
Originally the sniff only checked for `show_admin_bar( ... )` and `add_filter( 'show_admin_bar', ... )`.
* It didn't contain a further check for the actual value passed to these functions.
* It didn't check for usage of CSS to hide the admin bar
This PR fixes that.
Includes extensive additional unit tests.
Notes:
* The sniff now checks both PHP as well as CSS files.
* The class now extends the `WordPress_AbstractFunctionParameterSniff` for the PHP function parameter checks.
* It overloads the `register()` method to register additional tokens.
* It overloads the `process()` method of that class to only use the functions in the abstract class when passed a `T_STRING` token. For the …
=> AdminBarRemoval: More thorough checking for admin bar removal and hiding

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/AbstractVariableRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/CSRF/NonceVerificationSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/I18nSniff.php
This PR addresses duplicate code related to toggling between throwing errors and warnings.
Related to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/795#discussion_r96204333
It adds two helper functions `addMessage()` and `addFixableMessage()` (and one private grunt function).
Both functions take the same arguments as the PHPCS native `addError()`/`addWarning()` methods with one difference: an extra boolean `$is_error` parameter between the `$stackPtr` and the `$errorcode`.
The PR, of course, also implements the use of the helper functions removing duplicate code.
To use these functions, sniffs have to extend the `WordPress_Sniff`. Three of the sniffs involved did not yet do so. They now do & I've leveraged the fact that they do by letting them defer to …
=> New utility function: addMessage()

WordPress-Core/ruleset.xml
* The `exact` property defaults to `false`, but if the WP ruleset is combined with other ruleset, we want to make sure it stays that way.
* The scope indent is often justifiably different for inline HTML, heredocs and nowdocs. The added `ignoreIndentationTokens` property should make the sniff ignore indent issues when those tokens are encountered.
=> Ruleset tweaks: Make the scope indent sniff slightly less annoying

WordPress-Core/ruleset.xml, WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.inc, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.inc.fixed, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.php
> For associative arrays, values should start on a new line.
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation
Detecting this was easy, creating the fixer.... not so much...
I got it working, but would not be surprised if I rewrite the fixer in a few months or so. I've tried to anticipate the most common situations, but the fixer will fail on arrays with very inconsistent spacing.
Think:
```php
array(
'key' => array( 'key1' => 'value', 'key2' => array(
'another_value'
) ),
)
```
Anticipating a comment on line 43 of the `.fixed` file: the fixer will add a trailing comma to arrays which it is triggered on (if needed), but will *not* do so on arrays on which it is not triggered - that is covered by another sniff.
Fixes #638
* Allows for both long as …
=> Add a check that associative arrays are multi-line - includes fixer

CONTRIBUTING.md
This links through to https://asciinema.org/a/98078 which is a replay of the unit tests being run.
If we ended up with a docs/ site on GitHub, we could embed the asciinema player :-)
=> Add screenshot image of unit testing in terminal

WordPress/Sniff.php, WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php
Saves on the overhead of calling `count( $tokens )` numerous times.
=> Efficiency: Defer to the PHPCS native `$numTokens` property for the token count

WordPress/Sniffs/VIP/CronIntervalSniff.php, WordPress/Tests/VIP/CronIntervalUnitTest.inc, WordPress/Tests/VIP/CronIntervalUnitTest.php
* Deal correctly with WP time constants leading to more accurate error/warning messages.
* Takes advantage of the new function parameter utility functions for greater accuracy.
* Allow for short array syntax in callback for `add_filter`.
* Make the finding of the referenced function declaration more accurate and efficient by only looking at `T_FUNCTION` tokens, skipping past the rest of the function and breaking out if the right function is found. (Still could get confused over two classes in the same file with a same name method, but better than it was before)
* Minor other efficiency tweaks
=> Improve cron schedule sniff

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
Probably not often-used, but the global $is_IIS it is giving me a warning in an otherwise pristine coding-standards-adhering file :-(
=> Whitelist invalid snake_case WordPress globals

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
As expected, as soon as its merged, I see a typo in a property name ;-)
=> ValidVariableNameSniff: fix typo

.travis.yml, README.md, composer.json
PHPCS 2.8.1 has just been released and contains a fix for security vulnerability. I'd like to suggest we up the minimum version as the `Generic.PHP.Syntax` sniff is being used in the `WordPress-Extra`  ruleset.
From the release notes:
> This release contains a fix for a security advisory related to the improper handling of shell commands
>     * Uses of shell_exec() and exec() were not escaping filenames and configuration settings in most cases
>     * A properly crafted filename or configuration option would allow for arbitrary code execution when using some features
>     * All users are encouraged to upgrade to this version, especially if you are checking 3rd-party code
>           * e.g., you run PHPCS over libraries that you did not write
>           * e.g., you provide a web service …
=> Up the minimum PHPCS version to 2.8.1

WordPress/Sniff.php, WordPress/Tests/VIP/DirectDatabaseQueryUnitTest.inc
This eliminates the need to add `// WPCS: cache ok` when you're using one of these functions.
As a possible enhancement to this, we could check to see that specific table that is being used in the `$wpdb` call and then map the specific `clean_*_cache()` function to the table being used. I can see this being error prone, however, especially in the case where `$wpdb->query()` is being used as opposed to `$wpdb->upate()` or `$wpdb->delete()`.
=> Recognize clean_*_cache() functions as cacheDeleteFunctions

.travis.yml
As PHPCS upstream is taking its time to decide whether or not to make the test suite compatible with PHPUnit 6 or not, we might as well get the builds passing again in the mean time, so we can get the 0.11.0 release out the door.
This is intended (fingers crossed) as a temporary solution to be reverted once the testsuite for PHPCS is cross-version compatible with PHPUnit.
I've chosen to *only* download PHPUnit when we need a different version than the one installed by default in the Travis images to keep the build time down.
=> :rocket: Temporary solution for build failure.

WordPress/Sniff.php
A number of sniffs use capitalization in the errorcodes to improve readability. This was unnecessarily undone by the `string_to_errorcode()` implementation.
For the sniffs were the errorcodes have not necessarily changed while using this function, this maintains BC instead of breaking it.
=> Make the impact of the errorcode change slightly less.

CHANGELOG.md
Ok, finished... & ready for review :tada: 
Looking at the changelog now, I kind of think we may need to release new versions more often...
=> Changelog for version 0.11.0

CHANGELOG.md
Release date was still based on when the changelog PR was finished. Now set to this upcoming Monday.
=> Fix 0.11.0 release date

.travis.yml
Addresses:
> should be added in the `before_install` section of the .travis.yml, this way if any errors occur the build job will report `Errored` rather than `Failed`, this is important as it determines there was an issue setting up your environment rather than the code you are actually testing against
As per @ntwb's comment https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/753#discussion_r93976823
=> :rocket: Minor travis script tweak.

WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Tests/WP/EnqueuedResourcesUnitTest.inc, WordPress/Tests/WP/EnqueuedResourcesUnitTest.php
Also:
* Adds unit tests for `T_DOUBLE_QUOTED_STRING` which were missing
* Fixes bug in regexes which did not allow for quotes around the `stylesheet` phrase to be escaped.
* Removed the blanket test exclusion for PHP 5.2 in favour of selective test exclusion.
=> EnqueuedResourcesSniff: Trigger on enqueued resources in heredoc and nowdoc syntax.

WordPress/Sniff.php
Use the new `get_function_call_parameter()` utility method for more precise token walking.
=> Function is_sanitized(): minor tweak.

WordPress/Sniffs/CSRF/NonceVerificationSniff.php
As the `$errorForSuperGlobals` and `$warnForSuperGlobals` properties are no longer public, we might as well simplify the logic used.
Should give a small speed boost too as we no longer `array_merge()` every time a `T_VARIABLE` is processed and use `isset()` instead of `in_array()`.
=> NonceVerification: minor code simplification & efficiency improvement.

WordPress/Sniffs/WP/PreparedSQLSniff.php, WordPress/Tests/WP/PreparedSQLUnitTest.inc, WordPress/Tests/WP/PreparedSQLUnitTest.php
Also:
* Adds unit tests for multi-line `T_DOUBLE_QUOTED_STRING` and `T_CONSTANT_ENCAPSED_STRING` which were missing
=> PreparedSQLSniff: Trigger on variables in sql in heredocs and ignore nowdoc syntax

WordPress/Sniff.php, WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Tests/Files/FileNameUnitTest.php, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-phpunit.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-phpunit6.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-wpunit.inc
It is common practice to name test file classes `test-something.php`. This conflicts with the strict checking for `class-classname.php` filenames.
This PR changes the behaviour of the `FilenameSniff` to exclude classes which extend (or are) well-known unit test classes from the class name check.
The `custom_test_class_whitelist` property should now also be available to `FilenameSniff` to allow for whitelisting additional test classes.
See: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#global-variable-overloads-in-unit-tests
Notes:
* Split the `is_token_in_test_method()` method into two methods to be able to re-use the logic.
* Added the PHPUnit6 base test class to the whitelist.
* The `FileNameSniff` class now extends the …
=> Exclude test files from class name rule

WordPress/Sniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.php
=> ValidatedSanitizedInput: Add support for picking up on variables in heredocs

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/Sniffs/VIP/PostsPerPageSniff.php, WordPress/Sniffs/VIP/SlowDBQuerySniff.php
The method documentation for the `getGroups()` method in the `AbstractArrayAssignmentRestrictionsSniff` was incorrect (belonged to the `AbstractVariableRestrictionsSniff`).
Corrected now for both the abstract as well as the child classes.
=> AbstractArrayAssignmentRestrictions: Fix method documentation.

WordPress/AbstractVariableRestrictionsSniff.php
While unit testing something else I ran into this bug.
Basically, the sniff allows for adding several arrays with things to be sniffed for, however when examining a `T_DOUBLE_QUOTED_STRING` or - when I add this (waiting in the backwings) - a `T_HEREDOC`, only the first set of patterns is taken into account instead of all possible patterns.
This in effect meant that the sniff suffered from false negatives.
The original intend seems quite clear what with the $patterns being merged in every part of the control structure. The bug has been in the sniff from the very beginning. De-coupling the `if` statements solves this.
Additionally, within the last `if` structure, `$token['bracket_closer']` is referenced, while this array key will not be available when a `T_DOUBLE_QUOTED_STRING` or …
=> Fix persistent bug in VariableRestrictions abstract

WordPress/AbstractVariableRestrictionsSniff.php, WordPress/Tests/VIP/RestrictedVariablesUnitTest.inc, WordPress/Tests/VIP/RestrictedVariablesUnitTest.php
Includes unit tests for a concrete child implementation. (includes a unit test which wouldn't have passed without the fix in #889)
=> AbstractVariableRestrictionsSniff: add support for heredoc syntax.

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/AbstractVariableRestrictionsSniff.php, WordPress/Sniffs/CSRF/NonceVerificationSniff.php, WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/VIP/AdminBarRemovalSniff.php, WordPress/Sniffs/VIP/CronIntervalSniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php, WordPress/Sniffs/WP/PreparedSQLSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php
A number of function names have changed in the 0.11.0 release, but some of the end comments still reflected their old function names.
=> :books: Fix some end comments

WordPress/Sniff.php, WordPress/Tests/PHP/StrictComparisonsUnitTest.inc, WordPress/Tests/PHP/StrictComparisonsUnitTest.php
If there is no whitelist comment, but a comment on the next line would - for whatever reason - include a whitelist keyword, it was still regarded as a whitelist comment.
This commit fixes that by changing two things:
1. The whitelist comment is now expected to be on the same line as the statement end token.
2. The whitelist keyword will no longer be matched if it is part of another phrase. So the whitelist keyword `key` will now only match `key` and not `keyword`.
Includes unit tests for both fixes.
Found this when testing a sniff where there was a whitelist keyword which was a partial match for a custom property and the inline changing of the custom property on the next line was being regarded as a whitelist comment...
=> :ambulance: Fixes: Whitelist function could sometimes be a bit too eager

WordPress/AbstractClassRestrictionsSniff.php, WordPress/Sniff.php
* Move the namespace determination methods to the `WordPress_Sniff` class (in preparation for #900).
* Port in improvements to these methods which have since been made to them (by me) in the PHPCompatibility standard.
=> Move & improve two namespace related utility methods.

WordPress/Sniff.php
This PR documents the list style used for properties throughout the library in response to concerns raised about this in #904.
=> :books: Document the list style used for properties in the `WordPress_Sniff`

WordPress/Sniffs/WP/I18nSniff.php
Remember that I mentioned an issue with the whitespace/tab indent sniff upstream ? https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/907#discussion_r109304952
The PR I made to fix that has just been merged and is (correctly) throwing some errors our way ;-)
=> CS: minor whitespace fixes.

.travis.yml, WordPress-Core/ruleset.xml, WordPress-Docs/ruleset.xml, WordPress-Extra/ruleset.xml, WordPress-VIP/ruleset.xml, WordPress/ruleset.xml, project.ruleset.xml.example
Add checking of the XML files to the build testing as discussed here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/911#discussion_r109780017
Notes:
* Runs only once per build (`SNIFF=1`)
* Checks for valid XML
* Checks for consistent codestyle of the XML by doing an auto-format and comparing that against the original file.
I've tested this extensively with deliberately malformed XML and incorrect formatting and am confident this will work as intended.
=> Lint the XML ruleset files and check them for consistent code style

project.ruleset.xml.example
* Recommend using the `WordPress-Extra` + `WordPress-Docs` ruleset rather than `WordPress-Core`.
* Add example to exclude the Composer vendor directory.
* Remove some of the "extra" included rules which are already included by the WP rulesets (and move the rest of them down).
* Add info and example on how to include the `PHPCompatibility` standard. We already recommend its use in the readme, so we might as well show how.
* Add a number of the recommended custom properties to the example ruleset.
* Add/Clarify some documentation.
=> Update the `project.ruleset.xml` example file.

WordPress-Core/ruleset.xml, WordPress/Sniffs/WP/CapitalPDangitSniff.php, WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed, WordPress/Tests/WP/CapitalPDangitUnitTest.php
This PR adds a new sniff which checks whether `WordPress` is spelled correctly in text strings, comment text and class/interface/trait names and can catch a wide range of typical misspellings.
For this sniff, I've erred on the side of caution as this is **_very_** prone to false positives.
This means that some misspellings will likely be missed by this sniff, but that seemed the better choice than to have everyone be terribly annoyed by the sniff being really buggy.
Notes:
* The sniff has been added to the `WordPress-Core` ruleset.
* The sniff will throw a `warning` when a misspelling is found.
* The sniff will only throw one warning per token, even when more than one misspelling is found in the same phrase. The warning will in that case contain a count of the number of misspellings found …
=> :sparkles: New CapitalPDangitSniff

WordPress-Core/ruleset.xml
The WP spelling sniff was pulled before the XML ruleset validation changes, so the associated XML still needed to be adjusted to comply.
=> Fix codestyle for latest XML rule addition.

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
This will flag the following as errors:
```php
Self::do_something();
self:: do_something();
self ::do_something();
self :: do_something();
```
Note that it excludes the `NotUsed` error code which would flag the following:
```php
MyClassName::do_something();
```
Since there are instances of this in the core codebase, for better or worse.
=> Add Squiz.Classes.SelfMemberReference to WordPress-Core

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
This will only prevent false positives when the sniffs are run on a PHP version which contains the backfilled function/class etc., but should diminish annoyances for these.
Related to issue #915
=> PrefixAllGlobalsSniff: Allow for backfills of native PHP functions/classes etc

WordPress/Tests/Files/FileNameUnitTest.php, WordPress/Tests/Files/FileNameUnitTests/NonStrictClassNames/ClassNonStrictClass.inc, WordPress/Tests/Files/FileNameUnitTests/NonStrictClassNames/non-strict-class.inc, WordPress/Tests/Files/FileNameUnitTests/NonStrictClassNames/unrelated-filename.inc
The unit tests for non-strict class names were never enabled as the directory in which the test files live, wasn't listed in the `glob()` call.
This was previously not corrected as the `@codingStandardsChangeSetting` directives did not seem to work well in combination with a PHP open tag as the target token.
This has now been fixed. The unit tests should now pass and the directory has been included by making the `glob()` call more dynamic which will automatically include additional directories if these would be added in the future.
=> FileNameUnitTest: Re-enable the unit tests for non-strict class names.

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
In issue #915 @GaryJones identified some issues with the new `PrefixAllGlobals` sniff.
PR #916 fixed the over-zealousness when non-prefixed functions/constants etc backfilled for PHP functions.
This PR addresses the remaining issues:
* Arrays keys for `$GLOBALS` need to be prefixed too, so throw a warning when these are dynamic. I.e. `$GLOBALS['prefix' . $something]` is fine, `$GLOBALS[ $something ]` will now throw a warning. These cases were previously ignored completely.
* Dynamic hook names or constant names when used with `define()` which start with a prefixed string will now be correctly identified as prefixed. I.e.: `apply_filters( "'genesis_cpt_archive_settings_capability_' . $this->post_type->name" )`
* Dynamic hook names or constant names when used with `define()` *might* be …
=> Fix issue #915: handling of variable variables / hook names / $GLOBALS array keys

WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php
As there are by now quite a number of sniffs which use the `AbstractFunctionRestrictions` class as the basis and `T_STRING` tokens are quite common, the "_checking whether a T_STRING is a function call_" part might be done ten or more times for each `T_STRING` token.
By adding a preliminary check whether the token content matches one of the targeted functions, we can bow out early and prevent a lot of this overhead.
It would be even better if we could use a straight array with `isset()`, but unfortunately that won't work here as the list of functions can contain function names with wildcards.
Having this extra check *does* mean we have to decouple the `AbstractClassRestrictionsSniff::process_token()` method from the parent as for the class sniffs we don't know the class name yet at that …
=> AbstractFunctionRestrictions: Efficiency tweak.

README.md
This option is available since PHPCS 2.6.0 and as the minimum required PHPCS version for WPCS > 2.6.0, we can safely mention this in the readme.
Ref: https://github.com/squizlabs/PHP_CodeSniffer/pull/899
=> :books: README: Add information about setting the `installed_path` via the ruleset

WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
Declare statements are typically written without spaces in them.
This commit makes the `OperatorSpacing` sniff ignore them, similarly as is done upstream - https://github.com/squizlabs/PHP_CodeSniffer/pull/1411
It would be a good idea to do a complete compare and sync with upstream for this sniff at some point, but that's another matter.
=> OperatorSpacing: Ignore operators in declare statements

.travis.yml, README.md, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/VIP/AdminBarRemovalSniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc, WordPress/Tests/Variables/GlobalVariablesUnitTest.inc, WordPress/Tests/Variables/GlobalVariablesUnitTest.php, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.php, composer.json
PHPCS 2.9.0 has just been released. See https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/2.9.0
-----
PHPCS 2.9.0 contains a new `PHP_CodeSniffer_Tokens::$textStringTokens` array as well as several other improvements to some of the predefined arrays in `PHP_CodeSniffer_Tokens` which are being used by WPCS.
It therefore makes sense to take advantage of these upstream improvements to automatically improve the results of our sniffing.
In two places, replacing an existing manually created array with the new `PHP_CodeSniffer_Tokens::$textStringTokens` array means that the `T_INLINE_HTML` token is added to the array.
For both instances, the code has been reviewed and it was determined that the `T_INLINE_HTML` token can never be encountered there anyway as both examine function calls, so …
=> Update for PHPCS 2.9.0

WordPress-Core/ruleset.xml, WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Sniffs/VIP/RestrictedVariablesSniff.php, WordPress/Tests/Arrays/ArrayAssignmentRestrictionsUnitTest.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.php, WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.php
* Multi-line arrays should be indented by one tab from the beginning of the line containing the array opener.
* The array closer should be level with the indentation of the line containing the array opener.
While the `ScopeIndent` sniff checks this type of alignment for most structures, it turns out it doesn't do so for arrays (I suspect this is because PHPCS itself prefers a different array style).
This PR fixes that by adding a new sniff. Both the errors this sniff throws have been made fixable.
The new sniff has been added to the `WordPress-Core` ruleset.
Violations against this sniff in the WPCS codebase have been fixed.
N.B.: I consider this sniff a candidate for pulling upstream to `Generic` in due time.
=> :sparkles: New sniff to verify correct array indentation

WordPress-Core/ruleset.xml, WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractClassRestrictionsSniff.php, WordPress/AbstractVariableRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/Arrays/ArrayAssignmentRestrictionsSniff.php, WordPress/Sniffs/DB/RestrictedClassesSniff.php, WordPress/Sniffs/DB/RestrictedFunctionsSniff.php, WordPress/Sniffs/Functions/DontExtractSniff.php, WordPress/Sniffs/Functions/FunctionRestrictionsSniff.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Sniffs/PHP/DevelopmentFunctionsSniff.php, WordPress/Sniffs/PHP/DiscouragedPHPFunctionsSniff.php, WordPress/Sniffs/PHP/POSIXFunctionsSniff.php, WordPress/Sniffs/VIP/FileSystemWritesDisallowSniff.php, WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Sniffs/VIP/RestrictedVariablesSniff.php, WordPress/Sniffs/VIP/SessionFunctionsUsageSniff.php, WordPress/Sniffs/VIP/TimezoneChangeSniff.php, WordPress/Sniffs/Variables/VariableRestrictionsSniff.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Sniffs/WP/DiscouragedFunctionsSniff.php, WordPress/Sniffs/WhiteSpace/DisallowInlineTabsSniff.php, WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php, WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.inc, WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.php
> Tabs should be used at the beginning of the line for indentation, while spaces can be used mid-line for alignment.
This new sniff covers the second part of this rule. (The first part is already covered by the `Generic.WhiteSpace.DisallowSpaceIndent` sniff).
The error which is thrown is auto-fixable.
The new sniff has been added to the `WordPress-Core` ruleset.
Violations against this sniff in the WPCS codebase have been fixed.
Mostly involved `getGroups()` function example comments. Some of these have also been adjusted slightly to be in line with an earlier change (#812) in which these were missed and/or with the comment from the abstract parent class.
N.B.: I consider this sniff a candidate for pulling upstream to `Generic` in due time.
N.B.2: This sniff could probably do with some …
=> :sparkles: New sniff to verify that spaces are used for mid-line alignment

WordPress/Sniffs/Files/FileNameSniff.php
When doing `echo '<?php $x=1;' | phpcs`, I was getting:
> Filenames should be all lowercase with hyphens as word separators. Expected stdin, but found STDIN. (WordPress.Files.FileName.NotHyphenatedLowercase)
Naturally this is wrong.
=> Bypass WordPress.Files.FileName sniff when file is from STDIN

WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Tests/Files/FileNameUnitTests/ThemeExceptions/content-another_slug.inc, WordPress/Tests/Files/FileNameUnitTests/ThemeExceptions/content-slug.inc
Allow for the newly added `content-{$slug}.php` template file format.
Fixes #957
=> Fix issue 957: allow for template files using content-{slug}.php format

WordPress/Tests/Files/FileNameUnitTest.php, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit.inc
This was an issue with the PHPCS annotations not being picked up correctly. This should now work as expected.
=> FileNameUnitTest: fix false positive unit test.

WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Tests/Files/FileNameUnitTests/ThemeExceptions/category-another_slug.inc, WordPress/Tests/Files/FileNameUnitTests/ThemeExceptions/category-slug.inc, WordPress/Tests/Files/FileNameUnitTests/ThemeExceptions/page-slug_slug.inc, WordPress/Tests/Files/FileNameUnitTests/ThemeExceptions/tag-another_slug.inc, WordPress/Tests/Files/FileNameUnitTests/ThemeExceptions/tag-slug.inc
Based on the https://developer.wordpress.org/files/2014/10/template-hierarchy.png and https://wphierarchy.com/
The original list as taken from issue #470 was incomplete.
This still excludes `author-$nicename` templates as the `nicename` used in those is supposed to be with dashes AFAIK.
Fixes #959
=> Fix issue 959: account for more template hierarchy file name exceptions.

.travis.yml
The builds against HHVM have been failing for quite a while. This fixes it for now.
Generally speaking there is no official support for PHPUnit on HHVM. Select versions do appear to work, but this is hit & miss.
The version used to fix it now, is based on going back through Travis build logs to find a previous HHVM build which did pass and checking the PHPUnit version used by Travis at the time.
=> Fix the builds for HHVM

WordPress-Core/ruleset.xml, WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractVariableRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Sniffs/Files/FileNameSniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php, WordPress/Sniffs/WP/CapitalPDangitSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/WP/PreparedSQLSniff.php, WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Sniffs/WhiteSpace/DisallowInlineTabsSniff.php, WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php
As per recent change in the PHP coding standards handbook after discussion in https://core.trac.wordpress.org/ticket/41057
Fixes #964
In the second commit, these type of end comments as previously added to the WPCS codebase are removed as well.
=> Remove long construct end comments sniff

WordPress/Sniffs/VIP/SlowDBQuerySniff.php, WordPress/Tests/VIP/SlowDBQueryUnitTest.inc, WordPress/Tests/VIP/SlowDBQueryUnitTest.php
Continuation of @barryceelen's work in #897 to replace the `tax_query` whitelist flag with a `slow_query` whitelist flag.
Differences with the previous PR:
* Rebased the previous PR & squashed the commits.
* Moved the changelog comment from the function docblock to the class docblock.
* Uses `slow_query` instead of `slow query` (underscore, not space) as the whitelist flag.
* Throws a _"deprecated whitelist comment"_ warning when a `tax_query` whitelist comment is encountered.
* Prevents that message being thrown more than once.
Fixes #894
Fixes #897 (superseded by this PR)
=> Updated: Add 'slow query' whitelist flag

WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php, WordPress/Sniffs/PHP/YodaConditionsSniff.php, WordPress/Sniffs/VIP/SessionVariableUsageSniff.php, WordPress/Sniffs/WP/EnqueuedResourcesSniff.php, WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php, WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php
Most WPCS sniffs extend the `WordPress_Sniff` class. However there were some which so far didn't.
This PR changes that whenever possible.
The affected sniffs do not necessarily *need* to use the `WordPress_Sniff` class as they don't use any of the utility methods or properties contained therein, however it will make future development slightly more intuitive as (nearly) all sniffs now follow the same pattern, as well as make life easier for the PHPCS 3.x branch which is being developed.
The following exceptions still remain:
* `WordPress_Sniffs_Arrays_ArrayDeclarationSniff extends Squiz_Sniffs_Arrays_ArrayDeclarationSniff` - this sniff is a partial copy of the upstream sniff with some commented out code
* `WordPress_Sniffs_Arrays_ArrayDeclarationSpacingSniff extends …
=> Leverage the WordPress_Sniff class for (most of) the remaining sniffs

WordPress-Core/ruleset.xml, WordPress/Sniffs/Functions/FunctionCallSignatureNoParamsSniff.php, WordPress/Tests/Functions/FunctionCallSignatureNoParamsUnitTest.inc, WordPress/Tests/Functions/FunctionCallSignatureNoParamsUnitTest.inc.fixed, WordPress/Tests/Functions/FunctionCallSignatureNoParamsUnitTest.php
Report on and remove whitespace between function call parenthesis when the function call has no parameters.
This sniff *will* result in contradictory messages when run with PHPCS, but that can't really be helped.
```
5 | ERROR | [x] Expected 1 spaces after opening bracket; 6 found
|       |     (PEAR.Functions.FunctionCallSignature.SpaceAfterOpenBracket)
5 | ERROR | [x] Expected 1 spaces before closing bracket; 6 found
|       |     (PEAR.Functions.FunctionCallSignature.SpaceBeforeCloseBracket)
5 | ERROR | [x] Function calls without parameters should have no spaces
|       |     between the parenthesis.
|       |     (WordPress.Functions.FunctionCallSignatureNoParams.WhitespaceFound)
```
I've chosen to put this sniff in the `Functions` category to be consistent with the related sniff in …
=> :sparkles: New sniff: FunctionCallSignatureNoParams

WordPress-Extra/ruleset.xml, WordPress/Sniffs/CodeAnalysis/EmptyStatementSniff.php, WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.inc, WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.inc.fixed, WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.php
New sniff to detect superfluous semi-colons and empty PHP open-close tag combinations.
Includes an auto-fixer.
Added into a new `CodeAnalysis` category to be in line with the related upstream sniff.
As these issues are not explicitly mentioned in the WP Core Coding Style Handbook and are more along the lines of best practices, I've added the sniff to the `WordPress-Extra` ruleset.
For that same reason, I've elected to let the sniff throw warnings instead of errors.
For the current WP Core codestyle update, it would, however, be advisable to explicitly enable this sniff from the ruleset as issues which this sniff will fix, *have* already been detected in WP Core during a visual inspection.
Fixes #975
N.B. This sniff should eventually be merged with the upstream …
=> :sparkles: New `CodeAnalysis.EmptyStatement` sniff

WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
The tokenizer sometimes replaces tabs with spaces in the token `content`. Instead of undoing this with a `str_replace()`, use the `orig_content` instead for higher accuracy.
=> Minor tweak: use original content for indentation determination

WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.php
Up to now, this sniff was based on a copy of a very old and outdated version of the upstream sniff.
The upstream and downstream sniffs had diverged quite widely code-wise, but not intention-wise.
I've run both the `WordPress.WhiteSpace.OperatorSpacing` sniff as well as its upstream version `Squiz.WhiteSpace.OperatorSpacing` over both the WPCS unit tests for this sniff as well as the Squiz unit tests for this sniff.
While there were differences in the results, they were for the better in favour of the upstream version of the sniff.
The unit test file has been adjusted to only test for the WPCS additional token.
Fixes #988
This was added to the WPCS version in #67
```php
if (!$var ) {}
```
**Fixed**: by overloading the `register()` method and adding the token to the sniff.
This was …
=> OperatorSpacing sniff: Defer to upstream sniff for improved results.

WordPress-Core/ruleset.xml
See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/971#issuecomment-309605603
This was originally disabled in #366 as being too finicky, but fixes issues we are now running into with the WP coding standards update.
Fixes #971
Fixes #974
=> Core: Enable the `ControlStructures.ControlSignature.NewlineAfterOpenBrace` check

WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
This bug was introduced in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/789/commits/786c9bb5855b3bdeb6c33852dd92f089b160a5fa but had so far gone unreported. This PR effectively reverts the offending part of that commit.
Fixes #976
=> ControlStructureSpacing sniff: fix blank line after control structure / disappearing comment

WordPress-Extra/ruleset.xml
Added to the `Extra` ruleset as the requirement to have a closing semi-colon for embedded PHP is not explicitly mentioned in the WP Core Handbook.
It's also perfectly valid PHP and won't cause parse errors, so more of a best practice than anything else.
Fixes #465
=> Add `Squiz.PHP.EmbeddedPhp` sniff to `Extra`

WordPress-Core/ruleset.xml
Also moved the `tab-width` up as this is not a sniff specific, but a generic setting.
Fixes #990
=> Core: Set the default encoding in the ruleset

WordPress-Extra/ruleset.xml, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Tests/WP/DeprecatedClassesUnitTest.inc, WordPress/Tests/WP/DeprecatedClassesUnitTest.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
New sniff to detect & notify about usage of deprecated WP classes.
Moves one deprecated class which was listed in the `DeprecatedFunctions` to this new class.
Added the new sniff to the `Extra` ruleset in line with the `DeprecatedFunctions` sniff also being there.
Related to #576 and https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/979#issuecomment-310235086
To do once the sniff is merged:
=> :sparkles: New `WP.DeprecatedClasses` sniff

WordPress/Sniffs/WhiteSpace/DisallowInlineTabsSniff.php
Came across this error message in one of my own projects and realized that - unless you run PHPCS with the error codes showing -, the error message was not clear enough and could cause confusion about alignment (spaces) versus indentation (tabs).
=> DisallowInlineTabs sniff: make error text clearer

WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.php
While working on something else, I realized that the spacing around logical operators - `&&`, `||`, `and`, `or` and `xor` - was not checked at all by the WordPress coding standards so far.
This PR fixes that. Includes unit tests for the WPCS customizations.
=> OperatorSpacing sniff: check whitespace around logical operators

WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.php
For multi-line array declarations, the close brace of the array is supposed to be on its own line + aligned with the line containing the array keyword.
The `ArrayDeclaration` sniff will move the close brace to its own line.
The `ArrayIndentation` sniff is only intended to fix the close brace indentation.
The `ArrayIndentation` sniff was until now - incorrectly - presuming the close brace would already be on its own line with only whitespace before it.
While the array *item* indentation part of the sniff did not suffer from this issue, I've build in a little extra check in that part just to make sure.
Fixes the "case of the disappearing array close brace" as identified in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/998#issuecomment-310837386
=> ArrayIndentation sniff: Fix disappearing close brace when close brace not on its own line

WordPress-Core/ruleset.xml, WordPress/Sniffs/Arrays/ArrayDeclarationSniff.php, WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php, WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc, WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc.fixed, WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.php
New sniff to enforce a comma after each array item and check the spacing around it.
Rules:
- For multi-line arrays, a comma is needed after each array item.
- Same for single-line arrays, but no comma is allowed after the last array item.
- There should be no space between the comma and the end of the array item.
- There should be exactly one space between the comma and the start of the next array item for single-line items.
This sniff replaces the comma related checks within the `ArrayDeclaration` sniff which were buggy in a number of cases.
* The single-line array comma related checks in the `WordPress.Arrays.ArrayDeclaration` have been excluded via the ruleset.
*  The multi-line array comma related checks have been commented out in the `WordPress.Arrays.ArrayDeclaration` sniff as …
=> :sparkles: New `CommaAfterArrayItem` sniff

.travis.yml, WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
This PR is based on the earlier work done by @david-binda.
I've squashed the earlier (20) commits into one and rebased the PR.
Additionally this update contains the following changes:
* Document the setting of the PHP ini value in the travis build script.
* Set the branch this is tested with to `2.9` as PHPCS 3.x has come out since the original PR was pulled and is now `master`.
* Remove the `short_open_tag_enabled` property as the value of this is only used once, so the check can just as efficiently be done in the appropriate place.
* Adjust the regex delimiter to be backticks.
* Pass `$data` in the `addError()` call as an array as that's expected by PHPCS.
* Remove the throwing of a warning when short open echo tags _"might"_ be found. This warning was also added to the upstream …
=> Updated: Adding missing escaping check for `<?=`

project.ruleset.xml.example
* Don't imply that the rules which are excluded in the example are broken/buggy.
* Change a grammatically incorrect sentence `to to`.
* Add example customization for the new `DeprecatedClasses` sniff.
=> Minor improvements to the example ruleset file.

README.md, composer.json
https://github.com/DealerDirect/phpcodesniffer-composer-installer
=> Support phpcodesniffer-composer-installer for easy integrate code style

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
As the handbook has now been adjusted, this sniff can now be legitimately placed in the Core ruleset.
Thanks @ntwb for sorting that out, including the adjustments.
Fixes #1000
=> Move `Squiz.PHP.EmbeddedPhp` from `Extra` to `Core`

WordPress-Core/ruleset.xml
Single-line function calls which contain an associative array as a parameter should - according to the handbook - have each item in the associative array on a new line.
```php
my_function( true, array( 'a' => 'b' ) );
```
This causes the function call to effectively become multi-line, while not complying with the PEAR "parameters in a multi-line function call should start on a new line" expectation.
```php
my_function( true, array(
'a' => 'b'
) );
```
As the rules for that part of the PEAR sniff were disabled, this caused a fixer conflict, resulting in the file not being fixed at all, 
By allowing the PEAR fixer to apply those rules anyway, the fixer conflict is removed.
```php
my_function(
true, array(
'a' => 'b',
)
);
```
The currently chosen solution has been discussed in depth in …
=> Fix fixer conflict between PEAR.FunctionCallSignature and WP.ArrayDeclarationSpacing

WordPress-Core/ruleset.xml
As proposed in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/982#issuecomment-312607024
Also adds the newly added ~~section +~~ rules from the handbook which came out of the discussion in #982.
Partially fixes #982.
=> Add `PSR2.ControlStructures.SwitchDeclaration` to the `WordPress-Core` ruleset

WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.inc, WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.php
Set the `tabWidth` for the unit test file and see the fixes we would expect to happen.
N.B.: I realize that the new unit tests look like they are not all aligned in the code view for the unfixed file, but this is due to the GH tab size setting. With a tab size setting of `4`, there are actually aligned.
=> DisallowInlineTabs sniff: improve & add more unit tests.

project.ruleset.xml.example
P.S.: it would be nice if WP-core would actually comply with the `.min.js` naming conventions for minified JS ...
Some examples of files which are minified without the `.min.js` extensions:
* `html5.js` as shipped with most default themes
* `wp-includes/js/jquery/jquery.js`
* `wp-includes/js/jquery/jquery.query.js`
* `wp-includes/js/jquery/jquery.ui.touch-punch.js`
* `wp-includes/js/swfobject.js`
---- 
PR has been updated and now covers:
* Add exclusion of minified JS files.
* Add exclusion of Node modules directory
* Remove exclusion of `*.twig` files as that's not an extension that is included by PHPCS by default, so would need to be added via `--extensions=...` for those files to be picked up in the first place.
=> Example project.ruleset.xml: improve exclusion pattern suggestions

.travis.yml
No need to do it for each build.
=> Build: only lint the PHP files once per PHP version.

WordPress-Extra/ruleset.xml, WordPress/Sniffs/Classes/ClassInstantiationSniff.php, WordPress/Tests/Classes/ClassInstantiationUnitTest.1.inc, WordPress/Tests/Classes/ClassInstantiationUnitTest.1.inc.fixed, WordPress/Tests/Classes/ClassInstantiationUnitTest.2.inc, WordPress/Tests/Classes/ClassInstantiationUnitTest.2.inc.fixed, WordPress/Tests/Classes/ClassInstantiationUnitTest.js, WordPress/Tests/Classes/ClassInstantiationUnitTest.js.fixed, WordPress/Tests/Classes/ClassInstantiationUnitTest.php
New sniff to verify that objects being instantiated comply with some basic rules:
* Always use parenthesis.
* Don't have spaces (or comments) between the class name and the parenthesis.
* Don't assign new by reference (PHP only).
Sniffs both PHP as well as JS code.
Auto-fixes _missing parentheses_ and _space between class name and parentheses_.
Currently doesn't handle cases of object instantiations where the class name is held in a variable variable.
Fixes #919
=> New `ClassInstantiation` sniff to `WordPress-Extra`.

.travis.yml
Via https://core.trac.wordpress.org/ticket/41292
Travis CI have announced they are going to switch to Trusty as the default distro come July 18th
> https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
----
The current availability of PHP 5.2 and 5.3 in the Travis CI build environment is the following:
1.  `dist: precise` with `sudo: false` 
2.    `dist: trusty` with `sudo: false`
3.    `dist: precise` with `sudo: false`
4.    `dist: precise` with `sudo: required`
• WPCS' current Travis CI config uses option `1` above
• Travis CI will override this configuration with option `2` come July 18th 2017
• The workaround for this issue for PHP 5.2 & 5.3 until September 2017 is to use option `3` for the PHP 5.2 and 5.3 Travis CI jobs
• Come September 2017 Travis CI will …
=> Update `.travis.yml` to use Ubuntu Trusty by default and Precise for PHP 5.2/5.3

WordPress/Sniffs/PHP/YodaConditionsSniff.php, WordPress/Tests/PHP/YodaConditionsUnitTest.inc, WordPress/Tests/PHP/YodaConditionsUnitTest.php
This sniff is supposed to loop over the left-hand side of the condition,
checking for variables. If the left-hand side of the condition is not a
variable, then it should not give an error about it.
However, there were some issues with how we were detecting the beginning
of the left-hand side of the condition. Take the following example code:
```php
$sample = false !== strpos( $link, '%pagename%' ); // Ok.
```
This should not cause an issue, because the left-hand side of the
condition is just `false`. However, we weren't detecting the beginning
of the condition correctly; we'd end up checking right through the `=`
assignment operator and seeing the `$sample` variable. As a result, an
error would be given for this snippet.
To correct this, we just need to take assignment operators into …
=> Improve detection of condition beginning in Yoda conditions sniff

WordPress-Extra/ruleset.xml, WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Solves part of #576 
I got the list of deprecated parameters by looking where [`_deprecated_argument()`](https://developer.wordpress.org/reference/functions/_deprecated_argument/) was being used.
This is the first of three sniffs. The other two that will follow are
- `WordPress.WP.DeprecatedParameterValues` e.g. `bloginfo( 'url' );` where the value `url` is deprecated
- `WordPress.WP.DeprecatedParameterArgValues` e.g. For `wp_dropdown_categories( $args ) ` `$args['type']` cannot be `links`.
There will be an notice if the parameter value is not what is used by default. The default value is important as in some cases the deprecated parameter maybe in the middle. e.g. `load_plugin_textdomain()`
If a dynamic parameter is used then there will be still an error. The values for the deprecated …
=> Check for deprecated parameters

WordPress/Tests/Arrays/ArrayAssignmentRestrictionsUnitTest.php, WordPress/Tests/DB/RestrictedClassesUnitTest.php, WordPress/Tests/Variables/VariableRestrictionsUnitTest.php, WordPress/Tests/WP/I18nUnitTest.php
Unit tests which have a `setUp()` method and use this to set the value of properties or command line parameters, should always have a `tearDown()` method in which they clean up after themselves.
This PR is part of the preparation for PHPCS 3.x compatibility.
=> Unit tests: Prevent bleed through between unit tests.

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractVariableRestrictionsSniff.php, WordPress/Sniffs/Arrays/ArrayAssignmentRestrictionsSniff.php, WordPress/Sniffs/Variables/VariableRestrictionsSniff.php
This PR is part of the preparation for PHPCS 3.x compatibility.
The `removeTokenListener()` method was used to prevent the sniffs using these abstracts from being called for further files, however, this method will no longer exist in PHPCS 3.x with no alternative.
The `AbstractFunctionRestrictionSniff` also uses a `getGroups()` method, but calls it earlier and prevents the child sniffs from being run without groups by just not registering any token listeners if no groups are found.
This same methodology has now been implemented in the two abstracts which used the `removeTokenListener()` method, effectively making these sniffs more efficient and preventing the removal of the method from becoming a problem.
=> PHPCS 3.x prep: work round a function which will no longer exist

README.md
When using the [Travis CI example](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards#travis-ci) verbatim, the build seems to choke on:
```
- if [[ "$SNIFF" == "1" ]]; export PHPCS_DIR=/tmp/phpcs; fi
- if [[ "$SNIFF" == "1" ]]; export SNIFFS_DIR=/tmp/sniffs; fi
```
Adding `then` resolves that issue.
(In the current example the master branch of PHP_Codesniffer is used, which does not work with the current WPCS version. I guess this will be fixed via #1047.)
=> Update Travis CI example in README.md

.travis.yml, CONTRIBUTING.md, bin/phpcs.xml
* Run the sniffs using a higher PHP and PHPCS version.
* Minor simplification in the command to call phpcs.
* Show warnings, but do not break the build for it. Previously warnings wouldn't be shown at all.
* Move a number of command line options to the ruleset.
* Exclude the Composer `vendor` directory if it exists.
* Update the section in the `Contributing.md` regarding code style
=> Build: improve our own codestyle checking

WordPress/PHPCSAliases.php
Fix a mixup between `class_exists()` and `interface_exists()`:
* `PHP_CodeSniffer_Sniff` is the interface.
* `PHP_CodeSniffer_File` is a class.
=> PHPCS 3.x compat: prevent conflicts with other standards.

WordPress/PHPCSHelper.php, WordPress/Sniff.php
This PR is part of the PHPCS 3.x compatibility PR series.
PHPCS 3.x introduces a `--ignore-annotations` command line option to ignore any and all inline file ignore / line ignore / coding standard setting changes etc.
This PR ensures that the WPCS specific whitelist comments will also be ignored if the `--ignore-annotations` command line option is passed.
Fixes #862
=> PHPCS 3.x compat: Implement recognition of the `--ignore-annotations` setting

bin/pre-commit
This update presumes that devs using this pre-commit hook will be using PHPCS 3.x.
N.B. Can someone who actually uses the pre-commit hook test this ? I'm on Windows and AFAIK this won't work there. /cc @westonruter
=> PHPCS 3.x compat: Update the pre-commit hook code

.gitattributes, .github/CONTRIBUTING.md
This PR adds a `.gitattributes` file to keep the archives GH creates of the repo clean of development related files.
People using Composer can still get these files in their setup if they really want to, by using `--prefer-source`.
Refs:
* [Reddit: I don't need your tests in my production](https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production)
* [Blog: I don't need your tests in my production](https://blog.madewithlove.be/post/gitattributes/)
As the 0.13.0 release adds yet more files (`/Test` directory) which are not relevant to the end-user, I suggest this to be added to the 0.13.0 release.
=> Add a .gitattributes file

README.md, composer.json
Version 0.4.0 of the DealerDirect Composer plugin registers each standard individually as if they were root-directory standards, not a collection of standards, which exposes a bug in PHPCS 3.x.
Refs:
* squizlabs/PHP_CodeSniffer/pull/1581
* DealerDirect/phpcodesniffer-composer-installer/issues/33
=> Explicitly recommend v0.4.1+ of the DealerDirect Composer plugin

CHANGELOG.md
Preliminary changelog for the 0.13.0 release.
Covers everything which is currently in the 0.13.0 milestone, including the not yet merged PRs.
Tentative release date set at August 3rd.
=> Changelog for the 0.13.0 release.

WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Tests/PHP/StrictInArrayUnitTest.inc
With using `strtolower` the check does not implicitly rely on constants being lowercase.
Solves #1061
=> make comparision in StrictInArraySniff unaware of uppercase (Solves #1061)

WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.php
Subsequent lines in a multi-line text string should be ignored as the chosen indentation should be presumed intentional, like for HTML snippets.
Fixes #1064
=> ArrayIndentation sniff: fix bug with multi-line strings as array value

WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Tests/DB/RestrictedFunctionsUnitTest.php, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.php
As of WordPress 4.8, the core function `get_term_by()` is cached so we're going to stop recommending the use of `wpcom_vip_get_term_by()` instead. The function `wpcom_vip_get_term_by()`will be deprecated.
=> Stop using wpcom_vip_get_term_by() instead of get_term_by()

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc
Words in hook names by default should be separated by underscores, however, this is checked by another sniff and not the concern of this sniff.
As that sniff `ValidHookName` also allows for passing other separator characters, this sniff should allow for an arbitrary word separator.
=> PrefixAllGlobalsSniff: allow "prefix + non-word char" for improved support of hook names

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
Notes:
* Checking for the existence of a namespace separator should be enough here.
* Using `__NAMESPACE__` outside of a namespace will result in an empty string, however, the `\` in the string following it will be part of the namespace name, making the constant effectively unreachable (which is not our concern).
Fixes #1056
=> PrefixAllGlobals: Improve recognition of namespaced constants using `define()`

README.md
Give readers a heads up that the tab width needs to be explicitly changed in the package settings and that certain config options may present problems.
Fixes #1082
=> Update README.md to include Atom setup tips

.github/CONTRIBUTING.md, CHANGELOG.md, Test/phpcs3-bootstrap.php, WordPress/PHPCSAliases.php
The underlying issue has been reported upstream squizlabs/PHP_CodeSniffer/issues/1591 and should be fixed there.
In the mean time, this will fix it for the time being.
IMHO this should be released as WPCS 0.13.1 to make this hotfix available as soon as possible which is why I'm pulling this to `master` and have included a changelog for a 0.13.1 release.
Fixes #1087 
If this is accepted, shall I open a separate PR to merge `master` back into `develop` so they are in sync again or should I cherrypick this and send in a PR to `develop` as well ?
=> Hotfix: temporary plaster to fix issue 1087

WordPress-Extra/ruleset.xml, WordPress-VIP/ruleset.xml, WordPress/Sniff.php, WordPress/Sniffs/WP/DiscouragedConstantsSniff.php, WordPress/Tests/WP/DiscouragedConstantsUnitTest.inc, WordPress/Tests/WP/DiscouragedConstantsUnitTest.php
This sniff is based on a sniff previously pulled to the TRT fork of WPCS as `Theme.DeprecatedConstants`.
Related issue: WPTRT/WordPress-Coding-Standards/issues/23
Original PR: WPTRT/WordPress-Coding-Standards/pull/30
Covers the list of constants found in: Otto42/theme-check/pull/162
Differences between that sniff and this one:
* This sniff is a **_lot_** more comprehensive in preventing false positives.
The original sniff was one of the first ones I wrote and it's kind of sweet to look back at that code which I wrote over a year ago and see how much I've learned about writing sniffs in the mean time.
* The original sniff was called `Theme.DeprecatedConstants`, but in reality, most of these constants aren't officially deprecated, though their usage is discouraged and the constants being …
=> New `WordPress.WP.DiscouragedConstants` sniff

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
PR #1089 introduced two new utility methods to the `WordPress\Sniff` class: `is_class_constant()` and `valid_direct_scope()`.
This PR introduces one additional utility method `is_class_property()` and implements the use of this and the other two methods in other places in the code where appropriate (other than where they were originally introduced for).
These utility methods improve the accuracy of the scope detection.
=> Add `is_class_property()` utility method and implement use of this and the other two new utility methods

WordPress/Sniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php
This PR addresses the comments made here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/826#discussion_r127965474
This change allows for setting the `minimum_supported_version` property for all three `WP.Deprecated...` sniffs in one go, either via the command-line or by setting a config variable in a custom ruleset.
As this config variable is no longer directly related to a sniff, I've chosen to make the name slightly more specific/descriptive: `minimum_supported_wp_version` <= note the `_wp_`.
Usage:
```bash
phpcs . --standard=WordPress --runtime-set minimum_supported_wp_version 4.5
```
or in a ruleset:
```xml
<config name="minimum_supported_wp_version" value="4.5"/>
```
The above one liner can replace the custom property which would otherwise need to be …
=> Allow for setting the minimum supported WP version from the command line

WordPress-Extra/ruleset.xml, WordPress/Sniffs/CodeAnalysis/AssignmentInConditionSniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Tests/CodeAnalysis/AssignmentInConditionUnitTest.inc, WordPress/Tests/CodeAnalysis/AssignmentInConditionUnitTest.php
Most of the time variable assignments being made in conditions are unintentional and are in actual fact typos which were intended as a comparison.
In those cases when it isn't a typo, this is a typical code smell which is a prime candidate for refactoring.
This sniff will warn when any such a variable assignment is found in a condition.
Note: the sniff does currently **not** detect variable assignments in the conditional part of ternaries.
Includes extensive unit tests.
Inspired by [this twitter thread](https://twitter.com/jrf_nl/status/893891839903838209), or rather: the responses I received to my tweet.
Note: the fact that WP uses Yoda conditions does **not** invalidate the need for this sniff.
The Yoda conditions sniff only checks comparison operators, not assignment operators.
I've …
=> Add new `CodeAnalysis.AssignmentInCondition` sniff to `Extra`

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
This simple change means that namespace separators will be be ignored completely by the check for output escaping which fixes the immediate issue.
For a more thorough fix, the logic of the function would need to be refactored to take namespaced functions into account as well, but that's for another day.
Fixes #933
=> XSS.EscapeOutput sniff: Fix issue #933 - namespace separators.

WordPress-Extra/ruleset.xml
As proposed in _proposal 2_ in WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1101
If/when it would be decided to make this explicit in the handbook, these can be moved to the `Core` ruleset.
=> Add sniffs to verify modifier keywords for declared methods and properties to `Extra`

WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.1.inc, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.1.inc.fixed, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc.fixed, WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.php
Allow for a property to be set in a custom ruleset to allow single item associative arrays to be single line.
If someone can come up with a better (less lengthy) property name: please let me know and I'd happily adjust the PR.
I've chosen to implement this as a `true`/`false` toggle.
The toggle defaults to `false` based on the rule as it is in the handbook.
Alternatively, it could be implemented numerically, i.e. number of items needed before the associative array rule takes effect with a default of `0`, but that felt like it would make the rule very arbitrary where one project would have it at `1`, another at `3` etc., which would counter the use of having the rule at all.
Fixes #1104
----
=> ArrayDeclarationSpacing: add a property to make an exception for single item associative arrays

.travis.yml
I guess these could have been updated instead, but I think that now the command is pretty straightforward and doesn't really need it.
=> Remove outdated comments from .travis.yml

WordPress-Extra/ruleset.xml
PHPCS 3.1.0 will introduce a new `Generic.Files.OneObjectStructurePerFile` sniff will which check for all three in one go, but cannot be used yet. See: https://github.com/squizlabs/PHP_CodeSniffer/issues/1627 and https://github.com/squizlabs/PHP_CodeSniffer/pull/1630
The current sniffs in this proposal will not catch one file containing a class + an interface + a trait, but will catch any file containing two or more of the same type of object structure.
I've chosen to downgrade the message to a warning and to soften the error message a little.
Once these sniffs have been in for a while and we have not received negative feedback about them, we could chose to defer to the upstream sniffs and let them `error` with a sterner message.
=> Extra: Encourage the best practice of only declaring one class/interface/trait per file

WordPress-Core/ruleset.xml
Fixes #1115 
Note: PHPCS 2.x and 3.x releases only check for the `->` operator. The additional check for the `::` operator has been added recently and will be contained in the PHPCS 3.1 release.
=> Core: Add sniff to check for and fix whitespace around object operators

WordPress-Core/ruleset.xml, WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.1.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.2.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.3.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.css, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.js, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
This sniff complements the upstream `Generic.WhiteSpace.DisallowSpaceIndent` sniff.
The `Generic.WhiteSpace.DisallowSpaceIndent` sniff makes sure that tabs are used for indentation instead of spaces.
However, the sniff allows for precision alignment of `# spaces < tab_width`.
In WP it is not customary to use precision alignment, though there are a few exceptions where it is used intentionally.
This means that precision alignment can not be auto-fixed.
We can, however, throw a warning when precision alignment is detected which is what this sniff implements.
Notes:
* This sniff will detect precision alignment in PHP, JS as well as CSS files.
* The sniff adds a new `precision alignment` whitelist comment.
* The sniff will handle the "space before star"precision alignment for comments without …
=> New `WhiteSpace.PrecisionAlignment` sniff for `Core`

WordPress/Tests/VIP/SuperGlobalInputUsageUnitTest.inc
Wasn't impeding the unit tests or anything, but was causing issues when I was running some tests to detect fixer conflicts.
Fixing the syntax error will allow for adding an additional test to the travis run to automatically check for fixer conflicts based on the existing unit tests at some point in the future.
For this additional travis test to be added, upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/1645 will need to be merged first.
=> Fix syntax error in test file

WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.1.inc
If a multi-line comment contained a completely empty line, the sniff would throw a fatal error: `Fatal error: Uninitialized string offset: 0 in WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php on line 144`.
=> WhiteSpace.PrecisionAlignment: fix potential fatal error

WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/WP/I18nSniff.php
When the Precision Alignment sniff was pulled, the issues this threw up in the WPCS codebase were not fixed (yet). This PR fixed that.
=> Fix Precision Alignment issues found in the WPCS code base

.travis.yml, Test/phpcs3-bootstrap.php, phpunit.xml.dist
The upstream PR to support PHPUnit 6.x has (finally) been merged and will be released in PHPCS 3.1.
Currently builds against PHPCS `master` are failing because of this as the final version of the PHPCS PHPUnit 6.x support PR includes a test bootstrap in PHPCS which is not being loaded as we use our own bootstrap.
Easily solved though, by loading the upstream bootstrap - if the file exists - from our own PHPCS 3 bootstrap file. That way our unit testing will be compatible with all supported PHPCS 3.x versions.
The `beStrictAboutTestsThatDoNotTestAnything="false"` addition to the `phpunit.xml.dist` file is needed to prevent PHPUnit from reporting there are no tests in our test files (as the tests are in the upstream test suite and our "tests" are basically only data providers).
The changes …
=> Fix travis build: load PHPCS native bootstrap if available and test against PHP 7.2

phpcs.xml.dist.sample
Issue #1128 raised the interesting point that example exclusions maybe taken over literally by people who are not as familiar with PHPCS.
This minor change should prevent that.
=> Update example ruleset based on feedback

WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed, WordPress/Tests/CSRF/NonceVerificationUnitTest.inc, WordPress/Tests/Classes/ClassInstantiationUnitTest.inc, WordPress/Tests/Classes/ClassInstantiationUnitTest.inc.fixed, WordPress/Tests/DB/RestrictedClassesUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc, WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc, WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc, WordPress/Tests/VIP/DirectDatabaseQueryUnitTest.inc, WordPress/Tests/Variables/VariableRestrictionsUnitTest.inc, WordPress/Tests/Variables/VariableRestrictionsUnitTest.php, WordPress/Tests/WP/CapitalPDangitUnitTest.inc, WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed, WordPress/Tests/WP/DeprecatedClassesUnitTest.inc, WordPress/Tests/WP/DiscouragedConstantsUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.1.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.2.inc
Fixes a variety of parse errors, syntax errors and fatal "function/variable already declared" errors in the test case files.
These fixes are not necessarily needed for the unit tests to work properly, but - except for when intentional to test something - having valid unit test code makes sense.
=> UnitTests: fix unintentional syntax/parse errors in the test case files

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed, WordPress/Tests/WP/I18nUnitTest.2.inc, WordPress/Tests/WP/I18nUnitTest.php
This will facilitate the WordPress core to ship with `WordPress.WP.I18n` enabled with a ruleset that has:
```xml
<rule ref="WordPress.WP.I18n">
<properties>
<property name="text_domain" value="default" />
</properties>
</rule>
```
There seems to be an issue with unit tests whereby the `codingStandardsChangeSetting` directives aren't getting recognized. Help appreciated.
=> [WordPress.WP.I18n] Allow omitting $text_domain arg when 'default'

WordPress-Extra/ruleset.xml
In PHPCS 3.x, the message, type and a number of other errorcode properties can be changed for all errors in a sniff in one go.
In PHPCS 2.x this is not yet possible and needs to be configured for each errorcode individually.
Issues introduced (by me) in #1111
=> Ruleset: maintain compatibility with PHPCS 2.x

WordPress-Extra/ruleset.xml, WordPress/Sniffs/PHP/DiscourageGotoSniff.php, WordPress/Tests/PHP/DiscourageGotoUnitTest.inc, WordPress/Tests/PHP/DiscourageGotoUnitTest.php
Usage of `goto` is seen as a typical code smell.
This sniff is a duplicate of the same as pulled upstream in PR squizlabs/PHP_CodeSniffer#1664
Once the minimum PHPCS requirement for WPCS goes up beyond the version in which the upstream PR  is merged, this sniff can be safely removed.
The fact that this is a duplicate with an upstream sniff is also the reason why the sniff itself throws a `warning` which is changed to an `error` via the ruleset.
Adding this sniff to `Extra` for now. The sniff can be moved to `Core` once the handbook has been adjusted (if it will be).
Fixes #1149
=> Add New "WordPress.PHP.DiscourageGoto" sniff to `Extra`

WordPress/Sniffs/VIP/PostsPerPageSniff.php, WordPress/Tests/VIP/PostsPerPageUnitTest.inc, WordPress/Tests/VIP/PostsPerPageUnitTest.php
WordPress VIP rule restricts the number of `posts_per_page` variable to 100, with this change you will be able to set the limit of the `posts_per_page` variable in your `ruleset.xml` like:
~~~xml
<rule ref="WordPress.VIP.PostsPerPage">
<properties>
<property name="posts_per_page" value="200"/>
</properties>
</rule>
~~~
=> Add customisable property to set the posts_per_page variable

WordPress-Extra/ruleset.xml
For now, I've added this as a separate section to `Extra`, but I'd like to use this to (re-)open the discussion on having separate (sub-)standards which only deal with code style or best practices (not mixed).
Please add your voice to the discussions on this in #740 and #1067 (and let's make the discussion not be a blocker for this PR).
=> Modern code/Extra: add sniff to check for single blank line after namespace declaration

phpcs.xml.dist.sample
=> Update example ruleset for new `minimum_supported_wp_version` config variable

README.md, composer.json
Set version constraint to allow for use with PHP 5.3 (thanks, @GaryJones 🙂).
=> Bump version constraint of suggested package to support PHP 5.3

WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.1.inc
If the stars for a docblock/multi-line inline comment  were not properly aligned, the sniff would throw an error even though there was no precision alignment.
The incorrect alignment of the _stars_ is not this sniffs concern, but for another sniff.
As the sniff is new to `0.14.0`, this bugfix should be included in the upcoming release.
=> PrecisionAlignment: fix false positive in combination with incorrectly aligned comments

WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.php
If a previous array item has a trailing comment, the sniff would bow out as it would defer to the ArrayDeclarationSpacing sniff to fix a multi-line array where items are not all on their own line first.
However, in the case of a trailing comment and the next array item in actual fact starting on its own line, the ArrayDeclarationSpacing sniff would (correctly) not kick in and the indentation error for the item would never be addressed.
This fixes that. Includes unit tests.
N.B.: Verified & confirmed that the ArrayDeclaration sniff already handled this situation correctly.
Fixes #1179
=> ArrayIndentation: deal correctly with trailing comments

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
The Core handbook has been adjusted:
> The goto statement must never be used.
>
> The eval() construct is very dangerous, and is impossible to secure. Additionally, the create_function() function, which internally performs an eval(), is deprecated in PHP 7.2. Both of these must not be used.
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#clever-code
This moves the related checks which were already contained in `Extra` to the `Core` ruleset.
=> Move `eval` and `goto` restrictions from `Extra` to `Core`

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml, WordPress/Sniffs/PHP/DiscouragedPHPFunctionsSniff.php, WordPress/Sniffs/PHP/RestrictedPHPFunctionsSniff.php, WordPress/Tests/PHP/DiscouragedPHPFunctionsUnitTest.inc, WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.inc, WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.php, WordPress/ruleset.xml
The following has been added to the handbook:
> create_function() function, which internally performs an eval(), is deprecated in PHP 7.2. Both of these must not be used.
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#clever-code
`create_function` was already discouraged in `Extra` via the `WordPress.PHP.DiscouragedPHPFunctions` sniff.
As it is now forbidden for Core, this check has been moved a new `WordPress.PHP.RestrictedPHPFunctions` sniff and added to the `Core` ruleset.
=> New RestrictedPHPFunctions sniff to initially forbid `create_function`

WordPress-VIP/ruleset.xml
As the whole `Core` ruleset is included in `VIP`, there is no need for these sniffs to be included twice.
=> VIP ruleset: remove the explicit inclusion of two sniffs which are also in `Core`

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
The WP base `Sniff` class contains a list of WP global variables which is used by two sniffs.
The `ValidVariableName` sniff contains a secondary list of globals which don't follow the WP variable name guidelines.
I've done a quick compare and found some differences between the lists which needed to be fixed.
It would be nice to build up the mixed_case_vars list dynamically, but unfortunately, as the `ValidVariableName` sniff extends an upstream sniff rather than the WP `Sniff`, this is currently not an option.
=> Sync the WP global var lists

WordPress/Sniff.php
While PHPCS does not allow for additional spaces in custom properties which are passed through a ruleset, WPCS was already lenient about this when the property was (incorrectly) passed as a string.
This fix will also make WPCS lenient about this when the property is passed as an array.
Inspired by upstream issue squizlabs/PHP_CodeSniffer#1688
So for WPCS, all of the below four examples will now work properly as expected:
```xml
<property name="customAutoEscapedFunctions" value="foo, bar" />
<property name="customAutoEscapedFunctions" value="foo,bar" />
<property name="customAutoEscapedFunctions" value="foo, bar" type="array" />
<property name="customAutoEscapedFunctions" value="foo,bar" type="array" />
```
The upstream issue still stands, but a fix for that would only go into PHPCS …
=> Array properties: always be lenient about spaces

WordPress/Sniffs/PHP/StrictInArraySniff.php
When a dev has supplied `false` as the third parameter, this will in all likelyhood be a very conscious choice.
Using a different error code for that particular code allows for modularly excluding the warning from the ruleset.
No adjusted unit tests as the affected tests will still give a warning, just with a different error code.
=> StrictInArray: Allow for excluding warning when `false` is found

Test/phpcs2-bootstrap.php, Test/phpcs3-bootstrap.php, WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml, WordPress/AbstractClassRestrictionsSniff.php, WordPress/Sniffs/CSRF/NonceVerificationSniff.php, WordPress/Sniffs/Classes/ClassInstantiationSniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php, WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php, WordPress/Sniffs/PHP/StrictComparisonsSniff.php, WordPress/Sniffs/VIP/AdminBarRemovalSniff.php, WordPress/Sniffs/VIP/CronIntervalSniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/WP/DeprecatedClassesSniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Sniffs/WP/DeprecatedParametersSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php
This sniff has already been added and removed a couple of times previously, see the discussion in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/382#r29970107 amongst others.
Adding the `maxPadding` property will hopefully make the sniff more acceptable.
Sister-PR to the array arrow alignment sniff PR as requested in #1122.
The value for `maxPadding` which I've chosen is arbitrary - similar to my notes about `maxColumn` in #1135 - and could probably use some scrutiny before deciding on the real number to use. /cc @pento 
If it would change, both commits in this PR will change.
--- 
[Edit]: Oh and I ran this sniff (combined with #1135) over WP Core as well to check for new fixer conflicts and none were found, so we're good in that respect.
=> Add sniff to check for alignment of assignment operators to `Core`

WordPress/Sniffs/VIP/CronIntervalSniff.php, WordPress/Tests/VIP/CronIntervalUnitTest.inc, WordPress/Tests/VIP/CronIntervalUnitTest.php
This change allows for passing a minimum cron interval through a property in a custom ruleset.
Includes one additional minor documentation fix for a previously added property.
As per a comment I made in proposal 2 in #1157
=> CronInterval: make the minimum cron interval configurable

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml, WordPress/PHPCSAliases.php, WordPress/Sniffs/WhiteSpace/SemicolonSpacingSniff.php, WordPress/Tests/WhiteSpace/SemicolonSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/SemicolonSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/SemicolonSpacingUnitTest.php
Adds two sniffs that correct spacing on either side of the `require*`
after the parentheses are removed:
- `Squiz.WhiteSpace.SemicolonSpacing` (added to `Core`) — Requires no
whitespace before the semicolon.
- `Squiz.WhiteSpace.LanguageConstructSpacing` (added to `Extra`) —
Requires exactly one space after a control structure.
I ran both of these over some code to see if there were any issues, and the only problem that turned up was with the semicolon sniff on this code:
```php
for ( ; $next <= $end; ++$next ) {
```
```
---------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------- …
```
=> Improve fixes for PEAR.Files.IncludingFile.BracketsNotRequired

WordPress-Core/ruleset.xml, WordPress/Sniff.php, WordPress/Sniffs/PHP/YodaConditionsSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
Adds sniff to check for whitespace around comma's within a function call. Allows for new lines. All errors thrown are fixable.
For closures it will also check whitespace around the equals sign for default values.
Example cases:
```php
a( 1,2 ); // NoSpaceAfterComma
a( 1   ,2 ); // SpaceBeforeComma + NoSpaceAfterComma
a( 1,   2 ); // TooMuchSpaceAfterComma
a(
1,
2
); // OK
```
Fixes #1189
=> Core: Add `Generic.Functions.FunctionCallArgumentSpacing` sniff

.travis.yml
Now https://github.com/squizlabs/PHP_CodeSniffer/pull/1645 has been merged, I can pull the follow up PR to #1123.
By running the complete WPCS suite over the test case files, we should be able to catch at least some fixer conflicts early.
As PHPCS exits with an error code of `1` when all fixable errors have been fixed correctly, we need to run the command twice over the test files to get a `0` exit code allowing the build to pass.
Any other error code indicates a fixer conflict or other problem remaining.
The travis report will output a summary report which will indicate the files which "FAILED TO FIX" which can be used to start investigating the fixer conflict.
=> Travis: Add simple test for fixer conflicts to the build script

WordPress-Core/ruleset.xml, WordPress/AbstractClassRestrictionsSniff.php, WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php, WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php, WordPress/Sniffs/Classes/ClassInstantiationSniff.php, WordPress/Sniffs/WhiteSpace/ArbitraryParenthesesSpacingSniff.php, WordPress/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.php
This new sniff checks the spacing on the **_inside_** of arbitrary parentheses.
A conscious choice has been made not to check on the outside as this would very quickly conflict with other sniffs.
Arbitrary parentheses, for the purposes of this sniff, are all parentheses which do not belong to a control structure, function declaration, function call or language construct.
This is to prevent conflicts and duplication with rules for those type of constructs.
**Notes:**
* The sniff will throw (fixable) errors when an incorrect amount of whitespace (too much/too little) has been found on the inside or the parenthesis.
* The sniff will throw a warning when an empty set of arbitrary parentheses is encountered.
* The desired amount of whitespace on the inside of the parentheses can be configured …
=> New ArbitraryParenthesesSpacing sniff for Core

WordPress/Sniff.php, WordPress/Sniffs/WP/PreparedSQLSniff.php, WordPress/Tests/WP/PreparedSQLUnitTest.inc, WordPress/Tests/WP/PreparedSQLUnitTest.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
**This PR contains a bugfix and an enhancement. Pulled in one go as they would otherwise conflict.**
While working on some improvements for the `PreparedSQLPlaceholders` sniff, which includes a whitelist comment, I came across the following issue:
```php
// This works fine.
$sql = $wpdb->prepare( "SELECT * FROM $wpdb->users WHERE id = %d AND user_login = %s", $replacements ); // WPCS: PreparedSQLPlaceholders replacement count OK.
/*
* This would trigger a "Use placeholders and $wpdb->prepare();
* found // WPCS: PreparedSQLPlaceholders replacement count OK." error.
*/
$sql = $wpdb->prepare( // WPCS: PreparedSQLPlaceholders replacement count OK.
"SELECT *
FROM $wpdb->users
WHERE id = %d
AND user_login = %s",
$replacements
);
```
**Bugfix:** That the `WP.PreparedSQL` sniff triggers an error …
=> Improve whitelist comments + issue with PreparedSQL sniff

WordPress/Sniffs/WP/PreparedSQLSniff.php, WordPress/Tests/WP/PreparedSQLUnitTest.inc
As `floatval()`, `intval()` and the likes are in the `$SQLEscapingFunctions` array, we should also allow for variables being safe casted.
This PR makes it so:
* The tokens for `(int)`, `(float)` and `(bool)` will no longer trigger an error.
* Variables which are preceeded by one of these will be considered safe.
Included unit tests.
=> PreparedSQL: allow for safe casts

WordPress/Sniffs/CodeAnalysis/AssignmentInConditionSniff.php
A `while()` condition is the only control structure in which it is sometimes legitimate to use an assignment in condition.
Having a separate error code will enable people to selectively exclude warnings for this.
N.B.: same change has been pulled upstream.
N.B.2: I've not applied this to the second error message as when it's a non-variable assignment, it doesn't matter whether it's in a loop or not, it's always wrong.
=> AssignmentInCondition: add separate errorcode for assignment found in while

WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.1.inc, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.1.inc.fixed, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc.fixed
Everywhere else where a "ignore new lines" property is used, both in WPCS as well as in PHPCS upstream, the property is called `ignoreNewlines`.
Only just now realized that the `s` was missing from the property in the new `Arrays.MultipleStatementAlignment` sniff.
Not a BC-break as the sniff has not been in a release yet.
=> MultipleStatementAlignment: property name consistency

WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php, WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.inc
I should have thought of this before...
Function names in PHP are case-insensitive, so the sniff should check them in a case-insensitive manner.
Adjusted some existing unit tests to cover this.
=> PreparedSQLPlaceholders: do function name compares case-insensitively

WordPress/Sniff.php
I was getting a `WordPress.Files.FileName.InvalidClassFileName` error for test when I extended `WP_Ajax_UnitTestCase`.
=> Add WP_Ajax_UnitTestCase to \WordPress\Sniff::$test_class_whitelist

WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/XSS/EscapeOutputUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.php
WordPress does not have any `esc_attr_ex()` or `esc_html_ex()` functions, we have to `echo` the non-echoing variants, which do exist.
=> Fix suggestions for unsafe _ex() function

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc
Some core actions and filters are intended to be called by plugins and themes, so we don't need to throw an error when they are.
=> Naming Conventions: make exceptions for core hooks intended to be reused

.github/CONTRIBUTING.md, CHANGELOG.md, README.md
Complete, including the open PRs #1213 and #1214.
If there are no objections and no pertinent bugs found between now and then, I propose to release 0.14.0 ~~this Thursday~~ ~~this Monday (see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1215#issuecomment-339552840)~~ this Wednesday (delayed for reasons known to the team).
=> Changelog for the 0.14.0 release

WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc.fixed
The build failure has to do with an upstream fixer conflict between two sniffs fighting over tabs vs spaces.
This is related to a recent upstream change and should be reported there for further attention.
As the space is not important for this particular unit test, let's just prevent the conflict from happening for now.
=> Fix build failure

bin/phpcs.xml
This is now possible since PR #1207 has been merged.
Using an assignment in condition is a typical pattern used when walking the token arrays and should be ok for this library.
=> CS: exclude while assignment in condition from own CS rules

WordPress/Sniff.php, WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php, phpcs.xml.dist.sample
The minimum version should be three versions behind the latest WP release, so what with 4.9 having come out last week, it should now be 4.6.
@JDGrimes Want to run your deprecated function magic to see if we need to add functions/classes/parameters to the lists ?
=> Update default minimum WP version

WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc.fixed
This reverts commit c27064aa0a455cb4d924864612369b2847108d44 / PR #1238.
The upstream issue which was causing the build failure has been fixed, so I'm bringing back the odd spacing to allow us to continue to detect these kind of fixer conflicts early.
=> Revert "Fix build failure"

WordPress-VIP/ruleset.xml, WordPress/Sniffs/WP/PostsPerPageSniff.php, WordPress/Tests/VIP/PostsPerPageUnitTest.inc, WordPress/Tests/WP/PostsPerPageUnitTest.inc, WordPress/Tests/WP/PostsPerPageUnitTest.php
As noted in PR #1242, there was one sniff rename (split) not covered by that PR: `PostsPerPage`. This PR takes care of that one.
Split this sniff into two: one in VIP checking for disabling of pagination, one in WP checking for high pagination limit.
The WP version now throws a `warning`. This is reset to an error for use by VIP via the VIP ruleset.
=> PostsPerPage: split sniff

WordPress-Extra/ruleset.xml
A couple of sniffs which were previously in VIP are also useful for `Extra`. The messages in these sniffs have - where appropriate - been downgraded to warnings.
This commit adds these sniffs to the `Extra` ruleset.
Note: There are three more candidates for this:
* `DB.DirectDatabaseQuery`
* `DB.SlowDBQuery`
* `Security.ValidatedSanitizedInput`
I've not included the first two (yet) as those may need some more discussion first.
The third one is not included as it throws a lot of noise messages and has quite some open issues surrounding it, which should be addressed first IMO.
=> Add a couple of extra sniffs to `Extra`

WordPress/Sniffs/VIP/TimezoneChangeSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php
Fixes the incorrect message text as reported in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1242#issuecomment-353124042
I double-checked all the deprecation messages to be on the safe side and found one other sniff in which the new name had not been adjusted. That one is fixed here too.
=> Fix two "typo"'s in deprecation messages

WordPress-Extra/ruleset.xml, WordPress-VIP/ruleset.xml, WordPress/Sniffs/Security/SafeRedirectSniff.php, WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Tests/Security/SafeRedirectUnitTest.inc, WordPress/Tests/Security/SafeRedirectUnitTest.php, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc, WordPress/Tests/VIP/RestrictedFunctionsUnitTest.php
Introduces a sniff that warns about the use of the `wp_redirect()` function, suggesting
`wp_safe_redirect()` instead, to avoid malicious redirects.
This is based on the warning currently in `VIP.RestrictedFunctions`, but
in a more generic form.
I've added the sniff to the `WordPress-Extra` ruleset.
=> New Security.SafeRedirect sniff to encourage safe redirects

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed
The `WP.I18n` sniff did not properly verify whether the `T_STRING` found was actually a function call, in contrast to a method call or a namespaced function call.
I've fixed this now by extending the `AbstractFunctionRestriction` sniff and using the logic contained therein to make sure that only plain function calls are being addressed.
A future further improvement could be extending the `AbstractFunctionParameter` sniff instead to benefit from using the logic from the `get_function_call_parameters()` utility function.
For now, I've just made the function parenthesis check slightly more stable, by making it code style independent and adding an extra safeguard for live coding situations.
Fixes #1266
=> WP.I18n: Fix false positive on method calls.

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
_As discussed in #1157 with conclusion written up in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1157#issuecomment-345749743 ._
Hard excluding individual PHPCS rules makes it impossible for a custom ruleset to re-enable a rule.
By changing the severity instead, a custom ruleset can up the severity of a check to re-enable it.
Note: whether this will work or not depends on the loading order of rules. No guarantees given.
The fact that it may not work in certain circumstances, is something which should be addressed upstream.
=> Rulesets: lower severity instead of excluding checks

README.md
Following up on https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1256#issuecomment-350631622
I've created wiki pages containing the information which is (was) in the readme about configuring [Sublime Text](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Setting-up-WPCS-to-work-in-Sublime-Text) and [Atom](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Setting-up-WPCS-to-work-in-Atom) for use with PHPCS & WPCS.
This PR removes that information from the Readme and adds links to the wiki pages in it's place.
It also simplifies the IDE list to a bullet list.
=> Readme: move IDE setup instructions to the wiki

WordPress/Sniffs/CodeAnalysis/AssignmentInConditionSniff.php, WordPress/Tests/CodeAnalysis/AssignmentInConditionUnitTest.inc, WordPress/Tests/CodeAnalysis/AssignmentInConditionUnitTest.php
For "assignment in condition" check with ternaries, only ternaries in parentheses are checked as it is neigh impossible to determine where the condition starts otherwise.
Obviously, for that to work, the sniff should only take parentheses into account which are actually related to the ternary.
Fixed now.
Fixes #1227
~~P.S.: there may be more "delimiters" which should be taken into consideration, not just the semicolon, but I couldn't come up with valid example code at this moment. (head in other things). Please let me know if you can think of some, including example code, and I'll adjust the sniff.~~
[Edit]:
The renewed commit now takes a number of additional delimiters into account.
It also adds a separate errorcode for assignments found in ternaries.
=> AssignmentInCondition: fix bug where nested parentheses were presumed to be related to a ternary

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc, WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
The advantage of `wp_strip_all_tags()` over `strip_tags()` is that it does not leave the content of removed `<script>` and `<style>` tags behind.
> This differs from `strip_tags()` because it removes the contents of the `<script>` and `<style>` tags. E.g. `strip_tags( '<script>something</script>' )` will return ‘something’. `wp_strip_all_tags()` will return ”
Refs:
* https://developer.wordpress.org/reference/functions/wp_strip_all_tags/
* http://php.net/manual/en/function.strip-tags.php
=> AlternativeFunctions: detect `strip_tags()` and advise using `wp_strip_all_tags()` instead

WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.4.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
The PHP open tag may not be the first token in a file - think views starting with inline HTML -.
By starting the loop to examine all lines at the `$stackPtr`, inline HTML lines before the first PHP open tag were not being examined.
Files which do not contain a full PHP open tag `<?php`, but do contain short open echo tags `<?=` - i.e. views - were not being examined at all.
N.B.: this improvement will not work in PHPCS 2.x in combination with PHP 5.3 when the `short_open_tag` ini setting is turned off.
I deemed creating a work-around for that specific situation not worth the effort as PHPCS 2.x as well as PHP 5.3 support will be dropped this summer anyway.
The new line character is normally tokenized as `T_WHITESPACE`, however, not so when at the end of inline HTML, where …
=> PrecisionAlignment: fix various bugs

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc
Fixes #1275
This PR also contains a minor fix to the unit test case files (in a separate commit):
* Custom properties should be reset at the end of the unit test file in which they are used.
=> PrefixAllGlobals: bug fix - don't trigger on closure parameter definition

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc, WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
Fixes #1248
I've included the discouraged random seed generation functions in this PR as:
* they are not needed when using `wp_rand()`
* they are discouraged for use in PHP anyway
Refs:
* https://developer.wordpress.org/reference/functions/wp_rand/
* http://php.net/manual/en/function.rand.php
* http://php.net/manual/en/function.mt-rand.php
* http://php.net/manual/en/function.srand.php
* http://php.net/manual/en/function.mt-srand.php
=> AlternativeFunctions: add warning about using PHP native rand generation

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
This allows for prefixed functions, classes, hooks in camelCase and other naming conventions.
Fixes #1239 
While looking at the prefix check, I noticed a secondary bug which is fixed in a separate commit:
Invalid prefixes which did not pass the second validation check would still be added to the `validated_prefixes` array and the sniff would still run, even though no valid prefixes were available.
=> PrefixAllGlobals: make the prefix comparison more code style independent

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
Variables created by control structures, such as `$b` in `foreach ( $a as $b )` should also be prefixed when in the global namespace.
Verified that variable assignments in other control structures, `if`, `while`, `for` are correctly detected already and added unit tests to make sure they will continue to be detected correctly.
~~Goto labels are a special kind of control structure and while these are restricted to the same file and context, I have not been able to find any confirmation that `goto` labels have a concept of "local" versus "global".~~
~~Therefore `goto` labels when used will always need to be prefixed too.~~
This PR takes care of this.
Fixes #1236
=> PrefixAllGlobals: handle variables created by foreach

WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed
Properties always need to be completely reset at the end of the test file to not influence other test files for the same sniff.
=> I18n: minor fix to the unit test file

WordPress/Sniff.php, WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
Only show suggestions for WP functions which are recommended as alternative for native PHP functions, when the `minimum_supported_version` allows for it.
Note: the unit test file now contains a property setting. This property needs to be reset after use. The reset value has to be in-line with the default value as set in the `Sniff` class.
A note to that end has been added to the property documentation in the `Sniff` class.
=> AlternativeFunctions: only advise alternative if min WP version supports it

README.md, WordPress-VIP/ruleset.xml
We should always refer to "WordPress.com VIP" and never "WordPress VIP".
This change updates a few places where wording was slightly wrong.
The name of the standard remains "WordPress-VIP" as that's probably too
ingrained in folks processes to change.
=> WordPress-VIP: Ensure we use WordPress.com not WordPress.

.travis.yml
Validate the composer.json file on each build.
Ref: https://getcomposer.org/doc/03-cli.md#validate
Notes:
* This check has not been restricted to a specific PHP version as there may be different versions of Composer being run on different Travis PHP images, so validating the file once against each PHP/Composer combi should make sure the file is properly validated.
=> Travis/Build: validate the composer.json file

WordPress/Sniffs/WP/DeprecatedParametersSniff.php
According to the documentation, the value you are expected to pass for the deprecated parameter of the `wp_upload_bits()` function is `null`.
> $deprecated
>    (null|string) (Required) Never used. Set to null.
Ref: https://developer.wordpress.org/reference/functions/wp_upload_bits/
=> DeprecatedParameters: fix expected value for `wp_upload_bits()`

WordPress/Sniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.inc
The currently included list is arbitrary, but safe and can be expanded on in the future based on user-land requests.
The underlying `is_use_of_global_constant()` utility method was written by me and was originally written for and pulled to PHPCompatibility. The method is extensively unit tested in that standard.
Fixes #1200
=> EscapeOutput: allow for a limited set of safe PHP native constants

WordPress/Sniff.php, WordPress/Tests/Files/FileNameUnitTest.php, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-global-namespace-extends.1.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-global-namespace-extends.2.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.1.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.2.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.3.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.4.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.1.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.2.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.3.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.4.inc, WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.5.inc
Based on a non-GH report by @GaryJones .
This commit enhances the `Sniff::is_test_class()` method to handle namespaced test classes better.
* Will now correctly recognize whether a class is in a namespace and adjust the response based on that.
Previously, namespaces classes where the classname was one of the whitelisted global classes would pass, even though they were not the same class.
The same happened with extended classes.
* The other side of this was that a namespaced custom test class where the name was split between the namespace declaration and the extended class declaration was not correctly recognized as the whitelisted test class. Now it will be.
* Improves handling of FQN used for the extended class name, i.e. prefixed with a `\` to indicate global namespace.
* Adds tolerance …
=> Improve recognition of test classes

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
If `class_exists()` and the like are called without the second `$autoload` parameter set to `false`, it could trigger a (Composer) autoload file and in certain circumstances trigger a fatal `class not found` error.
If the class however is found and the file also contains side-effects, such as a typical block found at the top of a WP file (see below), it can also trigger a PHPCS process error with a `headers already send` notice.
As the check is only intended to detect backfills for PHP native functionality, adding the `$autoload` parameter should fix this.
```php
if ( ! function_exists( 'add_filter' ) ) {
header( 'Status: 403 Forbidden' );
header( 'HTTP/1.1 403 Forbidden' );
exit();
}
```
:point_right: As this is a bug which can break PHPCS runs completely, I would like to propose to …
=> PrefixAllGlobals: only recognize PHP native classes, don't try and autoload

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
If `class_exists()` and the like are called without the second `$autoload` parameter set to `false`, it could trigger a (Composer) autoload file and in certain circumstances trigger a fatal `class not found` error.
If the class however is found and the file also contains side-effects, such as a typical block found at the top of a WP file(see below), it can also trigger a PHPCS process error with a `headers already send` notice.
As the check is only intended to detect backfills for PHP native functionality, adding the `$autoload` parameter should fix this.
```php
if ( ! function_exists( 'add_filter' ) ) {
header( 'Status: 403 Forbidden' );
header( 'HTTP/1.1 403 Forbidden' );
exit();
}
```
=> [Backport 0.14.x] PrefixAllGlobals: only recognize PHP native classes, don't try and autoload

CHANGELOG.md
This adds the changelog for the 0.14.1 release which can be tagged straight after merging this PR.
=> Release 0.14.1

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
A large number of the global constants used in WP core are overrulable.
These constants, when they are being defined by plugins/themes, should, of course, not be prefixed.
This adds a list of the overrulable WP core constants to the sniff and prevents the sniff from throwing notices if any of those are being defined/declared.
Fixes #1311
Commit includes minor tidying up of the associated UnitTest file.
=> PrefixAllGlobals: allow for defining non-prefixed core globals

WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/Tests/PHP/DiscouragedPHPFunctionsUnitTest.inc, WordPress/Tests/VIP/FileSystemWritesDisallowUnitTest.inc
Prevent class declarations being confused with function calls
Fixes #898
N.B.: I do still intend to pull a much more comprehensive class to correctly analyze `T_STRING` tokens, but that's still a work in progress. In the mean time, this is a simple fix to make.
----
**[Edit]**: I've added a second commit along the same lines for preventing use statement aliases being confused with function call names.
Fixes #956
=> AbstractFunctionRestrictions: prevent some typical misidentifications of function calls

WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed
While this will be solved better in the future by a dedicated sniff to check function declarations (see #1101) , in the mean time, return type declarations should not be removed by the fixer in this sniff.
And as the placement of the opening brace for function declarations is also checked for by the `Generic.Functions.OpeningFunctionBraceKernighanRitchie` sniff, let's ignore this error for function declarations in this sniff and leave the fixing up to the upstream sniff.
Fixes #1202
=> WhiteSpace/ControlStructureSpacing: prevent fixer removing return type declarations

WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed
Looks like the original issue was already fixed by #1267, so just adding an additional unit test to safeguard against re-introducing the issue.
Closes #719
=> WP.I18n: add additional unit test

WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed
If a multi-line string is broken up across several lines, the indentation of subsequent lines should not be fixed, nor should any warnings/errors be thrown.
This worked perfectly well as long as the closing quote of the multi-line string was not on a line of its own.
Now the sniff will deal correctly with that edge-case as well.
=> ArrayIndentation: fix bug when dealing with multi-line string

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/WhiteSpace/SemicolonSpacingSniff.php
Turns out that using `end()` on a nested array in a (very) large array such as the `$tokens` array can be with large files, is significantly slower than copying the nested array to a local variable and using `end()` on that.
See: https://github.com/squizlabs/PHP_CodeSniffer/commit/6d15547ed874d0061c83e380496162e2ec2020c8#r28189947
@JDGrimes Do you agree ?
=> Minor performance optimization

WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Tests/Security/EscapeOutputUnitTest.inc, WordPress/Tests/Security/EscapeOutputUnitTest.php
The PHPCS `findEndOfStatement()` method returns the end token òr the last non-whitespace token if the end token is a "bracket", like a closing parenthesis.
In effect, this meant that the last token in a `trigger_error()` function call was never examined and that the sniff would underreport.
Fixed now. Includes unit tests.
If `$end_of_statement` had not been determined, the sniff would report on `OutputNotEscaped`, not on `UnsafePrintingFunction`s.
To report on `UnsafePrintingFunction`s, the code in the condition does not actually need the `$end_of_statement`, so this minor logic change allows for the sniff to report the correct error.
The sniff would up to now not handle short arrays correctly and would report on the open/close brackets, not on the content of the array.
Includes unit …
=> EscapeOutput: fix various bugs

WordPress/Sniff.php
=> Don't mark `get_template_part()` as safe for output

WordPress/Sniff.php
=> Add `readonly()` to the list of auto escaped functions

WordPress/Sniff.php
=> Remove `cancel_comment_reply_link()` from the list of auto escaped functions

WordPress/Sniff.php
=> Don't mark `get_comment_date()` and `get_comment_time()` as safe for output

composer.json
Just suggesting a package does not explain to a user why it would be interesting for them to install it and I've already had question about the suggestion.
The `suggest` entry in the `composer.json` file has a value which is not actually intended for version constraints, but to add a hint to the user about why they should install the package.
Up to now, the value in the WPCS `composer.json` was used for a version constraint. While this is still a good idea to mention in this case as the plugin needs a certain version to be compatible with the same PHP versions WPCS supports, adding the hint on why the package is suggested should help users even more.
Ref: https://getcomposer.org/doc/04-schema.md#suggest
=> Composer: add note about why the DealerDirect plugin is suggested

WordPress-VIP/ruleset.xml, WordPress/Sniffs/CSRF/NonceVerificationSniff.php, WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php, WordPress/Sniffs/Functions/DontExtractSniff.php, WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/Security/NonceVerificationSniff.php, WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/VIP/CronIntervalSniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Sniffs/VIP/SlowDBQuerySniff.php, WordPress/Sniffs/VIP/TimezoneChangeSniff.php, WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php, WordPress/Sniffs/Variables/GlobalVariablesSniff.php, WordPress/Sniffs/XSS/EscapeOutputSniff.php, WordPress/Tests/VIP/DirectDatabaseQueryUnitTest.inc, WordPress/Tests/VIP/PostsPerPageUnitTest.inc, WordPress/Tests/XSS/EscapeOutputUnitTest.inc
This PR actually fixes a number of things which I missed in the deprecation PR the first time around.
The `addWarning()` and `addError()` methods return a boolean value signifying whether or not the notice has been thrown. This will in most cases be `true`, but will return `false` when the notice for whatever reason is being ignored.
Instead of hard-setting the `$this->thrown` value to true, let's use the return value instead so if the message is ignored for one file, it will still be thrown for the next.
* Change the default values for the `$addedCustomFunctions` properties.
* Update the compares for the custom properties within the deprecated sniffs to prevent "deprecated property" messages being thrown unnecessarily.
Includes minor efficiency fix: No need to do the property compares if …
=> Fix deprecated sniff warnings

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc, WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
The `wp_strip_all_tags()` function does not allow for passing a list of allowed tags, while the PHP native function does, so the WP alternative is not a valid alternative when the second parameter `$allowable_tags` is passed.
Along the same lines, the `wp_parse_url()` function only added support for the PHP native second parameter `$component` in WP 4.7.0.
The changes now made means the sniff will bow out from throwing an error if either of the above situations is detected.
Refs:
* http://php.net/manual/en/function.strip-tags.php
* https://developer.wordpress.org/reference/functions/wp_strip_all_tags/
* http://php.net/manual/en/function.parse-url.php
* https://developer.wordpress.org/reference/functions/wp_parse_url/
=> AlternativeFunctions: improve handling of strip_tags() and parse_url()

WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
Calls to `preg_quote()` should always pass the delimiter, especially when a non-default delimiter is used.
=> PreparedSQLPlaceholders: minor fix

WordPress-Extra/ruleset.xml, WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php, WordPress/Tests/PHP/PregQuoteDelimiterUnitTest.inc, WordPress/Tests/PHP/PregQuoteDelimiterUnitTest.php
New sniff to detect calls to `preg_quote()` which don't pass the delimiter parameter.
The sniff has initially been added to the `Extra` ruleset.
Partially fixes #1371
Related #632
=> New "PregQuoteDelimiter" sniff

WordPress/Sniff.php
=> Remove `get_bookmark()` from the list of auto escaped functions

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
In the original sniff, invalid prefixes would be removed from the `$prefixes` array and not be taken into consideration.
However, hook names don't necessarily need to comply with the PHP naming conventions for function/class/variable names etc. While the WP naming conventions are in line with those, userland code may not use underscores as a word separator.
This minor change makes the sniff more tolerant towards less conventional hook word separators and changes the notice about "invalid prefixes" from an `error` to a `warning`.
=> PrefixAllGlobals: be more tolerant to non-conventional hook name separators

WordPress/Sniff.php
Closures can be declared within function calls when the function expects a call-back.
This situation was only partially handled within the `Sniff::get_function_call_parameters()` method.
Most of the time when a comma is encountered within a closure, it will be at a different nesting level than the original function call/array, which meant it would be disregarded and the method would return the correct results.
However, there are some, albeit rare, situations in which the comma would be at the target nesting level, causing the method to split the closure into two or more "parameters".
As far as I know, this bug has not caused any issues for any of the WPCS sniffs so far, but the situation should be handled correctly even so.
I came across this while working on #1371, the PR for which will …
=> Sniff::get_function_call_parameters(): correctly handle closures when passed as param

WordPress/Sniffs/Arrays/ArrayIndentationSniff.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc, WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed, WordPress/Tests/Arrays/ArrayIndentationUnitTest.php
When a trailing comment would stretch over multiple lines, the fixer went into a fixer conflict loop, trying to fix the same token again and again.
See upstream issue https://github.com/squizlabs/PHP_CodeSniffer/issues/2060 for more information.
=> ArrayIndentation: fix fixer conflict with multi-line trailing comments

README.md, phpcs.xml.dist.sample
Also includes a minor change in the Readme text pertaining to the same PHPCompatibility `testVersion` advice.
=> Example ruleset: update for WPCS 1.0.0 and PHPCompatibility best practices

WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed, WordPress/Tests/WP/I18nUnitTest.php
This builds onto the previously merged fix from PR #1376.
=> I18n: hardening of the "no translatable content" check

WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.inc, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
Inspired by #1236 / #1279.
This PR adds unit tests to safeguard that variable overrides in control structure conditions are detected properly.
The only two cases which were not yet correctly covered were:
```php
foreach ( $something as $pagenow ) {}  // $pagenow was not detected.
foreach ( $something as $pagenow => $menu ) {}  // $pagenow was detected, but $menu wasn't.
```
This PR also adjusts the error message to improve its usefulness by adding information on which WP variable is detected as being overridden, to it.
This is mostly useful when there are several variables assignments on one line, such as in a `foreach( $array as $key => $value )` statement or a multiple variable assignment `$varA = $varB = $varC = false;`.
=> GlobalVariablesOverride: detect WP variable overrides in foreach()

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
_Came across the previous PR while working on the 1.0.0 changelog and realized it was incomplete._
This PR builds onto the previously pulled #1279 which fixed #1236.
The code in the previous PR only took `foreach ( $array as $value )` declarations into account and did not yet cover `foreach ( $array as $key => $value )`.
=> PrefixAllGlobals: improve handling of variable created by global foreach()

WordPress-VIP/ruleset.xml, WordPress/AbstractArrayAssignmentRestrictionsSniff.php, WordPress/AbstractFunctionRestrictionsSniff.php, WordPress/AbstractVariableRestrictionsSniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Sniffs/WP/DiscouragedConstantsSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/ruleset.xml
The `$exclude` property which is included in most abstract sniffs and by extension in all sniffs which use these abstracts, used to expect a comma-delimited list.
This comma-delimited list was then exploded to an array from within the sniff.
In other words, in reality the sniff expected an `array`.
This has now been formalized. All `$exclude` properties now expect `array` input.
As outlined in #1368, this is not a BC-break as properties passed as a comma-delimited string will still be supported (for now). Support for this may be removed at some point in the future.
The upside of making this change is that users who use WPCS 3.3.0, can start using the new property array format in their custom rulesets which makes for a more easily readable ruleset.
Fixes #1368
Testing this PR is a little …
=> Abstracts: change $exclude property from string to array

README.md
Badges offer a quick overview of a project.
* Show `stable` and `unstable` version with their respective build status and last update date.
* Make the minimum supported PHP version and the version the code is tested on, more easily discoverable.
* Show the License and Contributor count more prominently
Notes:
* The `Tested on` badge will need manual updating each time a new PHP version is added to the Travis build matrix, but as this is approximately once a year, I figured that shouldn't be a problem.
* For the badges created via `img.shields.io`, I've noticed that if there are more than a couple, they may not always display properly.
To counter this, I've only used them when there was no good alternative and added a `maxAge` value to the `svg` URLs to try and get the images to cache …
=> README: add a few more badges

WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Tests/WP/CronIntervalUnitTest.inc, WordPress/Tests/WP/CronIntervalUnitTest.php
Allow for comments within the time interval definition.
=> CronInterval: make the sniff more code style independent

WordPress/Sniffs/WP/AlternativeFunctionsSniff.php, WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc, WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
The `AlternativeFunctions` sniff was throwing two different warnings whenever `file_get_contents()` was encountered, one advising to use `wp_remote_get()`, one advising to use the `WP_FileSystem`.
Aside from that, the warning is only really relevant when retrieving a remote URL. Using `file_get_contents()` for local files should not trigger a warning as discussed in #943.
This PR eliminates the notice about using the `WP_FileSystem` in favour of `wp_remote_get()`.
It also adds a parameter check to attempt to determine whether a local or a remote file is being retrieved and eliminates the `warning` when it is clear that `file_get_contents()` is used only to retrieve a local file.
Fixes #943
=> AlternativeFunctions: improve handling of file_get_contents()

.travis.yml
Since PHPCS 3 came out a number of minor versions have been released.
Currently, the builds were only tested for the PHPCS 3.x range against `master` ( currently `3.3.1-alpha`), while PHPCS 3.0.2 is the minimum supported PHPCS 3.x version.
As there have been numerous changes to the tokenizer between 3.0.2 and `master` which could influence the accuracy of the sniff results, the tests should be run against the minimum supported PHPCS 3.x version too.
Unfortunately PHPCS 3.0.2 still contained a bug in the new autoloader which caused a fatal error when unit tests would be run for sniffs in external standards extending other sniffs in the same external standard, so the actual minimum PHPCS 3.x version on which the unit tests can be run is `3.1.0`.
=> Travis: add builds to test against minimum supported PHPCS 3.x version

.phpcs.xml.dist, .travis.yml, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, composer.json
As the code in WPCS itself should be compatible with PHP 5.3 - nightly, why not let the PHPCompatibility standard check this for us ?
Composer:
* Adds `require-dev` section to `composer.json`.
* Adds install path for PHPCompatibility to the default script.
This is only run when WPCS is installed from the root, so only relevant for devs, so adding PHPCompatibility there can be considered "safe".
Note: PHPCS will complain if it is run with this installed path if PHPCompatibility is not installed, i.e. if Composer was run from root with `--no-dev`.
Travis:
* Switches over the Travis script to use Composer to install the dependencies.
- As the bootstraps are already coded to pick up PHPCS when installed in the `vendor` directory, no need for the `PHPCS_DIR` variable anymore.
- As the `phpcs` …
=> Travis/PHPCS: check WPCS own code for PHP cross-version compatibility

WordPress-Extra/ruleset.xml, WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php, WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.inc, WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.php
Follow on from #826
Solves part of #576
Added to the `Extra` ruleset with the other deprecated sniffs. I have added checks for `do_action_deprecated()` and `apply_filters_deprecated()` as they work well in this sniff but I am not sure if they fit in correctly.
=> Check for deprecated parameter values

README.md, composer.json
Since this week, the PHPCompatibility has been moved to a dedicated GitHub organisation account.
A `PHPCompatibilityWP` ruleset is now also available in a separate repo which already excludes all back-fills/poly-fills which WP provides.
For more details, see the [release notes of the PHPCompatibility 8.2.0 release](https://github.com/PHPCompatibility/PHPCompatibility/releases/tag/8.2.0).
:point_right: I was also wondering whether we should start to `suggest` the `PHPCompatibilityWP` ruleset from Composer, usage of which has become easy now it is in its own repo.
=> Composer & Readme: update organisation name PHPCompatibility

.github/CONTRIBUTING.md
... and fix namespace for the example sniff used as the sniff has been moved.
=> Contributing: discourage adding new whitelist comments

WordPress/ruleset.xml
This "hack" works and seems to be the simplest solution to the issue at hand.
**Beware**: just like in the original VIP deprecation, the VIP sniffs are being `exclude`d. This means that if people use the `WordPress` ruleset and in their custom ruleset reference any of the VIP sniffs, they will **not** see the deprecation warning.
Note: This uses `<exclude>` rather than `severity` as in PHPCS 2.9 severity could only be changed on error code level.
Custom rulesets can overrule this  by changing the `severity` of either the category if using PHPCS 3.x or of the error codes when using PHPCS 2.9.
Fixes #1425
Includes a few more spelling fixes in the same ruleset.
=> WordPress ruleset: fix deprecation notices coming through

.phpcs.xml.dist, .travis.yml, bin/class-ruleset-test.php
WPCS itself uses `WordPress-Extra` + `WordPress-Docs` for its CS, which includes `WordPress-Core`.
Those rulesets were therefore "tested" on each build, just by running them against the WPCS code.
However, the WPCS native CS ruleset also excludes some things and the CS check ignores warnings for the Travis run and it also left the `WordPress-VIP` and `WordPress` rulesets _untested_.
This PR intends to fix this by adding a minimal test file which should trigger most sniffs and testing each ruleset against it.
This should, from now on, prevent the ruleset issues we've seen related to the moving and deprecating of sniffs, i.e. #1325  and #1425.
This will also serve as an early warning system in case any of the upstream sniffs which are included in the rulesets would be removed/renamed or …
=> Travis: add a new check for early detection of ruleset problems

CHANGELOG.md
As discussed: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1423#discussion_r202716538
[ci skip]
=> Changelog: bring back `unreleased` section

.travis.yml
PR #1415 switched Travis over to using Composer to install the dependencies.
This now adds caching for the packages composer downloads to speed up the build process.
=> Travis: cache composer downloads

README.md
See screenshot for before/after:
=> Use SVG icons for Travis CI badges

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
When a project which wasn't using WPCS, starts to use it or when an project upgrades to WPCS > 0.12.0, one of the things the project most likely will run into is the prefixing of all globals.
When no prefixes are passed, the sniff will not throw any errors.
However, if the project does want to comply and wants to add a prefix configuration, it would be useful to get some insight into which prefixes are currently in use in a project and how often each is used to determine what prefixes to allow and/or what prefixes to consolidate.
PHPCS offers a metrics mechanism which can be used for this, the results of which can be viewed using the `--report-info` argument.
This PR takes advantage of that metrics report to:
1. Report on the frequency each of the allowed prefixes is used
2. Report on …
=> PrefixAllGlobals: add recording of metrics

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
This sniff has been in the [WP Core native custom ruleset](https://core.trac.wordpress.org/browser/trunk/phpcs.xml.dist) from the start as it was essential for the auto-fixers to work properly.
This PR now formalizes this by adding the sniff to the `WordPress-Core` ruleset.
The sniff was added to WPCS in PR #980 in response to issue #975.
The sniff checks for the following violations:
* Two semi-colons with no executable code in between.
* An empty PHP open - close tag combination.
The sniff has also been pulled to PHPCS upstream in https://github.com/squizlabs/PHP_CodeSniffer/pull/1814 (PR opened in December 2017 and still open).
/cc @pento
=> Move the WPCS `WordPress.CodeAnalysis.EmptyStatement` from `Extra` to `Core`

WordPress-Core/ruleset.xml, WordPress/PHPCSAliases.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
The `allowMultipleArguments` property of the `PEAR.Functions.FunctionCallSignature` sniff defaults to `true`.
By setting it to `false`, the sniff behaviour changes and demands that there is just one parameter on each line in a multi-line function call.
The behaviour for single-line function calls is not affected by this change.
This property has been added to the WP Core native custom ruleset in [changeset 43571](https://core.trac.wordpress.org/changeset/43571) as part of [trac ticket 44600](https://core.trac.wordpress.org/ticket/44600).
This PR now formalizes this by adding the property to the `WordPress-Core` ruleset.
Note: The WP Core handbook still needs to be adjusted to mention this change!
While this is a significant change, IMHO it is not a *breaking* change, but an enhancement, …
=> Core ruleset: change behaviour for the `PEAR/FunctionCallSignature` sniff

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml, WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php, WordPress/Tests/PHP/NoSilencedErrorsUnitTest.inc, WordPress/Tests/PHP/NoSilencedErrorsUnitTest.php
Until now, WPCS used the PHPCS native `Generic.PHP.NoSilencedErrors` sniff. This sniff would throw warnings for all uses of the `@` error silencing operator. However, there are a number of PHP functions for which the use of the error silencing operator is warranted as no amount of error checking can prevent warnings from being thrown.
This PR adds a new WPCS native `PHP.NoSilencedErrors` sniff which will:
* not throw warnings when the error silencing operator is used in combination with one of the whitelisted functions.
* throw warnings in all other cases.
* allows for a user-defined list of additional whitelisted functions to be passed via a custom ruleset.
* displays a brief snippet of code to show the context in which the error silencing operator is being used.
To get to the current …
=> New WPCS native `NoSilencedErrors` sniff

composer.json
Also allows the functionality to be run directly (`composer install-codestandards`) instead of having to do a full `composer install` or `composer update`.
=> Composer: Make script DRY

WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.3.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
While since #883, the `Sniff::is_test_class()` method already allowed for anonymous classes, the `Sniff::is_token_in_test_method()` did not.
Also, as OO structures can be nested in PHP, all relevant structures within which the test method is nested should be examined, not just the first encountered.
Note: examination of nested extended classes based on the class they extend is currently afflicted by a bug in PHPCS itself. I expect the bugfix I pulled for that to be included in the 3.3.2 release.
See: https://github.com/squizlabs/PHP_CodeSniffer/pull/2127
This PR also adjusts the `PrefixAllGlobals` sniff to allow for anonymous test classes and traits extending test classes. Includes unit tests for this particular change.
=>  Sniff::is_token_in_test_method(): allow for anonymous classes

WordPress-Docs/ruleset.xml, WordPress-Extra/ruleset.xml
While this sniff analyses comments, it is *not* a documentation related sniff, but rather a best practice sniff, so IMO, it should be in the `Extra` ruleset, not in the `Docs` ruleset.
The PHPCS default for the `maxPercentage` property is 35%.
This was previously upped in WPCS to 45% to prevent false positives for the `// End ...` comments.
However, as that rule and the associated sniff, have been removed, a lower value should be fine.
As a test case, I've ran the sniff over the `wp-admin` directory of WP Core and it looks like 40% should strike a good balance.
* Some of what was found in core was correctly identified commented out.
* Some were `// end` comments which should probably be removed.
* Some were just very non-descriptive inline comments which should be improved.
If needs be, …
=> Move CommentedOutCode check from Docs to Extra

WordPress/Sniff.php
* Only declare the array once.
* Use `isset()` instead of `in_array()`
=> Sniff::is_safe_casted(): minor efficiency fixes

WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.1.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
Inline HTML can contain javascript `<script>` blocks, which in turn can contain multi-line `/* */` style comments.
This sniff should not throw errors for those.
The implemented solution is quite simplistic, but determining whether or not we are within a `<script>` block can be quite complicated as - what with going into and out of PHP - the opener or closer may be in a PHP `echo` statement.
The simple solution implemented now may cause some false negatives, but that is preferable over false positives in this case.
=> PrecisionAlignment: prevent false positive for inline javascript comments

WordPress/Sniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
Includes unit tests in the ValidatedSanitizedInput test case file.
Relates to #763
=> Sniff::is_in_isset_or_empty(): improve code-style independence

.gitignore
These _ignores_ are not project specific, but user specific as they depend on which IDE the developer is using.
With that in mind, they should be added to the developer's `.git/info/exclude` file and don't belong in the project `.gitignore` file.
=> .gitignore: remove IDE specific files/folders

WordPress/Sniff.php, WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
Whether single or double quotes are used for the array key shouldn't matter as long as the array key itself matches.
Fixes #1467
=> ValidatedSanitizedInput: bug fix different quote style array keys

WordPress-Core/ruleset.xml, WordPress/Sniffs/PHP/TypeCastsSniff.php, WordPress/Tests/PHP/TypeCastsUnitTest.inc, WordPress/Tests/PHP/TypeCastsUnitTest.inc.fixed, WordPress/Tests/PHP/TypeCastsUnitTest.php
This sniff will check that PHP type casts are:
- lowercase;
- short form, i.e. (bool) not (boolean);
- normalized, i.e. (float) not (real).
The sniff also discourages the use of the `(unset)` and the `(binary)` casts, including the `b"$string"` binary cast, though it is susceptible to bug squizlabs/PHP_CodeSniffer#1574.
The sniff has been added to the `WordPress-Core` ruleset.
Once the minimum PHPCS version has gone up to PHPCS 3.3.0+, the lowercase check part of the sniff can be removed in favour of adding the `Generic.PHP.LowerCaseType` sniff  to the ruleset instead.
Fixes #1481
=> Core: New sniff to examine type casts

WordPress-Core/ruleset.xml
Sync the inline documentation with the texts as currently in the [WP Core handbook](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/).
=> Core ruleset: update inline documentation

composer.json
This commit adds two additional scripts and adjusts the existing one.
The additional scripts are just shortcuts to run `phpcs` and `phpcbf`.
The more important change is how the scripts are run - using the `@php` prefix ensures that the scripts are run against the same PHP version as with which Composer is called, instead of against the system default PHP version.
This is important if - as a WPCS dev - you change the PHP version for Composer to be able to test things against different PHP versions.
Ref: https://github.com/composer/composer/issues/7645
=> Composer: various tweaks

composer.json
Uses https://github.com/localheinz/composer-normalize to normalize the order and whitespace inside the `composer.json`.
No functional differences.
=>  Composer: Normalize composer.json

.phpcs.xml.dist, CHANGELOG.md, WordPress/Sniff.php, WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, composer.json, phpcs.xml.dist.sample
[PHPCompatibility 9.0.0](https://github.com/PHPCompatibility/PHPCompatibility/releases/tag/9.0.0) has just been released and renames all sniffs.
* Updated the version restrictions in `composer.json`.
As the sniff names have changed, set minimum version.
Note: PHPCompatibility 9.0.0 is still compatible with PHPCS 2.3.0 up to current, so this doesn't make a difference for running the CS check.
* Updated the WPCS native PHPCS ruleset for the new PHPCompatibility sniff codes.
* Updated the inline annotations for the new PHPCompatibility sniff codes.
* Updated the `phpcs.xml.dist.sample` to favour the `PHPCompatibilityWP` ruleset (was missed in PR #1426).
* Updated a few more links to the PHPCompatibility repo for the move to an organisation (which were missed in PR #1426).
=> Update for PHPCompatibility 9.0.0

WordPress/Sniff.php, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.4.inc
A namespace declaration can contain whitespace and comments and PHP will just ignore the whitespace and comments when reading the code. Also see: squizlabs/PHP_CodeSniffer#2150
While it is rare to encounter such code, this utility method should handle it correctly.
As for the `$namespaceName` to be returned by the method, this should not contain any whitespace or comments encountered. That way the namespace name will be "clean" for examination by sniffs.
Includes unit test via the `GlobalVariablesOverride` sniff.
=> Sniff::get_declared_namespace_name(): improve code-style independence

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
While the word "WordPress" can be used as _part of a prefix_, the word on its own should not be allowed as a prefix.
=> PrefixAllGlobals: add "WordPress" to the prefix blacklist

WordPress/Sniff.php
The whitelist comment for a sniff will often be (part of) the sniff name. This causes issues with inline coding standards setting changes which mention the sniff name and can therefore be confused with whitelist comments.
Think: whitelist comment `prefix` for the `PrefixAllGlobals` sniff where the sniff name would be mentioned in the setting change annotation.
While this is mainly an issue for the unit tests, the `has_whitelist_comment()` method should handle this correctly and ignore coding standards setting change comments.
Loosely related to #1492 / e1026802fe1dc5a4b7ed7b1b15d0ed1331008b58
=> Sniff::has_whitelist_comment(): ignore CS settings change comments

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.4.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
Until now, namespaced classes, functions and constants would be exempt from the "prefix all globals" rule, but the namespace name _itself_ was not examined.
As namespace names can, of course, also conflict, the namespace name should be prefixed with a plugin/theme specific prefix.
This PR adds that feature to the sniff. The PR builds onto the changes made in PR #1491 and #1492.
Notes:
* The sniff allows for underscores and (other) non-word characters in a passed prefix to be converted to namespace separators when used in a namespace name.
In other words, if a prefix of `my_plugin` is passed as the value of the custom property, a namespace name of `My\Plugin` will be accepted automatically.
* Passing a prefix property value containing namespace separators will now also be allowed and will …
=> PrefixAllGlobals: verify that namespace names use a prefix

WordPress/Tests/PHP/TypeCastsUnitTest.inc, WordPress/Tests/PHP/TypeCastsUnitTest.inc.fixed, WordPress/Tests/PHP/TypeCastsUnitTest.php, WordPress/Tests/PHP/YodaConditionsUnitTest.inc, WordPress/Tests/PHP/YodaConditionsUnitTest.php, WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.inc, WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.php
A fix for upstream issue squizlabs/PHP_CodeSniffer#1574 - tokenize binary casts as `T_BINARY_CAST` - has been committed to PHPCS and will be included in the PHPCS 3.4.0 release.
* The upstream change fixes a false negative in the `PHP.TypeCasts` sniff.
* There are two more sniffs which look at cast tokens `PHP.YodaConditions` and `WP.EnqueuedResourceParameters`.
- For the first, I've just added a unit test documenting the behaviour.
- For the second, I realized that while the sniff handled cast tokens, this specific situation wasn't tested at all. So I've added tests to that effect, including tests using binary casts.
=> Compatibility-fix for PHPCS 3.4.0

WordPress/Sniff.php, WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
When a class would be nested in parenthesis, the method did not recognize class properties properly.
To check for this without code duplication, the return of the `Sniff::valid_direct_scope()` method has changed. It used to always return a boolean. Now it will return `false` if not in a valid direct scope and the `$stackPtr` to the scope if it is.
Just like the rest of these methods, unit tested in the PHPCompatibility standard.
See also these issues for the same fix elsewhere:
* PHPCompatibility/PHPCompatibility#758
* squizlabs/PHP_CodeSniffer#2214
This fixes the false positive for line 124 in the `GlobalVariablesOverrideUnitTest.1.inc` test file.
=> Sniff::is_class_property: bug fix

WordPress/Sniffs/PHP/TypeCastsSniff.php, WordPress/Tests/PHP/TypeCastsUnitTest.inc, WordPress/Tests/PHP/TypeCastsUnitTest.inc.fixed, WordPress/Tests/PHP/TypeCastsUnitTest.php
Type casts can have spaces within the cast structure. The upstream `Squiz.WhiteSpace.CastSpacing` sniff in the `Core` ruleset guards against this.
However, the `WordPress.PHP.TypeCasts` should function independently of that sniff and should not throw errors (false positives) for type casts using the correct short form, but with superfluous whitespace within the parentheses.
This PR fixes this. Includes unit tests.
=> WordPress.PHP.TypeCasts: recognize casts independently of inside cast spacing

WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php, WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.inc.fixed, WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.php
Given the following test code:
```php
<?php
$a = (bool) $b;
$a = (bool)$b;
$a = (bool)       $b;
```
The current sniffs/ruleset would result in the following errors related to cast spacing:
```
3 | ERROR | [x] No space after closing casting parenthesis is prohibited
|       |     (WordPress.WhiteSpace.CastStructureSpacing.NoSpaceAfterCloseParenthesis)
3 | ERROR | [x] A cast statement must be followed by a single space
|       |     (Generic.Formatting.SpaceAfterCast.NoSpace)
4 | ERROR | [x] A cast statement must be followed by a single space
|       |     (Generic.Formatting.SpaceAfterCast.TooMuchSpace)
```
The errors for line 3 are basically duplicates.
Additionally, as shown by line 4, as the upstream sniff also checks the width of the space after a type cast, that sniff is the better …
=> Fix duplicate error being thrown / space after cast

WordPress/Sniff.php
As the `T_PHPCS_SET` token was only introduced in PHPCS 3.2.0, the check should be done against `type`, which is a string, not `code`, which is the integer constant.
The `type` part was correct, the `string` part wasn't.
Bug introduced in PR #1493 and not yet in any released version.
=> Sniff::has_whitelist_comment(): Minor bug fix

WordPress/Sniffs/CodeAnalysis/EmptyStatementSniff.php, WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.1.inc, WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.1.inc.fixed
Prevent the `WordPress.CodeAnalysis.EmptyStatement` sniff from triggering on two consecutive _semi_-colons in a `for()` statement.
=> CodeAnalysis/Emptystatement: bug fix

README.md, WordPress-VIP/ruleset.xml, WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php, WordPress/Sniffs/DB/SlowDBQuerySniff.php, WordPress/Sniffs/PHP/StrictInArraySniff.php, WordPress/Sniffs/Security/PluginMenuSlugSniff.php, WordPress/Sniffs/VIP/AdminBarRemovalSniff.php, WordPress/Sniffs/VIP/CronIntervalSniff.php, WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php, WordPress/Sniffs/VIP/FileSystemWritesDisallowSniff.php, WordPress/Sniffs/VIP/OrderByRandSniff.php, WordPress/Sniffs/VIP/PluginMenuSlugSniff.php, WordPress/Sniffs/VIP/PostsPerPageSniff.php, WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPress/Sniffs/VIP/RestrictedVariablesSniff.php, WordPress/Sniffs/VIP/SessionFunctionsUsageSniff.php, WordPress/Sniffs/VIP/SessionVariableUsageSniff.php, WordPress/Sniffs/VIP/SlowDBQuerySniff.php, WordPress/Sniffs/VIP/TimezoneChangeSniff.php, WordPress/Sniffs/WP/CronIntervalSniff.php, WordPress/Sniffs/WP/PostsPerPageSniff.php, WordPress/Sniffs/WP/TimezoneChangeSniff.php
The WordPress.com VIP team moved their coding standards documentation around, since they now have different documents for their different platforms:
- [WPCOM platform](https://lobby.vip.wordpress.com/wordpress-com-documentation/code-review-what-we-look-for/) (only available to those with VIP Lobby access)
- [VIP-Go platform](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)
Many of the existing link references were out of date and pointed to pages or page anchors that didn't exist. Since our `WordPress-VIP` standard is deprecated, and will be removed in `2.0.0`, it's easier to remove all of the link references in the `VIP` category ruleset and sniffs. I've added links to the above two pages into the ruleset.
The only references that remain are ones …
=> Docs: Remove and update VIP link references

CHANGELOG.md, README.md, WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php, WordPress/Sniffs/WP/I18nSniff.php, WordPress/Tests/WP/I18nUnitTest.1.inc, WordPress/Tests/WP/I18nUnitTest.1.inc.fixed
Only strings, comments and documentation was changed.
Instances inside test files were not touched.
Fixes #1526.
(We have no instance of any variation of meta box.)
=> Wording: Change text-domain to text domain

WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.2.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7a.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7b.inc, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7c.inc
This issue was discovered through a report upstream in issue squizlabs/PHP_CodeSniffer#2179#issuecomment-437634372.
What it comes down to is that if the `ignoreAlignmentTokens` property would be set, the `merge_custom_array()` call in the `process_token()` would override it with a flipped array with values `false` and for the next file, would override it again, flipping the array again etc etc.
This in effect made the custom property only work for the first file, not for subsequent files.
Includes unit tests to guard against the issue.
Additionally, I've improved the inline comments to clarify what's being tested in test case file 2.
=> PrecisionAlignment: bug fix

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc, WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
... for hook names and constant names when declared using `define()`.
The sniff would throw the error message on the line which contained the first token regarded as part of the parameter - which might be end of line whitespace on the line before the actual hook name or constant name  in a multi-line function call.
This minor change improves the line number precision for these situations.
Fixed #1495
=> PrefixAllGlobals: improve error position precision

WordPress/Sniff.php, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc, WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php, WordPress/Tests/WP/DeprecatedParametersUnitTest.inc, phpcs.xml.dist.sample
The minimum version should be three versions behind the latest WP release, so what with 5.0 having come out last week, it should now be 4.7.
I've used @JDGrimes 's deprecated code scanner and done a scan against the `5.0` tag for functions deprecated in WP 5.0 and this came up empty, so we should be good.
Running the tool against `trunk` *does* throw up some new deprecated functions, but I suspect that the documentation of those needs to be adjusted to `5.1`, what with the non-standard way in which `5.0` was eventually committed with `trunk` closed, while it already contained commits.
This has been reported in: https://core.trac.wordpress.org/ticket/45657
=> Update default minimum_supported_version to WP 4.7

WordPress-Docs/ruleset.xml
* Move one exclusion into a block of exclusions for the same sniff.
* Exclude a complete sniff where all errorcodes from that sniff were excluded anyway.
=> Docs ruleset: Minor tweaks

CHANGELOG.md
* Release date set at this **Tuesday December 18th**.
[ci skip]
=> Changelog for WPCS version 1.2.1

WordPress/Sniff.php
This method was used by the `AdminBarRemoval` sniff which has since been removed.
It was previously deprecated in WPCS 1.0.0 along with the sniff.
=> WPCS 2.0.0: Remove deprecated Sniff::has_html_open_tag() method

WordPress/Sniffs/Security/NonceVerificationSniff.php
While cleaning up a plugin, I noticed that the issue count for the `WordPress.Security.NonceVerification.NoNonceVerification` error code was different if I ran phpcs with the `-n` flag (no warnings).
Error codes should be unique. Having the same error code for something which is mandatory (`error`) and recommended (`warning`) is bad practice and does not properly allow for modular disabling of notices.
This PR fixes this.
As the error code is changing anyhow, I figured it made sense to also remove the duplication of the sniff name from the code.
This is a breaking change as `<exclude>`s for the old errorcode currently in custom rulesets will be invalidated by it, as well as inline annotations using the error code, so this PR should go into WPCS 2.0.0.
N.B.: The ruleset change is only …
=> NonceVerification: use separate errorcodes for warning vs error

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
While cleaning up a plugin, I noticed that the issue count for the `WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound` error code was different if I ran phpcs with the `-n` flag (no warnings).
Error codes should be unique. Having the same error code for something which is mandatory (`error`) and recommended (`warning`) is bad practice and does not properly allow for modular disabling of notices.
This PR fixes this.
This is a breaking change as for the warnings, `<exclude>`s for the old errorcode currently in custom rulesets will be invalidated by it.
=> PrefixAllGlobals: use separate errorcodes for warning vs error

WordPress/Sniffs/Security/EscapeOutputSniff.php, WordPress/Sniffs/WhiteSpace/ArbitraryParenthesesSpacingSniff.php, WordPress/Tests/Arrays/ArrayIndentationUnitTest.php, WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.php, WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.php, WordPress/Tests/Files/FileNameUnitTest.php, WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.php, WordPress/Tests/WP/I18nUnitTest.php, WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php, WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.php, WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
This just removes small inline code work-arounds for PHP 5.3 / PHPCS < 3.3.1 wherever I could find them.
=> WPCS 2.0.0: Remove work-arounds for PHP < 5.4 and PHPCS < 3.3.1

WordPress/PHPCSHelper.php
While strictly speaking the `PHPCSHelper` class is no longer needed at this moment, PHPCS 4.x may again contain breaking changes, so leaving it in place as a cross-version compatibility layer makes sense.
All the same, the PHPCS 2.x specific code can now be removed.
=> WPCS 2.0.0: Remove PHPCS 2.x code from PHPCSHelper class

WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
Interfaces can extend multiple other interfaces. Looking at the sniff code, no changes are needed in the sniff to account for this, however, adding an additional unit test to warrant against sniff changes in the future which may not take this into account.
N.B.: I've verified all other usages of the `T_INTERFACE` token in the whole of WPCS and this was the only one which looked at `extends/implements`, so the only one for which interfaces extending multiple other interfaces could be problematic.
See:
* http://php.net/manual/en/language.oop5.interfaces.php#example-208
Loosely related to:
* https://github.com/squizlabs/PHP_CodeSniffer/pull/2128
Fixes #1459 (which is effectively the same PR)
=> ValidFunctionName: Add additional unit test for interfaces extending multiple interfaces

WordPress-Core/ruleset.xml, WordPress-Extra/ruleset.xml
As of PHPCS 3.0.0, you can include individual error codes, not just complete sniffs.
Where WPCS rulesets included sniffs, but excluded more than 50% of the error codes from that sniff, it makes sense to switch them over to include individual error codes instead.
This also means that where previously, if the `type` and/or `message` of an individual error code was adjusted via the ruleset, the sniff needed to be included first and only after that, the details could be adjusted.
Now, the inclusion can just be done based on error code, providing all error codes in the sniff are adjusted.
To explain it better:
* If a sniff contained five error codes and we adjusted the message for one, there is no real advantage to changing over.
* If a sniff contained three error codes and we excluded one, …
=> Rulesets: minor simplifications (PHPCS 3.0+)
