WordPress/WordPress-Coding-Standards

README.md

Thought this worth it, given I also experienced this issue and it took some time to figure out the cause: 
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/273

Update README.md - reminder to update phpcs

---

WordPress/Sniffs/PHP/DiscouragedFunctionsSniff.php
WordPress/Tests/PHP/DiscouragedFunctionsUnitTest.inc
WordPress/Tests/PHP/DiscouragedFunctionsUnitTest.php

Encourage using wp_json_encode() instead of json_encode()

---

WordPress/Sniffs/PHP/StrictComparisonsSniff.php
WordPress/Tests/PHP/StrictComparisonsUnitTest.inc
WordPress/Tests/PHP/StrictComparisonsUnitTest.php

Sniffs and Unit Tests for Strict Comparisons so === not == and !== not
!=
Replaces ticker #243 that got scrubbed inadvertently

Strict Comparisons

---

CONTRIBUTING.md

Make a note about sniffs code standards

---

WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php
WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc

Whitelisting covers sanitization only. Validation can't be whitelisted away.
Fixes #293

Support whitelisting for input sanitization

---

.travis.yml

See http://docs.travis-ci.com/user/workers/container-based-infrastructure/.

Use container-based infrastructure for Travis

---

WordPress/Sniffs/XSS/EscapeOutputSniff.php

See https://github.com/fusioneng/Shortcake/pull/290#discussion_r28883624

Add wp_parse_id_list() to sanitizing functions

---

README.md
composer.json

See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/378#issuecomment-98499800.

Update comment about required phpcs version

---

WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.inc.fixed

Make ArrayKeySpacingRestrictions errors fixable

---

project.ruleset.xml.example

Ignore twig files for scanning

---

WordPress/Sniff.php

Add nl2br() to the list of formatting functions

---

WordPress/Sniffs/PHP/StrictComparisonsSniff.php
WordPress/Sniffs/PHP/YodaConditionsSniff.php
WordPress/Sniffs/VIP/PluginMenuSlugSniff.php
WordPress/Sniffs/VIP/SessionVariableUsageSniff.php
WordPress/Sniffs/Variables/GlobalVariablesSniff.php

Add error codes to all messages

---

WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc
WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed

Don't enforce closure open paren spacing by default

---

WordPress/Sniffs/VIP/OrderByRandSniff.php
WordPress/Tests/VIP/OrderByRandUnitTest.inc
WordPress/Tests/VIP/OrderByRandUnitTest.php

Add WordPress.VIP.OrderByRand

---

WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php
WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc
WordPress/Tests/VIP/RestrictedFunctionsUnitTest.php

Update Uncached Functions in WordPress.VIP.RestrictedFunctions

---

WordPress-Extra/ruleset.xml
WordPress-VIP/ruleset.xml
WordPress/Sniffs/PHP/StrictInArraySniff.php
WordPress/Tests/PHP/StrictInArrayUnitTest.inc
WordPress/Tests/PHP/StrictInArrayUnitTest.php

Introduce WordPress.PHP.StrictInArray for WordPress-VIP

---

WordPress/Sniff.php

Add wp_handle_upload() to sanitizing functions

---

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc

Also fixes message error.
Fixes #502

Remove PrivateNoUnderscore and PublicHasUnderscore from ValidVariableName

---

WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php
WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc
WordPress/Tests/VIP/RestrictedFunctionsUnitTest.php

See https://vip.wordpress.com/documentation/code-review-what-we-look-for/#use-wp_parse_url-instead-of-parse_url

Add parse_url to WordPress.VIP.RestrictedFunctions

---

README.md

:rainbow: Hope you like pictures! :rainbow:

Add Atom Linter instructions to README

---

README.md

Atom with linting ended up being insanely slow. SublimeLinter ain't as pretty but it gets the job done. =)

Add SublimeLinter-phpcs installation instructions

---

WordPress/Sniffs/WP/I18nSniff.php
WordPress/Tests/WP/I18nUnitTest.inc

Merge multi-line string literal tokens into single token

---

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc
WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php

Include cat_ID among whitelisted names for ValidVariableName sniff

---

WordPress-Core/ruleset.xml
WordPress-Docs/ruleset.xml

Ignore Squiz.Commenting.FunctionComment.ScalarTypeHintMissing

---

WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php

Per https://secure.php.net/manual/en/language.oop5.magic.php

Add debugInfo

---

WordPress-Core/ruleset.xml

Remove redundant sniff.

---

WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php

Also unduplicated error data in same sniff.

Fix one error missing identifier.

---

CHANGELOG.md

:warning: **Needs careful review!!!!!**
I've done a walk through of the first three pages of the closed PRs which AFAICS covers the merged PRs since Feb 1 when the last release was tagged.
I have *not* gone through the individual commits in the 0.10.0 PR branch.
Changes/adjustments to sniffs new to this release have not been listed individually.
@WordPress-Coding-Standards/admins Everyone, please carefully check through the list for:
* missed contributions
* correct description of the changes
* anything else which should be in the changelog
Please feel free to push directly to this branch to update it with your additions/changes.

(Preliminary) Changelog for the 0.10.0 version

---

WordPress/Sniffs/WP/I18nSniff.php
WordPress/Tests/WP/I18nUnitTest.inc
WordPress/Tests/WP/I18nUnitTest.inc.fixed

[I18n sniff] Disregard %% for placeholder numbering.

---

WordPress/AbstractArrayAssignmentRestrictionsSniff.php
WordPress/AbstractClassRestrictionsSniff.php
WordPress/Sniff.php
WordPress/Sniffs/Arrays/ArrayDeclarationSniff.php
WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
WordPress/Sniffs/PHP/YodaConditionsSniff.php
WordPress/Sniffs/VIP/CronIntervalSniff.php
WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php
WordPress/Sniffs/VIP/PluginMenuSlugSniff.php
WordPress/Sniffs/Variables/GlobalVariablesSniff.php
WordPress/Sniffs/WP/I18nSniff.php
WordPress/Sniffs/WP/PreparedSQLSniff.php
WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
WordPress/Sniffs/XSS/EscapeOutputSniff.php

Ran the codebase through Scrutinizer and applied a lot of quick fixes based on the feedback. Mostly variable type checks and potential type juggling issues.

Various fixes based on Scrutinizer input.

---

README.md

Was looking through stats and thought 74K and growing is quite a nice number of downloads to showcase with a badge. :)

Added downloads count badge to readme

---

WordPress/Sniff.php
WordPress/Tests/VIP/ValidatedSanitizedInputUnitTest.inc

See #721 
I'm not sure if this is right or not, so definitely needs a review please.

Add wp_strip_all_tags() as a sanitising function

---

README.md

Add link to tutorial about using PHPCS + WPCS in Visual Studio to the readme

---

README.md

Add a bit more information to the subset and add a link to the inline docs handbook
props to @GaryJones from https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/676#issuecomment-269079082

Improve documentation on subsets

---

README.md

For now, it only covers running WPCS on Travis without using Composer.
I imagine that in the future sub-sections might be added for Circle CI, Srutinizer etc.
Fixes #712

Add section about integration with CI tools to the Readme.

---

WordPress/AbstractFunctionRestrictionsSniff.php
WordPress/Sniffs/WP/PreparedSQLSniff.php
WordPress/Tests/PHP/DiscouragedPHPFunctionsUnitTest.inc
WordPress/Tests/Variables/GlobalVariablesUnitTest.inc
WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
WordPress/Tests/WP/I18nUnitTest.1.inc
WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc
WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed

(and some minor spacing issues)

Fix unintended parse errors in test files.

---

WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php

That's what the `$fix` return value is for.

Remove unnecessary checks for `$phpcsFile->Fixer`

---

README.md

Time to update the readme to give credit to the incredible surge of activity over the past year and ongoing.

Update project history

---

CONTRIBUTING.md
README.md

Update README and CONTRIBUTING regarding the new properties wiki page.

---

WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php
WordPress/Tests/VIP/DirectDatabaseQueryUnitTest.inc
WordPress/Tests/VIP/DirectDatabaseQueryUnitTest.php

DirectDatabaseQuery: Allow for heredoc and nowdoc.

---

WordPress/Sniffs/WP/I18nSniff.php
WordPress/Tests/WP/I18nUnitTest.inc
WordPress/Tests/WP/I18nUnitTest.inc.fixed
WordPress/Tests/WP/I18nUnitTest.php

More importantly, add unit tests for these syntaxes.

I18n: Add limited support for heredoc and nowdoc recognition.

---

WordPress/AbstractArrayAssignmentRestrictionsSniff.php
WordPress/AbstractClassRestrictionsSniff.php
WordPress/AbstractVariableRestrictionsSniff.php
WordPress/Sniff.php
WordPress/Sniffs/PHP/YodaConditionsSniff.php
WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php
WordPress/Sniffs/VIP/SessionVariableUsageSniff.php
WordPress/Sniffs/Variables/GlobalVariablesSniff.php
WordPress/Sniffs/WP/I18nSniff.php
WordPress/Sniffs/WP/PreparedSQLSniff.php
WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php
WordPress/Sniffs/XSS/EscapeOutputSniff.php

Collection of minor code tweaks which I picked up along the way over the last few days.

Various minor tweaks

---

README.md

Update PHPStorm documentation link in readme.

---

WordPress/Sniff.php
WordPress/Sniffs/VIP/CronIntervalSniff.php
WordPress/Sniffs/WP/PreparedSQLSniff.php
WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php

Some:
* Minor documentation fixes
* Efficiency fixes
* Error notice prevention fixes
* Minor code simplification

Various minor code fixes.

---

WordPress/Sniffs/Files/FileNameSniff.php

Trim Quotes (single and double) from $file.

---

WordPress/Sniffs/WP/CapitalPDangitSniff.php
WordPress/Tests/WP/CapitalPDangitUnitTest.inc
WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed

Don't fix capitalisation for "wordpress.pot"

---

README.md

I have fixed Some minor changes for "#Project history" content in  README.md file

Fix Project history content minor changes in README.md file

---

CHANGELOG.md

Changelog for the 0.12.0 release.

---

README.md

... to reflect the current state of the `wp-load.php` file in combination with the current WPCS sniffs.

Readme: Update the example output

---

CONTRIBUTING.md

While rewriting the text in the `Contributing.md` document regarding the unit tests, I noticed some more room for improvement.

Minor textual improvements to the Contributing.md document

---

README.md

While updating the text in the `Readme.md` document regarding the PHPCS 3.x compatibility, I noticed some more room for improvement.

Minor textual improvements to the Readme.md document

---

Test/phpcs2-bootstrap.php
Test/phpcs3-bootstrap.php

Old habits die hard ;-)
Part of 0.13.0 as it touches code which I introduced in a previous PR for this release.

Minor code style fix

---

README.md

See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1077#discussion_r130726631

Fix the version recommendation

---

WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php

Copy/paste artifact which is not needed in the version which was merged.

PrecisionAlignment: remove unused variable

---

Test/phpcs2-bootstrap.php
Test/phpcs3-bootstrap.php
WordPress-Extra/ruleset.xml

As discussed in #1143 
Closes #1143 
Closes #1007

[Extra] Add PEAR.Files.IncludingFile sniff

---

WordPress/Sniff.php

Came across these along the way.

Add some missing `@since` tags

---

.github/CONTRIBUTING.md
phpunit.xml.dist

Contributing: update info about unit testing

---

README.md

Fixes broken markdown syntax for an internal link at README.md

Fix markdown link at README.md

---

WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php

The error message was suffering from exactly the same as it was reporting... :facepalm:

PreparedSQLPlaceholders: Fix unclear error message

---

WordPress/Sniffs/PHP/YodaConditionsSniff.php
WordPress/Tests/PHP/YodaConditionsUnitTest.inc
WordPress/Tests/PHP/YodaConditionsUnitTest.php

This is a quick fix which seems to work well (see the unit tests), but more unit tests are welcome as I haven't studied it in-depth (and am keeping my fingers crossed it doesn't break the sniff for another exotic case).
Fixes #1181

YodaConditions: fix issue 1181 - complex ternary

---

WordPress/Sniffs/Files/FileNameSniff.php

Minor textual documentation change

---

WordPress/Sniffs/XSS/EscapeOutputSniff.php

As discussed in #1166, this PR adapts the message when using an unsafe printing function.

Adapt message for unsafe printing functions.

---

.github/CONTRIBUTING.md

Fixed config key for setting the installed path in php code sniffer.
https://github.com/squizlabs/PHP_CodeSniffer/blob/9caf0f199eabdaf30d1142f203312fd7252a115e/src/Config.php#L1609

Fixed: change installed_path to installed_paths in contribution doc.

---

WordPress/Sniffs/WP/I18nSniff.php
WordPress/Tests/WP/I18nUnitTest.1.inc
WordPress/Tests/WP/I18nUnitTest.1.inc.fixed

I18n: fix bug when translatable content is numeric zero

---

Test/phpcs3-bootstrap.php
WordPress-Core/ruleset.xml
WordPress/Sniff.php
WordPress/Sniffs/Security/EscapeOutputSniff.php

Various minor fixes which I came across along the way.

Various minor fixes

---

WordPress/Sniffs/DB/PreparedSQLSniff.php
WordPress/Tests/DB/PreparedSQLUnitTest.inc

PreparedSQL: make the sniff more code style independent

---

WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc
WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc.fixed

Fix false positive violation for return type colon

---

WordPress-Core/ruleset.xml
WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
WordPress/Sniffs/Functions/FunctionCallSignatureNoParamsSniff.php
WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php

Don't you just love renamed URLs without redirection ?

Fix links to the Core handbook

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/dependency-change.md
.github/ISSUE_TEMPLATE/feature_request.md

Create issue templates

---

CHANGELOG.md

* Release date set at this Monday **November 12th**.

Change log for WPCS version 1.2.0

---

WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
WordPress/Sniffs/Security/EscapeOutputSniff.php
WordPress/Sniffs/Security/NonceVerificationSniff.php

WPCS 2.0.0: Remove deprecated properties

---

.github/CONTRIBUTING.md

Contributing: update the documentation about installing and running the unit tests

---

WordPress/Sniffs/WP/DeprecatedClassesSniff.php
WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php

You learn something new every day. Never came across this function before, but simplifies a few code snippets.
Ref: https://php.net/manual/en/function.array-change-key-case.php

Clean up: use array_change_key_case()

---

CHANGELOG.md

* Release date set at this **Tuesday May 21st**.
Reviews & approval welcome. I'll merge this myself (if approved) just before the release.

Changelog for WPCS 2.1.1

---

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php

Add RECOVERY_MODE_COOKIE to whitelisted core constants

---

WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php

Fixes #1733 - Error on short prefixes

---

WordPress-Core/ruleset.xml

Found this during the work on the twentytwenty theme so I thought I should just make a PR.

Fixed minor grammar issue

---

WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
WordPress/Tests/WP/AlternativeFunctionsUnitTest.php

Just to be sure this was covered correctly (which it luckily was).

AlternativeFunctions: add extra unit test

---

WordPress/Sniffs/WP/CapitalPDangitSniff.php
WordPress/Tests/WP/CapitalPDangitUnitTest.inc
WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed

CapitalPDangit: minor tweak

---

WordPress/Sniffs/WP/DeprecatedClassesSniff.php
WordPress/Tests/WP/DeprecatedClassesUnitTest.inc
WordPress/Tests/WP/DeprecatedClassesUnitTest.php

Add some more deprecated classes to the list.
Refs:
* https://core.trac.wordpress.org/ticket/42364
* https://core.trac.wordpress.org/ticket/47699

DeprecatedClasses: update the sniff

---

WordPress/Docs/NamingConventions/ValidHookNameStandard.xml

ValidHookName: add documentation

---

WordPress/Docs/WP/EnqueuedResourcesStandard.xml

Adds documentation for WordPress.WP.EnqueuedResources.

---

WordPress/Docs/Security/SafeRedirectStandard.xml

Adds WP.Security.SafeRedirect documentation.

---

CHANGELOG.md

:exclamation: Reviews & approval welcome. I'll merge this myself (if approved) just before the release. :exclamation: 
* Release date set at this ~~**Sunday February 2nd**~~ **Tuesday February 4rd**.
* Includes all currently merged changes + PR #1858.

Changelog for WPCS 2.2.1

---

CHANGELOG.md

:exclamation: Reviews & approval welcome. I'll merge this myself (if approved) just before the release. :exclamation: 
* Release date set at this **Thursday May 14th**.

Changelog for WPCS 2.3.0

---

CHANGELOG.md

Changelog: fix link

---

.gitattributes

Just something I came across while working on the 3.0 branch.

.gitattributes: minor update

---

WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php

Attempt to make the error message clearer.

CastStructureSpacing: minor error message improvement

---

WordPress/Docs/WP/EnqueuedResourceParametersStandard.xml

Adds documentation for WordPress.WP.EnqueueResourceParameters.

---

.github/ISSUE_TEMPLATE/bug_report.md

After the umpteenth time of getting a non-reproducible bug report (not just in this repo, mind you), I figured it may help to add some more guidance to the bug report template.
Most important changes:
* Ask for the actual CLI command people have used.
* Ask for the custom ruleset used (if used).
* Give some guidance on how to find out the version numbers of the tooling used.

Bug report template: various improvements

---

README.md

Add link to "Running in GitHub Actions" doc page

---

WordPress/Tests/WP/CronIntervalUnitTest.inc

See: https://github.com/WordPress/WordPress-Coding-Standards/pull/2073#discussion_r940007958

WP/CronInterval: update inline annotations in test case file

---

WordPress-Core/ruleset.xml
WordPress-Extra/ruleset.xml

As per the discussion in #2101.

Core: only allow one property declaration per statement

---

WordPress-Extra/ruleset.xml

Extra: fix typo in rule

---

WordPress-Extra/ruleset.xml

Argh... two more... (follow up to #2096 and #2105)
(Happens when I'm working on too many things at the same time...)

Extra: fix (more) typos in rules

---

WordPress/Sniff.php
WordPress/Tests/Security/EscapeOutputUnitTest.inc
WordPress/Tests/Security/EscapeOutputUnitTest.php

Sniff::$formattingFunctions: add `antispambot()` to the list

---

WordPress/Tests/WP/PostsPerPageUnitTest.inc

Get rid of some strange space indents.

WP/PostsPerPage: minor clean up of test case file

---

WordPress/Helpers/EscapingFunctionsTrait.php
WordPress/Helpers/PrintingFunctionsTrait.php
WordPress/Sniffs/Security/EscapeOutputSniff.php

Minor doc tweaks

---

README.md

Follow up on #2338.
Sorry, looks like I used an outdated version of the badge code.

README: fix codecov badge

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/dependency-change.md
.github/ISSUE_TEMPLATE/feature_request.md

Updates for the issue templates in anticipation of the WPCS 3.0.0 release.

Issue template: minor tweaks

---

WordPress/Helpers/RulesetPropertyHelper.php
WordPress/Helpers/WPDBTrait.php

Helpers: add type declarations whenever possible

---

CHANGELOG.md

Adding the changelog for the v3.0.1 hotfix release.

Add changelog for v3.0.1

---

CHANGELOG.md

This doesn't affect the 3.0.1 release, but just to be correct for the future release :)

Fix the release date in the changelog

---

README.md

Just noticed this didn't display as intended.

README: minor tweak

---

.github/workflows/basic-qa.yml

* Update a URL which is no longer valid.
* Ensure all steps have a name.

GH Actions: minor tweaks

---

WordPress/Docs/NamingConventions/ValidFunctionNameStandard.xml

Add documentation for WordPress.NamingConventions.ValidFunctionName

---

.github/release-checklist.md

... to make sure this is checked a little more regularly.

Release checklist: add new action item

---

composer.json

Ref: https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.4.0

Composer: bump PHP Parallel Lint

---

README.md

README: make the call for funding stand out a bit more
